### ISSUE TITLE
fatal error: 'frida-core.h' file not found 

### ISSUE THREAD

**Issue by foxundermoon** [frida/frida#1006]
# build error on macos  with node 12.9.1

```log

frida@0.0.0 install /Volumes/data/workspace/android/hack/frida/frida-node
> prebuild-install || node-gyp rebuild

  CXX(target) Release/obj.target/frida_binding/src/addon.o
In file included from ../src/addon.cc:1:
In file included from ../src/application.h:4:
In file included from ../src/glib_object.h:4:
In file included from ../src/runtime.h:4:
../src/glib_context.h:4:10: fatal error: 'frida-core.h' file not found
#include <frida-core.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[2]: *** [Release/obj.target/frida_binding/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.9.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/data/workspace/android/hack/frida/frida-node
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@0.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by foxundermoon** [comment]
# full log
[2019-08-31T15_28_46_575Z-debug.log](https://github.com/frida/frida/files/3562579/2019-08-31T15_28_46_575Z-debug.log)

**Comment by lchnider** [comment]
same here :(
