### ISSUE TITLE
frida-ps -U gives the follwing error on OSX El Capitan

### ISSUE THREAD

**Issue by antojoseph** [frida/frida#101]
OS : El Capitan
Python : 2.7 
Python Module : pygments is installed 

x@xyz:/Users$ frida-ps -U
Traceback (most recent call last):
  File "/usr/local/bin/frida-ps", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pygments>=2.0.2

**Comment by oleavr** [comment]
Did you try `easy_install -U frida`?

**Comment by antojoseph** [comment]
Using Easy Install fixed the issue. Thanks
