### ISSUE TITLE
frida core not compiling

### ISSUE THREAD

**Issue by dhucul** [frida/frida#1028]
Traceback (most recent call last):
25>  File "C:\frida\frida-core\src\api\generate.py", line 400, in <module>
25>    main()
25>  File "C:\frida\frida-core\src\api\generate.py", line 13, in main
25>    parser.add_argument('api_vala', metavar='/path/to/frida.vala', type=argparse.FileType('r', encoding='utf-8'))
25>TypeError: __init__() got an unexpected keyword argument 'encoding'
25>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1.
25>Done building project "frida-core.vcxproj" -- FAILED.

**Comment by forensicmike** [comment]
1>------ Build started: Project: frida-core, Configuration: Debug Win32 ------
1>Serializing Winjector resources
1>Serializing Agent resources
1>Compiling vala code
1>Traceback (most recent call last):
1>  File "D:\frida\frida-core\src\api\generate.py", line 411, in <module>
1>    main()
1>  File "D:\frida\frida-core\src\api\generate.py", line 13, in main
1>    parser.add_argument('api_vala', metavar='/path/to/frida.vala', type=argparse.FileType('r', encoding='utf-8'))
1>TypeError: __init__() got an unexpected keyword argument 'encoding'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v150\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "frida-core.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 21 up-to-date, 0 skipped ==========

**Comment by forensicmike** [comment]
Don't know if it'll break stuff, but I replaced all instances of , encoding='utf-8') with blank and it compiled.

**Comment by xuelvming** [comment]
+1, have the same strange issue as well.  have to remove encoding argument too. But the strange thing is that, in some of our VM, encoding is working, while in other VMs, it's not working...
