### ISSUE TITLE
`Module.load()` fails to return a handle to the loaded module.

### ISSUE THREAD

**Issue by leonjza** [frida/frida#1029]
I have a dylib in an iOS applications Documents directory. When loading with `Module.load(dylibPath);`, an exception is thrown as follows:

```
Error: unable to find module '/var/mobile/Containers/Data/Application/87C72D23-BA24-4636-9E52-54DC14072D47/Documents/m.dylib'
    at Object.value [as getModuleByName] (frida/runtime/core.js:353:15)
    at Function.value [as load] (frida/runtime/core.js:221:22)
    at /m.js:26:34
    at performScheduledWorkItem (frida/node_modules/frida-objc-bridge/index.js:158:1)
```

While confusing at first, when running `Process.enumerateModules();`, the dylib actually did load successfully and could be used as normal:

```json
    {
        "base": "0x116bc4000",
        "name": "m.dylib",
        "path": "/private/var/mobile/Containers/Data/Application/4F0836B4-F36A-4E8F-AC80-E0B6293A4AD1/Documents/m.dylib",
        "size": 622592
    },
```

Some investigation revealed that once loaded, a call to [`Process.getModuleByName(moduleName)`](https://github.com/frida/frida-gum/blob/8d9da64f4010f10fe3f2f2ff454b9c9fecf810c0/bindings/gumjs/runtime/core.js#L220) is made with `moduleName` being the full path to the dylib that got loaded originally and not just `m.dylib`. This fails and causes the error above.

**Comment by srcdes** [comment]
dups with https://github.com/frida/frida/issues/1032#issuecomment-536783611

**Comment by 0xElessar** [comment]
Hello, I have exactly the same problem @leonjza. Did you manage to solve it somehow? I really like your idea to load and use modules like Flex dynamically. 
thanks
