### ISSUE TITLE
Stalking native function call

### ISSUE THREAD

**Issue by bannsec** [frida/frida#1036]
I'm attempting to perform a stalk on a native function call. The idea being, I'd like to perform certain stalking related tasks on specific functions that I call (ala `NativeFunction` or similar).

I'm currently doing the following:

- Start stalking on Process.getCurrentThreadId()
- Setup NativeFunction
- Call NativeFunction

While the NativeFunction call itself works, I get nothing back from the stalker on this thread. I'm wondering if Frida is intentionally deciding to hide that data from me, and how I can persuade it to allow me to stalk those arbitrary calls.

**Comment by bannsec** [comment]
having strangeness reproducing this rn... closing

**Comment by bannsec** [comment]
Ok, figured out the difference. Looks like what I do see is a bunch of calls inside frida-agent, but not out to the function:

```
 call   frida-agent-64.so:frida_agent_main+0x90878    frida-agent-64.so:frida_agent_main+0x904d2    0
 exec    frida-agent-64.so:frida_agent_main+0x9087d                                                 1
 block   frida-agent-64.so:frida_agent_main+0x9086b    frida-agent-64.so:frida_agent_main+0x9087f   1
 exec    frida-agent-64.so:frida_agent_main+0x90864                                                 1
 exec    frida-agent-64.so:frida_agent_main+0x90867                                                 1
 exec    frida-agent-64.so:frida_agent_main+0x90869                                                 1
 block   frida-agent-64.so:frida_agent_main+0x90864    frida-agent-64.so:frida_agent_main+0x9086b   1
 exec    frida-agent-64.so:frida_agent_main+0x9086b                                                 1
 exec    frida-agent-64.so:frida_agent_main+0x9086e                                                 1
 exec    frida-agent-64.so:frida_agent_main+0x90873                                                 1
 exec    frida-agent-64.so:frida_agent_main+0x90878                                                 1
 call   frida-agent-64.so:frida_agent_main+0x90878    frida-agent-64.so:frida_agent_main+0x904d2    0
 exec    frida-agent-64.so:frida_agent_main+0x9087d                                                 1
 block   frida-agent-64.so:frida_agent_main+0x9086b    frida-agent-64.so:frida_agent_main+0x9087f   1
 exec    frida-agent-64.so:frida_agent_main+0x90864                                                 1
 exec    frida-agent-64.so:frida_agent_main+0x90867                                                 1
 exec    frida-agent-64.so:frida_agent_main+0x90869                                                 1
 block   frida-agent-64.so:frida_agent_main+0x90864    frida-agent-64.so:frida_agent_main+0x9086b   1
 exec    frida-agent-64.so:frida_agent_main+0x9086b                                                 1
 exec    frida-agent-64.so:frida_agent_main+0x9086e                                                 1
 exec    frida-agent-64.so:frida_agent_main+0x90873                                                 1
 exec    frida-agent-64.so:frida_agent_main+0x90878                                                 1
 call   frida-agent-64.so:frida_agent_main+0x90878    frida-agent-64.so:frida_agent_main+0x904d2    0
```

Here's an example of what I'm trying to do

```js
var t = Memory.allocUtf8String("test")
var strlen = Module.getExportByName("libc.so.6", "strlen")
var f = new NativeFunction(strlen, "pointer", ["pointer"])

Stalker.follow(Process.getCurrentThreadId(), { events: {exec: true}, onReceive: function (events) { send(Stalker.parse(events)); }})

f(t)
```

**Comment by bannsec** [comment]
Been banging my head on this for a while now.. It appears that exclusion of the stalker on Frida's own thread is not being handled by `Stalker._exclude`. Been trying to trace down where decision logic is for if Frida will add a GumEvent or not, but can't seem to find it. Any hints would be appreciated.

**Comment by oleavr** [comment]
@bannsec On my phone right now so can only give you a hint: If you `git grep exclude` in frida-core you should find the call – IIRC it's in `lib/payload/script-engine.vala`.

**Comment by bannsec** [comment]
Thanks! I see that now. I don't think calls to libc would be in the stalker's personal memory range. Will try removing that call and see if i start seeing the events from inside NativeFunction calls.

**Comment by oleavr** [comment]
Well the exclusions currently only affect static function calls – `CALL <imm>`, `BL <imm>` – so other branches are followed. However as soon as Stalker sees a static function call to an excluded range, it doesn't follow execution and just performs the static function call as it would have been performed by the original call. That means that anything that called function does is invisible as far as Stalker is concerned – so calls to non-excluded ranges aren't seen either.

**Comment by bannsec** [comment]
Ah ok, that makes sense. Perhaps there could be an option to not exclude anything in the Stalker instantiation? I'd still be excluding a bunch, but just from the python side (or possibly manually in the js). Given the bloat, I would assume this would not be the default behavior.

**Comment by oleavr** [comment]
Yeah I think we should add `Stalker.clearExclusions()` or something like that. Wanna take a stab at adding it?

**Comment by bannsec** [comment]
Yeah. Think ive figured enough about the bindings I might be able to do it.

**Comment by bannsec** [comment]
Well... I added logic to clear out the excludes, and in doing so when I call clearExclusions it ends up with lock resource contention, and just spins forever.

backtrace:
```
#0  0x00007f865e17ee57 in sched_yield () at ../sysdeps/unix/syscall-template.S:78
#1  0x00007f865698b98c in spin_acquire_lock (sl=sl@entry=0x7f865e877384) at ../../../frida-gum/gum/dlmalloc.c:1962
#2  0x00007f865698cb53 in mspace_malloc (msp=0x7f865e877010, bytes=47) at ../../../frida-gum/gum/dlmalloc.c:5583
#3  0x00007f865693a393 in g_malloc () at ../../../glib/glib/gmem.c:100
#4  0x00007f86569dec76 in duk_heap_mem_alloc (heap=0x7f8654edc430, size=47) at ../../../frida-gum/bindings/gumjs/duktape.c:50254
#5  0x00007f86569e27ae in duk__strtable_alloc_hstring (extdata=0x0, strhash=1244648074, blen=14, str=0x7ffe2c4a0a58 "0x7f865e6d2420", heap=0x7f8654edc430) at ../../../frida-gum/bindings/gumjs/duktape.c:52070
#6  duk__strtable_do_intern (strhash=1244648074, blen=14, str=0x7ffe2c4a0a58 "0x7f865e6d2420", heap=0x7f8654edc430) at ../../../frida-gum/bindings/gumjs/duktape.c:52504
#7  duk_heap_strtable_intern (heap=0x7f8654edc430, str=0x7ffe2c4a0a58 "0x7f865e6d2420", blen=14) at ../../../frida-gum/bindings/gumjs/duktape.c:52642
#8  0x00007f86569e3134 in duk_heap_strtable_intern_checked (thr=0x7f8654f708f0, str=<optimized out>, blen=<optimized out>) at ../../../frida-gum/bindings/gumjs/duktape.c:52688
#9  0x00007f86569e3189 in duk_push_lstring (thr=0x7f8654f708f0, str=<optimized out>, len=<optimized out>) at ../../../frida-gum/bindings/gumjs/duktape.c:22038
#10 0x00007f86569b4e02 in gumjs_native_pointer_to_string_impl (args=0x7ffe2c4a0a40, ctx=0x7f8654f708f0) at ../../../frida-gum/bindings/gumjs/gumdukcore.c:2343
#11 gumjs_native_pointer_to_string (ctx=0x7f8654f708f0) at ../../../frida-gum/bindings/gumjs/gumdukcore.c:2311
#12 0x00007f86569d8316 in duk__handle_call_raw (thr=thr@entry=0x7f8654f708f0, idx_func=7, call_flags=call_flags@entry=0) at ../../../frida-gum/bindings/gumjs/duktape.c:64373
#13 0x00007f86569d854e in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x7f8654f708f0) at ../../../frida-gum/bindings/gumjs/duktape.c:64527
#14 duk_call_method (thr=thr@entry=0xb, nargs=nargs@entry=0) at ../../../frida-gum/bindings/gumjs/duktape.c:14269
#15 0x00007f86569dd115 in duk__defaultvalue_coerce_attempt (thr=0xb, thr@entry=0x7f8654f708f0, idx=idx@entry=6, func_stridx=func_stridx@entry=82) at ../../../frida-gum/bindings/gumjs/duktape.c:20155
#16 0x00007f86569d868c in duk__to_primitive_helper (check_symbol=1, hint=<optimized out>, idx=6, thr=0x7f8654f708f0) at ../../../frida-gum/bindings/gumjs/duktape.c:20265
#17 duk_to_primitive (thr=0x7f8654f708f0, idx=<optimized out>, hint=<optimized out>) at ../../../frida-gum/bindings/gumjs/duktape.c:20276
#18 0x00007f865689c846 in duk__vm_arith_add (idx_z=3, tv_y=0x7f865e6ed6d0, tv_x=0x7f865e7e5130, thr=0x7f8654f708f0) at ../../../frida-gum/bindings/gumjs/duktape.c:73300
#19 duk__js_execute_bytecode_inner (entry_act=entry_act@entry=0x7f8654f4dc70, entry_thread=<optimized out>) at ../../../frida-gum/bindings/gumjs/duktape.c:11299
#20 0x00007f86569d72d3 in duk_js_execute_bytecode (exec_thr=exec_thr@entry=0x7f8654f708f0) at ../../../frida-gum/bindings/gumjs/duktape.c:76051
#21 0x00007f86569d82d5 in duk__handle_call_raw (thr=thr@entry=0x7f8654f708f0, idx_func=0, call_flags=0) at ../../../frida-gum/bindings/gumjs/duktape.c:64345
#22 0x00007f86569f1f4b in duk_handle_call_unprotected (call_flags=<optimized out>, idx_func=<optimized out>, thr=0x7f8654f708f0) at ../../../frida-gum/bindings/gumjs/duktape.c:64527
#23 duk__pcall_method_raw (thr=thr@entry=0x7f8654f708f0, udata=udata@entry=0x7ffe2c4a1000) at ../../../frida-gum/bindings/gumjs/duktape.c:14342
#24 0x00007f86569dc82b in duk__handle_safe_call_inner (num_stack_rets=1, idx_retbase=0, entry_thread_state=1 '\001', entry_curr_thread=<optimized out>, udata=0x7ffe2c4a1000, func=0x7f86569f1f28 <duk__pcall_method_raw>, thr=0x7f8654f708f0) at ../../../frida-gum/bindings/gumjs/duktape.c:64580
#25 duk_handle_safe_call (thr=0x7f8654f708f0, func=0x7f86569f1f28 <duk__pcall_method_raw>, udata=0x7ffe2c4a1000, num_stack_args=<optimized out>, num_stack_rets=1) at ../../../frida-gum/bindings/gumjs/duktape.c:64825
#26 0x00007f86569dca95 in duk_pcall_method_flags (thr=<optimized out>, nargs=<optimized out>, call_flags=<optimized out>) at ../../../frida-gum/bindings/gumjs/duktape.c:14361
#27 0x00007f86569b9ee5 in _gum_duk_scope_call_method (self=self@entry=0x7ffe2c4a1058, nargs=nargs@entry=1) at ../../../frida-gum/bindings/gumjs/gumdukcore.c:1224
#28 0x00007f86569c786f in gum_duk_js_invocation_listener_on_enter (listener=0x7f865e830f40, ic=0x7f8654e33020) at ../../../frida-gum/bindings/gumjs/gumdukinterceptor.c:727
#29 0x00007f865698b555 in _gum_function_context_begin_invocation (function_ctx=0x7f865e82be80, cpu_context=0x7ffe2c4a1448, caller_ret_addr=0x7ffe2c4a14e0, next_hop=0x7ffe2c4a14d8) at ../../../frida-gum/gum/guminterceptor.c:1264
```

And the actual lock:

```
   │1956    #if !defined(USE_RECURSIVE_LOCKS) || USE_RECURSIVE_LOCKS == 0                                                                                                                                                                                                                                                     │
   │1957    /* Plain spin locks use single word (embedded in malloc_states) */                                                                                                                                                                                                                                                │
   │1958    static int spin_acquire_lock(int *sl) {                                                                                                                                                                                                                                                                           │
   │1959      int spins = 0;                                                                                                                                                                                                                                                                                                  │
   │1960      while (*(volatile int *)sl != 0 || CAS_LOCK(sl)) {                                                                                                                                                                                                                                                              │
   │1961        if ((++spins & SPINS_PER_YIELD) == 0) {                                                                                                                                                                                                                                                                       │
  >│1962          SPIN_LOCK_YIELD;                                                                                                                                                                                                                                                                                            │
   │1963        }                                                                                                                                                                                                                                                                                                             │
   │1964      }                                                                                                                                                                                                                                                                                                               │
```

Up a bit more, it's part of a heap call

```
   │50243   #if defined(DUK_USE_GC_TORTURE)                                                                                                                                                                                                                                                                                   │
   │50244           /* Simulate alloc failure on every alloc, except when mark-and-sweep                                                                                                                                                                                                                                      │
   │50245            * is running.                                                                                                                                                                                                                                                                                            │
   │50246            */                                                                                                                                                                                                                                                                                                       │
   │50247           if (heap->ms_prevent_count == 0) {                                                                                                                                                                                                                                                                        │
   │50248                   DUK_DDD(DUK_DDDPRINT("gc torture enabled, pretend that first alloc attempt fails"));                                                                                                                                                                                                              │
   │50249                   res = NULL;                                                                                                                                                                                                                                                                                       │
   │50250                   DUK_UNREF(res);                                                                                                                                                                                                                                                                                   │
   │50251                   goto skip_attempt;                                                                                                                                                                                                                                                                                │
   │50252           }                                                                                                                                                                                                                                                                                                         │
   │50253   #endif                                                                                                                                                                                                                                                                                                            │
  >│50254           res = heap->alloc_func(heap->heap_udata, size);                                                                                                                                                                                                                                                           │
   │50255           if (DUK_LIKELY(res || size == 0)) {                                                                                                                                                                                                                                                                       │
   │50256                   /* For zero size allocations NULL is allowed. */                                                                                                                                                                                                                                                  │
   │50257                   return res;                                                                                                                                                                                                                                                                                       │```

Any idea why this is happening or how to not have the locks contend?

**Comment by bannsec** [comment]
Adding that USE_RECURSIVE_LOCKS option seems to just cause a segfault of some kind instead.

Also, it appears to have nothing to do with the modifying of the exclusions array as I updated the stalker to simply not add itself to begin with and the same thing happened. Something to do with the nesting of allocs that comes from stalker tracing it's own thread...

**Comment by bannsec** [comment]
Ok. Think I figured out what's going wrong. It appears that when stalking
itself, it becomes reentrant. At the moment this is manifesting when the
gum event sync hits the spin lock, then it apparently gets interrupted or
something and hits it again. This effectively is causing the program to
spin at 100% CPU and never get the lock.

The recursive lock option does not appear to be an option for the current
gum event sending, as ive only found it in dlmalloc.

I'm not sure how to proceed at this time. Without some change in lock
behavior, this would appear to not be possible.

**Comment by bannsec** [comment]
Throwing in the towel. I implemented `Stalker.clearExclusions` (for x86, but not hard to move to others), but stalking of the frida thread has lead to gum spin locks that get stuck and never release when attempting to process events. Specifically, the following happens:

```
#0  0x00007fd3b27a31df in gum_spinlock_acquire (spinlock=spinlock@entry=0x7fd3b0327538) at ../../../frida-gum/gum/backend-x86/gumspinlock-x86.c:29
#1  0x00007fd3b282ff7f in gum_v8_event_sink_process (sink=0x7fd3b0327520, ev=0x7fd3abffe6f8) at ../../../frida-gum/bindings/gumjs/gumv8eventsink.cpp:177
#2  0x00007fd3b27a3360 in gum_exec_ctx_emit_block_event (ctx=<optimized out>, begin=<optimized out>, end=<optimized out>) at ../../../frida-gum/gum/backend-x86/gumstalker-x86.c:1665
```

That spinlock acquire gets stuck basically immediately. However, when single stepping through execution, It doesn't seem to. It only seems to get stuck when i continue all threads.

If anyone wants to pick this up, you can use this branch: https://github.com/bannsec/frida-gum/tree/clearExclusions

Being able to stalk NativeFunctions is something that would be a huge benefit for sure, so hope someone can figure out what's going on.

**Comment by oleavr** [comment]
Started solving this in the [feature/native-function-traps](https://github.com/frida/frida-gum/tree/feature/native-function-traps) branch. Almost got it working – works for the first call and crashes on the second. Once that's figured out it should be ready for merging.

**Comment by bannsec** [comment]
Sweet! I have managed to make a workaround where I create a cmodule to do the call that i want, call pthread_create on it, and then trace that new thread. It works alright but it's slow due to the need to compile and thread create each time.

**Comment by oleavr** [comment]
@bannsec Nice! That's a good workaround.

This new feature is now out in 12.7.26:
https://twitter.com/fridadotre/status/1204435195891535873

For fuzzing use-cases where you want to bombard the function over and over, the libffi overhead might be significant, but you can negate that by putting the loop that calls the function in a CModule, and calling that function through a `NativeFunction` with `traps: all`.

**Comment by bannsec** [comment]
Sweet! I'm definitely looking forward to trying this out!
