### ISSUE TITLE
No module named frida

### ISSUE THREAD

**Issue by sachlav** [frida/frida#1062]
To install frida I used the command 
`sudo pip install frida-tools` and installation was succesful, but when running the command `frida --version` I get the following error

`Traceback (most recent call last):
  File "/usr/local/bin/frida", line 8, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/frida_tools/repl.py", line 24, in main
    import frida
ImportError: No module named frida`

**Comment by tcskiran** [comment]
@sachlav How did you fix the issue?
