### ISSUE TITLE
[Strange] frida.enumerate_devices() did'n recognize my android phone

### ISSUE THREAD

**Issue by DXCyber409** [frida/frida#1086]
[My Version]
```
python -m pip install frida
Requirement already satisfied: frida in d:\rtews\python\python37\lib\site-packages (12.7.22)
```

[Problem]
I have encounted a strange problem that python frida does not recognize my android phone with the code below, which I have learned from https://www.frida.re/docs/home/. 
```
import frida
process = frida.get_usb_device().attach('com.app.com')
```
It works fine before(privious version or earlier time, I'm not sure), but now I can only get:
```
python e:/Workspace/Python3/frida/test.py
Traceback (most recent call last):
  File "e:/Workspace/Python3/frida/test.py", line 2, in <module>
    process = frida.get_usb_device().attach('com.app.com')
  File "D:\RTEws\Python\Python37\lib\site-packages\frida\__init__.py", line 82, in get_usb_device
    return get_device_matching(lambda d: d.type == 'usb', timeout, **kwargs)
  File "D:\RTEws\Python\Python37\lib\site-packages\frida\__init__.py", line 90, in get_device_matching
    return get_device_manager().get_device_matching(predicate, timeout, **kwargs)
  File "D:\RTEws\Python\Python37\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\RTEws\Python\Python37\lib\site-packages\frida\core.py", line 58, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
frida.InvalidArgumentError: device not found
```
The key message is: frida.InvalidArgumentError: device not found
And I'm sure my phone is connected to the PC and ADB or FRIDA-PS works fine.
```
adb devices
List of devices attached
beac33b8        device
```
```
frida-ps -U
  PID  Name
-----  ---------------------------------------------------
 8601  adbd
11399  com.android.deskclock
 4694  com.android.phone
18404  com.android.providers.calendar
24838  com.android.settings
...
```

[Trying to Figure Out]
So I started to review the key code of FRIDA-PS why it works. And I have found some code that reads the list of devices in \python\lib\site-packages\frida_tools\application.py.
```
def find_device(type):
    print(frida.enumerate_devices()) # Added to found some clue
    for device in frida.enumerate_devices():
        if device.type == type:
            return device
    return None
```
Modify and save, then frida-ps -U:
```
frida-ps -U
[Device(id="local", name="Local System", type='local'), Device(id="tcp", name="Local TCP", type='remote')]
[Device(id="local", name="Local System", type='local'), Device(id="tcp", name="Local TCP", type='remote'), Device(id="beac33b8", name="Xiaomi MI NOTE LTE", type='usb')]
  PID  Name
-----  ---------------------------------------------------
 8601  adbd
  353  adsprpcd
24398  android.process.media
  382  audiod
```
It was obvious that find_device() function have run twice, and the second time my phone shows up!
So I imitated this phenomenon, just run twice more to get device of my phone:
```
import frida
print(frida.enumerate_devices())
print(frida.enumerate_devices())
print(frida.enumerate_devices())
print(frida.enumerate_devices())
print(frida.enumerate_devices())
print(frida.enumerate_devices())
print(frida.enumerate_devices())
```
But the result is:
```
[Device(id="local", name="Local System", type='local'), Device(id="tcp", name="Local TCP", type='remote')]
[Device(id="local", name="Local System", type='local'), Device(id="tcp", name="Local TCP", type='remote')]
[Device(id="local", name="Local System", type='local'), Device(id="tcp", name="Local TCP", type='remote')]
[Device(id="local", name="Local System", type='local'), Device(id="tcp", name="Local TCP", type='remote')]
[Device(id="local", name="Local System", type='local'), Device(id="tcp", name="Local TCP", type='remote')]
[Device(id="local", name="Local System", type='local'), Device(id="tcp", name="Local TCP", type='remote')]
[Device(id="local", name="Local System", type='local'), Device(id="tcp", name="Local TCP", type='remote')]
```
I don't understand why the same code gives back differedt result. Can you help me to deal with it? Thanks.

[Again, What I want. (The page is too long...)]
I want the code below works fine :)
And it is kind of you to help me understanding why frida-ps works fine and the code does not.  :)
```
import frida
process = frida.get_usb_device().attach('com.app.com')
```

**Comment by MrYangCode** [comment]
me too

**Comment by yujunfeng24** [comment]
get_usb_device(1) to give it a higher timeout.

**Comment by DXCyber409** [comment]
> get_usb_device(1) to give it a higher timeout.

Cool! Thanks so much. So I forget about the time out.

**Comment by HongYuuu** [comment]
> get_usb_device(1) to give it a higher timeout.

Cool! Thanks so much
