### ISSUE TITLE
Should this output represent any problem?

### ISSUE THREAD

**Issue by 8lackberry** [frida/frida#1117]
`{"type":"error","description":"TypeError: api.art::mirror::Object::Clone is not a function","stack":"TypeError: api.art::mirror::Object::Clone is not a function\n    at cloneArtMethod (frida/node_modules/frida-java-bridge/lib/android.js:1266:1)\n    at resolveArtTargetMethodId (frida/node_modules/frida-java-bridge/lib/class-factory.js:1612:1)\n    at klass.f (eval at makeMethod (frida/node_modules/frida-java-bridge/lib/class-factory.js:1525:1), <anonymous>:1:306)\n    at klass.f (frida/node_modules/frida-java-bridge/lib/class-factory.js:1352:1)\n    at klass.sendMessageDelayed.implementation (/internal-agent.js:221:31)\n    at f (eval at implement (frida/node_modules/frida-java-bridge/lib/class-factory.js:2136:1), <anonymous>:1:285)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1266,"columnNumber":1}`

**Comment by TomieAi** [comment]
same issue
