### ISSUE TITLE
getUsbDevice can't find tcp connected device at first

### ISSUE THREAD

**Issue by tacesrever** [frida/frida#1129]
when adb connected using tcp like `adb connect ip:port`,  
run this code:  
```
const frida = require('frida');

async function sleep(ms) {
	return new Promise(resolve => setTimeout(resolve, ms));
}

async function tryGetDevice() {
    await frida.getUsbDevice().then((device) =>{
        console.log(device.id);
    }).catch((e) => {
        console.log(`${e.name}: ${e.message}`);
    });
}

async function run() {
    await tryGetDevice();
    await tryGetDevice();
    await sleep(1000);
    await tryGetDevice();
}

run();
```
result is:
```
Error: Device not found
Error: Device not found
192.168.1.101:5555
```

**Comment by tacesrever** [comment]
same problem on python:
```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida
>>> frida.get_usb_device()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python37\lib\site-packages\frida\__init__.py", line 82, in get_usb_device
    return get_device_matching(lambda d: d.type == 'usb', timeout, **kwargs)
  File "D:\Python37\lib\site-packages\frida\__init__.py", line 90, in get_device_matching
    return get_device_manager().get_device_matching(predicate, timeout, **kwargs)
  File "D:\Python37\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\Python37\lib\site-packages\frida\core.py", line 58, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
frida.InvalidArgumentError: device not found
>>> frida.get_usb_device()
Device(id="192.168.1.101:5555", name="*****", type='usb')
```

**Comment by tacesrever** [comment]
same issue to #1111

**Comment by tacesrever** [comment]
resolved by
```
async getUsbDevice() {
        return new Promise(async (resolve, reject) => {
            let mgr = frida.getDeviceManager();
            let device = await frida.getUsbDevice().catch(()=>{});
            if(device) resolve(device);
            else {
                mgr.added.connect( (d) => { resolve(d); } );
            }
        });
    }
```

**Comment by oleavr** [comment]
> resolved by

This code has a race-condition, as the device might have *just* been added before listening for the `added` signal. But this has already been solved in frida-node, [here](https://github.com/frida/frida-node/blob/dfae61764439b80ba06a583e8ffc884e80f64cef/lib/index.ts#L140-L212). All you need to do is call `getUsbDevice({ timeout: null })` to wait indefinitely, or a non-zero `timeout` in milliseconds.

**Comment by tacesrever** [comment]
see it, thanks.

**Comment by gMan1990** [comment]
```plain
# adb devices
List of devices attached
127.0.0.1:7555  device

# frida-ls-devices
Id     Type    Name
-----  ------  ------------
local  local   Local System
tcp    remote  Local TCP

# frida-ps -U | head -n 4
 PID  Name
----  ----------------------------------
 272  adbd
```
```plain
frida.get_usb_device()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\frida\__init__.py", line 82, in get_usb_device
    return get_device_matching(lambda d: d.type == 'usb', timeout, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\frida\__init__.py", line 90, in get_device_matching
    return get_device_manager().get_device_matching(predicate, timeout, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\frida\core.py", line 58, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
frida.InvalidArgumentError: device not found
```

1. how to `get_usb_device` @tacesrever
2. `adb forward tcp:27042 tcp:27042` and `frida.get_remote_device()` can fix this
