### ISSUE TITLE
crash when afl.init() put after import frida

### ISSUE THREAD

**Issue by JoeyJiao** [frida/frida#1160]
Hi,
I'm using python-afl to fuzz, and below script works fine.

> import afl
> import os
> afl.init()
> import frida
> 
> def on_message(message, data):
>     print(message)
> 
> def add(i, j):
>     k = i +  j
>     print(k)
> 
> device = frida.get_usb_device()
> add(0, 1)

However, if I put afl.init() after import frida, afl results in crash and cannot to start. I don't think it's error of afl, or python-afl. bt pasted.

> import afl
> import os
> import frida
> afl.init()
> 
> def on_message(message, data):
>     print(message)
> 
> def add(i, j):
>     k = i +  j
>     print(k)
> 
> device = frida.get_usb_device()
> add(0, 1)

> Thread 4.1 "python3" received signal SIGTERM, Terminated.
> syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
> 38	../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory.
> (gdb) bt
> Selected thread is running.
> (gdb) inferior 4
> [Switching to inferior 4 [process 4057839] (/usr/bin/python3.7)]
> [Switching to thread 4.1 (Thread 0x7ffff7c2e740 (LWP 4057839))]
> #0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
> 38	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
> (gdb) bt
> #0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
> #1  0x00007ffff7252e14 in g_cond_wait () at ../../../glib/glib/gthread-posix.c:1512
> #2  0x00007ffff4035264 in frida_async_task_execute (self=self@entry=0xa2d240, cancellable=cancellable@entry=0x0, error=error@entry=0x7fffffffc258) at ../../../frida-core/src/frida.vala:2591
> #3  0x00007ffff4035bcd in frida_device_manager_find_device_sync (self=<optimized out>, predicate=<optimized out>, predicate_target=0x7ffff3656cb0, timeout=<optimized out>, cancellable=0x0, error=error@entry=0x7fffffffc2a8) at ../../../frida-core/src/frida.vala:181
> #4  0x00007ffff4035cc2 in frida_device_manager_get_device_sync (self=<optimized out>, predicate=<optimized out>, predicate_target=<optimized out>, timeout=<optimized out>, cancellable=<optimized out>, error=0x7fffffffc2f8) at ../../../frida-core/src/frida.vala:90
> #5  0x00007ffff4002ef3 in PyDeviceManager_get_device_matching (self=0x7ffff786b8d0, args=0x7ffff3eb8370) at ../../../frida-python/src/_frida.c:1936
> #6  0x00000000005c8fe3 in _PyMethodDef_RawFastCallKeywords ()
> #7  0x00000000005c9346 in _PyCFunction_FastCallKeywords ()
> #8  0x0000000000536884 in ?? ()
> #9  0x00000000005394f2 in _PyEval_EvalFrameDefault ()
> #10 0x0000000000537ce7 in _PyEval_EvalCodeWithName ()
> #11 0x00000000005cafbe in _PyFunction_FastCallDict ()
> #12 0x000000000053a811 in _PyEval_EvalFrameDefault ()
> #13 0x00000000005373a7 in _PyEval_EvalCodeWithName ()
> #14 0x00000000005cafbe in _PyFunction_FastCallDict ()
> #15 0x00000000004e066e in ?? ()
> #16 0x00000000005ccf42 in PyObject_Call ()
> #17 0x000000000053a811 in _PyEval_EvalFrameDefault ()
> #18 0x00000000005373a7 in _PyEval_EvalCodeWithName ()
> #19 0x00000000005cafbe in _PyFunction_FastCallDict ()
> #20 0x000000000053a811 in _PyEval_EvalFrameDefault ()
> #21 0x00000000005373a7 in _PyEval_EvalCodeWithName ()
> #22 0x00000000005c9de8 in _PyFunction_FastCallKeywords ()
> #23 0x0000000000536640 in ?? ()
> #24 0x000000000053d381 in _PyEval_EvalFrameDefault ()
> #25 0x00000000005373a7 in _PyEval_EvalCodeWithName ()
> #26 0x000000000064d2a3 in PyEval_EvalCode ()
> #27 0x00000000006409c3 in ?? ()
> #28 0x0000000000640a77 in PyRun_FileExFlags ()
> #29 0x000000000064182a in PyRun_SimpleFileExFlags ()
> #30 0x000000000067942f in ?? ()
> #31 0x000000000067971e in _Py_UnixMain ()
> #32 0x00007ffff7e13bbb in __libc_start_main (main=0x4cfc60 <main>, argc=2, argv=0x7fffffffd4e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd4d8) at ../csu/libc-start.c:308
> #33 0x00000000005d030a in _start ()

**Comment by JoeyJiao** [comment]
frida version: 12.8.7
