### ISSUE TITLE
iOS - $ivars causes Frida to crash

### ISSUE THREAD

**Issue by Nightbringer21** [frida/frida#1182]
Trying to call $ivars on class instances causes Frida to throw an exception and crash, as shown below:
```
Traceback (most recent call last):
  File "/usr/local/bin/frida", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/frida_tools/repl.py", line 840, in main
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/frida_tools/application.py", line 186, in run
    self._reactor.run()
  File "/usr/local/lib/python3.6/dist-packages/frida_tools/application.py", line 560, in run
    self._run_until_return(self)
  File "/usr/local/lib/python3.6/dist-packages/frida_tools/repl.py", line 324, in _process_input
    if not self._eval_and_print(expression):
  File "/usr/local/lib/python3.6/dist-packages/frida_tools/repl.py", line 332, in _eval_and_print
    (t, value) = self._perform_on_reactor_thread(lambda: self._evaluate(expression))
  File "/usr/local/lib/python3.6/dist-packages/frida_tools/application.py", line 418, in _perform_on_reactor_thread
    raise error
  File "/usr/local/lib/python3.6/dist-packages/frida_tools/application.py", line 402, in work
    result[0] = f()
  File "/usr/local/lib/python3.6/dist-packages/frida_tools/repl.py", line 332, in <lambda>
    (t, value) = self._perform_on_reactor_thread(lambda: self._evaluate(expression))
  File "/usr/local/lib/python3.6/dist-packages/frida_tools/repl.py", line 486, in _evaluate
    result = self._script.exports.frida_repl_evaluate(text)
  File "/usr/local/lib/python3.6/dist-packages/frida/core.py", line 401, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/frida/core.py", line 333, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: Unable to handle type undefined
    at readType (frida/node_modules/frida-objc-bridge/index.js:2176)
    at u (frida/node_modules/frida-objc-bridge/index.js:1188)
    at frida/node_modules/frida-objc-bridge/index.js:1144
    at frida/node_modules/frida-objc-bridge/index.js:1226
    at reduce (native)
    at c (frida/node_modules/frida-objc-bridge/index.js:1228)
    at stringify (native)
    at frida/node_modules/core-js/library/modules/es6.symbol.js:111
    at frida/runtime/core.js:48

```
This seems to be associated with how the variable object is mapped in Swift compared to it being called through the ObjC binding. Getting an ivar description for the item as follows reveals that some of the values are marked as not representable (for reference, the application is DVIA-v2 SWIFT).

```
[iOS Device::DVIA-v2]-> sensitive._ivarDescription().toString()                                                                                          
"<DVIA_v2.SensitiveInformationViewController: 0x102b5bf00>:\nin DVIA_v2.SensitiveInformationViewController:\n\tusername (): **Value not representable**, \n\tpassword (): **Value not representable**, \nin ...
```
On another issue, it was also mentioned that you can use Stalker/MemoryAccessMonitor to gain access to these values. Could you provide an example?

**Comment by rainbowcardiod** [comment]
One work around is using a theos tweak and using `objc_getClass`, `class_getInstanceVariable` and `object_getIvar`
