### ISSUE TITLE
_frida.ProcessNotFoundError

### ISSUE THREAD

**Issue by xiaoxiaotu** [frida/frida#125]
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    session = frida.attach("cat")
  File "/usr/local/lib/python2.7/dist-packages/frida-6.2.0-py2.7-linux-x86_64.egg/frida/**init**.py", line 55, in attach
    return get_local_device().attach(target)
  File "/usr/local/lib/python2.7/dist-packages/frida-6.2.0-py2.7-linux-x86_64.egg/frida/core.py", line 87, in attach
    return Session(self._impl.attach(self._pid_of(target)))
  File "/usr/local/lib/python2.7/dist-packages/frida-6.2.0-py2.7-linux-x86_64.egg/frida/core.py", line 99, in _pid_of
    return self.get_process(target).pid
  File "/usr/local/lib/python2.7/dist-packages/frida-6.2.0-py2.7-linux-x86_64.egg/frida/core.py", line 64, in get_process
    raise _frida.ProcessNotFoundError("ambiguous name; it matches: %s" % ", ".join(["%s (pid: %d)" % (process.name, process.pid) for process in matching]))
frida.ProcessNotFoundError: ambiguous name; it matches: cat (pid: 2068), cat (pid: 3113)

**Comment by xiaoxiaotu** [comment]
why exist two cat pid,it's the problme ?

**Comment by oleavr** [comment]
I'm afraid it's because your system has two `cat` processes running.
