### ISSUE TITLE
A Frida agent exception has occurred.

### ISSUE THREAD

**Issue by OsamaMahmood** [frida/frida#1255]
Getting this error when trying to dump arguments of a method call

A Frida agent exception has occurred.
TypeError: cannot read property 'address' of undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:56618)
    at /script1.js:10272
    at frida/runtime/message-dispatcher.js:15
    at o (frida/runtime/message-dispatcher.js:25)

Python stack trace: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/objection/commands/ios/hooking.py", line 234, in watch_class_method
    api.ios_hooking_watch_method(selector,
  File "/Users/osamamahmood/Library/Python/3.8/lib/python/site-packages/frida/core.py", line 401, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "/Users/osamamahmood/Library/Python/3.8/lib/python/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/Users/osamamahmood/Library/Python/3.8/lib/python/site-packages/frida/core.py", line 333, in _rpc_request
    raise result[2]
frida.core.RPCException: TypeError: cannot read property 'address' of undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:56618)
    at /script1.js:10272
    at frida/runtime/message-dispatcher.js:15
    at o (frida/runtime/message-dispatcher.js:25)

**Comment by leonjza** [comment]
@OsamaMahmood this is specific to [objection](https://github.com/sensepost/objection) and you should rather open the issue there.

**Comment by OsamaMahmood** [comment]
thanks @leonjza
