### ISSUE TITLE
frida-server and frida-gadget doesnt run on Android 11 image

### ISSUE THREAD

**Issue by eybisi** [frida/frida#1292]
Since new [android](https://android-developers.googleblog.com/2020/03/run-arm-apps-on-android-emulator.html) 11 developer system images capable of translating ARM instructions to x86, I was trying to set up frida-server and work with arm only apps. But it turns out I cant connect to normal apps on android 11 image. When I start frida-server and connect with frida -U -f appname (all latest version 12.8.20)  app is closed and I get following debug log on logcat.
```
10793 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10793 F DEBUG   : Build fingerprint: 'google/sdk_gphone_x86_arm/generic_x86_arm:10/RPP4.200409.015/6455311:userdebug/dev-keys'
10793 F DEBUG   : Revision: '0'
10793 F DEBUG   : ABI: 'x86'
10793 F DEBUG   : Timestamp: 2020-05-06 21:04:55+0000
10793 F DEBUG   : pid: 535, tid: 10789, name: gum-js-loop  >>> system_server <<<
10793 F DEBUG   : uid: 1000
10793 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
10793 F DEBUG   : Abort message: 'Error: Java API only partially available; please file a bug. Missing: _ZN3art3Dbg9StartJdwpEv, _ZN3art3Dbg8GoActiveEv, _ZN3art3Dbg21RequestDeoptimizationERKNS_21DeoptimizationRequestE, _ZN3art3Dbg20ManageDeoptimizationEv, _ZN3art3Dbg9gRegistryE
10793 F DEBUG   :     at _getApi (frida/node_modules/frida-java-bridge/lib/android.js:378:1)
10793 F DEBUG   :     at getApi (frida/node_modules/frida-java-bridge/lib/android.js:93:1)
10793 F DEBUG   :     at tryInitialize (frida/node_modules/frida-java-bridge/index.js:39:1)
10793 F DEBUG   :     at new Runtime (frida/node_modules/frida-java-bridge/index.js:454:1)
10793 F DEBUG   :     at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:457:1)
10793 F DEBUG   :     at o (frida/node_modules/browser-pack/_prelude.js:1:1)
10793 F DEBUG   :     at frida/node_modules/browser-pack/_prelude.js:1:1
10793 F DEBUG   :     at Object.14.frida-java-bridge (frida/runtime/java.js:1:1)
10793 F DEBUG   :     at o (frida/node_modules/browser-pack/_prelude.js:1:1)
10793 F DEBUG   :     at r (frida/node_modules/browser-pack/_prelude.js:1:1)'
10793 F DEBUG   :     eax 00000000  ebx 00000217  ecx 00002a25  edx 00000006
10793 F DEBUG   :     edi e9597eae  esi b4d79248
10793 F DEBUG   :     ebp ed40db30  esp b4d791c8  eip ed40db39
10793 F DEBUG   : 
10793 F DEBUG   : backtrace:
10793 F DEBUG   :       #00 pc 00000b39  [vdso] (__kernel_vsyscall+9)
10793 F DEBUG   :       #01 pc 0005b058  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: f93c954efc24b8a2e43bc3d969ca228c)
10793 F DEBUG   :       #02 pc 00076833  /apex/com.android.runtime/lib/bionic/libc.so!libc.so (offset 0x75000) (abort+195) (BuildId: f93c954efc24b8a2e43bc3d969ca228c)
10793 F DEBUG   :       #03 pc 0021a01e  /data/local/tmp/re.frida.server/frida-agent-32.so
10793 F DEBUG   :       #04 pc 0010bcc3  /data/local/tmp/re.frida.server/frida-agent-32.so
```

**Comment by oleavr** [comment]
Please switch to Frida from git; we have an Android 11 fix that hasn't made it into a release yet.
