### ISSUE TITLE
Script is destroyed - crashes app

### ISSUE THREAD

**Issue by T3rm1** [frida/frida#1294]
I have Frida server running on my phone and connect remotely over wifi to it with

`frida-discover -H 192.168.178.24 -F`

The app then crashes. Server is still running. Happens with every app.

```
C:\Users\T3rm1>frida-discover -H 192.168.178.24 -F
Injecting script...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python37-32\lib\site-packages\frida_tools\application.py", line 604, in _run
    work()
  File "c:\python37-32\lib\site-packages\frida_tools\application.py", line 317, in _try_start
    self._start()
  File "c:\python37-32\lib\site-packages\frida_tools\discoverer.py", line 35, in _start
    self._discoverer.start(self._session, self._runtime, self)
  File "c:\python37-32\lib\site-packages\frida_tools\discoverer.py", line 89, in start
    params = self._script.exports.start()
  File "c:\python37-32\lib\site-packages\frida\core.py", line 401, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "c:\python37-32\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "c:\python37-32\lib\site-packages\frida\core.py", line 333, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script is destroyed
```

**Comment by kmille** [comment]
I'm having the same issue
