### ISSUE TITLE
Spawn application in x86 error from Frida 12.10.4

### ISSUE THREAD

**Issue by ags1236126** [frida/frida#1363]
I have a problem with frida server 12.10.4, in fact when I try to use frida for an application, I get the following error message.

Failed to spawn: java.lang.SecurityException: Not allowed to start activity Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=XXXX cmp=XXXX/.view.activity.HomeActivity }

I searched the internet but couldn't find anyone with a similar problem.
I found this issue (https://github.com/frida/frida/issues/683) but it's more than 2 years old and has no answers.

I had to anonymize some information (hence the XXXX). 
If needed I can provide more information about this bug.

I use Frida server x86 12.10.4 and a GenyMotion 3.1.0 emulator.
I emulate a Google Nexus 5 with Android 4.4 (Api 19)

Here's an output of logcat
Hope it helps !
```
PackageManager( 9190): at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:994) W/PackageManager( 9190): at android.content.pm.PackageItemInfo.loadLabel(PackageItemInfo. java:115) W/PackageManager( 9190): at dalvik.system.NativeStart.run(Native Method) W/PackageManager( 9190): at dalvik.system.NativeStart.run(Native Method) I/ActivityManager( 9190): Force stopping XXXXX appid=10076 user=0: from pid 9190 W/ContextImpl( 9190): Calling a method in the system process without a qualified user: android.app.ContextImpl.startActivity:1028 android.content.ContextWrapper.startActivity:311 dalvik.system.NativeStart.run:-2 dalvik.system.NativeStart.run:-2 <bottom of call stack> W/ContextImpl( 9190): Calling a method in the system process without a qualified user: android.app.ContextImpl.startActivity:1040 android.app.ContextImpl.startActivity:1029 android.content.ContextWrapper.startActivity:311 dalvik.system.NativeStart.run:-2 dalvik.system.NativeStart.run:-2 W/ActivityManager( 9190): Unable to find app for caller android.app.ActivityThread$ApplicationThread@52a07154 (pid=-1) when starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=XXXXX cmp=XXXXX/.view.activity.HomeActivity }
```

**Comment by securityhook** [comment]
Same issue with same Device on GenyMotion

**Comment by jxnuwangyankun** [comment]
same problem Here.I searched a lot on the internet only to find no answer.
I use Frida server arm 12.11.9 and Huawei H60-L01
my error message is
"Failed to spawn: java.lang.SecurityException: Not allowed to start activity Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.example.testdemo cmp=com.example.testdemo/.MainActivity } "
