### ISSUE TITLE
iPhone 8: Stalker events empty when calling functions

### ISSUE THREAD

**Issue by jiska2342** [frida/frida#1386]
Hi,

one more bug we observed during fuzzing ;)

A while ago, @ttdennis told me the fuzzer wouldn't work on his iPhone 8 because he couldn't call functions and stalk them in parallel. Since I got it working on my iPhone 7, 11, and SE2, I now tried it on my iPhone 8 and have the same issue.

Setup: iPhone 8, iOS 13.6, checkra1n 0.10.2 jailbreak, Frida 12.10.4. The issue shouldn't be too specific to these versions, though, except from the iPhone 8.

@ttdennis did a couple of changes to `frizzer` for fuzzing `bluetoothd`, however, the basic functionality is still the same. You can find the full Frida script [here](https://github.com/demantz/frizzer/blob/master/frizzer/frida_script.js#L65), which is then being polled by a [Python script](https://github.com/demantz/frizzer/blob/master/frizzer/fuzzer.py#L166). The essential part is the following:

```
    settarget: function(target) {
        debug("Target: " + target)
        target_function = ptr(target)

        Interceptor.attach(target_function, {
            onEnter: function (args) {
                Stalker.queueCapacity = 100000000
                Stalker.queueDrainInterval = 1000*1000

                debugCov("follow")
                stalker_events = undefined
                Stalker.follow(Process.getCurrentThreadId(), {
                    events: {
                        call: false,
                        ret: false,
                        exec: false,
                        block: false,
                        compile: true
                    },
                    onReceive: function (events) {
                        debugCov("onReceive")
                        var bbs = Stalker.parse(events,
                            {stringify: false, annotate: false});
                        if(stalker_events != undefined) {
                            warning("onReceive: Got another stalker event!")
                        }
                        stalker_events = bbs
                    }
                    /*onCallSummary: function (summary) {
                        console.log("onCallSummary: " + JSON.stringify(summary))
                    }*/
                });
            },
            onLeave: function (retval) {
                debugCov("unfollow")
                Stalker.unfollow(Process.getCurrentThreadId())
                debugCov("flush")
                Stalker.flush();
                if(gc_cnt % 100 == 0){
                    Stalker.garbageCollect();
                }
                gc_cnt++;
            }
        });
    },

```

Any ideas why this is blocking or doesn't work in parallel, despite seamlessly working on an iPhone 7 with the same Frida version?

**Comment by jiska2342** [comment]
Hi,

this issue still persists. I tried to minimize yet another fuzzing script, fuzzing yet another thing :) Since [`ToothPicker`](https://github.com/seemoo-lab/toothpicker) was released meanwhile, you might also be able to check out that project instead to reproduce the issue.

Device setup, both running Frida 12.11.17:

* iPhone 7, iOS 13.7 (17H35) - this one works
* iPhone 8, iOS 13.7 (17H35) - this one doesn't work

Yes, the IPSW is the same for the iPhone 7 and 8 despite the different processor :) I also have multiple iPhone 7 and 8 by now, so this is really the difference between the iPhone models and no other configuration issue. Both of them jailbroken with recent `checkm8` and so on.

When I attach to a function *and* stalk it, only the iPhone 8 produces the following exception:
```
<class 'frida.core.RPCException'>, RPCException('access violation accessing 0x10a49c000', 'Error', 'Error: access violation accessing 0x10a49c000\n    at /script1.js:153\n    at frida/runtime/message-dispatcher.js:15\n    at o (frida/runtime/message-dispatcher.js:25)'), <traceback object at 0x7fa75275bf00>
```

I think `ToothPicker` filters this error message somewhere, that's why I claimed it would not return any events in the previous bug description. This is also the case in my example, the `on_message` function is never called because the Frida script terminates.

JavaScript injected with Frida:
```
var _fuzz_me = ...;  // skipped on purpose, sorry ;)

// Enable coverage via stalker
var collect_coverage = true;
var gc_cnt = 0;
Stalker.trustThreshold = 0;

// Fuzzer
Interceptor.attach(_fuzz_me, {
    onEnter: function(args) {

        // Code that adjusts input skipped.
        // Required since we also need to adjust input when the function is called by iOS directly.

        // Coverage collection similar to ToothPicker/frizzer
        if (collect_coverage) {
            // (1)
            Stalker.follow({
                // (2)
                events: {
                    call: false,   // we don't need CALL instructions
                    ret: false,    // we don't need RET instructions
                    exec: false,   // we don't need all instructions
                    block: false,  // we don't need block executions
                    compile: true, // but we want trace compiled blocks for coverage
                },
                onReceive: function (events) {
                    // onReceive: Called with events containing a binary blob
                    //            comprised of one or more GumEvent structs.
                    //            See `gumevent.h` for details about the
                    //            format. Use `Stalker.parse()` to examine the
                    //            data.
                    // (3)
                    const bbs = Stalker.parse(events, {
                        stringify: true,
                        annotate: false
                    });
                    // (4)
                    send({
                        msgType: "coverage",
                        payload: bbs
                    })
                }
            });
        }
    },
    onLeave: function (retval) {
        if (collect_coverage) {
            // (5)
            Stalker.unfollow();
            Stalker.flush();
            // (6)
            gc_cnt++;
            if (gc_cnt % 100 === 0) {
                Stalker.garbageCollect();
            }
        }
    }
});



// Callable export, JSON serializable args
rpc.exports = {

    // Export the function for fuzzing.
    fuzzme: function (payload) {
        const payload_array = [];
        for (var i = 0; i < payload.length; i+=2) {
            payload_array.push(parseInt(payload.substring(i, i + 2), 16));
        }

        // Copy to buffer
        Memory.writeByteArray(payload_buffer, payload_array);

        _fuzz_me(payload_buffer, payload.length/2);
    }
};

```

Python side, obviously:
```
def on_message(message, data):
    if message_type == 'coverage':
        print("Got coverage event!")
        return
```

The issue also persists if I remove the last `events` option with `compile: false` and skip the `Stalker.parse` step, as well as setting different `trustThreshold` values.

Do you have any idea how to proceed with debugging on the iPhone 8?

**Comment by nezza** [comment]
I can confirm this issue, even a very simple Stalker example does not work on the iPhone X (running 14.3, Frida 14.2.3)

**Comment by jiska2342** [comment]
Yep, the issue persists on the iPhone 8 for me, as well. Currently on iOS 14.3 and 14.4 Beta here with the most recent Frida. The same scripts work on my iPhone 7, which uses the same iOS IPSWs/versions. The only difference is A10 vs. A11, so it might be an issue deep down in the dynamic function patching / Capstone?

**Comment by oleavr** [comment]
Thanks for reporting! If the target process doesn't crash, and the stalked thread continues running normally, then that means it's an unhandled branch instruction – meaning Stalker incorrectly recompiles a specific basic block. If you could figure out what the last block encountered is, that would be super-helpful. Enabling `block` events is usually the easiest, and looking at which instruction(s) the last one contains.

**Comment by nezza** [comment]
Hello,
The target process does crash, here is a very simple example that works on iPhone 7 but crashes on iPhone X, here is the full output:
```
Resumed
Attached
Thread ID: 1287
Thread ID: 3847
Thread ID: 5899
Thread ID: 6915
Thread ID: 8199
Thread ID: 10775
Thread ID: 11779
Thread ID: 15371
Traceback (most recent call last):
  File "/Users/thomas/code/tmp/frida/stalkertest.py", line 67, in <module>
    main()
  File "/Users/thomas/code/tmp/frida/stalkertest.py", line 62, in main
    script.load()
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 254, in load
    self._impl.load()
frida.TransportError: the connection is closed
```

Full script: 
https://gist.github.com/nezza/ba9bc0e4e25e366d4d1641eca22210cd
