### ISSUE TITLE
Cannot install via pip on OS X 10.11.4 with python 2.7 or 3.5

### ISSUE THREAD

**Issue by vvilhonen** [frida/frida#140]
**Exception: Could not find prebuilt Frida extension. Prebuilts only provided for python 2.6-2.7 and 3.5**

Output from python 3.5

```
» sudo -H pip3.5 install frida                                                                                                                                                                                                  1 ↵
Collecting frida
  Using cached frida-7.1.5.zip
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.2.7 in /usr/local/lib/python3.5/site-packages (from frida)
Requirement already satisfied (use --upgrade to upgrade): prompt-toolkit>=0.57 in /usr/local/lib/python3.5/site-packages (from frida)
Requirement already satisfied (use --upgrade to upgrade): pygments>=2.0.2 in /usr/local/lib/python3.5/site-packages (from frida)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/local/lib/python3.5/site-packages (from prompt-toolkit>=0.57->frida)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in /usr/local/lib/python3.5/site-packages (from prompt-toolkit>=0.57->frida)
Building wheels for collected packages: frida
  Running setup.py bdist_wheel for frida ... error
  Complete output from command /usr/local/opt/python3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-47pibif6/frida/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpj3razfdzpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.11-x86_64-3.5
  creating build/lib.macosx-10.11-x86_64-3.5/frida
  copying frida/__init__.py -> build/lib.macosx-10.11-x86_64-3.5/frida
  copying frida/application.py -> build/lib.macosx-10.11-x86_64-3.5/frida
  copying frida/core.py -> build/lib.macosx-10.11-x86_64-3.5/frida
  copying frida/discoverer.py -> build/lib.macosx-10.11-x86_64-3.5/frida
  copying frida/lsd.py -> build/lib.macosx-10.11-x86_64-3.5/frida
  copying frida/ps.py -> build/lib.macosx-10.11-x86_64-3.5/frida
  copying frida/repl.py -> build/lib.macosx-10.11-x86_64-3.5/frida
  copying frida/tracer.py -> build/lib.macosx-10.11-x86_64-3.5/frida
  running build_ext
  downloading prebuilt extension from https://pypi.python.org/packages/3.5/f/frida/frida-7.1.5-py3.5-macosx-10.6-intel.egg
  trying to get prebuilt extension from the current folder /private/tmp/pip-build-47pibif6/frida/frida-7.1.5-py3.5-macosx-10.6-intel.egg
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/tmp/pip-build-47pibif6/frida/setup.py", line 138, in <module>
      'build_ext': FridaPrebuiltExt
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 176, in run
      self.run_command('build')
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49, in run
      _build_ext.run(self)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
      self.build_extensions()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/tmp/pip-build-47pibif6/frida/setup.py", line 80, in build_extension
      raise Exception("Could not find prebuilt Frida extension. "
  Exception: Could not find prebuilt Frida extension. Prebuilts only provided for python 2.6-2.7 and 3.5

  ----------------------------------------
  Failed building wheel for frida
  Running setup.py clean for frida
Failed to build frida
Installing collected packages: frida
  Running setup.py install for frida ... error
    Complete output from command /usr/local/opt/python3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-47pibif6/frida/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0lq6nmpe-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-x86_64-3.5
    creating build/lib.macosx-10.11-x86_64-3.5/frida
    copying frida/__init__.py -> build/lib.macosx-10.11-x86_64-3.5/frida
    copying frida/application.py -> build/lib.macosx-10.11-x86_64-3.5/frida
    copying frida/core.py -> build/lib.macosx-10.11-x86_64-3.5/frida
    copying frida/discoverer.py -> build/lib.macosx-10.11-x86_64-3.5/frida
    copying frida/lsd.py -> build/lib.macosx-10.11-x86_64-3.5/frida
    copying frida/ps.py -> build/lib.macosx-10.11-x86_64-3.5/frida
    copying frida/repl.py -> build/lib.macosx-10.11-x86_64-3.5/frida
    copying frida/tracer.py -> build/lib.macosx-10.11-x86_64-3.5/frida
    running build_ext
    downloading prebuilt extension from https://pypi.python.org/packages/3.5/f/frida/frida-7.1.5-py3.5-macosx-10.6-intel.egg
    trying to get prebuilt extension from the current folder /private/tmp/pip-build-47pibif6/frida/frida-7.1.5-py3.5-macosx-10.6-intel.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-47pibif6/frida/setup.py", line 138, in <module>
        'build_ext': FridaPrebuiltExt
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49, in run
        _build_ext.run(self)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/private/tmp/pip-build-47pibif6/frida/setup.py", line 80, in build_extension
        raise Exception("Could not find prebuilt Frida extension. "
    Exception: Could not find prebuilt Frida extension. Prebuilts only provided for python 2.6-2.7 and 3.5

    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-47pibif6/frida/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0lq6nmpe-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-47pibif6/frida/
```

**Comment by reu-res** [comment]
Me too. Arch linux, python 2.7.11
```
sudo pip2 install -U frida
Collecting frida
  Using cached frida-7.1.5.zip
Requirement already up-to-date: colorama>=0.2.7 in /usr/lib/python2.7/site-packages (from frida)
Requirement already up-to-date: prompt-toolkit>=0.57 in /usr/lib/python2.7/site-packages (from frida)
Requirement already up-to-date: pygments>=2.0.2 in /usr/lib/python2.7/site-packages (from frida)
Requirement already up-to-date: six>=1.9.0 in /usr/lib/python2.7/site-packages (from prompt-toolkit>=0.57->frida)
Requirement already up-to-date: wcwidth in /usr/lib/python2.7/site-packages (from prompt-toolkit>=0.57->frida)
Installing collected packages: frida
  Found existing installation: frida 7.1.4
    Uninstalling frida-7.1.4:
      Successfully uninstalled frida-7.1.4
  Running setup.py install for frida ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-q7ZkZH/frida/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-R8qrkN-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/frida
    copying frida/__init__.py -> build/lib.linux-x86_64-2.7/frida
    copying frida/tracer.py -> build/lib.linux-x86_64-2.7/frida
    copying frida/repl.py -> build/lib.linux-x86_64-2.7/frida
    copying frida/ps.py -> build/lib.linux-x86_64-2.7/frida
    copying frida/lsd.py -> build/lib.linux-x86_64-2.7/frida
    copying frida/discoverer.py -> build/lib.linux-x86_64-2.7/frida
    copying frida/core.py -> build/lib.linux-x86_64-2.7/frida
    copying frida/application.py -> build/lib.linux-x86_64-2.7/frida
    running build_ext
    downloading prebuilt extension from https://pypi.python.org/packages/2.7/f/frida/frida-7.1.5-py2.7-linux-x86_64.egg
    trying to get prebuilt extension from the current folder /tmp/pip-build-q7ZkZH/frida/frida-7.1.5-py2.7-linux-x86_64.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-q7ZkZH/frida/setup.py", line 138, in <module>
        'build_ext': FridaPrebuiltExt
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 49, in run
        _build_ext.run(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "/tmp/pip-build-q7ZkZH/frida/setup.py", line 80, in build_extension
        raise Exception("Could not find prebuilt Frida extension. "
    Exception: Could not find prebuilt Frida extension. Prebuilts only provided for python 2.6-2.7 and 3.5
    
    ----------------------------------------
  Rolling back uninstall of frida
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-q7ZkZH/frida/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-R8qrkN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-q7ZkZH/frida/
```

**Comment by MariasStory** [comment]
Me too in Ubuntu.
There seems to be a hard codded python number that doesn't much the subversion and stops the installation.

**Comment by 0xABD** [comment]
PyPi packages now seem to be distributed from different URLs.
I confirm same errors while installing Frida from Python on all platforms.

**Comment by oleavr** [comment]
Should no longer be an issue in latest Frida 9.x – we now honor proxy settings.
