### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by salisbury-espinosa** [frida/frida#1416]
frida reports device not found but adb can discover it:
adb output
```
adb devices
List of devices attached
V2PgL7 	device
```
frida output:  
```
Device 'V2PgL7' not found
```
test by:
```
/home/user/anaconda3/bin/python /home/user/.local/bin/frida -D V2PgL7 -f re.frida.Gadget --no-pause -l ./frida_compiled.js --runtime v8
```

**Comment by salisbury-espinosa** [comment]
sometimes phone from 'adb devices' dont exists in 'frida-ls-devices'

**Comment by salisbury-espinosa** [comment]
when you call it again, the device is detected

```
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida
>>> frida.get_device('V2PgL7')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.7/site-packages/frida/__init__.py", line 86, in get_device
    return get_device_manager().get_device(id, timeout, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/frida/core.py", line 48, in get_device
    return self.get_device_matching(lambda d: d.id == id, timeout, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/frida/core.py", line 58, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
frida.InvalidArgumentError: device not found

>>> frida.get_device('V2PgL7')
Device(id="V2PgL7", name="Redmi Go", type='usb')
```

**Comment by salisbury-espinosa** [comment]
will be fixed here by adding timeout: 
https://github.com/frida/frida-tools/blob/master/frida_tools/application.py#L263
` self._device = frida.get_device(self._device_id)` -> ` self._device = frida.get_device(self._device_id, 1000)`
