### ISSUE TITLE
frida.NotSupportedError: failed to get the task for process xxx 

### ISSUE THREAD

**Issue by aaisha79** [frida/frida#1457]
Hey guys

Hopefully one of you guys can help me out here:

I am trying the following, in a test.py file:

import frida

device = frida.get_usb_device()
pid = device.spawn(["com.xx.xxx.xxxxx"])

However it fails with the following error:

Traceback (most recent call last):
File "test.py", line 4, in
pid = device.spawn(["com.xxx.xxx.xxxx"])
File "/usr/local/lib/python3.8/site-packages/frida/core.py", line 26, in wrapper
return f(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/frida/core.py", line 140, in spawn
return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: failed to get the task for process 823

I am running Frida version 12.11.17 on both my mac and JB iOS device (JB'd using checkra1n)

Thanks

**Comment by aaisha79** [comment]
Resolved by installing FRIDA for Pre A12 devices as JB device in question was iphone 6
