### ISSUE TITLE
frida.PermissionDeniedError: unable to access process with pid 22211 due to system restrictions

### ISSUE THREAD

**Issue by 1121aa** [frida/frida#1492]
Android9.0  64
frida 14.0.5 
frida-server-14.0.5-android-arm64

device.spawn(['/bin/sh', '-c', '/data/local/test'])

I am use spawn to start a arm application
then get err:

✔ spawn(argv=test)
✔ attach(pid=22205)
⚡ child_added: Child(pid=22211, parent_pid=22205, origin=fork)
✔ attach(pid=22211)
⚡ child_removed: Child(pid=22211, parent_pid=22205, origin=fork)
⚡ child_added: Child(pid=22211, parent_pid=22211, origin=exec, path='./test')
✔ attach(pid=22211)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_innerself.run()
  File "C:\Python38\lib\threading.py", line 870, in run self._target(*self._args, **self._kwargs)
  File "E:\Projects\test\so_hook\lib\site-packages\frida_tools\application.py", line 635, in _runwork()
  File "E:\Projects\test\main.py", line 1477, in <lambda> self._device.on("child-added", lambda child: self._reactor.schedule(lambda: self._on_child_added(child)))
  File "E:\Projects\test\main.py", line 1800, in _on_child_added self._instrument(child.pid, 1)
  File "E:\Projects\test\main.py", line 1760, in _instrument session = self._device.attach(pid)
  File "E:\Projects\test\so_hook\lib\site-packages\frida\core.py", line 26, in wrapper return f(*args, **kwargs)
  File "E:\Projects\test\so_hook\lib\site-packages\frida\core.py", line 156, in attach return Session(self._impl.attach(self._pid_of(target)))
**frida.PermissionDeniedError: unable to access process with pid 22211 due to system restrictions; try `sudo sysctl kernel.yama.ptrace_scope=0`, or run Frida as root**

**Comment by CtrlAltDelet** [comment]
did you solve it ? i met the same error ths

**Comment by xmicro** [comment]
Still a problem for me.
