### ISSUE TITLE
frida-discover and frida-trace fails with Enum type ScriptRuntime does not have a value named 'duk'

### ISSUE THREAD

**Issue by ajpagente** [frida/frida#1494]
**System:**
MacOS 10.15.1, frida 14.0.5
**Device:**
iPhone SE (1st gen), iOS 13.6.1, frida-server 14.0.5 iOS arm64

On the device, I run frida-server manually:
```
./frida-server &
```

frida-ps -U works however I am not able to attach to a process...

When running frida-trace, I get this error:
```
$ frida-trace -U -p 707 -i "*"
Failed to start tracing: Enum type ScriptRuntime does not have a value named 'duk', it only has: 'default', 'qjs', 'v8'
```

When running frida-discover, I get this error:
```
$ frida-discover -U -p 707
Injecting script...                                                     
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/frida_tools/application.py", line 527, in _run
    work()
  File "/usr/local/lib/python3.7/site-packages/frida_tools/application.py", line 301, in _try_start
    self._start()
  File "/usr/local/lib/python3.7/site-packages/frida_tools/discoverer.py", line 35, in _start
    self._discoverer.start(self._session, self._runtime, self)
  File "/usr/local/lib/python3.7/site-packages/frida_tools/discoverer.py", line 85, in start
    runtime=runtime)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 204, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
ValueError: Enum type ScriptRuntime does not have a value named 'duk', it only has: 'default', 'qjs', 'v8'
```

**Comment by oleavr** [comment]
It means your `frida` is too old compared to your `frida-tools`. The setup.py specifies the requirement, so this is odd as it shouldn't have let you upgrade one without the other.

**Comment by oleavr** [comment]
Oops, it's actually the opposite: your `frida-tools` is too old 🙂

**Comment by ajpagente** [comment]
Wow I should have checked frida-tools :S Sorry for the trouble, it's fine now. Thanks for the quick response @oleavr :)
