### ISSUE TITLE
Frida 14.0.8: --debug option with QuickJs causes "Failed to attach: v8 runtime not available due to build configuration"

### ISSUE THREAD

**Issue by Samulia-Sanchez** [frida/frida#1524]
I was trying to connect Frida 14.0.8 to frida-gadget injected into an android app. And it always failed.
IWhen the --debug option is used, it says:
**Failed to attach: v8 runtime not available due to build configuration**

I was not even trying to use v8 though, since that's not available anymore. 
I am also not even sure what the --debug option changes, and just had it in my scripts for ages now, so I removed it to make things work.

**Configuration**
frida             14.0.8
frida-tools       9.0.0
Windows 10

**Command's used**
frida -U -n Gadget -l libscript.so --no-pause --debug --runtime qjs
frida -U -n Gadget -l libscript.so --no-pause --debug 

**Output:**
    ____
    / _  |   Frida 14.0.8 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Failed to attach: v8 runtime not available due to build configuration
Traceback (most recent call last):
  File "c:\users\samulia\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\samulia\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\samulia\AppData\Local\Programs\Python\Python39\Scripts\frida.exe\__main__.py", line 7, in <module>
  File "C:\Users\samulia\AppData\Roaming\Python\Python39\site-packages\frida_tools\repl.py", line 855, in main
    app.run()
  File "C:\Users\samulia\AppData\Roaming\Python\Python39\site-packages\frida_tools\application.py", line 213, in run
    self._session.off('detached', self._schedule_on_session_detached)
  File "C:\Users\samulia\AppData\Roaming\Python\Python39\site-packages\frida\core.py", line 230, in off
    self._impl.off(signal, callback)
ValueError: unknown callback

**Comment by etuttle** [comment]
Ran into the same issue.  Fallout from the ultra-sudden switch to QuickJS, I suppose.  I'm impressed by how fast frida is moving, but it's disappointing that Dev Tools debugging didn't work the first time I needed it.
