### ISSUE TITLE
Regression in frida-gadget in version 14 with libhoudini

### ISSUE THREAD

**Issue by willish** [frida/frida#1556]
I am using frida-gadget 12.11.18 to successfully hook into ARM native libraries when using the ldplayer emulator (4.0.39), Android 7.

However, using Frida version 14, it fails with assertion error: `frida-core/lib/gadget/gadget.vala:679:frida_gadget_detect_location: assertion failed: (our_range != null)`

Any hints on what might be causing this?  Could the change to QuickJs from DuckTape have this kind of side-effect ?

Thank you for all your superhuman efforts on creating this wonderful tool.

```
12-04 04:57:29.978  2567  2567 I CocosAnalytics: ==> enableLogging: false
12-04 04:57:29.992  2567  2567 V libnb   : enter native_bridge2_isSupported /data/app/com.someappcompany.SomeApp-1/lib/arm/libcocos2djs.so
12-04 04:57:29.992  2567  2567 V libnb   : enter native_bridge2_loadLibrary /data/app/com.someappcompany.SomeApp-1/lib/arm/libcocos2djs.so
12-04 04:57:30.551  2567  2567 F Frida   : frida-core/lib/gadget/gadget.vala:679:frida_gadget_detect_location: assertion failed: (our_range != null)
--------- beginning of crash
12-04 04:57:30.551  2567  2567 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 2567 (pgame.SomeApp)
12-04 04:57:30.551  1239  1239 W         : debuggerd: handling request: pid=2567 uid=10047 gid=10047 tid=2567
12-04 04:57:30.616  2614  2614 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-04 04:57:30.616  2614  2614 F DEBUG   : Build fingerprint: 'google/android_x86/x86:7.1.2/N2G47H/4565141:/release-keys'
12-04 04:57:30.616  2614  2614 F DEBUG   : Revision: '0'
12-04 04:57:30.616  2614  2614 F DEBUG   : ABI: 'x86'
12-04 04:57:30.616  2614  2614 F DEBUG   : pid: 2567, tid: 2567, name: pgame.SomeApp  >>> com.someappcompany.SomeApp <<<
12-04 04:57:30.616  2614  2614 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
12-04 04:57:30.617  2614  2614 F DEBUG   : Abort message: 'frida-core/lib/gadget/gadget.vala:679:frida_gadget_detect_location: assertion failed: (our_range != null)'
12-04 04:57:30.617  2614  2614 F DEBUG   :     eax 00000000  ebx 00000a07  ecx 00000a07  edx 00000006
12-04 04:57:30.617  2614  2614 F DEBUG   :     esi c7ffe98c  edi c7ffe934
12-04 04:57:30.617  2614  2614 F DEBUG   :     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
12-04 04:57:30.617  2614  2614 F DEBUG   :     eip c7f29c10  ebp cfffc428  esp cfffc3cc  flags 00000296
12-04 04:57:30.619  2614  2614 F DEBUG   :
12-04 04:57:30.619  2614  2614 F DEBUG   : backtrace:
12-04 04:57:30.619  2614  2614 F DEBUG   :     #00 pc 00000c10  [vdso:c7f29000] (__kernel_vsyscall+16)
12-04 04:57:30.619  2614  2614 F DEBUG   :     #01 pc 0007aadc  /system/lib/libc.so (tgkill+28)
12-04 04:57:30.619  2614  2614 F DEBUG   :     #02 pc 000762b5  /system/lib/libc.so (pthread_kill+85)
12-04 04:57:30.619  2614  2614 F DEBUG   :     #03 pc 00027caa  /system/lib/libc.so (raise+42)
12-04 04:57:30.619  2614  2614 F DEBUG   :     #04 pc 0001eeb6  /system/lib/libc.so (abort+86)
12-04 04:57:30.619  2614  2614 F DEBUG   :     #05 pc 00009c1c  /system/lib/libhoudini.so (offset 0x219000)
12-04 04:57:31.010  1239  1239 W         : debuggerd: resuming target 2567
12-04 04:57:31.020  1454  1472 I BootReceiver: Copying /data/tombstones/tombstone_01 to DropBox (SYSTEM_TOMBSTONE)
12-04 04:57:31.028  1293  1293 I Zygote  : Process 2567 exited due to signal (6)
12-04 04:57:31.043  1454  2619 I WindowManager: Screen frozen for +1s666ms due to AppWindowToken{3d7d5fa token=Token{b287c1c ActivityRecord{59a518f u0 com.someappcompany.SomeApp/org.cocos2dx.javascript.AppActivity t3}}}
12-04 04:57:31.043  1454  2619 W ActivityManager:   Force finishing activity com.someappcompany.SomeApp/org.cocos2dx.javascript.AppActivity
12-04 04:57:31.046  1454  2619 W ActivityManager: Exception thrown during pause
12-04 04:57:31.046  1454  2619 W ActivityManager: android.os.DeadObjectException
12-04 04:57:31.046  1454  2619 W ActivityManager:       at android.os.BinderProxy.transactNative(Native Method)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at android.os.BinderProxy.transact(Binder.java:615)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:785)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1145)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3531)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3367)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:1855)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:619)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:477)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:353)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.AppErrors.crashApplication(AppErrors.java:305)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13676)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
12-04 04:57:31.047  1285  1285 E lowmemorykiller: Error opening /proc/2567/oom_score_adj; errno=2
12-04 04:57:31.047  1454  2619 W ActivityManager: Failed setting process group of 2567 to 1

`12-04 04:57:29.978  2567  2567 I CocosAnalytics: ==> enableLogging: false
12-04 04:57:29.992  2567  2567 V libnb   : enter native_bridge2_isSupported /data/app/com.someappcompany.SomeApp-1/lib/arm/libcocos2djs.so
12-04 04:57:29.992  2567  2567 V libnb   : enter native_bridge2_loadLibrary /data/app/com.someappcompany.SomeApp-1/lib/arm/libcocos2djs.so
12-04 04:57:30.551  2567  2567 F Frida   : frida-core/lib/gadget/gadget.vala:679:frida_gadget_detect_location: assertion failed: (our_range != null)
--------- beginning of crash
12-04 04:57:30.551  2567  2567 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 2567 (pgame.SomeApp)
12-04 04:57:30.551  1239  1239 W         : debuggerd: handling request: pid=2567 uid=10047 gid=10047 tid=2567
12-04 04:57:30.616  2614  2614 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-04 04:57:30.616  2614  2614 F DEBUG   : Build fingerprint: 'google/android_x86/x86:7.1.2/N2G47H/4565141:/release-keys'
12-04 04:57:30.616  2614  2614 F DEBUG   : Revision: '0'
12-04 04:57:30.616  2614  2614 F DEBUG   : ABI: 'x86'
12-04 04:57:30.616  2614  2614 F DEBUG   : pid: 2567, tid: 2567, name: pgame.SomeApp  >>> com.someappcompany.SomeApp <<<
12-04 04:57:30.616  2614  2614 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
12-04 04:57:30.617  2614  2614 F DEBUG   : Abort message: 'frida-core/lib/gadget/gadget.vala:679:frida_gadget_detect_location: assertion failed: (our_range != null)'
12-04 04:57:30.617  2614  2614 F DEBUG   :     eax 00000000  ebx 00000a07  ecx 00000a07  edx 00000006
12-04 04:57:30.617  2614  2614 F DEBUG   :     esi c7ffe98c  edi c7ffe934
12-04 04:57:30.617  2614  2614 F DEBUG   :     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
12-04 04:57:30.617  2614  2614 F DEBUG   :     eip c7f29c10  ebp cfffc428  esp cfffc3cc  flags 00000296
12-04 04:57:30.619  2614  2614 F DEBUG   :
12-04 04:57:30.619  2614  2614 F DEBUG   : backtrace:
12-04 04:57:30.619  2614  2614 F DEBUG   :     #00 pc 00000c10  [vdso:c7f29000] (__kernel_vsyscall+16)
12-04 04:57:30.619  2614  2614 F DEBUG   :     #01 pc 0007aadc  /system/lib/libc.so (tgkill+28)
12-04 04:57:30.619  2614  2614 F DEBUG   :     #02 pc 000762b5  /system/lib/libc.so (pthread_kill+85)
12-04 04:57:30.619  2614  2614 F DEBUG   :     #03 pc 00027caa  /system/lib/libc.so (raise+42)
12-04 04:57:30.619  2614  2614 F DEBUG   :     #04 pc 0001eeb6  /system/lib/libc.so (abort+86)
12-04 04:57:30.619  2614  2614 F DEBUG   :     #05 pc 00009c1c  /system/lib/libhoudini.so (offset 0x219000)
12-04 04:57:31.010  1239  1239 W         : debuggerd: resuming target 2567
12-04 04:57:31.020  1454  1472 I BootReceiver: Copying /data/tombstones/tombstone_01 to DropBox (SYSTEM_TOMBSTONE)
12-04 04:57:31.028  1293  1293 I Zygote  : Process 2567 exited due to signal (6)
12-04 04:57:31.043  1454  2619 I WindowManager: Screen frozen for +1s666ms due to AppWindowToken{3d7d5fa token=Token{b287c1c ActivityRecord{59a518f u0 com.someappcompany.SomeApp/org.cocos2dx.javascript.AppActivity t3}}}
12-04 04:57:31.043  1454  2619 W ActivityManager:   Force finishing activity com.someappcompany.SomeApp/org.cocos2dx.javascript.AppActivity
12-04 04:57:31.046  1454  2619 W ActivityManager: Exception thrown during pause
12-04 04:57:31.046  1454  2619 W ActivityManager: android.os.DeadObjectException
12-04 04:57:31.046  1454  2619 W ActivityManager:       at android.os.BinderProxy.transactNative(Native Method)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at android.os.BinderProxy.transact(Binder.java:615)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:785)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1145)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3531)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3367)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:1855)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:619)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:477)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:353)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.AppErrors.crashApplication(AppErrors.java:305)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13676)
12-04 04:57:31.046  1454  2619 W ActivityManager:       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
12-04 04:57:31.047  1285  1285 E lowmemorykiller: Error opening /proc/2567/oom_score_adj; errno=2
12-04 04:57:31.047  1454  2619 W ActivityManager: Failed setting process group of 2567 to 1
```

**Comment by willish** [comment]
We got a bit further using the following patch.  Now the gadget successfully executes and starts listening on the socket. However, the application remains paused (or deadlocked) even when the gadget is configured not to pause the application


[libhoudini.patch.zip](https://github.com/frida/frida/files/5658792/libhoudini.patch.zip)
