### ISSUE TITLE
java.lang.NoClassDefFoundError  

### ISSUE THREAD

**Issue by stayliv3** [frida/frida#156]
just follow this article https://cedricvb.be/post/seccon-2015-reverse-engineering-android-apk-2-400-writeup/

use frida 7.2.6 and android 4.4.2 

the error message 

➜  frida-script git:(master) ✗ frida -U kr.repo.h2spice.yekehtmai  -l ctf.js
     ____
    / _  |   Frida 7.2.6 - A world-class dynamic instrumentation framework
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/

Error: java.lang.NoClassDefFoundError: kr/repo/h2spice/yekehtmai/c
    at [object Object].pending.forEach.sources.forEach.Object.keys.forEach.v.object.v.hasOwnProperty.Array.every.call.Env.checkForExceptionAndThrowIt (gumjs-java.js:2357:31)
    at [object Object].<anonymous> (gumjs-java.js:2345:18)
    at [object Object].findClass (gumjs-java.js:2339:32)
    at ClassFactory.use (gumjs-java.js:426:40)
    at Runtime.pending.forEach.use (gumjs-java.js:315:33)
    at repl1.js:2:20
    at VM.perform (gumjs-java.js:2110:17)
    at Runtime.perform (gumjs-java.js:251:24)
    at repl1.js:1:8

**Comment by oleavr** [comment]
Hi,

Would you mind sharing the code in ctf.js?

Cheers!

**Comment by stayliv3** [comment]
i just follow the article.

the code of ctf.js 

`Java.perform(function () {
	console.log(Java.enumerateLoadedClasses(callbacks));
    var c = Java.use("kr.repo.h2spice.yekehtmai.c")
    c.a.implementation = function (str1, str2) {
        console.log("String1: " + str1)
        console.log("String2: " + str2)
    }
});%`


use the command 

`frida -U kr.repo.h2spice.yekehtmai  -l ctf.js`

**Comment by stayliv3** [comment]
i test on android 4.4.4 . it is OK. maybe it's the bug of my rom of android 4.4.2

**Comment by cheavyio** [comment]
I ran the same code as stayliv3 on a Samsung Galaxy S5 running 4.4.4 and in an ARM emulator running 4.4.2.   I'm getting the same error on the S5, but it runs fine in the emulator.

[USB::Samsung SM-G900V::13090]-> Error: java.lang.NoClassDefFoundError: kr/repo/h2spice/yekehtmai/c
    at [object Object].pending.forEach.sources.forEach.Object.keys.forEach.v.object.v.hasOwnProperty.Array.every.call.Env.checkForExceptionAndThrowIt (gumjs-java.js:2357:31)
    at [object Object].<anonymous> (gumjs-java.js:2345:18)
    at [object Object].findClass (gumjs-java.js:2339:32)
    at ClassFactory.use (gumjs-java.js:426:40)
    at Runtime.pending.forEach.use (gumjs-java.js:315:33)
    at repl2.js:3:20
    at VM.perform (gumjs-java.js:2110:17)
    at Runtime.perform (gumjs-java.js:251:24)
    at repl2.js:2:8

For reference I'm running 7.2.14.  The server version is 7.2.4.
