### ISSUE TITLE
dlopen failed: library "libresolv.so.2" not found

### ISSUE THREAD

**Issue by luffynas** [frida/frida#1562]
I'am try using Frida-Gadget v14.1.3 and showing error java.lang.UnsatisfiedLinkError: dlopen failed: library "libresolv.so.2" not found

2020-12-09 16:46:22.166 4237-4237/com.sample.cocos D/main: cocos_android_app_init
2020-12-09 16:46:22.175 4237-4237/com.sample.cocos D/AndroidRuntime: Shutting down VM
    
    --------- beginning of crash
2020-12-09 16:46:22.178 4237-4237/com.sample.cocos E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sample.cocos, PID: 4237
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libresolv.so.2" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.sample.cocos.lobby.onCreate(Unknown Source:2)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by luffynas** [comment]
I'am missing download for Frida-Gadget linux :'(, sorry

**Comment by tinmarino** [comment]
Thank you @luffynas that fixed it for me
