### ISSUE TITLE
call dalvik function with complex parameter 

### ISSUE THREAD

**Issue by stayliv3** [frida/frida#157]
in short i want to send the java.util.map type argument to the function .i can send the strings and int but don't know how to send the complex parameter.

the is the android source code 。
```
// Decompiled by JEB v1.5.201508100 - https://www.pnfsoftware.com

package com.xxxx.xxxx.http.d;



public final class a {
    private static final Map a;

    static {
        a.a = new HashMap();
    }

    public static Pair a(Map arg4, boolean arg5) {
        App.b();
        Map v0 = n.c();
        HashMap v1 = new HashMap();
        ((Map)v1).put("os", "android");
        ((Map)v1).put("client_key", "3c2cd3f3");
        if((App.o.isLogined()) && !((Map)v1).containsKey("token")) {
            ((Map)v1).put("token", App.o.getToken());
        }

        if(arg4 != null) {
            if(arg5) {
                v0.putAll(arg4);
            }
            else {
                ((Map)v1).putAll(arg4);
            }
        }

        a.b(v0, ((Map)v1));
        ((Map)v1).put("sig", a.a(v0, ((Map)v1)));
        if(arg5) {
            v0.putAll(((Map)v1));
            ((Map)v1).clear();
        }

        return new Pair(v0, v1);
    }

    private static String a(Map arg5, Map arg6) {
        String v0_1;
        StringBuilder v1;
        Object v0;
        ArrayList v2 = new ArrayList();
        Iterator v3 = arg5.entrySet().iterator();
        while(v3.hasNext()) {
            v0 = v3.next();
            v1 = new StringBuilder().append(((Map$Entry)v0).getKey()).append("=");
            if(((Map$Entry)v0).getValue() == null) {
                v0_1 = "";
            }
            else {
                v0 = ((Map$Entry)v0).getValue();
            }

            ((List)v2).add(v1.append(v0_1).toString());
        }

        v3 = arg6.entrySet().iterator();
        while(v3.hasNext()) {
            v0 = v3.next();
            v1 = new StringBuilder().append(((Map$Entry)v0).getKey()).append("=");
            if(((Map$Entry)v0).getValue() == null) {
                v0_1 = "";
            }
            else {
                v0 = ((Map$Entry)v0).getValue();
            }

            ((List)v2).add(v1.append(v0_1).toString());
        }

        try {
            Collections.sort(((List)v2));
        }
        catch(Exception v0_2) {
            v0_2.printStackTrace();
        }

        return CPU.getClock(App.c(), bp.a(((Collection)v2), "").getBytes(org.apache.internal.commons.io.a
                .f));
    }

    public static ApiManager$ApiType a(String arg3) {
        int v0 = arg3.indexOf(63);
        if(v0 != -1) {
            arg3 = arg3.substring(0, v0);
        }

        if(arg3.charAt(arg3.length() - 1) == 47) {
            arg3 = arg3.substring(0, arg3.length() - 1);
        }

        return a.a.get(arg3);
    }

    public static String a(String arg2, ApiManager$ApiType arg3) {
        String v0;
        switch(a$1.a[arg3.ordinal()]) {
            case 4: 
            case 5: {
                v0 = "https://" + arg3.name().toLowerCase() + ".kwai.com/rest/";
                break;
            }
            default: {
                v0 = "http://" + arg3.name().toLowerCase() + ".kwai.com/rest/";
                break;
            }
        }

        v0 = v0 + arg2;
        a.a.put(v0, arg3);
        return v0;
    }


```

i can hook this function **private static String a(Map arg5, Map arg6) {**   by using the following js code.

```
`Java.perform(function () {
    var a = Java.use("com.xxxx.xxxx.http.d.a")
    a.a.overload("java.util.Map","java.util.Map").implementation = function (str1, str2) {
        console.log("String1: " + str1)
        console.log("String2: " + str2)
    }
});`
```

now i just want to direct call the function and pass my own args to it .

i use this js:

```
send(Java.available); 
Java.perform(function () {
    var bb = Java.use("com.xxxx.xxxx.http.d.a");

    var dddd = {};
	dddd["key1"] = "value1";
	dddd["key2"] = "value2";

    ret = bb.a(dddd,dddd);
    send(ret);
});
```

but it does not work .
the error message is 

```
Error: a: argument types do not match any overload
    at a.f (gumjs-java.js:1081:27)
    at repl1.js:16:14
    at VM.perform (gumjs-java.js:2110:17)
    at gumjs-java.js:284:24
    at Array.forEach (native)
    at performPending (gumjs-java.js:282:21)
    at gumjs-java.js:264:29
    at VM.perform (gumjs-java.js:2110:17)
    at Runtime.perform (gumjs-java.js:259:24)
```

the type of the function is map.i just don't know how to overload the function to call it directly.

thanks for any help.

**Comment by enovella** [comment]
Sorry but the way of explaining yourself is way chaotic. 

Apparently, you will have to overload your method defining the input parameters as `java.util.Map`

Cheers

**Comment by stayliv3** [comment]
thanks for your reply. i'll modify the issue now.

**Comment by stayliv3** [comment]
i know where is my problem and would create a new issue to explain it .
