### ISSUE TITLE
Error: java.lang.NoClassDefFoundError (same as issue #156)

### ISSUE THREAD

**Issue by cheavyio** [frida/frida#159]
I ran the same code as stayliv3 (issue #156) on a Samsung Galaxy S5 running 4.4.4 and in an ARM emulator running 4.4.2. I'm getting the same error on the S5, but it runs fine in the emulator.

[USB::Samsung SM-G900V::13090]-> Error: java.lang.NoClassDefFoundError: kr/repo/h2spice/yekehtmai/c
at [object Object].pending.forEach.sources.forEach.Object.keys.forEach.v.object.v.hasOwnProperty.Array.every.call.Env.checkForExceptionAndThrowIt (gumjs-java.js:2357:31)
at [object Object]. (gumjs-java.js:2345:18)
at [object Object].findClass (gumjs-java.js:2339:32)
at ClassFactory.use (gumjs-java.js:426:40)
at Runtime.pending.forEach.use (gumjs-java.js:315:33)
at repl2.js:3:20
at VM.perform (gumjs-java.js:2110:17)
at Runtime.perform (gumjs-java.js:251:24)
at repl2.js:2:8

For reference I'm running 7.2.14. The server version is 7.2.4.

**Comment by oleavr** [comment]
This was a regression introduced in 7.2.4, fixed in 7.2.10. Please upgrade the server version to the latest version (7.2.24 right now). It is strongly recommended to run the latest version on both host and device.

Cheers!
