### ISSUE TITLE
Error while re-hook a Java constructor: expected a NativePointer object

### ISSUE THREAD

**Issue by lorenzodifuccia** [frida/frida#1604]
Hi there 👋🏻,
opening this issue because I'm encountering an `expected a NativePointer object` error trying to revert an implementation of a Java class constructor (`$init`) and set a new one.

**Testing JS script**:
```js
Java.perform(() => {
    const $Base64 = Java.use("android.util.Base64"),
        $Base64_init = $Base64.$init;
    
    console.log("PTR Base64.$init.implementation: ", $Base64_init.implementation);

    $Base64_init.implementation = function(...args) {
        console.log("Hello from implementation 1");
        return $Base64_init.apply(this, args)
    }
    console.log("PTR new Base64.$init.implementation: ", $Base64_init.implementation);
    console.log("Base64.$new:", $Base64.$new());

    $Base64_init.implementation = null;
    console.log("PTR revert Base64.$init.implementation: ", $Base64_init.implementation);
    
    $Base64_init.implementation = function(...args) {
        console.log("Hello from implementation 2");
        return $Base64_init.apply(this, args)
    }

    console.log("PTR new Base64.$init.implementation: ", $Base64_init.implementation);
    console.log("Base64.$new:", $Base64.$new());
})
```

**Output from `frida -FU -l script.js`**:
```
PTR Base64.$init.implementation:  null
PTR new Base64.$init.implementation:  0x7d9ef5f080
Hello from implementation 1
Base64.$new: android.util.Base64@6c0dca9
PTR revert Base64.$init.implementation:  null
Error: expected a pointer
    at value (frida/runtime/core.js:170)
    at Bt (frida/node_modules/frida-java-bridge/lib/android.js:927)
    at activate (frida/node_modules/frida-java-bridge/lib/android.js:1008)
    at replace (frida/node_modules/frida-java-bridge/lib/android.js:1057)
    at set (frida/node_modules/frida-java-bridge/lib/class-factory.js:1010)
    at set (frida/node_modules/frida-java-bridge/lib/class-factory.js:925)
    at <anonymous> (/script.js:15)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:237)
    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:212)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:231)
    at perform (frida/node_modules/frida-java-bridge/index.js:191)
    at <eval> (/script.js:24)
```

**Same error from `v8` (more verbose)**:
```
Error: expected a NativePointer object
    at Object.value [as patchCode] (frida/runtime/core.js:170:1)
    at Bt (frida/node_modules/frida-java-bridge/lib/android.js:904:1)
    at Xt.activate (frida/node_modules/frida-java-bridge/lib/android.js:1008:1)
    at er.replace (frida/node_modules/frida-java-bridge/lib/android.js:1057:1)
    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1010:1)
    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:925:1)
    at /script.js:17:33
    at o.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)
    at v._performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:237:1)
    at frida/node_modules/frida-java-bridge/index.js:212:1
```

**Versions**:
- `frida-tools`: 9.1.0
- `frida`: 14.2.4
- `frida-server`: 14.2.3
- Android: 8.0.0 (on SM-A750FN)

Thank you 🙏🏻

**Comment by lorenzodifuccia** [comment]
Solved calling `Java.deoptimizeEverything();`.
Not sure of why, but it works.

```js
Java.perform(() => {
    Java.deoptimizeEverything();
    const $Base64 = Java.use("android.util.Base64"),
        $Base64_init = $Base64.$init;
    
    console.log("PTR Base64.$init.implementation: ", $Base64_init.implementation);

    $Base64_init.implementation = function(...args) {
        console.log("Hello from implementation 1");
        return $Base64_init.apply(this, args)
    }
    console.log("PTR new Base64.$init.implementation: ", $Base64_init.implementation);
    console.log("Base64.$new:", $Base64.$new());

    $Base64_init.implementation = null;
    console.log("PTR revert Base64.$init.implementation: ", $Base64_init.implementation);
    
    $Base64_init.implementation = function(...args) {
        console.log("Hello from implementation 2");
        return $Base64_init.apply(this, args)
    }

    console.log("PTR new Base64.$init.implementation: ", $Base64_init.implementation);
    console.log("Base64.$new:", $Base64.$new());
})
```

```
PTR Base64.$init.implementation:  null
PTR new Base64.$init.implementation:  0x7d9e13f080
Hello from implementation 1
Base64.$new: android.util.Base64@e9c5063
PTR revert Base64.$init.implementation:  null
PTR new Base64.$init.implementation:  0x7d9e13f080
Hello from implementation 2
Base64.$new: android.util.Base64@89e9460
```

**Comment by lorenzodifuccia** [comment]
**Reopening** because `Java.deoptimizeEverything()` seems to be a valid mitigation in case of the execution of only one script injected into a process.
In case two scripts are loaded and injected, the latter one, even re-calling (or not) the _deoptimize_ inside his `Java.perform` task, it will raise an `expected a pointer` error.

Seems to be an issue with `.implementation` of Frida's Java bridge, when running two separate scripts.

Example (where `ciao.js` is the script posted above):

![image](https://user-images.githubusercontent.com/22743521/105605866-c108f780-5d96-11eb-887f-8b0300c011e7.png)
