### ISSUE TITLE
objection explore not works for me

### ISSUE THREAD

**Issue by gasabdullaev** [frida/frida#1607]
When I try objection -g com.airbnb.app explore (any app instead "com.airbnb.app") it not works.
I see for a few second "Using USB device iPhone" and when it ends with timeout error.

Any ideas how to fix it?

<img width="628" alt="Screen Shot 2021-01-17 at 2 57 48 PM" src="https://user-images.githubusercontent.com/54663916/104839785-7b4eb980-58d4-11eb-884c-4b5770f1f957.png">

`gas@GASs-MacBook-Pro_ ~ % objection -g com.airbnb.app explore
Using USB device iPhone
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/objection/console/cli.py", line 114, in explore
    agent.inject()
  File "/usr/local/lib/python3.9/site-packages/objection/utils/agent.py", line 202, in inject
    session = self.get_session()
  File "/usr/local/lib/python3.9/site-packages/objection/utils/agent.py", line 166, in get_session
    self.spawned_pid = self.device.spawn(state_connection.gadget_name)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.TransportError: timeout was reached`

**Comment by XdaemonX** [comment]
Maybe your frida server is not started

**Comment by viperbluff** [comment]
any solutions? facing the same issue
