### ISSUE TITLE
Error: Unable to determine ClassLinker field offsets

### ISSUE THREAD

**Issue by Daemonceltics** [frida/frida#1610]
Pixel2 8.0.0; frida-server 14.2.6
walleye:/data/local/tmp # ./frida-server-14.2.6-android-arm64
{"type":"error","description":"Error: Unable to determine ClassLinker field offsets","stack":"Error: Unable to determine ClassLinker field offsets\n    at Fe (frida/node_modules/frida-java-bridge/lib/android.js:374:1)\n    at frida/node_modules/frida-java-bridge/lib/memoize.js:4:1\n    at Pe (frida/node_modules/frida-java-bridge/lib/android.js:184:1)\n    at Re (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n    at v._tryInitialize (frida/node_modules/frida-java-bridge/index.js:17:1)\n    at new v (frida/node_modules/frida-java-bridge/index.js:9:1)\n    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:313:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at frida/node_modules/browser-pack/_prelude.js:1:1\n    at Object.20.frida-java-bridge (frida/runtime/java.js:1:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":374,"columnNumber":1}

**Comment by ByboyCn** [comment]
Hello, is it solved? I have the same problem as yours here
![image](https://user-images.githubusercontent.com/17998816/106858408-94d96900-66fc-11eb-962d-da304fe9e2d8.png)

**Comment by Daemonceltics** [comment]
> Hello, is it solved? I have the same problem as yours here
> ![image](https://user-images.githubusercontent.com/17998816/106858408-94d96900-66fc-11eb-962d-da304fe9e2d8.png)

No， it should be compatibility bug after view frida source code.

**Comment by jalee0606** [comment]
Is there any fix for this? I tried the latest frida version on the earliest walleye (8.0.0 (OPD1.170816.010, Sep 2017)). I am still getting this error.

**Comment by AnonymousVip** [comment]
I Am Also Facing the Same Problem..Anyone
@oleavr

**Comment by jalee0606** [comment]
I updated to walleye 8.1.0 and I could use the latest frida.

**Comment by redacted-text** [comment]
Same as https://github.com/frida/frida/issues/2176
