### ISSUE TITLE
Error running frida

### ISSUE THREAD

**Issue by ArchangelX1** [frida/frida#1653]
MBP ~ % frida --version

***
Failed to load the Frida native extension: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_frida.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_frida.cpython-39-darwin.so: no matching architecture in universal wrapper
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_frida.cpython-39-darwin.so: no matching architecture in universal wrapper
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/frida", line 33, in <module>
    sys.exit(load_entry_point('frida-tools==9.2.2', 'console_scripts', 'frida')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/frida_tools/repl.py", line 24, in main
    import frida
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/frida/__init__.py", line 24, in <module>
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/frida/__init__.py", line 7, in <module>
    import _frida
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_frida.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_frida.cpython-39-darwin.so: no matching architecture in universal wrapper
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_frida.cpython-39-darwin.so: no matching architecture in universal wrapper

BigSur 11.2.2
Apple M1
Python 3.9.2

I have followed every tutorial I could find and nothing works.
Please help

**Comment by ArchangelX1** [comment]
I had to uninstall python3 and then reinstall python3 using homebrew. Hope this helps someone later.
