### ISSUE TITLE
Traceback: ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by bahkadomos** [frida/frida#1676]
After I run **frida-ps -U** or **frida-ps -U 127.0.0.1:21503** I get this error:
Exception in thread Thread-1:

```
Traceback (most recent call last):
  File "c:\program files\python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\program files\python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\program files\python39\lib\site-packages\frida_tools\application.py", line 639, in _run
    work()
  File "c:\program files\python39\lib\site-packages\frida_tools\application.py", line 334, in _try_start
    self._start()
  File "c:\program files\python39\lib\site-packages\frida_tools\ps.py", line 34, in _start
    self._list_processes()
  File "c:\program files\python39\lib\site-packages\frida_tools\ps.py", line 45, in _list_processes
    pid_column_width = max(map(lambda p: len("%d" % p.pid), processes))
ValueError: max() arg is an empty sequence
```
Command **frida-ls-devices** is output connected USB device correctly:
```
Id               Type    Name
---------------  ------  ------------
local            local   Local System
127.0.0.1:21503  usb     G011A
socket           remote  Local Socket
```

Command **frida-ps** without args does not cause an error (expected displays processes from a computer).

How to run frida on a connected device?

Python 3.9.2
frida==14.2.14
frida-tools==9.2.3
Emulator: memu

**Comment by FD-** [comment]
I am seeing the exact same error on Python 3.9.4 installed through brew. Could you find a solution in the meantime?
