### ISSUE TITLE
TypeError: r.art::mirror::Object::Clone is not a function

### ISSUE THREAD

**Issue by bader-mb** [frida/frida#1684]
Frida-server Version: 14.2.14
Android Version: [rooted] v5.1

When I run the ./frida-server on my android, I get this error and keeps running:

`{"type":"error","description":"TypeError: r.art::mirror::Object::Clone is not a function","stack":"TypeError: r.art::mirror::Object::Clone is not a function\n    at Bt (frida/node_modules/frida-java-bridge/lib/android.js:1183:1)\n    at Vt.replace (frida/node_modules/frida-java-bridge/lib/android.js:1028:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1010:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:925:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:249:24)\n    at init (/internal-agent.js:33:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n    at v._performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238:1)\n    at frida/node_modules/frida-java-bridge/index.js:213:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1183,"columnNumber":1}`

**Comment by natanocr** [comment]
I am also having the same error, let me know if you have any newness.

**Comment by echos2019** [comment]
I am also having this problem. And my android is android5.1, frida is v14.2.18

**Comment by bossNzXD** [comment]
me too

**Comment by Young-Lord** [comment]
me too,using [LDPlayer](https://www.ldmnq.com/)

**Comment by Heming9** [comment]
I have the same issue when installed Xposed and I tried to disable the Xposed in the Xposed installer but never work.

**Comment by Heming9** [comment]
> I have the same issue when installed Xposed and I tried to disable the Xposed in the Xposed installer but never work.

yes, when I uninstall Xposed using Xposed uninstaller and the Frida server work again
