### ISSUE TITLE
CentOS 7 missing Java 11 API

### ISSUE THREAD

**Issue by LykourgosPap** [frida/frida#1702]
Hello everybody,

I am trying to install frida on a CentOS to debug a java 11 application. However, the typical Java api missing is thrown:
```
Error: Java API only partially available; please file a bug. Missing: _ZN10JavaThread27thread_from_jni_environmentEP7JNIEnv_
    at P (frida/node_modules/frida-java-bridge/lib/jvm.js:143:1)
    at C (frida/node_modules/frida-java-bridge/lib/jvm.js:12:1)
    at g._tryInitialize (frida/node_modules/frida-java-bridge/index.js:17:1)
    at new g (frida/node_modules/frida-java-bridge/index.js:9:1)
    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:317:1)
```

It seems that the debug symbols are available, but only the specific JavaThread::thread_from_jni_environment is missing.
Java 8 has this symbol available but Java 11 has not:

```
$nm /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64/lib/server/libjvm.so
[...]
000000000153a5b8 b AbortVMOnCompilationFailure
000000000153a628 b AbortVMOnException
000000000153a620 b AbortVMOnExceptionMessage
000000000153a6f2 b AbortVMOnSafepointTimeout
000000000153a6f1 b AbortVMOnVMOperationTimeout
00000000014f11c0 d AbortVMOnVMOperationTimeoutDelay
0000000000a98da8 t acb_CopyLeft
0000000000a98d0a t acb_CopyRight
                 U accept@@GLIBC_2.2.5
                 U access@@GLIBC_2.2.5
0000000000a98fe4 t aci_CopyLeft
0000000000a98f75 t aci_CopyRight
0000000000a990f6 t acl_CopyLeft
0000000000a99063 t acl_CopyRight
0000000000a98ee4 t acs_CopyLeft
0000000000a98e66 t acs_CopyRight
00000000014f077c d ActiveProcessorCount
0000000001550c40 b AdapterHandlerLibrary_lock
00000000014f06e0 d AdaptiveSizeDecrementScaleFactor
00000000014f06d0 d AdaptiveSizeMajorGCDecayTimeScale
00000000014f0730 d AdaptiveSizePolicyCollectionCostMargin
00000000014f0770 d AdaptiveSizePolicyInitializingSteps
000000000153a3c8 b AdaptiveSizePolicyOutputInterval
00000000014f0760 d AdaptiveSizePolicyWeight
000000000153a3d0 b AdaptiveSizeThroughPutPolicy
00000000014f0758 d AdaptiveTimeWeight
000000000152ce90 b addexports_count
000000000152ce70 b addmods_count
000000000152ce80 b addopens_count
000000000152cea0 b addreads_count
000000000152fff0 b addressType
000000000153a3e8 b AggressiveHeap
000000000153a61d b AggressiveOpts
00000000015300aa b AggressiveUnboxing
00000000014ef800 d AliasLevel
00000000014ef930 d AlignVector
000000000153a4e8 b AllocateHeapAt
00000000014f1058 d AllocateInstancePrefetchLines
00000000014f1068 d AllocatePrefetchDistance
000000000153a608 b AllocatePrefetchInstr
00000000014f1060 d AllocatePrefetchLines
00000000014f1050 d AllocatePrefetchStepSize
[...]
$ nm /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64/lib/server/libjvm.so | grep -i _ZN10JavaThread27thread_from_jni_environmentEP7JNIEnv_
$ nm /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-1.el7.x86_64/jre/lib/amd64/server/libjvm.so | grep -i _ZN10JavaThread27thread_from_jni_environmentEP7JNIEnv_
0000000000714c30 t _ZN10JavaThread27thread_from_jni_environmentEP7JNIEnv_
```
Does anybody know of a workaround for this?
Running debug-info install java-11-openjdk does not solve the issue

**Comment by adam-flynn** [comment]
Hi, I have the same problem. Looking at the JDK sources and disassembly, it appears that the thread_from_jni_environment has been inlined. Hence the symbol is omitted from the release version. I've some ideas:
1. Recompile JDK without inlining thread_from_jni_environment
2. Recompile Frida to use a caller of thread_from_jni_environment and saves the JavaThread return value and try to get it from there.
3. Recompile Frida to disassemble some caller of thread_from_jni_environment and dynamically inject a thread_from_jni_environment function
4. Use some other tool altogether (maybe JVMTI?)

But I hope @oleavr can provide a good solution here...

**Comment by adam-flynn** [comment]
By the way, it's not limited to CentOS. I am using Ubuntu 18.04 and was using a JVM from https://adoptopenjdk.net/releases.html?variant=openjdk13&jvmVariant=hotspot

**Comment by LykourgosPap** [comment]
Thank you for your answers Adam, I think solution number 3 would be the cleanest, as I dont want to change the JVM of the target machine. Problem is I am 0% familiar with Frida codebase, therefore this task needs a fair amount of time. If I do it I will update here!!!

**Comment by adam-flynn** [comment]
In my OpenJDK 13 JVM (libjvm.so), the disassembly of [jfr_retransform_classes](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/jfr/jni/jfrJniMethod.cpp#L103) is:

```
push rbp
mov rbp,rsp
push r12
mov r12,rdx
lea rdx,[rdi-0x310]
push rbx
mob rbs,rdi
mov eax,DWORD PTR [rdx+0x3a0]
sub eax,0xdeab
cmp eax,0x1
jbe is_terminated_true
mov rdi,rdx
call block_if_vm_exited
xor edx,edx
is_terminated_true:
mov rsi,r12
mov rdi,rbx
pop rbx
pop r12
pop rbp
jmp retransform_classes
```

Evidently, the return value of [`thread_from_jni_environment`](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/thread.hpp#L1302) is just the `env` argument minus `0x310`.

I first compiled Frida 14.2.18 by checking out that tag from the Frida Git repository (by the way, the latest Git version gives a segmentation fault when attempting to frida-trace anything**) and running:
```
(cd frida-tools && make)
make core-linux-x86_64-thin
make tools-linux-x86_64-thin
```

I edited `frida-gum/bindings/gumjs/node_modules/frida-java-bridge/lib/jvm.js` to remove any reference to thread_from_jni_environment and instead having:
```
const thread = env.handle.sub(0x310);
```

I touched `frida-gum/bindings/gumjs/runtime/java.js` so that it will recompile my changes to the above file, then I reran the compile:

```
make core-linux-x86_64-thin
make tools-linux-x86_64-thin
```

I ensured that I have pip-installed all the Frida runtime dependencies, and added the modified Frida from `build/frida_thin-linux-x86_64/bin` to the PATH. It seems to be working on an application like JADX, but I'm still unable to get it working for one which uses custom class loaders.

** @oleavr: When I used version ad38f43, frida-trace gives an error about FileMonitorEnableTask not having `main-context` property... I see that you refactored the code and recently added FileMonitor.vala, but I can't see why it would have a problem!

**Comment by oleavr** [comment]
@adam-flynn Ah yes, fixed this regression in frida-core last night. Haven't yet updated the submodule, so you'll have to pull it manually for now.

**Comment by adam-flynn** [comment]
@oleavr I spoke too early about it working for jadx-gui. Apparently a lot of functions when hooked will cause Frida to hang when the function is triggered. E.g. hooking `jadx.gui.ui.MainWindow!buildFileChooser`.

**Comment by MaxBourgeois** [comment]
After having had problems too , I found the thread_from_jni_environment symbol in this jdk version : **OpenJDK11U-jdk_x64_linux_11.0.13_8** 

```
➜  server nm libjvm.so | grep -i thread | grep jni
00000000008ef590 t jni_AttachCurrentThread
00000000008ef560 t jni_AttachCurrentThreadAsDaemon
00000000008df0b0 t jni_DetachCurrentThread
00000000008f2160 t _ZL17jni_invoke_staticP7JNIEnv_P9JavaValueP8_jobject11JNICallTypeP10_jmethodIDP18JNI_ArgumentPusherP6Thread
00000000008e36b0 t _ZL20jni_invoke_nonstaticP7JNIEnv_P9JavaValueP8_jobject11JNICallTypeP10_jmethodIDP18JNI_ArgumentPusherP6Thread
00000000008fffc0 t _ZN10JavaThread27thread_from_jni_environmentEP7JNIEnv_
...
```

I hope that helps

**Comment by teamblubee** [comment]
I had a similar issue, downloading the referenced OpenJDK11U version, installing java and javac with update-alternatives and now I have Java support.

@MaxBourgeois thanks for the pointer!

**Comment by iddoeldor** [comment]
> After having meet some problems too, I found the `thread_from_jni_environment` symbol in this jdk version (latest) : **OpenJDK11U-jdk_x64_linux_11.0.13_8**
> 
> ```
> ➜  server nm libjvm.so | grep -i thread | grep jni
> 00000000008ef590 t jni_AttachCurrentThread
> 00000000008ef560 t jni_AttachCurrentThreadAsDaemon
> 00000000008df0b0 t jni_DetachCurrentThread
> 00000000008f2160 t _ZL17jni_invoke_staticP7JNIEnv_P9JavaValueP8_jobject11JNICallTypeP10_jmethodIDP18JNI_ArgumentPusherP6Thread
> 00000000008e36b0 t _ZL20jni_invoke_nonstaticP7JNIEnv_P9JavaValueP8_jobject11JNICallTypeP10_jmethodIDP18JNI_ArgumentPusherP6Thread
> 00000000008fffc0 t _ZN10JavaThread27thread_from_jni_environmentEP7JNIEnv_
> ...
> ```
> 
> `Java.available` finally returns true
> 
> I hope that helps

do you have a link ? i've downloaded the same and symbol not found
