### ISSUE TITLE
compile gumjs failed, no such file or directory, lstat frida/frida-gum/bindings/gumjs/timers

### ISSUE THREAD

**Issue by centy720** [frida/frida#1741]
inja: Entering directory `build/tmp-android-arm/frida-gum'
[151/189] Generating gumjs-runtime with a custom command
FAILED: bindings/gumjs/gumquickscript-runtime.h bindings/gumjs/gumquickscript-objc.h bindings/gumjs/gumquickscript-java.h bindings/gumjs/gumv8script-runtime.h bindings/gumjs/gumv8script-objc.h bindings/gumjs/gumv8script-java.h bindings/gumjs/gumcmodule-runtime.h
/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/generate-runtime.py arm /Users/xxx/Downloads/frida/frida-gum/bindings/gumjs /Users/xxx/Downloads/frida/frida-gum/gum /Users/xxx/Downloads/frida/build/sdk-android-arm/include /Users/xxx/Downloads/frida/build/sdk-android-arm/lib /Users/xxx/Downloads/frida/build/tmp-android-arm/frida-gum/bindings/gumjs/quickcompile /Users/xxx/Downloads/frida/build/tmp-android-arm/frida-gum/bindings/gumjs
[Error: Can't walk dependency graph: ENOENT: no such file or directory, lstat '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/timers'
    required by /Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/node_modules/frida-objc-bridge/index.js] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/timers',
  stream: Labeled {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 0 },
      length: 0,
      pipes: [Labeled],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      error: [Function],
      data: [Function: ondata],
      _mutate: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: false,
    allowHalfOpen: true,
    _options: { objectMode: true },
    _wrapOptions: { objectMode: true },
    _streams: [ [Deps], [Transform] ],
    length: 2,
    label: 'deps'
  },
  inputs: Set {
    '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/runtime/objc.js',
    '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/node_modules/typescript/lib/lib.d.ts',
    '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/node_modules/typescript/lib/lib.es5.d.ts',
    '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/node_modules/typescript/lib/lib.dom.d.ts',
    '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/node_modules/typescript/lib/lib.webworker.importscripts.d.ts',
    '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/node_modules/typescript/lib/lib.scripthost.d.ts',
    '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/package.json',
    '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/node_modules/frida-objc-bridge/package.json',
    '/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/node_modules/frida-objc-bridge/index.js'
  }
}
Traceback (most recent call last):
  File "/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/generate-runtime.py", line 335, in <module>
    subprocess.check_call([node_script_path("frida-compile"), "./runtime/objc.js", "-o", objc] + quick_options, cwd=input_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/xxx/Downloads/frida/frida-gum/bindings/gumjs/node_modules/.bin/frida-compile', './runtime/objc.js', '-o', '/Users/xxx/Downloads/frida/build/tmp-android-arm/frida-gum/bindings/gumjs/runtime-build-quick/objc.js', '-c']' returned non-zero exit status 1.
ninja: build stopped: subcommand failed.
make[1]: *** [build/frida-android-arm/lib/pkgconfig/frida-gum-1.0.pc] Error 1
make: *** [core-android-arm64] Error 2

**Comment by puppywang** [comment]
I solve it by downgrade `frida-compile` from 10.2.1 to 10.0.0, enter `frida-gum/binding/gumjs` directory, and use `npm install frida-compile@10.0.0`, then restart your compile.
