### ISSUE TITLE
How to fix ""type":"error","description":"Error: invalid address","stack":"Error: invalid address\n" error? 

### ISSUE THREAD

**Issue by toraidl** [frida/frida#1768]
When  I try to run frida-server on android (MIUI12.5 android 11),  it stuck at the error shown as below.
Can someone help figure it out What does it mean and how to fix it ? 
Thanks 
{"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:170:1)
\n    at zt (frida/node_modules/frida-java-bridge/lib/android.js:945:1)\n    at Ut.activate (frida/node_modules/frida-java-bridge/lib/android.js:998:1)\n    at
Gt.replace (frida/node_modules/frida-java-bridge/lib/android.js:1045:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class
-factory.js:1010:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:925:1)\n    at installLaunchTimeoutRemov
alInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n
  at g._performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238:1)","fileName":"frida/runtime/core.js","lineNumber":170,"columnNumber":1}

**Comment by lx32056127** [comment]
I had the same problem today and found that turning off SELinux solved the problem



```
adb shell setenforce 0
```

**Comment by Curious-chen** [comment]
thanks, I solved this problem by your means. 

> I had the same problem today and found that turning off SELinux solved the problem
> 
> ```
> adb shell setenforce 0
> ```

thanks, I solved this problem by your means.

**Comment by radubogdan2k** [comment]
So is it impossible to use a frida-agent app on these phones without rooting them?

**Comment by MlgmXyysd** [comment]
> I had the same problem today and found that turning off SELinux solved the problem
> 
> ```
> adb shell setenforce 0
> ```

Same problem, but `setenforce 0` not work.

```
/data/local/tmp # getenforce
Permissive
/data/local/tmp # frida-server
{"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:203:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1185:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1099:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:205:1)","fileName":"frida/runtime/core.js","lineNumber":203,"columnNumber":1}
```

**Comment by iamvinny** [comment]
One way to solve this is to let your device boot and only then plug it to your PC.

**Comment by vutranHS** [comment]
adb shell
su
mount -o remount,rw '/'
chmod 777 /
adb shell "su -c setenforce 0"
setprop persist.device_config.runtime_native.usap_pool_enabled false
settings put system screen_off_timeout 100000000
