### ISSUE TITLE
frida.TimedOutError: unexpectedly timed out while waiting for app to launch

### ISSUE THREAD

**Issue by von-der-eretier** [frida/frida#1772]
I'm, having issues trying to bypass SSLpinning in a Samsung A50.

When I use objection --gadget <process_name> explore, the app restart but I got a timeout from Frida:

`objection --gadget <redacted> explore
Using USB device `SM A505FN`
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/objection/console/cli.py", line 114, in explore
    agent.inject()
  File "/usr/local/lib/python3.9/dist-packages/objection/utils/agent.py", line 202, in inject
    session = self.get_session()
  File "/usr/local/lib/python3.9/dist-packages/objection/utils/agent.py", line 166, in get_session
    self.spawned_pid = self.device.spawn(state_connection.gadget_name)
  File "/usr/local/lib/python3.9/dist-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/frida/core.py", line 149, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.TimedOutError: unexpectedly timed out while waiting for app to launch`

Any idea? I tried all that I know but I can't yet.

Thanks in advance

**Comment by oleavr** [comment]
Check if USAP is enabled, and if so disable it. (It's not yet supported.)

**Comment by von-der-eretier** [comment]
Running this from a root shell, right?

`setprop persist.device_config.runtime_native.usap_pool_enabled false`

Another way to do it?

**Comment by von-der-eretier** [comment]
It works, error is gone.

Now it catch the restart of the App, but SSL pinning bypass still doesn't work. Any suggestion someone?

**Comment by oleavr** [comment]
@von-der-eretier Glad to here!  Just FYI the latest Frida 15.x finally supports USAP, so this can now be closed.  Regarding pinning, that sounds like a great question for https://t.me/fridadotre.  Cheers!
