### ISSUE TITLE
Failed to spawn: frida.InvalidOperationError: process is not suspended

### ISSUE THREAD

**Issue by 2foil** [frida/frida#1778]
iPhone 6s 
iOS: 15.6 with jailbreak by checkra1n
frida version: 15.0.8
Cydia Substrate: 0.9.7113

When Cydia Substrate is not installed, frida is able to spwan apps successfully.
After the Substrate was installed, frida failed to spwan apps.
The error message is

```
Traceback (most recent call last):
  File "./venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1b1da4c88d8f>", line 1, in <module>
    runfile('./scripts/deepknow/ios_crack_sapwn.py', wdir='./scripts/deepknow')
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "./scripts/deepknow/ios_crack_sapwn.py", line 30, in <module>
    device.resume(pid)
  File "./venv/lib/python3.8/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "./venv/lib/python3.8/site-packages/frida/core.py", line 157, in resume
    self._impl.resume(self._pid_of(target))
frida.InvalidOperationError: process is not suspended
```

**Comment by 2foil** [comment]
Solved after re-jailbreak the iPhone 6s.
