### ISSUE TITLE
Error: VM::AttachCurrentThread failed: -1

### ISSUE THREAD

**Issue by Tr0142014** [frida/frida#1788]
talk guys, it's okay with you ....

I have a problem, I've been in it for some time

I have a physical cell phone, Samsung S21, on it I ROOT with Magisk

After doing the entire installation, I installed Frida on it and tried to solve the OWASP CTF

![image](https://user-images.githubusercontent.com/18498916/127135245-d1c6f6d6-0526-44d7-a158-482dea4b22f2.png)

the javascript code I'm using is 100% functional, as it already works in Memu Emulator (x86)

![image](https://user-images.githubusercontent.com/18498916/127135452-ff992a08-eb4b-420d-b467-2e7ee3751362.png)

my phone is installed frida in the ok version of the operating system

but when I do the injection it returns the following error:

`
Spawned owasp.mstg.uncrackable1. Resuming main thread!
Error: VM::AttachCurrentThread failed: -1
    at o (frida/node_modules/frida-java-bridge/lib/result.js:4)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:25)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:14)
    at Xe (frida/node_modules/frida-java-bridge/lib/android.js:499)
    at Ie (frida/node_modules/frida-java-bridge/lib/android.js:195)
    at Ce (frida/node_modules/frida-java-bridge/lib/android.js:16)
    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:17)
    at g (frida/node_modules/frida-java-bridge/index.js:9)
    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:317)
    at call (native)
    at o (/_java.js)
    at <anonymous> (/_java.js)
    at <anonymous> (frida/runtime/java.js:1)
    at call (native)
    at o (/_java.js)
    at r (/_java.js)
    at <eval> (frida/runtime/java.js:3)
    at _loadJava (native)
    at get (frida/runtime/core.js:114)
    at <eval> (/root.js:1) `
    
    
    
remembering that Im solving this ctf   [UnCrackable App for Android Level 1](https://github.com/OWASP/owasp-mstg/tree/master/Crackmes)
    
 ps: already tried to install frida module in magisk and work for it too same error..

**Comment by hhxdestiny** [comment]
I repeated the same problem

**Comment by arydob** [comment]
same issue

**Comment by NovalisDev** [comment]
same issue

**Comment by hhxdestiny** [comment]
latest

**Comment by djt3** [comment]
same issue on a mi 8 lite with android 10

**Comment by reidsneo** [comment]
Samsung Galaxy Tab S6 Lite using Magisk 23 also occured same error

**Comment by GOATS2K** [comment]
I can confirm this also happens on a OnePlus 7T Pro, running Android 11 with the June 2021 security patch.

**Comment by arkaroy14** [comment]
same issue here using android 11 custom rom on Realme X2 Pro . It seems this issue is only occuring on Android 11 as my other device Redmi note 4 on android 10 running frida-server smoothly..

**Comment by Zerogoki00** [comment]
Same issue on POCO X3 PRO with Android 11 (ArrowOS)

**Comment by RealIndica** [comment]
Same issue Samsung S21 5G Exynos latest Magisk & latest Frida server

**Comment by jjsdub556** [comment]
Same on POCO X3 PRO, Android 11 (ArrowOS),  Magisk 23.0, Frida 5.1.3.

**Comment by rmartinsanta** [comment]
What solved the problem for me was disabling Zygote Preforking (no restart required):

```
su
setprop persist.device_config.runtime_native.usap_pool_enabled false
getprop | grep usap
```

**Comment by d0gkiller87** [comment]
> In case it is useful to someone, what solved some problems for me in Android 11 was disabling Zygote Preforking 
This answer solved my problem on Android 10. Thank you 👍

**Comment by mrh1234** [comment]
I had a similar issue and using frida server 15.1.1 solved it. I did not test newer versions.

**Comment by elisaado** [comment]
Same issue, even after disabling preforking

**Comment by Gunkkk** [comment]
> ```
> setprop persist.device_config.runtime_native.usap_pool_enabled false
> getprop | grep usap
> ```
It works for same issue with Android11.

**Comment by BrunoPincho** [comment]
> ```
> getprop | grep usap
> ```

worked for me as well in Android 10 - oneplus A5000

**Comment by norahoficial** [comment]
> Caso seja útil para alguém, o que resolveu alguns problemas para mim no Android 11 foi desabilitar o Zygote Preforking (sem necessidade de reinicialização):
> 
> ```
> su
> setprop persist.device_config.runtime_native.usap_pool_enabled false
> getprop | grep usap
> ```

OBRIGADO! OBRIGADO!!! VOCÊ ME SALVOU AMIGO 👏👏

**Comment by norahoficial** [comment]
THANKS! THANKS!!! YOU SAVED ME FRIEND 👏👏

**Comment by norahoficial** [comment]
> In case it is useful to someone, what solved some problems for me in Android 11 was disabling Zygote Preforking (no restart required):
> 
> ```
> su
> setprop persist.device_config.runtime_native.usap_pool_enabled false
> getprop | grep usap
> ```

THANK YOU! THANKS!!! YOU SAVED ME FRIEND 👏👏

**Comment by hilario-0** [comment]
> In case it is useful to someone, what solved some problems for me in Android 11 was disabling Zygote Preforking (no restart required):
> 
> ```
> su
> setprop persist.device_config.runtime_native.usap_pool_enabled false
> getprop | grep usap
> ```

This solves my problem I'm using physical android 11 OnePlus8T
Thanks @rmartinsanta

**Comment by Neigb** [comment]
it works on Android 13!

**Comment by Soon-gz** [comment]
su
setprop persist.device_config.runtime_native.usap_pool_enabled false
getprop | grep usap

it works on android 11

**Comment by SafaSafari** [comment]
if those methods doesn't work, check this comment: https://github.com/frida/frida/issues/2719#issuecomment-1869274133

**Comment by cxzero** [comment]
Thanks for sharing https://github.com/frida/frida/issues/2719#issuecomment-1869274133 @SafaSafari!

With `setprop persist.sys.usap_pool_enabled false` I was able to spawn processes with the latest **frida-server-16.2.1-android-arm64** in a rooted OnePlus 5 device with Android 10. In my case a reboot was needed.

Checked that the property is properly set:
```
getprop | grep usap
[persist.sys.usap_pool_enabled]: [false]
```
The only thing that **_keeps logging is this error_** when running frida-server but working fine for now:
```
OnePlus5:/data/local/tmp # ./frida-server-16.2.1-android-arm64
{"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:207:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1185:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1099:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":207,"columnNumber":1}
```
**Other fixes mentioned (not working for me and needed more testing):**
I've tried https://github.com/frida/frida/issues/1788#issuecomment-932833126, also mentioned in https://github.com/frida/frida-core/issues/346#issuecomment-735900106 before but without success. There is also a similar one in https://github.com/frida/frida/issues/2719#issuecomment-1869341323.

I've also seen that versions 15.1.17 https://github.com/frida/frida/issues/2423#issuecomment-1447600107 and 6.0.3 https://github.com/frida/frida/issues/2423#issuecomment-1466607112, https://github.com/frida/frida/issues/2360#issuecomment-1410882971 worked for others.

**Comment by nutterthanos** [comment]
> The only thing that **_keeps logging is this error_** when running frida-server but working fine for now:
> 
> ```
> OnePlus5:/data/local/tmp # ./frida-server-16.2.1-android-arm64
> {"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:207:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1185:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1099:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":207,"columnNumber":1}
> ```

Fix for that is simple setenforce 0
