### ISSUE TITLE
frida-ps tool breaks on process compare

### ISSUE THREAD

**Issue by nologic** [frida/frida#1794]
version 15.0.8

frida_tools assumes process object type and breaks when more than one gadget is connected.

```
% frida-ps -H localhost
PID  Name
---  ---------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "[]/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "[]/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users//Library/Python/3.8/lib/python/site-packages/frida_tools/application.py", line 639, in _run
    work()
  File "/Users/[]/Library/Python/3.8/lib/python/site-packages/frida_tools/application.py", line 334, in _try_start
    self._start()
  File "/Users/[]/Library/Python/3.8/lib/python/site-packages/frida_tools/ps.py", line 34, in _start
    self._list_processes()
  File "/Users/[]/Library/Python/3.8/lib/python/site-packages/frida_tools/ps.py", line 52, in _list_processes
    for process in sorted(processes, key=cmp_to_key(compare_processes)):
  File "/Users/[]/Library/Python/3.8/lib/python/site-packages/frida_tools/ps.py", line 147, in __lt__
    return mycmp(self.obj, other.obj) < 0
  File "/Users/[]/Library/Python/3.8/lib/python/site-packages/frida_tools/ps.py", line 126, in compare_processes
    a_has_icon = a.get_small_icon() is not None
AttributeError: '_frida.Process' object has no attribute 'get_small_icon'
```

**Comment by oleavr** [comment]
You need to update to the latest frida-tools – the one you have is for Frida 14.

**Comment by DarkAnakin** [comment]
Haven't use it for quite some time and upgrade it today from 14.2.18 to 15.1.1 and I get the same error.
Am I missing something?

```
frida-ps --version
15.1.1

frida-ps -U
 PID  Name
----  ---------------------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/angelofskies/.local/lib/python3.9/site-packages/frida_tools/application.py", line 639, in _run
    work()
  File "/home/angelofskies/.local/lib/python3.9/site-packages/frida_tools/application.py", line 334, in _try_start
    self._start()
  File "/home/angelofskies/.local/lib/python3.9/site-packages/frida_tools/ps.py", line 34, in _start
    self._list_processes()
  File "/home/angelofskies/.local/lib/python3.9/site-packages/frida_tools/ps.py", line 52, in _list_processes
    for process in sorted(processes, key=cmp_to_key(compare_processes)):
  File "/home/angelofskies/.local/lib/python3.9/site-packages/frida_tools/ps.py", line 147, in __lt__
    return mycmp(self.obj, other.obj) < 0
  File "/home/angelofskies/.local/lib/python3.9/site-packages/frida_tools/ps.py", line 126, in compare_processes
    a_has_icon = a.get_small_icon() is not None
AttributeError: '_frida.Process' object has no attribute 'get_small_icon'
```
