### ISSUE TITLE
Error when starting frida-server-15.0.16-android-arm64

### ISSUE THREAD

**Issue by TonicBoomerKewl** [frida/frida#1820]
### Here are the commands I entered into PowerShell that results in the error:

```console
PS C:\> adb root
PS C:\> adb shell
$ su
# chmod -R 755 /data/local/tmp/
# /data/local/tmp/frida-server-15.0.16-android-arm64 &
[1] 6412
# {"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode](frida/runtime/core.js:170:1)\n    at zt (frida/node_modules/frida-java-bridge/lib/android.js:945:1)\n    at Ut.activate (frida/node_modules/frida-java-bridge/lib/android.js:998:1)\n    at Gt.replace (frida/node_modules/frida-java-bridge/lib/android.js:1045:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1010:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:925:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)\n    at init(/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n    at g._performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238:1)","fileName":"frida/runtime/core.js","lineNumber":170,"columnNumber":1}
# getprop
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
```

### Other notes:
- frida-server-15.0.16-android-arm64 is already pushed to /data/local/tmp
- some output of "getprop" command is hidden
- frida version is 15.0.16
- im using a real phone, not an android emulator

**Comment by s1341** [comment]
Just confirmed that 15.0.17 is working fine on android 11.

**Comment by TonicBoomerKewl** [comment]
> Just confirmed that 15.0.17 is working fine on android 11.

Do you know any rooted android emulators that can run **arm64** android frida server? The app that i'm trying to use frida on has arm64-v8a architecture, and when using x86_64 frida server, it cannot see the app's modules, even though I opened up the .apk file and the module is there. Using arm64 frida server gives error for me on NoxPlayer android 7 and MEmu android 7.

**Comment by s1341** [comment]
Nope sorry. I don't have experience using arm64 emulators, and an arm64-v8a app is not going to work on an x86 emulator...

**Comment by TonicBoomerKewl** [comment]
Somehow the app still works and runs fine on NoxPlayer, which should be x86 emulator. I checked "adb shell getprop" command and its x86_64 ...

**Comment by mrh1234** [comment]
I am getting the same error message as the original poster when running the frida server version 15.0.18 as well as older versions. However everything seems to work fine until now and the frida server is fully functional. 

I use a rooted galaxy s21 ultra.

**Comment by mrh1234** [comment]
I still get this error message using frida server 15.1.1, however with this version I can hook everything and every use case works for me. I did not test newer versions.
