### ISSUE TITLE
How can i use frida client in android app

### ISSUE THREAD

**Issue by sevenshal** [frida/frida#1826]
I am building a android app which running in root android device.
Now i can run frida-server with Process in root mode.
How can i connect the daemon in my android app and run my script.
Now when i use gadget script mode, the app crash when loading so.

JNI DETECTED ERROR IN APPLICATION: unknown format specifier: ''
    in call to ExceptionClear
    from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String)
"main" prio=5 tid=1 Runnable
  | group="main" sCount=0 dsCount=0 flags=0 obj=0x75964460 self=0xa66fd000
  | sysTid=19029 nice=0 cgrp=default sched=0/0 handle=0xaaa3e4a4
  | state=R schedstat=( 1231981471 89890457 191 ) utm=111 stm=12 core=4 HZ=100
  | stack=0xbe1fd000-0xbe1ff000 stackSize=8MB
  | held mutexes= "mutator lock"(shared held)
  native: #00 pc 002387f7  /system/lib/libart.so (???)
  native: #01 pc 002cbff1  /system/lib/libart.so (???)
  native: #02 pc 002c8693  /system/lib/libart.so (???)
  native: #03 pc 0019d359  /system/lib/libart.so (???)
  native: #04 pc 0019d6c7  /system/lib/libart.so (???)
  native: #05 pc 00025403  /system/lib/libart.so (???)
  native: #06 pc 00025349  /system/lib/libart.so (???)
  native: #07 pc 0002392d  /system/lib/libart.so (???)
  native: #08 pc 00000261   (???)
  at java.lang.Runtime.nativeLoad(Native method)
  at java.lang.Runtime.doLoad(Runtime.java:1099)
  - locked <0x0af6cc74> (a java.lang.Runtime)
  at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
  - locked <0x0af6cc74> (a java.lang.Runtime)
  at java.lang.System.loadLibrary(System.java:1657)
  at com.my.app.frida.Frida.init(Frida.java:26)
  at com.my.app.App.onCreate(App.java:157)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5844)
  at android.app.ActivityThread.-wrap1(ActivityThread.java:-1)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:176)
  at android.app.ActivityThread.main(ActivityThread.java:6662)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
  
Java Code:
```java
        System.loadLibrary("gadget");
 ```
apk so files:
```
my.apk
  lib
    armeabi-v7a
      libgadget.config.so
      libgadget.so
```

**Comment by Nord-1** [comment]
Here are few links to get you successfully get the job done: 

https://frida.re/docs/gadget/#listen
https://lief-project.github.io/doc/stable/tutorials/09_frida_lief.html#id8
https://github.com/sensepost/objection/wiki/Patching-Android-Applications#patching---dependencies
https://koz.io/using-frida-on-android-without-root/
https://www.netspi.com/blog/technical/mobile-application-penetration-testing/four-ways-bypass-android-ssl-verification-certificate-pinning/?print=pdf

**Comment by harshitshah4** [comment]
Facing the same issue on Samsung Galaxy J7 prime, Android v8, working on most of the other devices.

What is your device version ?

**Comment by harshitshah4** [comment]
@sevenshal are you using magisk or magisk hide in device ?
