### ISSUE TITLE
Spawn android app from frida returns frida.NotSupportedError: java API not available 

### ISSUE THREAD

**Issue by wejdan** [frida/frida#183]
I am trying to hook to function in android game that called very early during the startup of the app.
I could not use the usual hooking methods because the function is called too soon before frida can attach to the process.So I searched for frida early instrumentation and found something called spawn.
After some research I wrote this script to spwan the game from frida

```
import frida
import sys


device = frida.get_device_manager().enumerate_devices()[-1]
pid = device.spawn(["com.app"])
print (pid)
session = device.attach(pid)
ss = '''
Interceptor.attach(Module.findExportByName("somelib.so" , "function"), {
    onEnter: function(args) {
       console.log("hello")


    },
    onLeave:function(retval){
       send(retval);



    }
});
'''    
script = session.create_script(ss)
script.load()
device.resume(pid)
session.detach()
```

however when I run the script I get this error

```
Traceback (most recent call last):
  File "birds.py", line 6, in <module>
    pid = device.spawn(["com.app"])
  File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 84, in spawn
    return self._impl.spawn(argv)
frida.NotSupportedError: java API not available
```

**Comment by yinzehaonb** [comment]
did you make it well?
