### ISSUE TITLE
Error: Unable to determine ClassLinker field offsets

### ISSUE THREAD

**Issue by DingChengMing** [frida/frida#1845]
Phone: Pixel2 arm64-v8a
Start frida error:
{"type":"error","description":"Error: Unable to determine ClassLinker field offsets","stack":"Error: Unable to determine ClassLinker field offsets\n    at Ge (frida/node_modules/frida-java-bridge/lib/android.js:378:1)\n    at frida/node_modules/frida-java-bridge/lib/memoize.js:4:1\n    at Ie (frida/node_modules/frida-java-bridge/lib/android.js:186:1)\n    at Ce (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n    at g._tryInitialize (frida/node_modules/frida-java-bridge/index.js:17:1)\n    at new g (frida/node_modules/frida-java-bridge/index.js:9:1)\n    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:317:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at frida/node_modules/browser-pack/_prelude.js:1:1\n    at Object.20.frida-java-bridge (frida/runtime/java.js:1:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":378,"columnNumber":1}

**Comment by tollytu** [comment]
Thr  Same problem that I met
