### ISSUE TITLE
Module.Load "dlopen failed: 'mycustomlib.so' segment 0: Permission denied

### ISSUE THREAD

**Issue by RealIndica** [frida/frida#1868]
Still trying to get the hang of Frida, but this this error shows up when I call my function :
```
function loadLibrary(library: string){  //library == "/data/local/tmp/libBootstrap.so"

    Module.load(library);

    if (library == "/data/local/tmp/libBootstrap.so"){
        var func_ptr = Module.findExportByName('libBootstrap.so', 'Initialize');
        var f = new NativeFunction(func_ptr as NativePointerValue, 'bool', []);
        f();
    }
    
}
```

Error :
```
Error: dlopen failed: couldn't map "/data/local/tmp/libBootstrap.so" segment 0: Permission denied
    at Function.value [as load] (frida/runtime/core.js:189:1)
    at injectLibrary (agent/Bootstrap/init.ts:24:12)
    at Initialize (agent/Bootstrap/init.ts:9:5)
    at agent/index.ts:30:15
    at executor (node_modules/frida-il2cpp-bridge/dist/il2cpp/base.js:79:1)
```

I am using a Frida Gadget. (I am rooted, but frida-server seems to be problematic)

If anyone has any solutions please let me know :)

**Comment by dan4ik94** [comment]
@RealIndica try loading your custom lib with lief.
https://lief-project.github.io/doc/latest/tutorials/09_frida_lief.html
