### ISSUE TITLE
ImportError: DLL load failed while importing _frida: The specified module could not be found.

### ISSUE THREAD

**Issue by hanirouatbi1** [frida/frida#1878]
```
C:\Users\MSI>frida --version

***
Failed to load the Frida native extension: DLL load failed while importing _frida: The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\Scripts\frida-script.py", line 33, in <module>
    sys.exit(load_entry_point('frida-tools==10.4.1', 'console_scripts', 'frida')())
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\site-packages\frida_tools\repl.py", line 24, in main
    import frida
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\__init__.py", line 24, in <module>
    raise ex
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\__init__.py", line 7, in <module>
    import _frida
ImportError: DLL load failed while importing _frida: The specified module could not be found.
```
windows 10 version 21h1
Python 3.10.0

**Comment by hanirouatbi1** [comment]
Solved !
Solution : Install Python 3.7.0 and it will work 100%

**Comment by BlackINT3** [comment]
Because the import function table of _frida.cp310-win_amd64.pyd is unavailable(compiler bug?), wait for a new offcial build to fix.
![image](https://user-images.githubusercontent.com/35478470/142561999-a9bda470-7c5e-46b3-a873-95b8375c5aff.png)

**Comment by raulsiles** [comment]
Please, re-open this issue as it needs to be fixed for future Python versions. It can be reproduced in a Windows 10 64-bit system both with Python 3.10.1 and 3.10.2. It is good to have a workaround by going back to previous Python 3.x versions, but I suggest to keep it as pending for a future fix:
```
C:\>python -V
Python 3.10.2

C:\>frida-ls-devices

***
Failed to load the Frida native extension: DLL load failed while importing _frida: The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Python3\Scripts\frida-ls-devices-script.py", line 33, in <module>
    sys.exit(load_entry_point('frida-tools==10.4.1', 'console_scripts', 'frida-ls-devices')())
  File "C:\Python3\lib\site-packages\frida_tools\lsd.py", line 6, in main
    import frida
  File "C:\Python3\lib\site-packages\frida\__init__.py", line 24, in <module>
    raise ex
  File "C:\Python3\lib\site-packages\frida\__init__.py", line 7, in <module>
    import _frida
ImportError: DLL load failed while importing _frida: The specified module could not be found.
```

**Comment by Shameel123** [comment]
> Please, re-open this issue as it needs to be fixed for future Python versions. It can be reproduced in a Windows 10 64-bit system both with Python 3.10.1 and 3.10.2. It is good to have a workaround by going back to previous Python 3.x versions, but I suggest to keep it as pending for a future fix:
> 
> ```
> C:\>python -V
> Python 3.10.2
> 
> C:\>frida-ls-devices
> 
> ***
> Failed to load the Frida native extension: DLL load failed while importing _frida: The specified module could not be found.
> Please ensure that the extension was compiled for Python 3.x.
> ***
> 
> Traceback (most recent call last):
>   File "C:\Python3\Scripts\frida-ls-devices-script.py", line 33, in <module>
>     sys.exit(load_entry_point('frida-tools==10.4.1', 'console_scripts', 'frida-ls-devices')())
>   File "C:\Python3\lib\site-packages\frida_tools\lsd.py", line 6, in main
>     import frida
>   File "C:\Python3\lib\site-packages\frida\__init__.py", line 24, in <module>
>     raise ex
>   File "C:\Python3\lib\site-packages\frida\__init__.py", line 7, in <module>
>     import _frida
> ImportError: DLL load failed while importing _frida: The specified module could not be found.
> ```

Facing similar issue with same specs as you mentioned.

**Comment by nazeno** [comment]
> > Please, re-open this issue as it needs to be fixed for future Python versions. It can be reproduced in a Windows 10 64-bit system both with Python 3.10.1 and 3.10.2. It is good to have a workaround by going back to previous Python 3.x versions, but I suggest to keep it as pending for a future fix:
> > ```
> > C:\>python -V
> > Python 3.10.2
> > 
> > C:\>frida-ls-devices
> > 
> > ***
> > Failed to load the Frida native extension: DLL load failed while importing _frida: The specified module could not be found.
> > Please ensure that the extension was compiled for Python 3.x.
> > ***
> > 
> > Traceback (most recent call last):
> >   File "C:\Python3\Scripts\frida-ls-devices-script.py", line 33, in <module>
> >     sys.exit(load_entry_point('frida-tools==10.4.1', 'console_scripts', 'frida-ls-devices')())
> >   File "C:\Python3\lib\site-packages\frida_tools\lsd.py", line 6, in main
> >     import frida
> >   File "C:\Python3\lib\site-packages\frida\__init__.py", line 24, in <module>
> >     raise ex
> >   File "C:\Python3\lib\site-packages\frida\__init__.py", line 7, in <module>
> >     import _frida
> > ImportError: DLL load failed while importing _frida: The specified module could not be found.
> > ```
> 
> Facing similar issue with same specs as you mentioned.

Same version 3.10.2, same error here too

**Comment by oleavr** [comment]
The issue is in our setup.py's [hack](https://github.com/frida/frida-python/blob/3f635bc84bab96a7eb97d1c75a0cb75013c28ab2/setup.py#L145-L146) that patches the downloaded extension, replacing the hard-coded Python DLL name reference (e.g. `python38.dll`) with e.g. `python310.dll`. This is so we don't have to build an extension per Python release, since the 3.x ABI is stable. However, this hack won't work here since the string now needs more space. Perhaps we can move the build machine to 3.10, and just make sure we insert a NUL byte so it will also work for versions with only two digits.

**Comment by raulsiles** [comment]
This issue can be closed. The latest Frida version, 15.1.17, fixes the "ImportError" and it works in Windows with Python 3.10.2:
```
C:\>python -V
Python 3.10.2

C:\>frida --version
15.1.17

C:\>pip3 list | findstr frida-tools
frida-tools                       10.5.4

C:\>frida-ls-devices
Id      Type    Name
------  ------  ------------
local   local   Local System
socket  remote  Local Socket
```

**Comment by 89z** [comment]
https://github.com/frida/frida/issues/1927

**Comment by 89z** [comment]
https://github.com/frida/frida-python/issues/191

**Comment by 89z** [comment]
> The latest Frida version, 15.1.17, fixes the "ImportError" and it works in Windows with Python 3.10.2

I can confirm this. Newer Frida fixes now works with Python 3.10.

**Comment by Justxd22** [comment]
Doesn't work on python 3.9.6 from the docs it says python 3.x so it should work fine

```
$ py --version
Python 3.9.6                                                                      $
$ pip install frida-tools                                                         Collecting frida-tools
  Using cached frida_tools-10.6.1-py3-none-any.whl
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from frida-tools) (0.4.4)
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from frida-tools) (2.9.0)                     Collecting frida<16.0.0,>=15.0.0
  Using cached frida-15.1.17-cp39-cp39-linux_aarch64.whl
Requirement already satisfied: prompt-toolkit<4.0.0,>=2.0.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from frida-tools) (3.0.24)
Requirement already satisfied: setuptools in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from frida<16.0.0,>=15.0.0->frida-tools) (56.0.0)
Requirement already satisfied: wcwidth in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from prompt-toolkit<4.0.0,>=2.0.0->frida-tools) (0.2.5)
Installing collected packages: frida, frida-tools
Successfully installed frida-15.1.17 frida-tools-10.6.1                           WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/data/data/com.termux/files/usr/bin/python3 -m pip install --upgrade pip' command.                                           $
$ frida-ps
                                                                                  ***
Failed to load the Frida native extension: dlopen failed: library "libpython3.10.so.1.0" not found
Please ensure that the extension was compiled for Python 3.x.                     ***

Traceback (most recent call last):                                                  File "/data/data/com.termux/files/usr/bin/frida-ps", line 8, in <module>
    sys.exit(main())                                                                File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/frida_tools/ps.py", line 17, in main                                                                from frida_tools.application import ConsoleApplication
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/frida_tools/application.py", line 23, in <module>
    import frida
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/frida/__init__.py", line 24, in <module>
    raise ex
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/frida/__init__.py", line 7, in <module>
    import _frida
ImportError: dlopen failed: library "libpython3.10.so.1.0" not found
```

It's looking for "libpython3.10.so.1.0" which obviously is not installed i tried renaming "libpython3.9.so.1.0" to "libpython3.10.so.1.0" in /lib/ still doesn't work why using a hard coded path???

**Comment by Justxd22** [comment]
Edit: 
As @oleavr said it's a problem with setup.py patching to `libpython3.8.so.1.0` for example has one digit `8` while 3.10 has two digits `10` i tried using `00` as a null in hex editor resulting in `libpython3.8..so.1.0` doesn't work a quick search, there's a tool made for patching elf 

`
patchelf --replace-needed  libpython3.10.so.1.0 libpython3.9.so.1.0 ./_frida.cpython-39.so
`
It's now working!

Installed on termux android 10
![Screenshot_20220430_003936_com noodlecake altosadventure](https://user-images.githubusercontent.com/66136622/166073464-4d588b69-dd91-4562-91c1-27d9a761d3d4.jpg)

**Comment by hagag-Fintech** [comment]
Doesn't work on python 3.12 from the docs it says the python

Failed to load the Frida native extension: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_frida.abi3.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_frida.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_frida.abi3.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_frida.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
Please ensure that the extension was compiled correctly
***

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/frida", line 5, in <module>
    from frida_tools.repl import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida_tools/repl.py", line 18, in <module>
    import frida
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida/__init__.py", line 16, in <module>
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida/__init__.py", line 4, in <module>
    import _frida
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_frida.abi3.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_frida.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_frida.abi3.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_frida.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by hagag-Fintech** [comment]
It occurs because it cannot set the path correctly due to privileges

to fix this issue:
Uninstall the frida - pip uninstall frida-tools
then install it with sudo - sudo pip install frida-tools

It should be fixed now.

**Comment by Davis-3450** [comment]
Had the same issue in >3.8, used 3.8 and it worked
