### ISSUE TITLE
Android crashes + reboots upon running frida-server

### ISSUE THREAD

**Issue by hacker-h** [frida/frida#1879]
My Android device suddenly reboots upon running frida server.
Occasionally it takes longer time and logs this error before rebooting:
```json
{
  "type": "error",
  "description": "TypeError: Cannot read property 'queryIntentActivities' of null",
  "stack": "TypeError: Cannot read property 'queryIntentActivities' of null\n    at detectLauncherPackageName (/internal-agent.js:403:36)\n    at init (/internal-agent.js:49:21)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n    at g._performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238:1)\n    at frida/node_modules/frida-java-bridge/index.js:213:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n    at g._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)\n    at g.perform (frida/node_modules/frida-java-bridge/index.js:192:1)\n    at /internal-agent.js:490:6",
  "fileName": "/internal-agent.js",
  "lineNumber": 403,
  "columnNumber": 36
}
```
Sometimes the device even becomes stuck before booting and has to be hardly resetted.

To reproduce:
1. Start frida-server-15.1.4-android-arm64 on an Android 6.0 device via adb:
   `adb shell su -c "/data/local/tmp/frida-server"`
2. wait for a few seconds.
3. The Android device crashes and reboots.

device: ZTE Blade A610 PLUS
Android 6.0
rooted: yes
Android security patch level: 05.01.2017
Kernel version: 3.18.22
Frida Version: 15.1.4

`adb --version`:
Android Debug Bridge version 1.0.41
Version 31.0.2-7242960

**Comment by Mino260806** [comment]
encountered same problem today on android 11. it used to work yesterday but when I tried it today it crashed my system

**Comment by Amrsatrio** [comment]
Happens to me aswell on Xiaomi Mi A2 with stock Android 10.

**Comment by MonkeyKingSunWuKong** [comment]
Happens to me aswell on Redmi K50 Ultra with stock Android 12.

**Comment by dreathe** [comment]
Facing the same issue here, the system architecture is arm64.

[ro.board.platform]: [msm8952]
[ro.build.hardware.version]: [D2-2]
[ro.build.version.sdk]: [23]
[ro.hardware]: [qcom]
[ro.product.manufacturer]: [Xiaomi]
[ro.product.model]: [Redmi Note 3]
[ro.product.name]: [kenzo]

**Comment by CookiesNIce** [comment]
I am having the same problem with my Samsung tablet.

Android 11
Frida version 16.0.7

**Comment by fabian-nunes** [comment]
> I am having the same problem with my Samsung tablet.
> 
> Android 11 Frida version 16.0.7
> 
> Edit: I tried it on 2 different Samsung devices. Both are different models but Frida still kept crashing. So I decided to try it on a Xiaomi phone and it worked without any problems. I don't know if this is related to ROM or if it is a problem with Samsung devices in general. I was using Frida on my Samsung phone for long time but then it stopped working (it started to crash everytime)

I am having the same problem

Android 11
Frida 16.0.8
Samsung A40 rooted

**Comment by dreathe** [comment]
My solution which made it work, was using a older version of Frida.

Frida: 15.2.2 

Ensure on both devices u have the same version. Any new version 16.x will not work, atleast for me.

**Comment by fabian-nunes** [comment]
Thanks that fixed it, i also need to execute this command too 
`setprop persist.device_config.runtime_native.usap_pool_enabled false`
to fix this problem https://github.com/frida/frida/issues/1788

**Comment by 0xdd04** [comment]
does not work at all for me, already did "setprop persist.device_config.runtime_native.usap_pool_enabled false" 

spec:
- [ro.build.version.sdk]: [31]
- [ro.product.model]: [2201123G]
- rooted

tried both frida==15.2.2 & frida==16.0.8

**Comment by fabian-nunes** [comment]
Check if you have the correct version of the frida-tools and gadget installed. For frida 15.2.2 use frida tools version 11.0.0.

**Comment by seagate00** [comment]
> does not work at all for me, already did "setprop persist.device_config.runtime_native.usap_pool_enabled false"
> 
> spec: [ro.build.version.sdk]: [31] [ro.product.model]: [2201123G] rooted
> 
> tried both frida==15.2.2 & frida==16.0.8

on my galaxy s22 device (android 13, sdk 31) frida-server has started with this prop, but he also behaved (with a restart). But after restarting, I find that frida-server is running successfully

**Comment by jhlee8804** [comment]
I uupgraded to frida 16.0.10 version and it got resolved.

**Comment by gauravssnl** [comment]
I installed the frida-server-16.1.11-android-arm64 version first , it worked for a while and I tried to run the below command as per Frida doc : frida-trace -U -i open com.android.chrome , then my phone crashed and restarted.

**What work for me** 

I have installed the frida-server-16.1.11-linux-arm64 ( **Linux version** ) and that works for me and phone is not crashing. You all can give this solution a try and let me know.


Note : my phone architecture is ARM64, please install the corresponding Linux version according to your phone architecture.

Let me know  your results.

**Comment by dem0ns** [comment]
crashed with frida 16.1.11

**Comment by Qvd66** [comment]
Did anyo find solution for this?

**Comment by unf0rgvn** [comment]
Same here. I'm testing on a Physical Android version 5.1.1 (Galaxy J7), with frida-server=16.0.1 and frida-tools=16.4.8 (checked with `frida --version`), anyone have a solution?

**Comment by yooo1999** [comment]
`setprop persist.device_config.runtime_native.usap_pool_enabled false`
Help me , @oleavr  consider to handle that reboot
