### ISSUE TITLE
Hook Java Function Crash,When Signature contains [[B

### ISSUE THREAD

**Issue by Imzpy** [frida/frida#1893]
```
Phone: Google Pixel XL
System: Android 7.1 NDE63H
FridaVersion: 15.1.1
```
```
//Java Code
public class MainActivity extends AppCompatActivity
{

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        byte[] arr1 = {1,1,1};
        return_bytes(arr1);
        byte[][] arr2 = new byte[3][4];
        return_bytes(arr2);
    }

    public void return_bytes(byte[][] ttt)
    {
        Log.e("IMXZ",ttt[0][0] + "");
    }
    public void return_bytes(byte[] ttt)
    {
        Log.e("IMXZ",ttt[0] + "");
    }
}
```
```
//Frida Js Code
console.log("[+] JScript Loaded")

console.log(Process.arch)

Java.perform(function()
{
		
		var JavaString = Java.use("java.lang.String");
		
		var MainActivity = Java.use("com.google.myapplication.MainActivity");
		console.log(MainActivity)
		MainActivity.return_bytes.overload('[B').implementation = function(arr)
		{
			console.log("Im [B");
			
			console.log(Java.use("android.util.Log").getStackTraceString(Java.use("java.lang.Exception").$new()));
			
			this.return_bytes(arr);
			
        }
		MainActivity.return_bytes.overload('[[B').implementation = function(arr)
		{
			console.log("Im [[B");
			
			console.log(Java.use("android.util.Log").getStackTraceString(Java.use("java.lang.Exception").$new()));
			
			this.return_bytes(arr);
			
        }
		
        console.log("down!");

});
```
```
//Logcat
2021-11-02 17:35:55.893 20732-20732/com.google.myapplication E/IMXZ: 1

It Can Print 1 

But On Run Sign With [[B Function  

The Application Is Crash 

2021-11-02 17:35:55.903 20732-20732/com.google.myapplication D/AndroidRuntime: Shutting down VM
2021-11-02 17:35:55.904 20732-20732/com.google.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.myapplication, PID: 20732
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.myapplication/com.google.myapplication.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "[L[B;" on path: DexPathList[[zip file "/data/app/com.google.myapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.myapplication-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2649)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6088)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "[L[B;" on path: DexPathList[[zip file "/data/app/com.google.myapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.myapplication-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.myapplication.MainActivity.return_bytes(Native Method)
        at com.google.myapplication.MainActivity.onCreate(MainActivity.java:19)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2602)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6088) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 

```

**Comment by Imzpy** [comment]
```
//Frida Console Print
Im [B
java.lang.Exception
        at com.google.myapplication.MainActivity.return_bytes(Native Method)
        at com.google.myapplication.MainActivity.onCreate(MainActivity.java:17)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2602)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6088)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)


```
The "Im [[B" and "JavaTraceMsg" No output

**Comment by xiaokanghub** [comment]
win10
Frida -> 14.2.13
Android 10(Pixel 4)
Frida Server -> 14.2.13
work well for your code
so please check your environment, such as your classes name, the version of frida on PC is same as that on mobile and etc

**Comment by Imzpy** [comment]
> win10 Frida -> 14.2.13 Android 10(Pixel 4) Frida Server -> 14.2.13 适用于您的代码， 因此请检查您的环境，例如您的类名称，PC 上的 frida 版本与移动设备上的相同，并且等等

I've tested 14.2.13 and you are right.
I tried the latest version, 15.1.10, but it didn't work.
If it's just Hook , it can work 
But when app call the [[B function, Frida will crash.
You can try it.
```
//cmd
frida -U -f com.google.test_bytes -l auto_task.js --runtime=v8 --no-pause
```

**Comment by xiaokanghub** [comment]
the latest frida seems not support old Android :), not very friendly to older device

**Comment by Imzpy** [comment]
> > win10 Frida -> 14.2.13 Android 10(Pixel 4) Frida Server -> 14.2.13 适用于您的代码，因此请检查您的环境，您的类名称，PC 上的 frida 版本与移动设备上的相同，并且等等
> 
> 我已经测试了 14.2.13，你是对的。 我尝试了最新版本 15.1.10，但没有用。 如果只是 Hook ，它可以工作 但是当应用程序调用 [[B 函数时，Frida 会崩溃。 你可以试试看。
> 
> ```
> //cmd
> frida -U -f com.google.test_bytes -l auto_task.js --runtime=v8 --no-pause
> ```



> the latest frida seems not support old Android :), not very friendly to older device

It shows the same situation on piexl3 , Android 9

**Comment by xiaokanghub** [comment]
> > > win10 Frida -> 14.2.13 Android 10(Pixel 4) Frida Server -> 14.2.13 适用于您的代码，因此请检查您的环境，您的类名称，PC 上的 frida 版本与移动设备上的相同，并且等等
> > 
> > 
> > 我已经测试了 14.2.13，你是对的。 我尝试了最新版本 15.1.10，但没有用。 如果只是 Hook ，它可以工作 但是当应用程序调用 [[B 函数时，Frida 会崩溃。 你可以试试看。
> > ```
> > //cmd
> > frida -U -f com.google.test_bytes -l auto_task.js --runtime=v8 --no-pause
> > ```
> 
> > the latest frida seems not support old Android :), not very friendly to older device
> 
> It shows the same situation on piexl3 , Android 9

kk, I have same problem , '[[B]' to '[L[B', It should be a Frida bug

**Comment by xiaokanghub** [comment]
@oleavr

**Comment by Imzpy** [comment]
> @oleavr

I think so, too

Ha ha, I know for the first time that GitHub can @ author

**Comment by Kavakuo** [comment]
Same problem with frida 15.1.17, Pixel 5 @ Android 11

**Comment by ssikyou** [comment]
Same in latest 15.1.22

**Comment by ahmedmani** [comment]
this is still a problem in 15.2.2

**Comment by javiercr** [comment]
I've tested different versions and the latest one that does not crashes as described in this issue is 14.2.18. 

However that version does not include [this commit](https://github.com/frida/frida-java-bridge/commit/00b8b2666377f5d8d8d2383fb1b6eba350b125d6) which was introduced in 15.0.0 and helps printing byte array as string (i.e. rendering the list of decimals rather than just [Object object]). 

On 14.2.18 you'll need to call `object.toJSON().toString()` manually.

**Comment by meiraxx** [comment]
Having this same issue.
