### ISSUE TITLE
Maximum call stack size exceeded frida-server arm64

### ISSUE THREAD

**Issue by andrey-yalta** [frida/frida#1904]
Hello! I use Meizu M5 (android 6.0, flyme 6.3.1 OG) with this processor:

_Processor       : AArch64 Processor rev 2 (aarch64)
processor       : 0
model name      : AArch64 Processor rev 2 (aarch64)
BogoMIPS        : 26.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 2
Hardware        : MT6750_

I tried using different versions of the frida-server, there are:

_frida-server-15.1.1-android-arm64
frida-server-15.1.4-android-arm64
frida-server-15.1.6-android-arm64
frida-server-15.1.10-android-arm64_

,but everywhere I get an error:

_{"type":"error","description":"RangeError: Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at Array.forEach (<anonymous>)\n    at ne (frida/node_modules/frida-java-bridge/lib/class-factory.js:623:1)\n    at CallbackContext.<anonymous> (frida/node_modules/frida-java-bridge/lib/class-factory.js:592:1)\n    at Function.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1057:1)\n    at Proxy.e (frida/node_modules/frida-java-bridge/lib/class-factory.js:580:1)\n    at Function.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:963:1)\n    at Proxy.e (frida/node_modules/frida-java-bridge/lib/class-factory.js:547:1)\n    at Proxy.sendMessageDelayed.implementation (/internal-agent.js:443:31)\n    at ne (frida/node_modules/frida-java-bridge/lib/class-factory.js:613:1)\n    at CallbackContext.<anonymous> (frida/node_modules/frida-java-bridge/lib/class-factory.js:592:1)","fileName":null,"lineNumber":null,"columnNumber":null}_

help me please, what do I need to change to make it work? Thanks!

**Comment by tirekin** [comment]
I get the same error with Xperia M5, Android 6.0. Tried different versions of frida, any version after 12.11.18 stops working with the same error.

After I running:

`root@hollyss:/data/local/tmp # ./frida-server-15.1.12-android-arm64 `

The error I get is the following:

> "type":"error","description":"RangeError: Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at Proxy.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:721:1)\n    at frida/node_modules/frida-java-bridge/lib/class-factory.js:626:1\n    at Array.forEach (<anonymous>)\n    at ne (frida/node_modules/frida-java-bridge/lib/class-factory.js:623:1)\n    at CallbackContext.<anonymous> (frida/node_modules/frida-java-bridge/lib/class-factory.js:592:1)\n    at Function.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1057:1)\n    at Proxy.e (frida/node_modules/frida-java-bridge/lib/class-factory.js:580:1)\n    at Function.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:963:1)\n    at Proxy.e (frida/node_modules/frida-java-bridge/lib/class-factory.js:547:1)\n    at Proxy.sendMessageDelayed.implementation (/internal-agent.js:443:31)","fileName":"frida/node_modules/frida-java-bridge/lib/class-factory.js","lineNumber":721,"columnNumber":1}

**Comment by zhbzhbzhbz** [comment]
same issue

**Comment by MZCretin** [comment]
Have you resove this problem？

**Comment by jeytin** [comment]
same issue. help!

**Comment by Ristovski** [comment]
Same issue, also Android 6

**Comment by Ristovski** [comment]
Frida appears to corrupt the ART stack:

```
06-13 22:07:44.990 16607 16621 W art     : Throwing OutOfMemoryError "PushLocalFrame"
06-13 22:07:44.995 16607 16621 F art     : art/runtime/thread.cc:1335] Throwing new exception 'PushLocalFrame' with unexpected pending exception: java.lang.OutOfMemoryError: PushLocalFrame
06-13 22:07:44.995 16607 16621 F art     : art/runtime/thread.cc:1335]   at android.os.Process$ProcessStartResult android.os.Process.start(java.lang.String, java.lang.String, int, int, int[], int, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String[]) (Process.java:-2)
06-13 22:07:44.995 16607 16621 F art     : art/runtime/thread.cc:1335]   at android.os.Process$ProcessStartResult android.os.Process.start(java.lang.String, java.lang.String, int, int, int[], int, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String[]) (Process.java:-2)
06-13 22:07:44.995 16607 16621 F art     : art/runtime/thread.cc:1335]   at android.os.Process$ProcessStartResult android.os.Process.start(java.lang.String, java.lang.String, int, int, int[], int, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String[]) (Process.java:-2)
06-13 22:07:44.995 16607 16621 F art     : art/runtime/thread.cc:1335]   at android.os.Process$ProcessStartResult android.os.Process.start(java.lang.String, java.lang.String, int, int, int[], int, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String[]) (Process.java:-2)
06-13 22:07:44.995 16607 16621 F art     : art/runtime/thread.cc:1335]   at android.os.Process$ProcessStartResult android.os.Process.start(java.lang.String, java.lang.String, int, int, int[], int, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String[]) (Process.java:-2)
```

This repeats infinitely.
