### ISSUE TITLE
frida-server-14.2.18-android-arm64 promote error on android 12 device

### ISSUE THREAD

**Issue by lx866** [frida/frida#1921]
when i start frida-server-14.2.18-android-arm64 on android 12 device, it promote error as below:

{"type":"error","description":"Error: Unable to determine ArtMethod field offsets","stack":"Error: Unable to determine ArtMethod field offsets\n    at frida/node_modules/frida-java-bridge/lib/android.js:417:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n    at Ge (frida/node_modules/frida-java-bridge/lib/android.js:402:1)\n    at Object.getArtMethodSpec (frida/node_modules/frida-java-bridge/lib/memoize.js:4:1)\n    at o (frida/node_modules/frida-java-bridge/lib/class-model.js:73:1)\n    at _ (frida/node_modules/frida-java-bridge/lib/class-model.js:62:1)\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)\n    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)\n    at frida/node_modules/frida-java-bridge/index.js:212:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":417,"columnNumber":1}

**Comment by KANGOD** [comment]
frida-server-14.2.18-android-arm64
frida-server-15.1.17-android-arm64

On Android S devices, both of above rise an error when `adb shell "/data/local/tmp/frida-server &"`,
of which 15.1.17's error log

> {"type":"error","description":"Error: Unable to determine ArtMethod field offsets","stack":"
Error: Unable to determine ArtMethod field offsets
    at frida/node_modules/frida-java-bridge/lib/android.js:417:1
    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)
    at Ge (frida/node_modules/frida-java-bridge/lib/android.js:402:1)
    at Object.getArtMethodSpec (frida/node_modules/frida-java-bridge/lib/memoize.js:4:1)
    at o (frida/node_modules/frida-java-bridge/lib/class-model.js:73:1)
    at _ (frida/node_modules/frida-java-bridge/lib/class-model.js:62:1)
    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)
    at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)
    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)
    at frida/node_modules/frida-java-bridge/index.js:212:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":417,"columnNumber":1   
","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":417,"columnNumber":1}
