### ISSUE TITLE
Does Frida 15.1.12 compatible with Python 3.10?

### ISSUE THREAD

**Issue by derodevil** [frida/frida#1927]
Does Frida 15.1.12 compatible with Python 3.10.0? I got this error message : 

```
***
Failed to load the Frida native extension: DLL load failed while importing _frida: The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\Scripts\frida-script.py", line 33, in 
    sys.exit(load_entry_point('frida-tools==10.4.1', 'console_scripts', 'frida')())
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\lib\site-packages\frida_tools\repl.py", line 24, in main
    import frida
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\__init__.py", line 24, in 
    raise ex
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\__init__.py", line 7, in 
    import _frida
ImportError: DLL load failed while importing _frida: The specified module could not be found.
```

Using Frida 15.1.9 and Python 3.9.6 works fine.

**Comment by cedws** [comment]
I've reverted to Python 3.7.0 as a workaround. If you do this be sure to reinstall Frida too.

**Comment by derodevil** [comment]
Do you mean Python 3.10 instead of Python 3.7.0?

**Comment by 89z** [comment]
Same problem here

**Comment by 89z** [comment]
https://github.com/frida/frida-python/issues/191

**Comment by 89z** [comment]
Here is a note from Python developer:

> "_frida.cp310-win_amd64.pyd" is a bad build or corrupted file. It imports a procedure with no name from a DLL with no name, which causes the loader to search for a file named ".DLL". Even if that were found, it imports another procedure with no name or correct ordinal from "IPHLPAPI.DLL". There are probably more problems with this DLL.

https://bugs.python.org/issue46276

**Comment by raulsiles** [comment]
This issue is fixed in Frida version 15.1.17. See #1878.
