### ISSUE TITLE
Release rpm for Fedora 35

### ISSUE THREAD

**Issue by scrool** [frida/frida#1967]
Please provide rpm for Fedora 35.

Currently rpm is provided only for 34. There is no issue with that - it is still supported distribution version for another 4 months or so (until May 17, 2022). Release 35 is the newest one released in November, 2021 and will be supported for another 11 monts (until December 2022).

rpm from Fedora 34 can be installed even on 35, but Frida tools doesn't work for it, e.g.:
```
$ frida-ps                             
Traceback (most recent call last):
  File "/usr/local/bin/frida-ps", line 33, in <module>
    sys.exit(load_entry_point('frida-tools==10.4.1', 'console_scripts', 'frida-ps')())
  File "/usr/local/lib/python3.9/site-packages/frida_tools/ps.py", line 17, in main
    from frida_tools.application import ConsoleApplication
  File "/usr/local/lib/python3.9/site-packages/frida_tools/application.py", line 21, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
```

even though that package is installed on the system:
```
$ rpm -q python3-colorama
python3-colorama-0.4.4-4.fc35.noarch
```

From what I can tell the issue is that this package is installed for python 3.10, which is system's default python version:
```
$ python3 -c 'import colorama; print(colorama.__file__)'
/usr/lib/python3.10/site-packages/colorama/__init__.py
$ rpm -qf $(command -v python3)
python3-3.10.0-1.fc35.x86_64
```

There are no rpms for this python module on 3.9 on Fedora 35.

**Comment by scrool** [comment]
I wasn't sure how to (re)create build environment from which rpms are created so I created minimal container with necessary dependencies installed + some changes to create rpms for Fedora 35. See here, if you are interested: https://github.com/scrool/frida-rpm-builder

**Comment by scrool** [comment]
Well, and only now I have tried to run it and I found that because Fedora doesn't use `dist-packages` but `site-packages` e.g. `frida-ps` fails like this:
```
$ frida-ps
Traceback (most recent call last):
  File "/usr/local/bin/frida-ps", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'frida-tools==10.4.1' distribution was not found and is required by the application
```

And I confirmed this with:
```
$ cd /usr/local/lib/python3.10/
$ sudo ln -s dist-packages site-packages
```
after which `frida-ps` works on Fedora 35.
