### ISSUE TITLE
Frida server is not working on Android 12 which supports multi arch

### ISSUE THREAD

**Issue by cryptax** [frida/frida#1977]
I am using an Android emulator AVD with **Android 12 x86_64**. 
Since Android 11, Android supports [multi architectures](https://android-developers.googleblog.com/2020/03/run-arm-apps-on-android-emulator.html), so for instance you can run an Android ARM app on an Android x86 emulator.

When I log in the emulator, note I get this prompt: `emulator64_x86_64_arm64` and not only `x86_64` (or `arm64`).

I am trying to use **Frida server 15.1.14 x86_64** on the emulator and it complains

```
emulator64_x86_64_arm64:/data/local/tmp # ./frida-server-15.1.14-android-x86_64                                                                                                   
{"type":"error","description":"TypeError: r is not a function","stack":"TypeError: r is not a function\n    at CallbackContext.lt (frida/node_modules/frida-java-bridge/lib/android.js:548:1)\n    at NativeFunction.<anonymous> (<anonymous>)\n    at dt (frida/node_modules/frida-java-bridge/lib/android.js:543:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)\n    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)\n    at frida/node_modules/frida-java-bridge/index.js:212:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n    at y._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":548,"columnNumber":1}
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at dt (frida/node_modules/frida-java-bridge/lib/android.js:543:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)\n    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)\n    at frida/node_modules/frida-java-bridge/index.js:212:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n    at y._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)\n    at y.perform (frida/node_modules/frida-java-bridge/index.js:192:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":543,"columnNumber":1}
```

My guess is that this emulator _does not work on those very recent Android emulator_ (probably >=11). I confirm the same server works on Android emulator 8 and 9.

Is a Frida server planned for 11+? Thanks

**Comment by cryptax** [comment]
Duplicate of https://github.com/frida/frida/issues/1917
