### ISSUE TITLE
TimedOutError when trying to spawn Android apps

### ISSUE THREAD

**Issue by cryptax** [frida/frida#2005]
I am currently unable to spawn an **Android app** on an Android **emulator** using Frida: it reboots the emulator (!) and in the end, I get a `TimedOutError`.

```
$ frida -U -l okhttp.js -f com.core.course
...
Failed to spawn: unexpectedly timed out while waiting for app to launch
```

This seems to **happen with any Android app**... For example, same with `frida -U -l okhttp.js -f com.android.contacts`, where `com.android.contacts` is a system app. This is extremely weird, because for sure it used to work before! 

**Environment**:

- Frida 15.1.14
- Frida Tools 10.4.1
- Android Emulator 8, x86_64 root, no Play Store. *I'll test with other emulators soon and let you know*
- Inside the emulator, a Frida Server 15.1.14 x86_64
- Python 3.8.10, Linux Mint 20.2

**Other attempts**

Instead of using Frida command line, I tried with a Python script that does the same:

```python
...
device = frida.get_usb_device(timeout=1)
pid = device.spawn(["com.core.course"])
session = device.attach(pid)
script = session.create_script(javascript_source)
script.load()
device.resume(pid)
sys.stdin.read()
```

and the result is the same

```
$ python3 frida-alien-spawn.py 
Traceback (most recent call last):
  File "frida-alien-spawn.py", line 10, in <module>
    pid = device.spawn(["com.core.course"])
  File "/home/axelle/softs/venv/objection-venv/lib/python3.8/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/home/axelle/softs/venv/objection-venv/lib/python3.8/site-packages/frida/core.py", line 149, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.TimedOutError: unexpectedly timed out while waiting for app to launch
```

**Other tests**

- `frida-ps -U` works fine

**Misc**

Initially, I thought this was an error of _Objection_ or _FRIDA-dexdump_, but this [issue at Objection - see the end](https://github.com/sensepost/objection/issues/401) made me test directly with Frida, and notice that indeed, the issue seems to be with Frida!

**Comment by cryptax** [comment]
I've created a video of the issue.
You see that Frida communicates correctly with the emulator. However we are unable to spawn any app.

https://user-images.githubusercontent.com/2493690/152315061-0a2639b7-0aa8-4305-a572-3cf95d580caf.mp4

**Comment by cryptax** [comment]
Still occurs with Frida `15.1.16`

**Comment by cryptax** [comment]
Important remark: the issue does not happen with Android 9 _x86_. It seems it only happens with **x86_64**.

```
Spawned `com.android.contacts`. Use %resume to let the main thread start executing!
[Android Emulator 5554::com.android.contacts]->
```

**Comment by bthrx** [comment]
I have had this issue as well. It was working with x86_64 with the Frida 15.1.15 release however when I downgraded back to that version with 10.4.1 frida-tools it was no longer working for me on x86_64. With the latest release of frida-tools 10.5.4 it will spawn applications but when applying a script with -l or --codeshare it gives a `Failed to load script: the connection is closed` error.

**Comment by cryptax** [comment]
The issue still occurs with Frida **15.1.17** and Frida tools **10.5.4**

- TimedOutError with Android 8 x86_64 and Android 9 x86_64
- Works with Android 10 x86_64, and with Android 9 x86
- `frida-ps -U` works in all cases.

Test: `frida -U -f com.android.contacts`. Note it also fails with `--debug`

**Comment by aburaksahin** [comment]
After upgrading from 15.1.11 -> 15.1.17. I've encountered this issue.

**Comment by joaogmarques** [comment]
> I have had this issue as well. It was working with x86_64 with the Frida 15.1.15 release however when I downgraded back to that version with 10.4.1 frida-tools it was no longer working for me on x86_64. With the latest release of frida-tools 10.5.4 it will spawn applications but when applying a script with -l or --codeshare it gives a `Failed to load script: the connection is closed` error.

Was getting this issue on API lvl 30 x86_64 emulator with frida version 15. With frida 14.2.18 no errors shown.
The error never appeared on physical devices.

**Comment by cryptax** [comment]
Just tested with Frida Tools **10.6.1** and Frida 15.1.17: still the same problem `Failed to spawn: unexpectedly timed out while waiting for app to launch`.

- The issue is with _emulators_ (not physical devices)
- **Android 8 x86_64 emulator: time out**
- **Android 9 x86_64 emulator: time out**
- Android 10 x86_64 emulator: works
- Android 11 x86_64 emulator: works

**Comment by freeload101** [comment]
Same here Frida 15.2.2

Android 12 x86_64 emulator: time out
Android 10 x86_64 emulator: time out

same with objection :
objection --gadget com.sushirolls.app explore
frida.TimedOutError: unexpectedly timed out while waiting for app to launch

same with universal-android-ssl-pinning-bypass-with-frida.js
frida -U -f com.sushirolls.app -l universal-android-ssl-pinning-bypass-with-frida.js --no-pause
Failed to spawn: unexpectedly timed out while waiting for app to launch

same with com.duckduckgo.mobile.android:
objection --gadget com.duckduckgo.mobile.android explore


Strange thing is frida is not even running on the emulator ?!?! yet ....

C:\DELETE\frida-server-15.2.2-android-x86_64>adb shell -t "ps -A | grep -ia frida"

C:\DELETE\frida-server-15.2.2-android-x86_64>frida-ps -U | find "gapps"
1639  com.google.process.gapps

I feel like it's not connecting to the actual frida server on the device
frida-server-15.2.2-android-x86_64

adb shell -t "file /data/local/tmp/frida-server"
/data/local/tmp/frida-server: ELF shared object, 64-bit LSB x86-64, dynamic (/system/bin/linker64), for Android 21, built by NDK r24-beta1 (7856742)



When I did get Frida to work 5 years ago it was with hardware... now I am trying to build a lajit 'portable' script and this is THE part I can't working .. like the most important part...

**Comment by captn3m0** [comment]
Moto G4 Plus running Android 7.0. Have frida 14.2.7 working. Latest one breaks similarly.

**Comment by bulutg** [comment]
I am having the same issue with x86_64 Android 10 emulator

**Comment by RevB3nd** [comment]
> 刚刚用 Frida Tools **10.6.1** 和 Frida 15.1.17 进行了测试：仍然是同样的问题。`Failed to spawn: unexpectedly timed out while waiting for app to launch`
> 
> * 问题出在_模拟器_（不是物理设备）上
> * **Android 8 x86_64模拟器：超时**
> * **Android 9 x86_64模拟器：超时**
> * Android 10 x86_64模拟器：有效
> * Android 11 x86_64模拟器：有效

Now I have encountered the same problem as you, how should I solve it？

**Comment by rebasecase** [comment]
Still broken. Frida latest. (16.7.14)
