### ISSUE TITLE
Error installing frida on Windows

### ISSUE THREAD

**Issue by Rothes** [frida/frida#2012]
## Description
Got errors while installing frida. Tried on Python3.10.2/3.9.10/3.7.9/3.7.2, which got same error.

`pip install frida==15.1.10` will stuck on `  Building wheel for frida (setup.py) ... -`

## System
**OS:** Windows 11 x64 b22543.1000

## Trace
```text
K:\Program Files\Python310\Lib>pip install frida
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting frida
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c6/0e/9b837472e1dd866ef002a6bf5f2dde42b0c4f0bfcf8f5ab80797a148025e/frida-15.1.17.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in k:\program files\python310\lib\site-packages (from frida) (58.1.0)
Building wheels for collected packages: frida
  Building wheel for frida (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\frida
      copying frida\core.py -> build\lib.win-amd64-3.10\frida
      copying frida\__init__.py -> build\lib.win-amd64-3.10\frida
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qqsid_hj\frida_97651b42450746a2bcffe6522e28a180\setup.py", line 288, in <module>
          setup(
        File "K:\Program Files\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "K:\Program Files\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "K:\Program Files\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "K:\Program Files\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "K:\Program Files\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "K:\Program Files\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "K:\Program Files\Python310\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "K:\Program Files\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "K:\Program Files\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "K:\Program Files\Python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "K:\Program Files\Python310\lib\distutils\command\build_ext.py", line 340, in run
          self.build_extensions()
        File "K:\Program Files\Python310\lib\distutils\command\build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "K:\Program Files\Python310\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qqsid_hj\frida_97651b42450746a2bcffe6522e28a180\setup.py", line 119, in build_extension
          index_url = normalize_url(index_url)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qqsid_hj\frida_97651b42450746a2bcffe6522e28a180\setup.py", line 207, in normalize_url
          if not path.endswith("/"):
      TypeError: endswith first arg must be bytes or a tuple of bytes, not str
      looking for prebuilt extension in home directory, i.e. C:\Users\Administrator/frida-15.1.17-py3.10-win-amd64.egg
      prebuilt extension not found in home directory, will try downloading it
      querying pypi for available prebuilds
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for frida
  Running setup.py clean for frida
Failed to build frida
Installing collected packages: frida
  Running setup.py install for frida ... error
  error: subprocess-exited-with-error

  × Running setup.py install for frida did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\frida
      copying frida\core.py -> build\lib.win-amd64-3.10\frida
      copying frida\__init__.py -> build\lib.win-amd64-3.10\frida
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qqsid_hj\frida_97651b42450746a2bcffe6522e28a180\setup.py", line 288, in <module>
          setup(
        File "K:\Program Files\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "K:\Program Files\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "K:\Program Files\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "K:\Program Files\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "K:\Program Files\Python310\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "K:\Program Files\Python310\lib\distutils\command\install.py", line 568, in run
          self.run_command('build')
        File "K:\Program Files\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "K:\Program Files\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "K:\Program Files\Python310\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "K:\Program Files\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "K:\Program Files\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "K:\Program Files\Python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "K:\Program Files\Python310\lib\distutils\command\build_ext.py", line 340, in run
          self.build_extensions()
        File "K:\Program Files\Python310\lib\distutils\command\build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "K:\Program Files\Python310\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qqsid_hj\frida_97651b42450746a2bcffe6522e28a180\setup.py", line 119, in build_extension
          index_url = normalize_url(index_url)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qqsid_hj\frida_97651b42450746a2bcffe6522e28a180\setup.py", line 207, in normalize_url
          if not path.endswith("/"):
      TypeError: endswith first arg must be bytes or a tuple of bytes, not str
      looking for prebuilt extension in home directory, i.e. C:\Users\Administrator/frida-15.1.17-py3.10-win-amd64.egg
      prebuilt extension not found in home directory, will try downloading it
      querying pypi for available prebuilds
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> frida

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by Rothes** [comment]
Solved by putting `frida-15.1.17-py3.10-win-amd64.egg` to `C:\Users\Administrator`
