### ISSUE TITLE
`TypeError: n is not a function` issue on Android 12 Emulator

### ISSUE THREAD

**Issue by wrlu** [frida/frida#2018]
Frida server met an issue and let me file a bug .
Frida version: 15.1.17
Target information: Android 12 Emulator, with fingerprint `google/sdk_gphone64_x86_64/emulator64_x86_64_arm64:12/SE1A.211012.001/7818354:userdebug/dev-keys`
Output details:
```json
{
    "type": "error",
    "description": "TypeError: n is not a function",
    "stack": "TypeError: n is not a function
        at CallbackContext.pt (frida/node_modules/frida-java-bridge/lib/android.js:552:1)
        at NativeFunction.<anonymous> (<anonymous>)
        at lt (frida/node_modules/frida-java-bridge/lib/android.js:543:1)
        at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1
        at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)
        at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)
        at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)
        at frida/node_modules/frida-java-bridge/index.js:212:1
        at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)
        at y._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)",
    "fileName": "frida/node_modules/frida-java-bridge/lib/android.js",
    "lineNumber": 552,
    "columnNumber": 1
}
{
    "type": "error",
    "description": "Error: Unable to perform state transition; please file a bug",
    "stack": "Error: Unable to perform state transition; please file a bug
        at lt (frida/node_modules/frida-java-bridge/lib/android.js:543:1)
        at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1
        at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)
        at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)
        at frida/node_modules/frida-java-bridge/index.js:212:1
        at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)
        at y._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)
        at y.perform (frida/node_modules/frida-java-bridge/index.js:192:1)
        at /internal-agent.js:490:6",
    "fileName": "frida/node_modules/frida-java-bridge/lib/android.js",
    "lineNumber": 543,
    "columnNumber": 1
}
```

**Comment by Binozo** [comment]
Problem still exists
