### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Nishantbhagat57** [frida/frida#2021]
================================================
                Frida Started!
================================================
{"type":"error","description":"TypeError: n.art::mirror::Object::Clone is not a function","stack":"TypeError: n.art::mirror::Object::Clone is not a function\n    at rn (frida/node_modules/frida-java-bridge/lib/android.js:1238:1)\n    at $t.replace (frida/node_modules/frida-java-bridge/lib/android.js:1083:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1011:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:926:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at y._performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238:1)\n    at frida/node_modules/frida-java-bridge/index.js:213:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1238,"columnNumber":1}

**Comment by mContext** [comment]
I solved the problem after uninstalling the Xposed framework.
