### ISSUE TITLE
Ill-formed JS scripts lead to "frida.TransportError: timeout was reached"

### ISSUE THREAD

**Issue by Chaoses-Ib** [frida/frida#2028]
frida: 15.1.17
frida-tools: 10.5.4
Python: 3.9.1
OS: Windows 11 22000.527 x64

Reproduce the issue:
```python
import frida
import subprocess

notepad = subprocess.Popen("notepad.exe")

session = frida.attach("notepad.exe")
print(session)

script = session.create_script("""
1+1
""")
print(script)

script = session.create_script("""
1+
""")
print(script)

def on_message(message, data):
    print(message)
script.on('message', on_message)
script.load()

input()
notepad.kill()
```
Output:
```
Session(pid=22764)
<_frida.Script object at 0x0000019615406150>
Traceback (most recent call last):
  File "C:\frida\timeout.py", line 14, in <module>
    script = session.create_script("""
  File "C:\ProgramData\Miniconda3\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\frida\core.py", line 262, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
frida.TransportError: timeout was reached
```

Why does the ill-formed JS script result in a TransportError rather than a syntax error? It's confusing and hides the real problem. I hope this will be fixed or at least documented to make frida more friendly for people not familiar with JS.

**Comment by re995** [comment]
This happens in Android and iOS too when the script has syntax error(s)

**Comment by diewu0421** [comment]
I have the same problem, but my script has no syntax problem。
