### ISSUE TITLE
MacOs 12.2.1  pip install

### ISSUE THREAD

**Issue by striveben** [frida/frida#2030]
pip3 install frida
WARNING: Ignoring invalid distribution -rida (/Users/cpr/Library/Python/3.7/lib/python/site-packages)
WARNING: Ignoring invalid distribution - (/Users/cpr/Library/Python/3.7/lib/python/site-packages)
WARNING: Ignoring invalid distribution -umpy (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -rida (/Users/cpr/Library/Python/3.7/lib/python/site-packages)
WARNING: Ignoring invalid distribution - (/Users/cpr/Library/Python/3.7/lib/python/site-packages)
WARNING: Ignoring invalid distribution -umpy (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages)
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting frida
  Using cached http://mirrors.aliyun.com/pypi/packages/c6/0e/9b837472e1dd866ef002a6bf5f2dde42b0c4f0bfcf8f5ab80797a148025e/frida-15.1.17.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from frida) (60.9.3)
Building wheels for collected packages: frida
  Building wheel for frida (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-3.7
      creating build/lib.macosx-10.9-x86_64-3.7/frida
      copying frida/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/frida
      copying frida/core.py -> build/lib.macosx-10.9-x86_64-3.7/frida
      running build_ext
      looking for prebuilt extension in home directory, i.e. /Users/cpr/frida-15.1.17-py3.7-macosx-10.9-x86_64.egg
      prebuilt extension not found in home directory, will try downloading it
      querying pypi for available prebuilds
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/y_/vn4gwqxn4fqg1940p7p_1zgm0000gn/T/pip-install-dr64ca73/frida_b9750e1fd049487c887f06d670aa1e9f/setup.py", line 330, in <module>
          zip_safe=False
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/y_/vn4gwqxn4fqg1940p7p_1zgm0000gn/T/pip-install-dr64ca73/frida_b9750e1fd049487c887f06d670aa1e9f/setup.py", line 119, in build_extension
          index_url = normalize_url(index_url)
        File "/private/var/folders/y_/vn4gwqxn4fqg1940p7p_1zgm0000gn/T/pip-install-dr64ca73/frida_b9750e1fd049487c887f06d670aa1e9f/setup.py", line 207, in normalize_url
          if not path.endswith("/"):
      TypeError: endswith first arg must be bytes or a tuple of bytes, not str
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for frida
  Running setup.py clean for frida
Failed to build frida
WARNING: Ignoring invalid distribution -rida (/Users/cpr/Library/Python/3.7/lib/python/site-packages)
WARNING: Ignoring invalid distribution - (/Users/cpr/Library/Python/3.7/lib/python/site-packages)
WARNING: Ignoring invalid distribution -umpy (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages)
Installing collected packages: frida
  Running setup.py install for frida ... error
  error: subprocess-exited-with-error

  × Running setup.py install for frida did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      running install
      /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-3.7
      creating build/lib.macosx-10.9-x86_64-3.7/frida
      copying frida/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/frida
      copying frida/core.py -> build/lib.macosx-10.9-x86_64-3.7/frida
      running build_ext
      looking for prebuilt extension in home directory, i.e. /Users/cpr/frida-15.1.17-py3.7-macosx-10.9-x86_64.egg
      prebuilt extension not found in home directory, will try downloading it
      querying pypi for available prebuilds
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/y_/vn4gwqxn4fqg1940p7p_1zgm0000gn/T/pip-install-dr64ca73/frida_b9750e1fd049487c887f06d670aa1e9f/setup.py", line 330, in <module>
          zip_safe=False
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/command/install.py", line 670, in run
          self.run_command('build')
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/y_/vn4gwqxn4fqg1940p7p_1zgm0000gn/T/pip-install-dr64ca73/frida_b9750e1fd049487c887f06d670aa1e9f/setup.py", line 119, in build_extension
          index_url = normalize_url(index_url)
        File "/private/var/folders/y_/vn4gwqxn4fqg1940p7p_1zgm0000gn/T/pip-install-dr64ca73/frida_b9750e1fd049487c887f06d670aa1e9f/setup.py", line 207, in normalize_url
          if not path.endswith("/"):
      TypeError: endswith first arg must be bytes or a tuple of bytes, not str
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> frida

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: Ignoring invalid distribution -rida (/Users/cpr/Library/Python/3.7/lib/python/site-packages)
WARNING: Ignoring invalid distribution - (/Users/cpr/Library/Python/3.7/lib/python/site-packages)
WARNING: Ignoring invalid distribution -umpy (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -rida (/Users/cpr/Library/Python/3.7/lib/python/site-packages)
WARNING: Ignoring invalid distribution - (/Users/cpr/Library/Python/3.7/lib/python/site-packages)
WARNING: Ignoring invalid distribution -umpy (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages)

**Comment by BackTrackCRoot** [comment]
windows same.

**Comment by uniking** [comment]
archlinu, Python 3.10.2， same problem.

**Comment by Azulath** [comment]
I can confirm this issue on macOS Big Sur 11.6.4 with Python 3.9.10.

**Comment by wjbwsb** [comment]
the same problem. 
macOS 11.4. python 3.7

**Comment by BTingTingTingB** [comment]
the same problem
win10 python3.9

**Comment by BTingTingTingB** [comment]
![屏幕截图 2022-03-14 202428](https://user-images.githubusercontent.com/32012918/158171587-6a902c88-dae2-43dd-abec-fba3e7a30fc3.png)
The error is from the code I make the sign, it should be mistake maintainers made, I tried to fix,but there many many many places to need fixed.Em.....

**Comment by ShiKangBao** [comment]
临时解决办法:
https://github.com/frida/frida/issues/2012
https://pypi.tuna.tsinghua.edu.cn/simple/frida/

**Comment by douniwan5788** [comment]
this bug has been introduced from 15.1.5, when setup.py tries to parse index-url. bytes and str start been different since python 3, I think the maintainers are still using python2...

Temporary workaround:

```
pip config unset global.index-url
pip config unset global.extra-index-url
```

**Comment by Azulath** [comment]
> this bug has been introduced from 15.1.5, when setup.py tries to parse index-url. bytes and str start been different since python 3, I think the maintainers are still using python2...
> 
> Temporary workaround:
> 
> ```
> pip config unset global.index-url
> pip config unset global.extra-index-url
> ```

So, this means until the maintainers make the switch to python3 this issue will persist.
Do we know if said switch is on their roadmap?

**Comment by maximebories** [comment]
Same with macOS Monterey 12.3 on Apple Silicon and Python 3.9.12,

Except @douniwan5788 fails :

<img width="1237" alt="Screenshot 2022-04-06 at 22 36 37" src="https://user-images.githubusercontent.com/30550722/162066337-2698b862-9cfe-42b6-af83-68ce54f77bb3.png">

**Comment by b1gcat** [comment]
need help too ...

**Comment by syheliel** [comment]
> > this bug has been introduced from 15.1.5, when setup.py tries to parse index-url. bytes and str start been different since python 3, I think the maintainers are still using python2...
> > Temporary workaround:
> > ```
> > pip config unset global.index-url
> > pip config unset global.extra-index-url
> > ```
> 
> So, this means until the maintainers make the switch to python3 this issue will persist. Do we know if said switch is on their roadmap?

@douniwan5788 Thanks, that solves my problem.

**Comment by ucstone** [comment]
I had a  same problem. Here's how I solved it
1.  open https://pypi.org/project/frida/ and click "download files", choose download tar.gz and egg package For your system and Python version
2.  move egg file to your home directory.  etc: cp ~/Downloads/frida-15.1.17-py3.9-macosx-11.0-arm64.egg ~/frida-15.1.17-py3.9-macosx-11.0-arm64.egg  （The official package is 3.8, but you can manually change the file name to a version number that matches your environment）
3.  unzip tar.gz file，tar zxvf frida-15.1.17.tar.gz
4. cd frida-15.1.17; python3 setup.py install
5. This solves the problem

**Comment by karl-xing** [comment]
1. download frida-15.1.4 from here
[https://pypi.tuna.tsinghua.edu.cn/packages/65/ab/d066fec284ffcbb5d223856953cd5bfb4538b77b3e3219b5014c962a2d3b/frida-15.1.4.tar.gz#sha256=fab41905230cc101519981ea24186b678e4afe24768087fb260b6293a11c96b9](url)
2. python3 setup.py install

**Comment by RoyZhengHuijiang** [comment]
我是这样解决window 上的这种问题：
1.通过楼上的地址下载.egg的文件
1.先把下载好的egg库文件放到python安装目录下：\Lib\site-packages这个文件夹
2.在python\Lib\site-packages这个目录下打开cmd命令窗口
3.输入代码 easy_install 你要安装的egg库文件名，例如我安装的是：easy_install frida-15.1.14-py3.8-win-amd64.egg

**Comment by Azulath** [comment]
I tried it again today and everything seems to work now. I do not know who fixed this issue, but I think it should work for everyone in this thread.
