### ISSUE TITLE
Android Server; n is not a function, unable to perform state transition

### ISSUE THREAD

**Issue by Davincible** [frida/frida#2037]
I get these two error lines:

```json
{
  "type": "error",
  "description": "TypeError: n is not a function",
  "stack": "TypeError: n is not a function\n    at CallbackContext.pt (frida/node_modules/frida-java-bridge/lib/android.js:552:1)\n    at NativeFunction.<anonymous> (<anonymous>)\n    at lt (frida/node_modules/frida-java-bridge/lib/android.js:543:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)\n    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)\n    at frida/node_modules/frida-java-bridge/index.js:212:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at y._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)",
  "fileName": "frida/node_modules/frida-java-bridge/lib/android.js",
  "lineNumber": 552,
  "columnNumber": 1
}
```

```json
{
  "type": "error",
  "description": "Error: Unable to perform state transition; please file a bug",
  "stack": "Error: Unable to perform state transition; please file a bug\n    at lt (frida/node_modules/frida-java-bridge/lib/android.js:543:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)\n    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)\n    at frida/node_modules/frida-java-bridge/index.js:212:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at y._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)\n    at y.perform (frida/node_modules/frida-java-bridge/index.js:192:1)\n    at /internal-agent.js:490:6",
  "fileName": "frida/node_modules/frida-java-bridge/lib/android.js",
  "lineNumber": 543,
  "columnNumber": 1
}
```

Using an android virtual device (android studio toolchain) with android platform31, on linux

**Comment by pecampelo** [comment]
I had the same issue, on API 32, using x86_64 and running frida-server inside an android virtual device.

```
{"type":"error","description":"TypeError: n is not a function","stack":"TypeError: n is not a function\n
at CallbackContext.pt (frida/node_modules/frida-java-bridge/lib/android.js:552:1)\n    at NativeFunction.<an
onymous> (<anonymous>)\n    at lt (frida/node_modules/frida-java-bridge/lib/android.js:543:1)\n    at frida/
node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-jav
a-bridge/lib/class-model.js:7:1)\n    at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:
115:1)\n    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)\n    at frida/node_mod
ules/frida-java-bridge/index.js:212:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1
)\n    at y._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)","fileName":
"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":552,"columnNumber":1}
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error:
 Unable to perform state transition; please file a bug\n    at lt (frida/node_modules/frida-java-bridge/lib/
android.js:543:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.bui
ld (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at I._make (frida/node_modules/frida-j
ava-bridge/lib/class-factory.js:115:1)\n    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory
.js:63:1)\n    at frida/node_modules/frida-java-bridge/index.js:212:1\n    at c.perform (frida/node_modules/
frida-java-bridge/lib/vm.js:12:1)\n    at y._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bri
dge/index.js:211:1)\n    at y.perform (frida/node_modules/frida-java-bridge/index.js:192:1)\n    at /interna
l-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":543,"columnN
umber":1}
```

**Comment by pecampelo** [comment]
David, is your attempt still working on platform 30?

**Comment by DefinitlyEvil** [comment]
Also happens on API 35.

**Comment by mrexodia** [comment]
It is because of https://github.com/frida/frida-java-bridge/issues/309

**Comment by mrexodia** [comment]
You can try this workaround:

```
adb install -r -d com.android.art@331012050.decompressed.apex
```

[com.android.art@331012050.decompressed.apex.zip](https://github.com/user-attachments/files/16782293/com.android.art%40331012050.decompressed.apex.zip)

This will forcefully downgrade `com.android.art`, which should make Frida work again (at least until another silent OTA update happens).

**Comment by Displema** [comment]
> 
> ```
> adb install -r -d com.android.art@331012050.decompressed.apex
> ```

> This will forcefully downgrade `com.android.art`, which should make Frida work again (at least until another silent OTA update happens).

On Android 14 you can no longer downgrade app using the -d flag to the _adb install_ command. I tried also to use CorePatch and Let me Downgrade xposed module but they didn't work (maybe because I am using a fork of LSposed)

**Comment by mrexodia** [comment]
You can still downgrade, but you need to use an APEX package from an older Android 14 version. Additionally you can downgrade by running `pm uninstall com.google.android.art`

**Comment by Displema** [comment]
I'm getting the same error after downgrading through `pm`. Where can I find the apex files for com.google.android.art?

**Comment by XuliGan4eg2006** [comment]
Here is working solution:

```
adb shell
pm uninstall com.google.android.art
```
and reboot your phone!

**Comment by DefinitlyEvil** [comment]
> Here is working solution:
> 
> ```
> adb shell
> pm uninstall com.google.android.art
> ```
> 
> and reboot your phone!

Cool! Thanks for sharing. Gonna try it out later.

**Comment by Displema** [comment]
Another solution that worked for me was just moving the file to another directory: I moved it from `/data/local/tmp` to `/data/adb/` and it worked flawlessly

**Comment by False-Mask** [comment]
> You can try this workaround:
> 
> ```
> adb install -r -d com.android.art@331012050.decompressed.apex
> ```
> 
> [com.android.art@331012050.decompressed.apex.zip](https://github.com/user-attachments/files/16782293/com.android.art%40331012050.decompressed.apex.zip)
> 
> This will forcefully downgrade `com.android.art`, which should make Frida work again (at least until another silent OTA update happens).

@mrexodia hi, is there any way to fallback the google play system update? (keep all my data：)

**Comment by mrexodia** [comment]
You shouldn't be running any rooting or any of these commands on a phone you're not ready to re-flash at a moment's notice to be honest...

**Comment by lllionlll** [comment]
> Another solution that worked for me was just moving the file to another directory: I moved it from `/data/local/tmp` to `/data/adb/` and it worked flawlessly

I've tried it and still got the issue

**Comment by flamecopper** [comment]
1|bluejay:/data/apex/decompressed # pm uninstall com.android.art
Failure [DELETE_FAILED_ABORTED: Failed to uninstall apex com.android.art]

**Comment by flamecopper** [comment]
luejay:/data/adb # Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
