### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ABC'

### ISSUE THREAD

**Issue by JensEk** [frida/frida#2040]
Hi sry Iam pretty new to Frida but have had it up and running until yesterday when I tried install fridump aswell.
Now Iam getting this error message when Iam trying to run following command: frida -U -l -f --no-pause

Traceback (most recent call last):
File "/usr/local/bin/frida", line 8, in
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/frida_tools/repl.py", line 34, in main
from frida_tools import _repl_magic
File "/usr/local/lib/python2.7/dist-packages/frida_tools/_repl_magic.py", line 7, in
class Magic(abc.ABC):
AttributeError: 'module' object has no attribute 'ABC'

Guess it has something to do with python2.7 but uncertain what to do next. If any suggestion pls help :D

Regards
Jeek

**Comment by g2asell2019** [comment]
correct command:

`frida -U -f com.identifier.app -l security.js --no-pause`

with `com.identifier.app` is identifier of app
with `security.js` is script you want to inject

I assume you're talking about iOS:
[https://frida.re/docs/examples/ios/](url)
