### ISSUE TITLE
Android access violation in function overloading.

### ISSUE THREAD

**Issue by mothran** [frida/frida#208]
When running the below script
```javascript
Java.perform(function () {
	var WebView = Java.use("android.webkit.WebView");
	WebView.loadUrl.overload("java.lang.String").implementation = function (s) {
		console.log(s.toString());
		this.loadUrl.overload("java.lang.String").call(this, s);
	};
});
```

I get the following error:
```
Error: access violation accessing 0x9f5d69b0
    at WebView.loadUrl (eval at makeMethod (frida/node_modules/frida-java/lib/class-factory.js:979:7), <anonymous>:1:225)
    at WebView.loadUrl.overload.implementation (repl1.js:5:45)
    at loadUrl (eval at implement (frida/node_modules/frida-java/lib/class-factory.js:1367:5), <anonymous>:1:255)
```

It appears to be due to the overload().call() method.  This happens for any function I try and overload. 

I am using client 8.2.3 and 8.2.2 server, because 8.2.3 segv's on every phone / emulator I try it on.

**Comment by mothran** [comment]
The phone I was working on was 6.0.1.

**Comment by oleavr** [comment]
Please file Java issues in [frida-java](https://github.com/frida/frida-java). Cheers!
