### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jeytin** [frida/frida#2094]
android 6.0
arm64

```json

{
    "type": "error",
    "description": "RangeError: Maximum call stack size exceeded",
    "stack": "RangeError: Maximum call stack size exceeded\n    at Proxy.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:722:1)\n    at frida/node_modules/frida-java-bridge/lib/class-factory.js:627:1\n    at Array.forEach (<anonymous>)\n    at ne (frida/node_modules/frida-java-bridge/lib/class-factory.js:624:1)\n    at CallbackContext.<anonymous> (frida/node_modules/frida-java-bridge/lib/class-factory.js:592:1)\n    at Function.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1058:1)\n    at Proxy.e (frida/node_modules/frida-java-bridge/lib/class-factory.js:580:1)\n    at Function.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:964:1)\n    at Proxy.e (frida/node_modules/frida-java-bridge/lib/class-factory.js:547:1)\n    at Proxy.sendMessageDelayed.implementation (/internal-agent.js:443:31)",
    "fileName": "frida/node_modules/frida-java-bridge/lib/class-factory.js",
    "lineNumber": 722,
    "columnNumber": 1
}

```

help!

**Comment by Ristovski** [comment]
Duplicate of https://github.com/frida/frida/issues/1904

**Comment by mirabilos** [comment]
This seems to be an `arm64`-specific thing: I got a Debian package that builds on `amd64` and `armhf` but fails on `arm64` with the same error message, deep in babeljs…
