### ISSUE TITLE
 n.art::mirror::Object::Clone is not a function (Frida Failed to Start..........)

### ISSUE THREAD

**Issue by alimp5** [frida/frida#2105]
at fist, I would thank you Frida team :X 

Windows 10 - 64 bit (latest build)
python 3.8.10 and 3.9.10 (both 64 bits)
frida packagee - latest version (15.1.x) for android x86.
Memu: 7.6.6 and 8.0.0 and 6.5.1.

I uninstalled the Memu 8.0.0 and test 7.6.6 and didn't work. even i tested the 6.5.1 and i got errors below.
Frida successfully installed on both python 3.8 and 3.9 without problem.

### 1st windows command prompt:
> D:\Program Files\Microvirt\MEmu>adb.exe shell /data/local/tmp/frida-server
>  
> {"type":"error","description":"TypeError: n.art::mirror::Object::Clone is not a function","stack":"TypeError: n.art::mirror::Object::Clone is not a function\n    at rn (frida/node_modules/frida-java-bridge/lib/android.js:1238:1)\n    at $t.replace (frida/node_modules/frida-java-bridge/lib/android.js:1083:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1011:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:926:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at y._performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238:1)\n    at frida/node_modules/frida-java-bridge/index.js:213:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1238,"columnNumber":1}
> 

### 2nd windows command prompt:

> D:\Program Files\Microvirt\MEmu>frida --no-paus -U -l frida-ssl-bypass.js -f com.tronlinkpro.wallet
>  
>     
> Frida 15.1.22 - A world-class dynamic instrumentation toolkit
>    | (_| |
>     > _  |   Commands:
>    /_/ |_|       help      -> Displays the help system
>    . . . .       object?   -> Display information about 'object'
>    . . . .       exit/quit -> Exit
>    . . . .
>    . . . .   More info at https://frida.re/docs/home/
>    . . . .
>    . . . .   Connected to SM-G935F (id=192.168.100.99:5555)
> Spawned `com.tronlinkpro.wallet`. Resuming main thread!
> TypeError: not a function
>     at rn (frida/node_modules/frida-java-bridge/lib/android.js:1238)
>     at replace (frida/node_modules/frida-java-bridge/lib/android.js:1083)
>     at set (frida/node_modules/frida-java-bridge/lib/class-factory.js:1011)
>     at set (frida/node_modules/frida-java-bridge/lib/class-factory.js:926)
>     at <anonymous> (frida/node_modules/frida-java-bridge/index.js:212)
>     at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
>     at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:232)
>     at perform (frida/node_modules/frida-java-bridge/index.js:192)
>     at <anonymous> (/frida-ssl-bypass.js:728)
>     at apply (native)
>     at <anonymous> (frida/runtime/core.js:51)
> [SM-G935F::com.tronlinkpro.wallet ]-> Connection terminated
> [SM-G935F::com.tronlinkpro.wallet ]->
> 
> Thank you for using Frida!

**Comment by wxx6** [comment]
I have the same problem with your 1st
