### ISSUE TITLE
Frida Install problem , please help

### ISSUE THREAD

**Issue by LOVEChen** [frida/frida#2116]
install commmand 
pip install frida

and frida -version

```
***
Failed to load the Frida native extension: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_frida.cpython-39-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_frida.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "/usr/local/bin/frida", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/frida_tools/repl.py", line 24, in main
    import frida
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/frida/__init__.py", line 24, in <module>
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/frida/__init__.py", line 7, in <module>
    import _frida
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_frida.cpython-39-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_frida.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

**Comment by wengxianxun** [comment]
怎么解决

**Comment by qzhuorui** [comment]
请问下，有解决方法吗
