### ISSUE TITLE
Error: Unable to determine ClassLinker field offsets

### ISSUE THREAD

**Issue by gopalsamyrajendran** [frida/frida#2138]
When I run Frida arm64 version it's showing me the following error. I'm using pixel OS Android 12.  Please help me to solve this issue, anyone. Thanks 

/data/local/tmp # {"type":"error","description":"Error: Unable to determine ClassLinker field offsets","stack":"Error: Unable to determine ClassLinker field offsets\n    at Ue (frida/node_modules/frida-java-bridge/lib/android.js:378:1)\n    at frida/node_modules/frida-java-bridge/lib/memoize.js:4:1\n    at Me (frida/node_modules/frida-java-bridge/lib/android.js:186:1)\n    at xe (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n    at g._tryInitialize (frida/node_modules/frida-java-bridge/index.js:17:1)\n    at new g (frida/node_modules/frida-java-bridge/index.js:9:1)\n    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:317:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at frida/node_modules/browser-pack/_prelude.js:1:1\n    at Object.20.frida-java-bridge (frida/runtime/java.js:1:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":378,"columnNumber":1}

**Comment by gopalsamyrajendran** [comment]
<img width="853" alt="issue" src="https://user-images.githubusercontent.com/53430049/173196244-e14b219c-506f-486f-bc13-000c3ea47bf7.PNG">

**Comment by gopalsamyrajendran** [comment]
**Solution**: this is an OS-related issue. to solve this you need to either update the os, Downgrade it or change the ROM completely to another version. That helped me to fix it. Thanks to Bob from the Frida community (Telegram)
