### ISSUE TITLE
Installing 9.0.11 via pip - network query failed

### ISSUE THREAD

**Issue by strano666** [frida/frida#216]
I've tried to update/install to 9.0.11 via pip, but the installation fails.

I've highlighted the line interesting for me: there is a try to search the prebuilt extension in the home directory because of a `network query failed`.

The error persists both on macOS (fresh installation of Frida) and Arch Linux (update)
This output is for macOS case.
```
$ sudo pip install frida
Collecting frida
  Downloading frida-9.0.11.tar.gz
Collecting colorama>=0.2.7 (from frida)
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Collecting prompt-toolkit>=0.57 (from frida)
  Downloading prompt_toolkit-1.0.9-py2-none-any.whl (241kB)
    100% |████████████████████████████████| 245kB 1.6MB/s 
Collecting pygments>=2.0.2 (from frida)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 932kB/s 
Collecting six>=1.9.0 (from prompt-toolkit>=0.57->frida)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit>=0.57->frida)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Installing collected packages: colorama, six, wcwidth, prompt-toolkit, pygments, frida
  Running setup.py install for frida ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-FLNlq9/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xP8QeD-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-intel-2.7
    creating build/lib.macosx-10.12-intel-2.7/frida
    copying frida/__init__.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/application.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/core.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/discoverer.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/lsd.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/ps.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/repl.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/tracer.py -> build/lib.macosx-10.12-intel-2.7/frida
    running build_ext
    querying pypi for available prebuilds
    **network query failed**
    looking for prebuilt extension in home directory, i.e. /Users/alfonso***/frida-9.0.11-py2.7-macosx-10.11-intel.egg
    no prebuilt extension found in home directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-FLNlq9/frida/setup.py", line 182, in <module>
        'build_ext': FridaPrebuiltExt
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/build_ext.py", line 49, in run
        _build_ext.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
        self.build_extension(ext)
      File "/private/tmp/pip-build-FLNlq9/frida/setup.py", line 122, in build_extension
        raise network_error
    Exception: Could not find prebuilt Frida extension. Prebuilds only provided for python 2.6-2.7 and 3.x.
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-FLNlq9/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xP8QeD-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-FLNlq9/frida/
```

**Comment by oleavr** [comment]
Please try again now, `9.0.13` should be a complete release (were going through some hiccups during a release a few hours ago).
