### ISSUE TITLE
linux-arm64 Frida Server - Failed to spawn: unable to handle 32-bit processes due to build configuration

### ISSUE THREAD

**Issue by gskip17** [frida/frida#2172]
**Frida server "fails to spawn 32-bit processes" on arm64, however frida may attach to the process normally if the process is already running.** Once attached, frida-server behaves normally and the entire api works fine. 

Target platform is - 
`Linux (none) 5.4.0 #1 SMP PREEMPT Thu Jul 22 16:09:27 UTC 2021 aarch64 GNU/Linux`

armv8 64-bit processor. 

I am using a manually compiled arm64 frida-server from the repo. I disabled all unnecessary features for my target.

```
FRIDA_V8 ?= disabled
FRIDA_CONNECTIVITY ?= disabled
FRIDA_DATABASE ?= disabled
FRIDA_JAVA_BRIDGE ?= disabled
FRIDA_OBJC_BRIDGE ?= disabled
FRIDA_SWIFT_BRIDGE ?= disabled
```

This is the feedback I get when attempting to spawn the process. `frida-trace` gives the exact same error.

```
Traceback (most recent call last):
  File "/home/____/frida/hook.py", line 31, in <module>
    device.spawn(["/usr/bin/the_process -L"])
  File "/usr/lib/python3/dist-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/frida/core.py", line 149, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: unable to handle 32-bit processes due to build configuration
```

I have seen other issues posted with a similar error but for spawning 64-bit processes - [where the problem was using the wrong frida-server](https://github.com/frida/frida/issues/999). 

I am unsure that what I am experiencing is the same issue, because I can spawn other processes just fine with this arm64 frida-server, and _I can attach to the specific process in question if it is already running_. The process I am spawning has no anti-debug/instrumentation features that would prevent frida from spawning the proc. aarch64 instructions are 32-bits wide, but the process itself is definitely 64-bit.

At first I thought maybe frida-server did not like something in the elf header or something, but the header seems like what one would expect (64-bit). 

```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Position-Independent Executable file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x8344
  Start of program headers:          64 (bytes into file)
  Start of section headers:          170344 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         27
  Section header string table index: 26
```

Is there a specific build configuration for frida-server that would fix this? Any ideas what the problem might be?

Thank you for your time!

**Comment by gskip17** [comment]
I think I have narrowed it down to where frida is complaining.

in `frida-core/blob/main/src/linux/frida-helper-process.vala` the following functions are called - 
```
		private static Gum.CpuType cpu_type_from_file (string path) throws Error {
			try {
				return Gum.Linux.cpu_type_from_file (path);
			} catch (GLib.Error e) {
				if (e is IOError.NOT_FOUND)
					throw new Error.EXECUTABLE_NOT_FOUND ("Unable to find executable at '%s'".printf (path));
				else if (e is IOError.NOT_SUPPORTED)
					throw new Error.EXECUTABLE_NOT_SUPPORTED ("Unable to spawn executable at '%s': unsupported file format".printf (path));
				else
					throw new Error.PERMISSION_DENIED ("%s", e.message);
			}
		}
```

Which then calls this function in `frida-gum/blob/main/gum/backend-linux/gumprocess-linux.c`

```
GumCpuType
gum_linux_cpu_type_from_file (const gchar * path,
                              GError ** error)
{
  GumCpuType result = -1;
  FILE * file;
  guint8 ei_data;
  guint16 e_machine;

  file = fopen (path, "rb");
  if (file == NULL)
    goto beach;

  if (fseek (file, EI_DATA, SEEK_SET) != 0)
    goto beach;
  if (fread (&ei_data, sizeof (ei_data), 1, file) != 1)
    goto beach;

  if (fseek (file, 0x12, SEEK_SET) != 0)
    goto beach;
  if (fread (&e_machine, sizeof (e_machine), 1, file) != 1)
    goto beach;

  if (ei_data == ELFDATA2LSB)
    e_machine = GUINT16_FROM_LE (e_machine);
  else if (ei_data == ELFDATA2MSB)
    e_machine = GUINT16_FROM_BE (e_machine);
  else
    goto unsupported_ei_data;

  switch (e_machine)
  {
    case 0x0003:
      result = GUM_CPU_IA32;
      break;
    case 0x003e:
      result = GUM_CPU_AMD64;
      break;
    case 0x0028:
      result = GUM_CPU_ARM;
      break;
    case 0x00b7:
      result = GUM_CPU_ARM64;
      break;
    case 0x0008:
      result = GUM_CPU_MIPS;
      break;
    default:
      goto unsupported_executable;
  }

  goto beach;

unsupported_ei_data:
  {
    g_set_error (error, GUM_ERROR, GUM_ERROR_NOT_SUPPORTED,
        "Unsupported ELF EI_DATA");
    goto beach;
  }
unsupported_executable:
  {
    g_set_error (error, GUM_ERROR, GUM_ERROR_NOT_SUPPORTED,
        "Unsupported executable");
    goto beach;
  }
beach:
  {
    if (file != NULL)
      fclose (file);

    return result;
  }
}

```

And for some strange reason it is returning `GUM_CPU_ARM` in the case statement. Causing the eventual call resume to call  `obtain_for32_bit` being called, instead of `obtain_for_64bit`, which is where the exception occurs.

```
		private async LinuxHelper obtain_for_32bit (Cancellable? cancellable) throws Error, IOError {
			if (factory32 == null) {
				var store = get_resource_store ();
				if (sizeof (void *) != 4 && store.helper32 == null)
					throw new Error.NOT_SUPPORTED ("Unable to handle 32-bit processes due to build configuration");
				factory32 = new HelperFactory (store.helper32, store, main_context);
				factory32.lost.connect (on_factory_lost);
				factory32.output.connect (on_factory_output);
				factory32.uninjected.connect (on_factory_uninjected);
			}

			return yield factory32.obtain (cancellable);
		}
```

Now I am trying to figure out why `gum_linux_cpu_type_from_file` is returning the wrong architecture.

Maybe this is a freak issue with the specific binary I am trying to spawn.

**Comment by sashakiwi** [comment]
Isn't this wrong?
                public async void resume (uint pid, Cancellable? cancellable) throws Error, IOError {
                        var cpu_type = cpu_type_from_pid (pid);
                        var helper = yield obtain_for_cpu_type (cpu_type, cancellable);
                        try {
                                yield helper.resume (pid, cancellable);
                        } catch (Error e) {
                                if (!(e is Error.INVALID_ARGUMENT))
                                        throw e;
                                _**if (cpu_type == Gum.CpuType.AMD64 || cpu_type == Gum.CpuType.ARM64)_
                                        helper = yield obtain_for_32bit (cancellable);**
                                else
                                        helper = yield obtain_for_64bit (cancellable);
                                yield helper.resume (pid, cancellable);
                        }
                }
