### ISSUE TITLE
Frida-Server not running on Android 12 YAAP Rom

### ISSUE THREAD

**Issue by OsamaMahmood** [frida/frida#2194]
I have YAAP Android 12 rom installed on my Oneplus Pro and have installed frida-server (https://github.com/frida/frida/releases/download/15.2.2/frida-server-15.2.2-android-arm64.xz) but i am unable to get it working when i try to run Frida0server i get the following error:
```
OnePlus7ProNR:/ # frida-server
{"type":"error","description":"Error: Unable to determine Runtime.jni_ids_indirection_ offset","stack":"Error: Unable to determine Runtime.jni_ids_indirection_ offset\n    at He (frida/node_modules/frida-java-bridge/lib/android.js:330:1)\n    at Ze (frida/node_modules/frida-java-bridge/lib/android.js:275:1)\n    at frida/node_modules/frida-java-bridge/lib/memoize.js:4:1\n    at ze (frida/node_modules/frida-java-bridge/lib/android.js:190:1)\n    at Oe (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:29:1)\n    at new _ (frida/node_modules/frida-java-bridge/index.js:21:1)\n    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:332:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at frida/node_modules/browser-pack/_prelude.js:1:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":330,"columnNumber":1}
```
On my laptop:

```
❯ frida-ps -U                                                                                                                                      ─╯
Failed to enumerate processes: cannot read property 'getRunningAppProcesses' of undefined

```

**Comment by salman0ansari** [comment]
same problem
