### ISSUE TITLE
Java API only partially available; please file a bug. Missing: _ZN3art15instrumentation15Instrumentation20EnableDeoptimizationEv

### ISSUE THREAD

**Issue by EasTomfLA** [frida/frida#2201]
hello,i use frida with android12 and pixel 4, and got this error msg,any body could help,plese

{"type":"error","description":"Error: Java API only partially available; please file a bug. Missing: _ZN3art15instrumentation15Instrumentation20EnableDeoptimizationEv","stack":"Error: Java API only partially available; please file a bug. Missing: _ZN3art15instrumentation15Instrumentation20EnableDeoptimizationEv\n    at Ae (frida/node_modules/frida-java-bridge/lib/android.js:178:1)\n    at ye (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n    at y._tryInitialize (frida/node_modules/frida-java-bridge/index.js:17:1)\n    at new y (frida/node_modules/frida-java-bridge/index.js:9:1)\n    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:320:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at frida/node_modules/browser-pack/_prelude.js:1:1\n    at Object.20.frida-java-bridge (frida/runtime/java.js:1:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at r (frida/node_modules/browser-pack/_prelude.js:1:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":178,"columnNumber":1}

**Comment by EasTomfLA** [comment]
> hello,i use frida with android12 and pixel 4, and got this error msg,any body could help,plese
> 
> {"type":"error","description":"Error: Java API only partially available; please file a bug. Missing: _ZN3art15instrumentation15Instrumentation20EnableDeoptimizationEv","stack":"Error: Java API only partially available; please file a bug. Missing: _ZN3art15instrumentation15Instrumentation20EnableDeoptimizationEv\n at Ae (frida/node_modules/frida-java-bridge/lib/android.js:178:1)\n at ye (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n at y._tryInitialize (frida/node_modules/frida-java-bridge/index.js:17:1)\n at new y (frida/node_modules/frida-java-bridge/index.js:9:1)\n at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:320:1)\n at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n at frida/node_modules/browser-pack/_prelude.js:1:1\n at Object.20.frida-java-bridge (frida/runtime/java.js:1:1)\n at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n at r (frida/node_modules/browser-pack/_prelude.js:1:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":178,"columnNumber":1}

frida version use
15117 15122  1522 1520

**Comment by rushkii** [comment]
I have the same issue, anyone know what's the problem?
