### ISSUE TITLE
Unable to run Frida on windows

### ISSUE THREAD

**Issue by AshishDora** [frida/frida#2202]
Traceback (most recent call last):
  File "C:\Python27\Scripts\frida-script.py", line 11, in <module>
    load_entry_point('frida-tools==11.0.0', 'console_scripts', 'frida')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\frida_tools\repl.py", line 402
    def _exec_and_print(self, exec, arg):
                                 ^
SyntaxError: invalid syntax

**Comment by aklee** [comment]
same question

**Comment by aklee** [comment]
same on macos

➜  ~ frida --help
Traceback (most recent call last):
  File "/Users/ak/Library/Python/2.7/bin/frida", line 5, in <module>
    from frida_tools.repl import main
  File "/Users/ak/Library/Python/2.7/lib/python/site-packages/frida_tools/repl.py", line 402
    def _exec_and_print(self, exec, arg)

**Comment by 01-x-x-10** [comment]
Linux:

Traceback (most recent call last):
  File "/home/dbg/.local/bin/frida", line 5, in <module>
    from frida_tools.repl import main
  File "/home/dbg/.local/lib/python2.7/site-packages/frida_tools/repl.py", line 402
    def _exec_and_print(self, exec, arg):
                                 ^
SyntaxError: invalid syntax
