### ISSUE TITLE
Android frida server run error

### ISSUE THREAD

**Issue by Simp1erByteDance** [frida/frida#2203]
when I run frida server on Android 11, which version name is RQ3A.210605.005 and model is Pixel 3a,it's result is. always show as follows,Frida server's version is 15.2.2.
```
"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:203:1)\n    at dn (frida/node_modules/frida-java-bridge/lib/android.js:1196:1)\n    at un.activate (frida/node_modules/frida-java-bridge/lib/android.js:1262:1)\n    at _n.replace (frida/node_modules/frida-java-bridge/lib/android.js:1310:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1017:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:932:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":203,"columnNumber":1}
```

**Comment by sysloser** [comment]
Try
`adb shell setenforce 0`
