### ISSUE TITLE
In frida when I try to unpining any apps then shows error 

### ISSUE THREAD

**Issue by joyahamad074** [frida/frida#2262]
Hi,
I have face some issue in frida. I have install all successfully as well as install frida-tools using pip install.

And the command `frida-ps -U` also working fine and show all the applications as well.
now the problem is when I try to unpining bypass any app by using this command `frida -U 6157 --no-pause -l ./frida-script.js` 

it shows me some error which is: 

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\frida-script.py", line 11, in <module>
    load_entry_point('frida-tools==11.0.0', 'console_scripts', 'frida')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\frida_tools\repl.py", line 402
    def _exec_and_print(self, exec, arg):
                                 ^
SyntaxError: invalid syntax
```

So how can I fix it

**Comment by raoshaab** [comment]
Try with below command
( it will show running apps ) 
```
frida-ps -Ua 
```
Copy the app name
run this
``` 
frida -U -f com.app.name -l frida-script.js --no-pause
```

**Comment by jacopotediosi** [comment]
@joyahamad074 why do you use python2. We are in 2022. Frida is for python3.
