### ISSUE TITLE
run frida-server-16.0.1-android-arm64 failed

### ISSUE THREAD

**Issue by rongwwei** [frida/frida#2276]
After setenforce 0
I still get this error

frida-16.0.1

android_arm64

Error: invalid address
    at Object.value [as patchCode] (frida/runtime/core.js:203:1)
    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)
    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)
    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)
    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1017:1)
    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:932:1)
    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)
    at init (/internal-agent.js:51:3)
    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)
    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js

**Comment by loody** [comment]
+1

**Comment by loody** [comment]
+1

**Comment by eebssk1** [comment]
Even worse. I'm getting segementation fault

**Comment by a-gamer** [comment]
+1

**Comment by danielniccoli** [comment]
Same error here with a Google Pixel 3 and Android 12. Frida Server 16.0.8
`setenforce 0` doesn't change this.

```json
{
   "type":"error",
   "description":"Error: invalid address",
   "stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:203:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1016:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:931:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)",
   "fileName":"frida/runtime/core.js",
   "lineNumber":203,
   "columnNumber":1
}
```

**Comment by ay-kay** [comment]
I am receiving the same error on a Pixel 3a running Android 12 and Frida 16.0.11. 

```
# /data/local/tmp/frida-server &
[1] 12707
sargo:/ # {"type":"error","description":"Error: invalid address","stack":"Error: invalid address
    at Object.value [as patchCode] (frida/runtime/core.js:203:1)
    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)
    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)
    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)
    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1016:1)
    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:931:1)
    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)
    at init (/internal-agent.js:51:3)
    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)
    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":203,"columnNumber":1}
```

Has anyone been able to narrow down the error or has a workaround available?

**Comment by ChoudharyImran** [comment]
OnePlus5T:/ # /data/local/tmp/frida-server &
[1] 17944
OnePlus5T:/ # {"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:203:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1185:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1099:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":203,"columnNumber":1}

Has anyone helped me

**Comment by nulldot0** [comment]
Same with here
OnePlus8T:/data/local/tmp # ./frida-server                                     
{"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:203:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1185:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1099:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":203,"columnNumber":1}
