### ISSUE TITLE
Launch frida-server-16.0.1-arm64 on rooted Google Pixel 6 Pro error

### ISSUE THREAD

**Issue by Aspen-TWN** [frida/frida#2299]
```sh
adb shell "su -c \"/data/local/tmp/frida_srv.elf\""
```
```json
{"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:203:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1017:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:932:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":203,"columnNumber":1}
```

```sh
adb shell getprop
```
Part of system properties:
```text
[ro.system.build.date]: [Fri Oct  8 09:11:33 UTC 2021]
[ro.system.build.date.utc]: [1633684293]
[ro.system.build.tags]: [release-keys]
[ro.system.build.type]: [user]
[ro.system.build.version.incremental]: [7805805]
[ro.system.build.version.release]: [12]
[ro.system.build.version.release_or_codename]: [12]
[ro.system.build.version.sdk]: [31]
[ro.system.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.system.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.system.product.cpu.abilist64]: [arm64-v8a]
[ro.system_ext.build.date]: [Fri Oct  8 09:11:33 UTC 2021]
[ro.system_ext.build.date.utc]: [1633684293]
[ro.system_ext.build.tags]: [release-keys]
[ro.system_ext.build.type]: [user]
[ro.system_ext.build.version.incremental]: [7805805]
[ro.system_ext.build.version.release]: [12]
[ro.system_ext.build.version.release_or_codename]: [12]
[ro.system_ext.build.version.sdk]: [31] 
```

**Comment by MartinKayJr** [comment]
```
adb shell
setenforce 0
```
close SELinux

**Comment by danielniccoli** [comment]
Same error here with a Google Pixel 3 and Android 12. Frida Server 16.0.8

**Comment by danielniccoli** [comment]
Same as #2276 ?
