### ISSUE TITLE
Regression in 15.1.28: FAILED: agents/fs/fs_agent.js

### ISSUE THREAD

**Issue by CyrilBrulebois** [frida/frida#2303]
For the [PTS project](https://pts-project.org/), I maintain a `frida` package bundling `python-linux` and `tools-linux`.

Trying to refresh the initial packaging (15.1.17), I first moved to 15.1.28 which no longer builds:

```
[1/2] Generating agents/fs/fs-agent.js with a custom command
FAILED: agents/fs/fs_agent.js 
/home/kibi/work/clients/pirogue/deb-frida/frida-tools/agents/build.py ../../../frida-tools/agents/fs/agent.ts ../../../frida-tools/agents/fs/package.json ../../../frida-tools/agents/fs/package-lock.json ../../../frida-tools/agents/fs/tsconfig.json agents/fs/fs_agent.js agents/fs/fs_agent.js.p
file:///home/kibi/work/clients/pirogue/deb-frida/build/tmp_thin-linux-x86_64/frida-tools-python3.9/agents/fs/fs_agent.js.p/node_modules/frida-compile/dist/compiler.js:219
                        const pkgMain = pkgMeta.main ?? "index.js";
                                                      ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
Command '[PosixPath('node_modules/.bin/frida-compile'), PosixPath('agent.ts'), '-c', '-o', PosixPath('/home/kibi/work/clients/pirogue/deb-frida/build/tmp_thin-linux-x86_64/frida-tools-python3.9/agents/fs/fs_agent.js')]' returned non-zero exit status 1.
[2/2] Generating agents/tracer/tracer-agent.js with a custom command
ninja: build stopped: subcommand failed.
Could not rebuild /home/kibi/work/clients/pirogue/deb-frida/build/tmp_thin-linux-x86_64/frida-tools-python3.9
make[3]: *** [Makefile.linux.mk:422: build/tmp_thin-linux-x86_64/frida-tools-python3.9/.frida-stamp] Error 1
```

The build environment is as follows:
- Debian 11
- amd64, native build
- GCC 10.2.1
- Python 3.9

It seems to me that something regressed in `frida-compile` which is bundled in tool/SDK tarballs that are downloaded during the build.

Trying to pinpoint what happened, I can confirm that all versions between 15.1.17 and 15.1.27 (inclusive) do build fine, and that 15.1.28 is the first version that shows that regression. Digging further, the last known good commit is b8a2a24296877b7e0b290c09504aa37fa8f9ea5a, the first bad one is 19ac731c04acce794680edf6e02714ee0134212c.

Of course, the plan is to catch up with more recent releases, and upgrading to the last 15.1.x release was a first step that I assumed would be easy. Building 16.0.2 results in a different error, which I'll file in a moment.

**Comment by CyrilBrulebois** [comment]
I'm seeing similar issues with 15.2.0:

```
file:///home/kibi/work/clients/pirogue/deb-frida/build/tmp_thin-linux-x86_64/frida-core/src/compiler/node_modules/frida-compile/dist/system/node.js:49
    const realpathSync = _fs.realpathSync.native ?? _fs.realpathSync;
                                                  ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR! code 1

```

or with 15.2.2:

```
file:///home/kibi/work/clients/pirogue/deb-frida/build/tmp_thin-linux-x86_64/frida-core/src/compiler/node_modules/frida-compile/dist/compiler.js:230
    const opts = ts.getParsedCommandLineOfConfigFile(crosspath.join(projectRoot, "tsconfig.json"), defaultTsOptions, configFileHost)?.options ?? defaultTsOptions;
                                                                                                                                     ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
```
