### ISSUE TITLE
Package Frida and Frida-Tools NOT WORKING

### ISSUE THREAD

**Issue by AkariOficial** [frida/frida#2308]
Hello, I have frida-magisk(ROOT)
but when I try to install the frida and Frida-Tools dependencies(Python/Node) both give errors.

I'm using **Python 3.11** currently, I believe it's incompatibility with the new python version, but I don't know what to do as I can't roll back the python version in Termux.

### MESSAGE ERROR:
```bash
~ $ pip install frida frida-tools
Collecting frida
  Using cached frida-16.0.2.tar.gz (38 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting frida-tools
  Using cached frida_tools-12.0.1-py3-none-any.whl
Requirement already satisfied: setuptools in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from frida) (65.5.0)
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from frida-tools) (0.4.6)
Requirement already satisfied: prompt-toolkit<4.0.0,>=2.0.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from frida-tools) (3.0.32)
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from frida-tools) (2.13.0)
Requirement already satisfied: wcwidth in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from prompt-toolkit<4.0.0,>=2.0.0->frida-tools) (0.2.5)
Building wheels for collected packages: frida
  Building wheel for frida (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for frida (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/frida
      copying frida/__init__.py -> build/lib.linux-aarch64-cpython-311/frida
      copying frida/core.py -> build/lib.linux-aarch64-cpython-311/frida
      copying frida/py.typed -> build/lib.linux-aarch64-cpython-311/frida
      creating build/lib.linux-aarch64-cpython-311/_frida
      copying _frida/py.typed -> build/lib.linux-aarch64-cpython-311/_frida
      copying _frida/__init__.pyi -> build/lib.linux-aarch64-cpython-311/_frida
      running build_ext
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 412, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 484, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 102, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 324, in run
          self.run_command("build")
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-fx0s4te6/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 34, in build_extension
      RuntimeError: Need frida-core devkit to build from source.
      Download one from https://github.com/frida/frida/releases, extract it to a directory,
      and then add an environment variable named FRIDA_CORE_DEVKIT pointing at the directory.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for frida
Failed to build frida
ERROR: Could not build wheels for frida, which is required to install pyproject.toml-based projects
```
####
### Any solution? 
> I already tried to put another version like (3.9.7) but it gives SSL error in pip

**Comment by NamasteAbhi** [comment]
Same Issue With Me How Can I Fix It any Solution

**Comment by AkariOficial** [comment]
@NamasteAbhi 
I installed python 3.8.10 and it is working now, look in my repository https://github.com/AkariOficial/termux-packages 
ps: I compiled just for aarch64. assuming you get the same error then your device is aarch64

**Comment by kyzsuukii** [comment]
Download frida-devkit 

https://github.com/frida/frida/releases/download/16.0.2/frida-core-devkit-16.0.2-android-arm.tar.xz

https://github.com/frida/frida/releases/download/16.0.2/frida-core-devkit-16.0.2-android-arm64.tar.xz

and extract it to directory what u want (ex: $TMPDIR)

then `export FRIDA_CORE_DEVKIT=/path/to/devkit/`

now u can install frida without any issue
`pip install frida frida-tools`

**Comment by kyzsuukii** [comment]
![Screenshot_2022-11-17-23-22-46-073_com.termux.jpg](https://user-images.githubusercontent.com/110718021/202486582-fadc001e-676f-4b5d-b484-12c7b27c2f38.jpg)

**Comment by a-gamer** [comment]
> ![Screenshot_2022-11-17-23-22-46-073_com.termux.jpg](https://user-images.githubusercontent.com/110718021/202486582-fadc001e-676f-4b5d-b484-12c7b27c2f38.jpg)

I'm  aarch64

**Comment by AkariOficial** [comment]
> Download frida-devkit
> 
> https://github.com/frida/frida/releases/download/16.0.2/frida-core-devkit-16.0.2-android-arm.tar.xz
> 
> https://github.com/frida/frida/releases/download/16.0.2/frida-core-devkit-16.0.2-android-arm64.tar.xz
> 
> and extract it to directory what u want (ex: $TMPDIR)
> 
> then `export FRIDA_CORE_DEVKIT=/path/to/devkit/`
> 
> now u can install frida without any issue `pip install frida frida-tools`

@kyzsuukii thx for posting another solution (more efficient)

**Comment by kyzsuukii** [comment]
> > ![Screenshot_2022-11-17-23-22-46-073_com.termux.jpg](https://user-images.githubusercontent.com/110718021/202486582-fadc001e-676f-4b5d-b484-12c7b27c2f38.jpg)
> 
> I'm  aarch64
> 

same solution just use frida-devkit arm64

**Comment by snooppr** [comment]
> > > ![Screenshot_2022-11-17-23-22-46-073_com.termux.jpg](https://user-images.githubusercontent.com/110718021/202486582-fadc001e-676f-4b5d-b484-12c7b27c2f38.jpg)
> > 
> > 
> > I'm  aarch64
> 
> same solution just use frida-devkit arm64

Sorry to be off topic, can you tell me how you changed the background to an image?

**Comment by kyzsuukii** [comment]
> > > > ![Screenshot_2022-11-17-23-22-46-073_com.termux.jpg](https://user-images.githubusercontent.com/110718021/202486582-fadc001e-676f-4b5d-b484-12c7b27c2f38.jpg)
> > > 
> > > 
> > > I'm  aarch64
> > 
> > same solution just use frida-devkit arm64
> 
> Sorry to be off topic, can you tell me how you changed the background to an image?

https://github.com/termux/termux-app/actions/runs/3409602990

**Comment by Qvd66** [comment]
> @NamasteAbhi I installed python 3.10.8 and it is working now, look in my repository https://github.com/AkariOficial/termux-packages ps: I compiled just for aarch64. assuming you get the same error then your device is aarch64
> 
> and also the frida-tools that works in that version of python is `pip install frida-tools==10.8.0`

 i installed python 3.10.8 and installed frida-tools 10.8.0 however how do i do the same for my android emulator which is x86_64 and i can't install python 3.10.8 for x86?

**Comment by whyakari** [comment]
> > @NamasteAbhi I installed python 3.10.8 and it is working now, look in my repository https://github.com/AkariOficial/termux-packages ps: I compiled just for aarch64. assuming you get the same error then your device is aarch64
> > and also the frida-tools that works in that version of python is `pip install frida-tools==10.8.0`
> 
> i installed python 3.10.8 and installed frida-tools 10.8.0 however how do i do the same for my android emulator which is x86_64 and i can't install python 3.10.8 for x86?

You must compile Python 3.10.8 for your architecture.

**Comment by Qvd66** [comment]
> > > @NamasteAbhi I installed python 3.10.8 and it is working now, look in my repository https://github.com/AkariOficial/termux-packages ps: I compiled just for aarch64. assuming you get the same error then your device is aarch64
> > > and also the frida-tools that works in that version of python is `pip install frida-tools==10.8.0`
> > 
> > 
> > i installed python 3.10.8 and installed frida-tools 10.8.0 however how do i do the same for my android emulator which is x86_64 and i can't install python 3.10.8 for x86?
> 
> You must compile Python 3.10.8 for your architecture.

 By compile u mean turning Python-3.10.8.rpm files to deb Using alien and then installed it by dpkg? however there is some error in compilation. How do i fix this?

**Comment by Chandi371** [comment]
> Download frida-devkit
> 
> https://github.com/frida/frida/releases/download/16.0.2/frida-core-devkit-16.0.2-android-arm.tar.xz
> 
> https://github.com/frida/frida/releases/download/16.0.2/frida-core-devkit-16.0.2-android-arm64.tar.xz
> 
> and extract it to directory what u want (ex: $TMPDIR)
> 
> then `export FRIDA_CORE_DEVKIT=/path/to/devkit/`
> 
> now u can install frida without any issue `pip install frida frida-tools`

After this also I get that error
$ export FRIDA_CORE_DEVKIT=storage/0/emulated/download
~ $ pip install frida frida-tools
Collecting frida
  Using cached frida-16.6.6.tar.gz (920 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting frida-tools
  Using cached frida_tools-13.6.1-py3-none-any.whl
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from frida-tools) (0.4.6)
Requirement already satisfied: prompt-toolkit<4.0.0,>=2.0.0 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from frida-tools) (3.0.50)
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from frida-tools) (2.0.2)
Collecting websockets<14.0.0,>=13.0.0 (from frida-tools)
  Using cached websockets-13.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: wcwidth in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from prompt-toolkit<4.0.0,>=2.0.0->frida-tools) (0.2.13)
Using cached websockets-13.1-py3-none-any.whl (152 kB)
Building wheels for collected packages: frida
  Building wheel for frida (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for frida (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-armv8l-cpython-312/frida
      copying frida/__init__.py -> build/lib.linux-armv8l-cpython-312/frida
      copying frida/core.py -> build/lib.linux-armv8l-cpython-312/frida
      copying frida/py.typed -> build/lib.linux-armv8l-cpython-312/frida
      creating build/lib.linux-armv8l-cpython-312/frida/_frida
      copying frida/_frida/__init__.pyi -> build/lib.linux-armv8l-cpython-312/frida/_frida
      copying frida/_frida/py.typed -> build/lib.linux-armv8l-cpython-312/frida/_frida
      running build_ext
      Downloading toolchain 20250114...
      Unable to download toolchain: missing bundle at https://build.frida.re/deps/20250114/toolchain-linux-armv8l.tar.xz

      Specify --without-prebuilds=toolchain to only use tools on your PATH.

      Another option is to do what Frida's CI does:

          ./releng/deps.py build --bundle=toolchain

      This produces a tarball in ./deps which gets picked up if you retry `./configure`.
      You may also want to make a backup of it for future reuse.
      make: *** [Makefile:4: all] Error 1
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 130, in <module>
        File "<string>", line 18, in main
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 186, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 983, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 379, in run
          self.run_command("build")
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 136, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 365, in run
          self.build_extensions()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 481, in build_extensions
          self._build_extensions_serial()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-avaxfjwy/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 507, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 120, in build_extension
        File "/data/data/com.termux/files/usr/lib/python3.12/subprocess.py", line 573, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for frida
Failed to build frida
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (frida)
~ $
