### ISSUE TITLE
issue with frida can't start

### ISSUE THREAD

**Issue by a-gamer** [frida/frida#2372]
when try to run frida get error 

python3.11

frida16.0.8
when try to run any frida commands get this error

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/frida", line 5, in <module>
    from frida_tools.repl import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/frida_tools/repl.py", line 27, in <module>
    from pygments.lexers.javascript import JavascriptLexer
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pygments/__init__.py", line 37, in <module>
    from pygments.util import StringIO, BytesIO
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pygments/util.py", line 27, in <module>
    tag_re = re.compile(r'<(.+?)(\s.*?)?>.*?</.+?>(?uism)')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 24

**Comment by silverbullet-herr** [comment]
try this:
pip uninstall pygments && pip install pygments to install the latest version instead of the required version that's how it worked for me

**Comment by saurabhtxy94-lgtm** [comment]
EMULATER BYPAS
