### ISSUE TITLE
Android: Unable to start activity when spawning

### ISSUE THREAD

**Issue by JohnCoates** [frida/frida#2410]
Getting the following error on `frida --usb --file com.scb.phone`:

```
Spawned `com.scb.phone`. Resuming main thread!                          
[Pixel 6::com.scb.phone ]-> Process crashed: java.lang.RuntimeException: 246164584

***
FATAL EXCEPTION: main
Process: com.scb.phone, PID: 2795
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.scb.phone/com.scb.phone.view.activity.splash.SplashActivity}: java.lang.RuntimeException: 246164584
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.RuntimeException: 246164584
	at com.scb.phone.view.activity.splash.SplashActivity.getResources(Unknown Source:671)
	at android.view.Window.getDefaultFeatures(Window.java:1924)
	at android.view.Window.<init>(Window.java:733)
	at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:352)
	at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:363)
	at android.app.Activity.attach(Activity.java:7950)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
	... 12 more
***
```

Happy to help debug if you point me in the right direction.

**Comment by MIraK1E** [comment]
Hello sir, did your manage to solve this?
