### ISSUE TITLE
Unable to attach to exe on windows 16.0.11

### ISSUE THREAD

**Issue by sanktanglia** [frida/frida#2456]
Traceback (most recent call last):
  File "C:\d4\code\frida\frida-dump-ssl.py", line 48, in <module>
    main()
  File "C:\d4\code\frida\frida-dump-ssl.py", line 23, in main
    session = frida.attach('Diablo IV.exe')
  File "C:\Users\nesin\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
  File "C:\Users\nesin\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\nesin\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 1010, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
frida.ProcessNotRespondingError: process with pid 1916 either refused to load frida-agent, or terminated during injection

**Comment by jpstotz** [comment]
Does it work with other processes? I would expect that commercial (online) games like Diablo IV contains anti-hooking measures to make cheating and bot development more difficult.

**Comment by ricsirigu** [comment]
I am facing the same problem also with a simple hello world written in C (Windows 11 ARM and Frida 16)

**Comment by pefish** [comment]
same problem

**Comment by tinyhare** [comment]
On windows, it seems that the process cannot be started in the sandbox.
I set the "-no-sandbox" parameter when I started chrome and solved the problem:

<img width="596" height="394" alt="Image" src="https://github.com/user-attachments/assets/9ac8b676-f869-4f9f-8c82-afeaf837a2f0" />
