### ISSUE TITLE
Missing: _ZNK3art6Thread13DecodeJObjectEP8_jobject 

### ISSUE THREAD

**Issue by benquike** [frida/frida#2468]
Running frida server on Android (Pixel 7 Pro) got the following message: 

```
 {"type":"error","description":"Error: Java API only partially available; please file a bug. Missing: _ZNK3art6Thread13DecodeJObjectEP8_jobject","stack":"Error: Java API only partially available; please file a bug. Missing: _ZNK3art6Thread13DecodeJObjectEP8_jobject\n    

at ze (frida/node_modules/frida-java-bridge/lib/android.js:181:1)
at Oe (frida/node_modules/frida-java-bridge/lib/android.js:16:1) 
at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:29:1)
at new _ (frida/node_modules/frida-java-bridge/index.js:21:1) 
at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:332:1)
at o (frida/node_modules/browser-pack/_prelude.js:1:1)
at frida/node_modules/browser-pack/_prelude.js:1:1
at Object.22.frida-java-bridge (frida/runtime/java.js:1:1)
 at o (frida/node_modules/browser-pack/_prelude.js:1:1)
 at r (frida/node_modules/browser-pack/_prelude.js:1:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":181,"columnNumber":1}
```

**Comment by gsingh93** [comment]
Pixel 7 Pro works for me with Android 13, but I got this error on Android 14. I fixed it by commenting out this line and building `frida-server` manually: https://github.com/frida/frida-java-bridge/blob/9199ce480d89488d210d538a2a3e1abec128af34/lib/android.js#L191

**Comment by DongZhuX** [comment]
command : adb shell pm uninstall com.google.android.art
and rboot

**Comment by flamecopper** [comment]
pm uninstall com.google.android.art          
Failure [DELETE_FAILED_ABORTED: Failed to uninstall apex com.google.android.art]
