### ISSUE TITLE
App Spawning Issue (Time Out)

### ISSUE THREAD

**Issue by b1naryTR** [frida/frida#2509]
When I try to spawn processes with `-f` flag app simply will not spawn. I am using crDroid 9.4 on my Poco F1.
Eg: `frida -U -l .\frida-script.js -f com.beemdevelopment.aegis` command outputs;
```
PS C:\Users\PC1\Desktop> frida -U -l .\frida-script.js -f com.beemdevelopment.aegis
     ____
    / _  |   Frida 16.0.18 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to POCO F1 (id=4c5d0a5d)
Failed to spawn: unexpectedly timed out while waiting for signal from process with PID 23571
```
There is a random ass service on that PID.
`ps -A | grep 23571` outputs;
`root         23571   765 14789992 55336 __skb_wait_for_more_packets 0 S usap64`
When I kill that PID frida just "times out" from another PID.

Here is some device info to help debugging;
`Linux localhost 4.9.337-perf-g153a7273b25b #1 SMP PREEMPT Mon Apr 17 14:40:42 EEST 2023 aarch64 Toybox`
Build Number: `TQ2A.230405.003.E1`

**Comment by b1naryTR** [comment]
Update: Still same on crDroid 9.5 with May 2023 security patch.

**Comment by LaiKash** [comment]
I am facing the same issue with a Poco x3 pro: https://github.com/frida/frida/issues/2516 

Are you running MIUI with xiaomi.eu or a AOESP based ROM @b1naryTR?

**Comment by LaiKash** [comment]
> > I am facing the same issue with a Poco x3 pro: #2516
> > Are you running MIUI with xiaomi.eu or a AOESP based ROM @b1naryTR?
> 
> Nope, I am on crDroid which is based on LineageOS.

Then it should be related with the security patch or Android 13 for Poco devices. Was it working in a previous security patch version?

**Comment by b1naryTR** [comment]
Yeah, I think so.

**Comment by MandroidR** [comment]
> > I am facing the same issue with a Poco x3 pro: #2516
> > Are you running MIUI with xiaomi.eu or a AOESP based ROM @b1naryTR?
> 
> Nope, I am on crDroid which is based on LineageOS.

I have same issue in crdroid 12.1

**Comment by tbm98** [comment]
I have same issue with latest frida-script.ja and frida-tools/frida-server
run on android 10/samsung galaxy s9

**Comment by QQbit** [comment]
lastweek it's work but today I found same issue  
Android 11 
Frida version :  frida-server-16.0.19-android-arm64

**Comment by endlessmeal** [comment]
Same
Android 11
Frida version: 16.0.19

**Comment by rushkii** [comment]
Same issue on Android 12 POCO F4 with frida 16.0.19 and frida-server 16.0.19.
```sh
>frida -U -l ./frida-script.js -f "jp.naver.line.android"
     ____
    / _  |   Frida 16.0.19 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to 22021211RG (id=85206705)
Failed to spawn: unexpectedly timed out while waiting for signal from process with PID 1936
```

**Comment by ea3tjun** [comment]
I also have this problem on Mi Pad4 with Pixel Experience Android13

**Comment by b1naryTR** [comment]
Still doesn't work on crDroid 9.7. Please help. @oleavr

**Comment by Happy9119** [comment]
I'm also facing same issue in Android 11 on OnePlus 6T, have frida 16.1.7 installed with same version of frida server. 

Traceback (most recent call last):
  File "/home/kali/.local/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/home/kali/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/kali/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kali/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kali/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/objection/console/cli.py", line 114, in explore
    agent.inject()
  File "/home/kali/.local/lib/python3.9/site-packages/objection/utils/agent.py", line 202, in inject
    session = self.get_session()
  File "/home/kali/.local/lib/python3.9/site-packages/objection/utils/agent.py", line 166, in get_session
    self.spawned_pid = self.device.spawn(state_connection.gadget_name)
  File "/home/kali/.local/lib/python3.9/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/frida/core.py", line 968, in spawn
    return self._impl.spawn(program, **kwargs)
frida.TimedOutError: unexpectedly timed out while waiting for signal from process with PID 11484

OnePlus6T:/ # ps -e | grep 11484                                                                                                                                                             
root          11484    888 15570720 57620 __skb_wait_for_more_packets 0 S usap64

**Comment by AiziChen** [comment]
Same issue in 2024, with frida-server-16.1.10-android-arm64 in Android 13.
