### ISSUE TITLE
Error: invalid address

### ISSUE THREAD

**Issue by swer45** [frida/frida#2511]
`{
 "type": "error",
 "description": "Error: invalid address",
 "stack": "Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:203:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1185:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1099:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)",
 "fileName": "frida/runtime/core.js",
 "lineNumber": 203,
 "columnNumber": 1
}`

Frida server gives me this error if I try to execute it, if I set enforce to Permissive this errors dissapear but I can't autostart apps and after few minutes my phone auto restart. I'm using xiaomi.eu rom Android 13 in POCO X3 Pro.

**Comment by swer45** [comment]
In AOSP roms like crDroid this don't happen.
