### ISSUE TITLE
frida version 16.0.11 executes hook functions, sometimes recursively indefinitely

### ISSUE THREAD

**Issue by dzdzdzd123** [frida/frida#2522]
I am using frida 16.0.11 to execute hook functions, sometimes recursively indefinitely.
The code is as follows
`Java.perform(function () {
    let DESede = Java.use("com.xiaojianbang.app.DESede");
    DESede["desede"].implementation = function (str) {
        console.log(`DESede.desede is called: str=${str}`);
        let result = this["desede"](str);
        console.log(`DESede.desede result=${result}`);
        return result;
    };
})`

result is:

java.lang.Throwable
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.DES.des_2(Native Method)
	at com.xiaojianbang.app.MainActivity.onClick(MainActivity.java:85)
	at android.view.View.performClick(View.java:7441)
	at android.view.View.performClickInternal(View.java:7418)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28676)

**Comment by Vishalsng112** [comment]
someone, please address this issue. I am also facing a similar issue.
