### ISSUE TITLE
Error with Goland 1.20 under Linux

### ISSUE THREAD

**Issue by FafnerKeyZee** [frida/frida#2526]
Hey,

When I try to open an executable (created with goland 1.20)  under Linux with the last build on pip. I got the following error
```fafner@ransomlol:~/test$ python3 extract.py ./d_linux_amd64 
pid: 3344
Traceback (most recent call last):
  File "/home/fafner/test/extract.py", line 150, in <module>
    main(target_process)
  File "/home/fafner/test/extract.py", line 73, in main
    session = frida.attach(pid)
  File "/home/fafner/.local/lib/python3.10/site-packages/frida/__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
  File "/home/fafner/.local/lib/python3.10/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "/home/fafner/.local/lib/python3.10/site-packages/frida/core.py", line 1010, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
frida.NotSupportedError: loader crashed with signal 11; please file a bug
        rip: 00007fc332655cf0
        rsp: 00007fff5311de70
        rbp: 0000000000000000
        rax: 00007fc332655cc0
        rcx: 00007fc3327f0000
        rdx: 00007fc3327ef1ad
        rbx: 00007fc3327e24b8
        rsi: 0000000000000000
        rdi: 00007fc3327f0028
         r8: 0000000000000000
         r9: 0000000000000000
        r10: 0000000000000000
        r11: 0000000000000000
        r12: 0000000000000000
        r13: 0000000000000000
        r14: 0000000000000000
        r15: 0000000000000000
``` 
With the same build for PE32+ (aka win 64) There is no problem.

Snippet is:
```

def main(target_process):                                                                                                                                
            
    pid = frida.spawn(target_process)                                                
    print('pid: %d' % pid)
                                          
    session = frida.attach(pid)
                                  
``` 

Please let me know if you need more details.
BTW it is working fine with a gcc compiled ELF64

BR,

**Comment by FafnerKeyZee** [comment]
Same error if I use frida-trace
``` 
fafner@ransomlol:~/test$ frida-trace --debug ./d_linux_amd64 
Failed to attach: loader crashed with signal 11; please file a bug      
        rip: 00007fe268caccf0
        rsp: 00007ffe2c64d0d0
        rbp: 0000000000000000
        rax: 00007fe268caccc0
        rcx: 00007fe268e48000
        rdx: 00007fe268e471ad
        rbx: 00007fe268e394b8
        rsi: 0000000000000000
        rdi: 00007fe268e48028
         r8: 0000000000000000
         r9: 0000000000000000
        r10: 0000000000000000
        r11: 0000000000000000
        r12: 0000000000000000
        r13: 0000000000000000
        r14: 0000000000000000
        r15: 0000000000000000
 ```
Concerning the binary:
```
d_linux_amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=11fG-mHMUfcNpYlmi3Jp/VyLI3XG_8tglOQ4D2AXv/gvQd9FPaTg7YQb6pFQf5/jpsppzAhJnYTPntbzN21, stripped
``` 

BR

**Comment by haohaolee** [comment]
frida currently doesn't support static linked binary for linux

**Comment by pimterry** [comment]
I hit this same signal 11 error too, I can confirm it's also static linking in my case - `ldd ./binary` prints "not a dynamic executable".

Fair enough, since that makes Frida largely unusable in this scenario anyway, though it would be nice to see a clearer error about what's happening here.

**Comment by IamHuskar** [comment]
> frida currently doesn't support static linked binary for linux

现在好像还是不能处理static linked 比如 gcc --static的文件
