### ISSUE TITLE
Frida inject not working on Android 14

### ISSUE THREAD

**Issue by riyadmondol2006** [frida/frida#2545]
{"type":"error","description":"Error: Java API only partially available; please file a bug. Missing: _ZNK3art6Thread13DecodeJObjectEP8_jobject","stack":"Error: Java API only partially available; please file a bug. Missing: _ZNK3art6Thread13DecodeJObjectEP8_jobject\n    at ze (frida/node_modules/frida-java-bridge/lib/android.js:181:1)\n    at Oe (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:29:1)\n    at new _ (frida/node_modules/frida-java-bridge/index.js:21:1)\n    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:332:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at frida/node_modules/browser-pack/_prelude.js:1:1\n    at Object.22.frida-java-bridge (frida/runtime/java.js:1:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at r (frida/node_modules/browser-pack/_prelude.js:1:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":181,"columnNumber":1}                    Java API only partially available; please file a bug. Missing: _ZNK3art6Thread13DecodeJObjectEP8_jobject

**Comment by zzzzfeng** [comment]
Seem there is an answer #2468

**Comment by mihai9621** [comment]
![Screenshot_2024-04-02-10-07-07-711_io github huskydg magisk-edit](https://github.com/frida/frida/assets/36726985/b5ef91f9-5a75-43e2-81a4-91608a9c4425)
