### ISSUE TITLE
Assertion failed local libc different than remote libc

### ISSUE THREAD

**Issue by razaina** [frida/frida#255]
Hi,

when I try to attach to an application via a python script or if I try to use frida-trace command, i get the following errors:

`> $ frida-trace -U -f com.google.android.calendar                                                                                                                   
`

```
Traceback (most recent call last):
  File "hook.py", line 23, in <module>
    process = frida.get_usb_device().attach('com.google.android.calendar')
  File "/home/r/Tools/frida/venv/lib/python3.6/site-packages/frida/core.py", line 97, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.TransportError: the connection is closed
```

`Frida:ERROR:../../../../frida-core/src/linux/frida-helper-glue.c:2059:frida_resolve_library_function: assertion failed (local_library_path == remote_library_path): ("/system/lib/libc.so" == "/lib/libc.so")`

**Comment by enovella** [comment]
Hi @razaina,

could you provide more details about your set up and versions? 
Also, if you are  using a `python` script might be handy to share the critical parts to try to identify the error.

Cheers

**Comment by razaina** [comment]
```
> $ frida --version   
9.1.18
```

```
> $ git rev-parse HEAD  
45cf1583265fa539095066741fa80fd5381c2da4
```

```
shell@hammerhead:/ $ uname -a
Linux localhost 3.4.0-g7717f76 #1 SMP PREEMPT Wed Nov 4 21:42:24 UTC 2015 armv7l
```


The python script is very simple:

```
import frida

print("[+] Attaching...\n")
process = frida.get_usb_device().attach('com.google.android.calendar')
print("[+] Yeah!")
```

Crash log:
```
03-22 16:30:35.593  5206  5206 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5206 (frida-helper-32)
03-22 16:30:35.694   332   332 F DEBUG   : pid: 5206, tid: 5206, name: frida-helper-32  >>> /data/local/tmp/re.frida.server/frida-helper-32 <<<
03-22 16:30:35.710   332   332 F DEBUG   :     #05 pc 001dc14d  /data/local/tmp/re.frida.server/frida-helper-32
03-22 16:30:35.710   332   332 F DEBUG   :     #06 pc 001db101  /data/local/tmp/re.frida.server/frida-helper-32 (g_assertion_message_cmpnum+188)
03-22 16:30:35.710   332   332 F DEBUG   :     #07 pc 0006bdb5  /data/local/tmp/re.frida.server/frida-helper-32 (_frida_helper_service_do_inject+168)
03-22 16:30:35.710   332   332 F DEBUG   :     #08 pc 0006257d  /data/local/tmp/re.frida.server/frida-helper-32
03-22 16:30:35.710   332   332 F DEBUG   :     #09 pc 000642b3  /data/local/tmp/re.frida.server/frida-helper-32
03-22 16:30:35.710   332   332 F DEBUG   :     #10 pc 00121639  /data/local/tmp/re.frida.server/frida-helper-32
03-22 16:30:35.710   332   332 F DEBUG   :     #11 pc 001c44d5  /data/local/tmp/re.frida.server/frida-helper-32 (g_main_context_dispatch+196)
03-22 16:30:35.710   332   332 F DEBUG   :     #12 pc 001c471f  /data/local/tmp/re.frida.server/frida-helper-32
03-22 16:30:35.710   332   332 F DEBUG   :     #13 pc 001c493d  /data/local/tmp/re.frida.server/frida-helper-32 (g_main_loop_run+168)
03-22 16:30:35.713   332   332 F DEBUG   :     #14 pc 00060a51  /data/local/tmp/re.frida.server/frida-helper-32 (frida_helper_service_run+36)
03-22 16:30:35.713   332   332 F DEBUG   :     #15 pc 000609fd  /data/local/tmp/re.frida.server/frida-helper-32 (frida_main+36)
03-22 16:30:35.713   332   332 F DEBUG   :     #17 pc 00060994  /data/local/tmp/re.frida.server/frida-helper-32
```

**Comment by razaina** [comment]
Hi,

no idea regarding why local and remote path are different in this case?

**Comment by neoz** [comment]
In some process, we have 2 more module of libc.so, so frida could not find correct libc.so
14200000     424K r--p  /system/lib/arm/libc.so
1426a000      12K rw-p  /system/lib/arm/libc.so
b76b1000     628K r-xp  /system/lib/libc.so
b774f000       8K r--p  /system/lib/libc.so
b7751000      12K rw-p  /system/lib/libc.so
