### ISSUE TITLE
Crashes after a few seconds.

### ISSUE THREAD

**Issue by mohe2015** [frida/frida#258]
If I hook com.snapchat.android frida crashes after a few seconds:
```
Events injected: 1
## Network stats: elapsed time=38ms (0ms mobile, 0ms wifi, 38ms not connected)
[*] Running...
[*] called java.io.File.exists() on file /data/misc/user/0/cacerts-removed/7999be0d.0
[*] called java.io.File.exists() on file /data/misc/user/0/cacerts-added/2db8aa5b.0
[*] called java.io.File.exists() on file /data/misc/user/0/cacerts-added/d76c6500.0
[*] called java.io.File.exists() on file /data/misc/user/0/cacerts-added/7999be0d.0
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/cache
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/cache
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/cache
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/video_quality_rules_file
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/3217a6e0513b72259a763fac60dc9703
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/9d1dcba0da4fba596284bddff9f77225
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/a57cc69b24e43dd25925699cf8add918
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/bee83098936eb513ab9103fd28add8fd
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/137e5d9231a19c23bda89445d3cd83d9
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/bba18a26203ebd220eeae73c77de0f08
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/f9e4868afc9aa940dd71bb77feb4c870
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/b64c1deb6be7d2de524878d50322626e
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/a24da5d68183e2871ec132e98a86f152
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/4ef2641e64a7a566c8a726e1b976b11b
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/d3b49a6663f8f6cb93d8ceb974653467
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/6e6fd8f000ee4358909829bb004d149b
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/470029bd6746dc73b473a236efd8f003
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/0aa39314ea540677c2501f0d7d62cd3b
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/dffbcbf1f64ab84356dbe4ad9328362d
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/09442c4c1503d5182d84e088ad982f94
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/3d6d51edd216e22c6a6f4da01f51ba2b
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/1ff398b626106b5b90e7debd117d5e6a
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/29bec533e23295397c9f697790aad7b4
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/34921714409a2042a6d26d374441a335
[*] called java.io.File.exists() on file /data/user/0/com.snapchat.android/files/media_cache/f928d44f5b925ca5be02b616bd85b073
Traceback (most recent call last):
  File "native_test.py", line 97, in <module>
    script.load()
  File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 300, in load
    self._impl.load()
frida.TransportError: the connection is closed
```

The script:
```
import frida, sys
import subprocess


def on_message(message, data):
    if message['type'] == 'send':
        print("[*] {0}".format(message['payload']))
    else:
        print(message)


hook_code = """
    Java.perform(function () {

        var File = Java.use("java.io.File");
        var Activity = Java.use("android.app.Activity");
        var PackageManager = Java.use("android.app.ApplicationPackageManager");
        var NameNotFoundException = Java.use("android.content.pm.PackageManager$NameNotFoundException");
        var Debug = Java.use("android.os.Debug");
        var Runtime = Java.use("java.lang.Runtime");
        var IOException = Java.use("java.io.IOException");
        var ApplicationInfo = Java.use("android.content.pm.ApplicationInfo");
        var FileObserver = Java.use("android.os.FileObserver");

        File.exists.implementation = function () {
            var file_path = this.path['value'];

            send("called java.io.File.exists() on file "+file_path);

            var root_locations = ['/su/bin/su'];
            for (i = 0; i < root_locations.length; i++) {
                if (root_locations[i] === file_path){
                    send(file_path+" does not exist...");
                    return false;
                }
            }
            return this.exists.call(this);
        };

        PackageManager.getInstallerPackageName.implementation = function(package) {
                send("getInstallerPackageName"); // TODO just fake return value with own package
                return "com.android.vending";
        };

        PackageManager.getPackageInfo.implementation = function(package, flags) {
            send("getPackageInfo "+package+" "+flags);

            if (package == "eu.chainfire.supersu") {
                throw NameNotFoundException.$new();
            }
            return this.getPackageInfo.call(this, package, flags);
        };

        Debug.isDebuggerConnected.implementation = function () {
            send("isDebuggerConnected");
            return false;
        };

        // TODO override other overloads
        // TODO only block specific commands
        Runtime.exec.overload("java.lang.String").implementation = function (command) {
            send("exec "+command);
            throw IOException.$new();
        };

        // TODO just fake for the own package
        Activity.getApplicationInfo.implementation = function() {
            //send("getApplicationInfo");
            var ret = this.getApplicationInfo.call(this);

            if (ret != null) {
                ret.flags.value = 0;
            }

            return ret;
        };

       /* FileObserver.$new.overload("java.lang.String").implementation = function (path) {
            send("FileObserver");
        };*/

     /*   FileObserver.startWatching.implementation = function (path) {
            send("startWatching");
        };*/

    });
"""

try:
    subprocess.call(['adb', 'shell', 'am', 'force-stop', 'com.snapchat.android'])
    subprocess.call(['adb', 'shell', 'monkey', '-p', 'com.snapchat.android', '-c', 'android.intent.category.LAUNCHER', '1'])
    process = frida.get_usb_device(10).attach('com.snapchat.android')
    script = process.create_script(hook_code)
    script.on('message', on_message)
    print('[*] Running...')
    script.load()
    sys.stdin.read()
except KeyboardInterrupt:
    subprocess.call(['adb', 'shell', 'am', 'force-stop', 'com.snapchat.android'])

```

**Comment by max01203** [comment]
Hi, 
First I advice you to split the code in 2 files, 1 for the python and 1 for the JS script to let you the ability to read the code with syntax highlighting in JS. 
About your error I suggest you to reduce the function that you hook to check if the crash still occurs because in my opinion the crash come from a function that you want to hook and make the application crash. I suggest to give us a look to adb logcat using the PID of the application to have a look about why the application crashed.

Thanks,
