### ISSUE TITLE
Failed to enumerate processes: unable to open library: No such file or directory

### ISSUE THREAD

**Issue by lingduyu1234** [frida/frida#2593]
My Device:

- Redmi Note 3, 
- MIUI10 8.11.22 | 开发板, 
- Android 6.0.1, 
- already root, 
- cpu is arm64-v8a
- USB debug has opened

1. Download [frida-server-16.1.3-android-arm64](https://github.com/frida/frida/releases/download/16.1.3/frida-server-16.1.3-android-arm64.xz)

2. push it to my phone and run it, but error like this: 

> {"type":"error","description":"Error: Java API only partially available; please file a bug. Missing: JNI_GetCreatedJavaVMs, _ZN3art17ReaderWriterMutex13ExclusiveLockEPNS_6ThreadE, _ZN3art17ReaderWriterMutex15ExclusiveUnlockEPNS_6ThreadE, _ZN3art10ThreadList9ResumeAllEv, _ZN3art6Thread14CurrentFromGdbEv, _ZN3art3Dbg14SetJdwpAllowedEb","stack":"Error: Java API only partially available; please file a bug. Missing: JNI_GetCreatedJavaVMs, _ZN3art17ReaderWriterMutex13ExclusiveLockEPNS_6ThreadE, _ZN3art17ReaderWriterMutex15ExclusiveUnlockEPNS_6ThreadE, _ZN3art10ThreadList9ResumeAllEv, _ZN3art6Thread14CurrentFromGdbEv, _ZN3art3Dbg14SetJdwpAllowedEb\n    at ze (frida/node_modules/frida-java-bridge/lib/android.js:181:1)\n    at Oe (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:29:1)\n    at new _ (frida/node_modules/frida-java-bridge/index.js:21:1)\n    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:332:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at frida/node_modules/browser-pack/_prelude.js:1:1\n    at Object.22.frida-java-bridge (frida/runtime/java.js:1:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at r (frida/node_modules/browser-pack/_prelude.js:1:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":181,"columnNumber":1}

3. download [frida-server-16.1.3-android-arm](https://github.com/frida/frida/releases/download/16.1.3/frida-server-16.1.3-android-arm.xz), push and run, it worked

4. **pip install frida**, **pip install frida-tools**, Both of them are the latest versions.
> frida --16.1.3, frida-tools --12.2.1

5. when I run **frida-ps -U** it print: 
> Failed to enumerate processes: unable to open library: No such file or directory

I tried:
**adb forward tcp:27042 tcp:27042
adb forward tcp:27043 tcp:27043**
but it still print that.

_Some great god can save me, thanks very much!_

**Comment by lordgzar** [comment]
same issue but with a slightly different error.
Failed to enumerate processes: dlopen failed: library "/proc/self/fd/472" not found

I'm using a rooted Samsung Galaxy Note 4 running Android 5.1

**Comment by lingduyu1234** [comment]
I did the same thing. It can be print right codes with the 雷电模拟器

**Comment by lingduyu1234** [comment]
> same issue but with a slightly different error. Failed to enumerate processes: dlopen failed: library "/proc/self/fd/472" not found
> 
> I'm using a rooted Samsung Galaxy Note 4 running Android 5.1

I did the same thing. It can be print right codes with the 雷电模拟器

**Comment by joseluisinigo** [comment]
> My Device:
> 
> * Redmi Note 3,
> * MIUI10 8.11.22 | 开发板,
> * Android 6.0.1,
> * already root,
> * cpu is arm64-v8a
> * USB debug has opened
> 
> 1. Download [frida-server-16.1.3-android-arm64](https://github.com/frida/frida/releases/download/16.1.3/frida-server-16.1.3-android-arm64.xz)
> 2. push it to my phone and run it, but error like this:
> 
> > {"type":"error","description":"Error: Java API only partially available; please file a bug. Missing: JNI_GetCreatedJavaVMs, _ZN3art17ReaderWriterMutex13ExclusiveLockEPNS_6ThreadE, _ZN3art17ReaderWriterMutex15ExclusiveUnlockEPNS_6ThreadE, _ZN3art10ThreadList9ResumeAllEv, _ZN3art6Thread14CurrentFromGdbEv, _ZN3art3Dbg14SetJdwpAllowedEb","stack":"Error: Java API only partially available; please file a bug. Missing: JNI_GetCreatedJavaVMs, _ZN3art17ReaderWriterMutex13ExclusiveLockEPNS_6ThreadE, _ZN3art17ReaderWriterMutex15ExclusiveUnlockEPNS_6ThreadE, _ZN3art10ThreadList9ResumeAllEv, _ZN3art6Thread14CurrentFromGdbEv, _ZN3art3Dbg14SetJdwpAllowedEb\n    at ze (frida/node_modules/frida-java-bridge/lib/android.js:181:1)\n    at Oe (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:29:1)\n    at new _ (frida/node_modules/frida-java-bridge/index.js:21:1)\n    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:332:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at frida/node_modules/browser-pack/_prelude.js:1:1\n    at Object.22.frida-java-bridge (frida/runtime/java.js:1:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at r (frida/node_modules/browser-pack/_prelude.js:1:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":181,"columnNumber":1}
> 
> 3. download [frida-server-16.1.3-android-arm](https://github.com/frida/frida/releases/download/16.1.3/frida-server-16.1.3-android-arm.xz), push and run, it worked
> 4. **pip install frida**, **pip install frida-tools**, Both of them are the latest versions.
> 
> > frida --16.1.3, frida-tools --12.2.1
> 
> 5. when I run **frida-ps -U** it print:
> 
> > Failed to enumerate processes: unable to open library: No such file or directory
> 
> I tried: **adb forward tcp:27042 tcp:27042 adb forward tcp:27043 tcp:27043** but it still print that.
> 
> _Some great god can save me, thanks very much!_

The problem comes from the architecture that you have downloaded from frida-server. Another test.

**Comment by stuacct073** [comment]
i have meet the same error, then i adjust my frida version solve this problem. my frida version is 
```
   frida-server==16.0.2
   frida==16.0.2
   frida-tools==12.0.4
```

**Comment by hhhhhhhds6** [comment]
> i have meet the same error, then i adjust my frida version solve this problem. my frida version is
> 
> ```
>    frida-server==16.0.2
>    frida==16.0.2
>    frida-tools==12.0.4
> ```
hello i installed 
frida-server==16.4.5
   frida==16.4.5
frida-tools=12.5.0
how to solve it

**Comment by bartlomiejduda** [comment]
I believe that this error may also occur when you have mismatch on target architecure between frida-server and frida client.
For example:
 1. Frida-server **64-bit** and frida client **32-bit**
 2. Frida-server **32-bit** and frida client **64-bit**

So to fix this, you would need to **set your frida-server and client both to 64-bit or both to 32-bit**.
