### ISSUE TITLE
pip install frida on ARM installs intel binaries

### ISSUE THREAD

**Issue by techvoltage** [frida/frida#261]
file /usr/local/lib/python3.4/dist-packages/_frida.cpython-34m.so gives
ELF 32-bit LSB  shared object, Intel 80386, version 1 (SYSV), dynamically linked, stripped

**Comment by pyc0de** [comment]
same for:
file /usr/local/lib/python2.7/dist-packages/_frida.so                     /usr/local/lib/python2.7/dist-packages/_frida.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, not strippedib/python2.7/dist-packages/_frida.so:

wich leads to:
frida-ls-devices

***
Failed to load the Frida native extension: /usr/local/lib/python2.7/dist-packages/_frida.so: cannot open shared object file: No such file or directory
Please ensure that the extension was compiled for Python 2.7.
***

Traceback (most recent call last):
  File "/usr/local/bin/frida-ls-devices", line 7, in <module>
    from frida.lsd import main
  File "/usr/local/lib/python2.7/dist-packages/frida/__init__.py", line 26, in <module>
    raise ex
