### ISSUE TITLE
Invalid instruction error on Android 13

### ISSUE THREAD

**Issue by be4zad** [frida/frida#2669]
###### Information
OS: Android 13

ROM: crDroid 9.0 (based on los)

Root: Rooted with Magisk / Also tried with magisk-frida

Server version: 16.0.4

I'm getting this error when I start frida-server on Android 13:
```
{"type":"error","description":"Error: invalid instruction","stack":"Error: invalid instruction\n    at Function.value (frida/runtime/core.js:427:1)\n    at Tn (frida/node_modules/frida-java-bridge/lib/android.js:1734:1)\n    at frida/node_modules/frida-java-bridge/lib/android.js:1612:1\n    at Object.value [as patchCode] (frida/runtime/core.js:207:1)\n    at In (frida/node_modules/frida-java-bridge/lib/android.js:1611:1)\n    at vt (frida/node_modules/frida-java-bridge/lib/android.js:581:1)\n    at frida/node_modules/frida-java-bridge/lib/memoize.js:4:1\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:576:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)","fileName":"frida/runtime/core.js","lineNumber":427,"columnNumber":1}
```
And this for client tools (e.g. frida-ps -U):
```
Failed to enumerate processes: cannot read properties of undefined (reading 'getRunningAppProcesses')
```

Any solution?

**Comment by optickavarka** [comment]
Same problem for me 
OS: Android 13 
frida: 16.1.8

**Comment by wAnFen1017** [comment]
```
pm uninstall com.google.android.art
reboot
```

**Comment by xxx252525** [comment]
I'm having this issue as well, my frida version is 15.5.7

**Comment by xxx252525** [comment]
I'm having this issue as well, my frida version is 16.5.7

**Comment by CoolSlimbo** [comment]
Second this.

**Comment by aaptel** [comment]
Same issue on android 11, rooted with magisk.
Samsung tab A SM-T510

**Comment by groszdaniel** [comment]
Having this on a crDroid 10.13 GSI, based on Android 14, on a Xiaomi Redmi 9C. Could be related to the fact that it's a phone with an a64 (i.e. partly 32-bit, I'm not sure about the details) OS.
