### ISSUE TITLE
Spawngating and childgating compatibility issues

### ISSUE THREAD

**Issue by Myshtea** [frida/frida#2692]
I wanted to try to create an instrumentation that is complete. I.E that instruments the main process, the child processes and the spawned processes. 

For this I tried to merge the examples for childgating and spawngating [Found here](https://gist.github.com/pellaeon/3925b0fd2d8939e12b38325d16c0003b)

The important part of the merge looks like this : 
```python
   [...]
    def _instrument(self, pid):
        print("✔ attach(pid={})".format(pid))
        session = self._device.attach(pid)
        session.on("detached", lambda reason:
            self._reactor.schedule(lambda:
                self._on_detached(pid, session, reason)))
        if CHILD_GATING:
            print("✔ enable_child_gating()")
            session.enable_child_gating()
        print("✔ create_script()")
        script = session.create_script("""
        Java.perform(function() {});
                                       """)
        script.on("message", lambda message, data:
            self._reactor.schedule(
                lambda: self._on_message(pid, message)))
        print("✔ load()")
        script.load()
        print("✔ resume(pid={})".format(pid))
        self._device.resume(pid)
        self._sessions.add(session)
   def _on_delivered_spawn(self, child):
        print("⚡ spawn-added: {}".format(child))
        if child.identifier.startswith(app_package_name):
            self._instrument(child.pid)
        else:
            self._device.resume(child.pid)
   
    def _on_delivered_child(self, child):
        print("⚡ child-added: {}".format(child))
        self._instrument(child.pid)
```
    
--- 
Sadly this results in the following output :
```bash
✔ enable_spawn_gating()
✔ spawn(PACKAGE)
✔ attach(pid=6854)
✔ enable_child_gating()
✔ create_script()
✔ load()
✔ resume(pid=6854)
⚡ spawn-added: Spawn(pid=6945, identifier="PACKAGE:Metrica")
✔ attach(pid=6945)
✔ enable_child_gating()
✔ create_script()
✔ load()
✔ resume(pid=6945)
⚡ child-added: Child(pid=7593, parent_pid=6854, origin=fork)
✔ attach(pid=7593)
✔ enable_child_gating()
✔ create_script()
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "/home/myshtea/.pyenv/versions/3.11.4/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/myshtea/.pyenv/versions/3.11.4/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/myshtea/.pyenv/versions/3.11.4/lib/python3.11/site-packages/frida_tools/reactor.py", line 70, in _run
    work()
  File "/mnt/data/XXX/spawngating.py", line 30, in <lambda>
    lambda: self._on_delivered_child(child)))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/XXX/spawngating.py", line 77, in _on_delivered_child
    self._instrument(child.pid)
  File "/mnt/data/XXX/spawngating.py", line 56, in _instrument
    script = session.create_script("""
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myshtea/.pyenv/versions/3.11.4/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/myshtea/.pyenv/versions/3.11.4/lib/python3.11/site-packages/frida/core.py", line 628, in create_script
    return Script(self._impl.create_script(source, **kwargs))  # type: ignore
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.TransportError: timeout was reached
```

Sometimes the main process simply stops silently. 
So I wondered if the childgating and spawngating functionality are not compatible?

More generally, if I want to be sure that the whole program and spawned processes are instrumented with the same frida script. Would I need to use a method like this? or should I simply use the child gating and spawn gating in two different executions ?

**Comment by Myshtea** [comment]
After some more testing, it seems like this problem can be repeated when using directly the childgating code (with no change) at least in my setup.

So I have the same error code that is started on script.load().
```bash
✔ spawn(solitaire.patience.card.games.klondike.free)
✔ attach(pid=7119)
✔ enable_child_gating()
✔ create_script()
✔ load()
✔ resume(pid=7119)
⚡ child-added: Child(pid=8242, parent_pid=7119, origin=fork)
✔ attach(pid=8242)
✔ enable_child_gating()
✔ create_script()
✔ load()
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "/home/myshtea/.pyenv/versions/3.11.4/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/myshtea/.pyenv/versions/3.11.4/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/myshtea/.pyenv/versions/3.11.4/lib/python3.11/site-packages/frida_tools/reactor.py", line 70, in _run
    work()
  File "/mnt/data/Documents/Work/Test/ATTools/temp/childgating.py", line 18, in <lambda>
    lambda: self._on_delivered(child)))
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Work/Test/ATTools/temp/childgating.py", line 57, in _on_delivered
    self._instrument(child.pid)
  File "/mnt/data/Documents/Work/Test/ATTools/temp/childgating.py", line 50, in _instrument
    script.load()
  File "/home/myshtea/.pyenv/versions/3.11.4/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/myshtea/.pyenv/versions/3.11.4/lib/python3.11/site-packages/frida/core.py", line 290, in load
    self._impl.load()
frida.TransportError: timeout was reached
```

If have been using :
frida version 16.1.7 
frida-server 16.1.7
