### ISSUE TITLE
Traceback (most recent call last) error message

### ISSUE THREAD

**Issue by orelamihay86** [frida/frida#2710]
Hi all,
I just installed python (Python 3.9.5) and install Frida using pip (pip v 23.3.1)

but when try to use Frida I received the below error, please help me!

Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\frida.exe\__main__.py", line 4, in <module>
  File "C:\Python39\lib\site-packages\frida_tools\repl.py", line 18, in <module>
    import frida
  File "C:\Python39\lib\site-packages\frida\__init__.py", line 17, in <module>
    from . import core
  File "C:\Python39\lib\site-packages\frida\core.py", line 39, in <module>
    from typing_extensions import NotRequired
ImportError: cannot import name 'NotRequired' from 'typing_extensions' (C:\Python39\lib\site-packages\typing_extensions.py)

Please help

Thanks!

**Comment by Rffrench** [comment]
Running `pip3 install typing-extensions --upgrade` worked for me
