### ISSUE TITLE
library "libm.so.5" not found

### ISSUE THREAD

**Issue by dodiwahyu** [frida/frida#2724]
I experienced problems when injecting the Frida Gadget lib version 16.1.8 on Android OS 14. When I ran the application I encountered the following error message: 

`
Installing build/app/outputs/flutter-apk/app-uat-debug.apk...
E/AndroidRuntime(15690): FATAL EXCEPTION: main
E/AndroidRuntime(15690): Process: com.example.app, PID: 15690
E/AndroidRuntime(15690): java.lang.UnsatisfiedLinkError: dlopen failed: library "libm.so.5" not found: needed by /data/app/~~hYV6q8YuBpN28dajQwqqBA==/id.co.tokiomarine_life.amsuat-niYzPOfPl-W3xGvXi8BYlw==/base.apk!/lib/arm64-v8a/libfrida-gadget.so in namespace clns-6
E/AndroidRuntime(15690): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
E/AndroidRuntime(15690): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/AndroidRuntime(15690): 	at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime(15690): 	at com.example.app.MainActivity.<clinit>(MainActivity.kt:38)
E/AndroidRuntime(15690): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(15690): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(15690): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
E/AndroidRuntime(15690): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1378)
E/AndroidRuntime(15690): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
E/AndroidRuntime(15690): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
E/AndroidRuntime(15690): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(15690): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/AndroidRuntime(15690): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/AndroidRuntime(15690): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
E/AndroidRuntime(15690): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15690): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(15690): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(15690): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(15690): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15690): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(15690): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
`

**Comment by paishouxiaoshaou** [comment]
Regarding the architecture issue, please pay attention to the ARM version
