### ISSUE TITLE
Invlaid address error, Error: invalid address\n

### ISSUE THREAD

**Issue by sloopnoob** [frida/frida#2766]
Device: Oneplus Nord 5G
Android:12
```
tried setenforce 0 already, same error.
{"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:207:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1185:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1099:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":207,"columnNumber":1}
```

**Comment by AiziChen** [comment]
same error with my Realme phone, Android 13. use frida-server-v16.2.1

**Comment by wzx623303532** [comment]
same error in my xiaomi9 phone
Magisk: 26.1
Android 13
frida-server-v16.1.4

{"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:207:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1209:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1275:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1323:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1185:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1099:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":207,"columnNumber":1}

**Comment by sgxgsx** [comment]
@sloopnoob were you able to resolve it?
The following commands from similar problems didn't help
setprop sys.usap.enable false
setenforce 0

OxygenOS 13.1
Oneplus 8
frida-server-v16.2.1

Magisk is present, zygisk is off magiskhide off. 

Frida worked on this phone well at least a few months ago.

```

Spawned `x.xxxxxx.xxxxxxx`. Resuming main thread!                   
Error: invalid address
    at value (frida/runtime/core.js:207)
    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1215)
    at activate (frida/node_modules/frida-java-bridge/lib/android.js:1275)
    at replace (frida/node_modules/frida-java-bridge/lib/android.js:1323)
    at set (frida/node_modules/frida-java-bridge/lib/class-factory.js:1185)
    at set (frida/node_modules/frida-java-bridge/lib/class-factory.js:1099)
    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:224)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:244)
    at perform (frida/node_modules/frida-java-bridge/index.js:204)
    at <anonymous> (/home/xxxxxxxxxxxxxxxxxx/unpinning_scripts/un.js:54)
    at apply (native)
    at <anonymous> (frida/runtime/core.js:51)

```
