### ISSUE TITLE
biometrics_bypass got frida.core.RPCException: TypeError: cannot read property 'objc_lookUpClass' of null

### ISSUE THREAD

**Issue by yvza** [frida/frida#2779]
### Error Detail :
```
A Frida agent exception has occurred.
TypeError: cannot read property 'objc_lookUpClass' of null
    at o (frida/node_modules/frida-objc-bridge/index.js:179)
    at get (frida/node_modules/frida-objc-bridge/index.js:149)
    at <anonymous> (/script1.js:22318)
    at iosUiBiometricsBypass (/script1.js:22714)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23)

Python stack trace: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/opt/homebrew/lib/python3.11/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/opt/homebrew/lib/python3.11/site-packages/objection/commands/ui.py", line 90, in bypass_touchid
    api.ios_ui_biometrics_bypass()
  File "/opt/homebrew/lib/python3.11/site-packages/frida/core.py", line 179, in method
    return script._rpc_request("call", js_name, args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/frida/core.py", line 491, in _rpc_request
    raise result.error
frida.core.RPCException: TypeError: cannot read property 'objc_lookUpClass' of null
    at o (frida/node_modules/frida-objc-bridge/index.js:179)
    at get (frida/node_modules/frida-objc-bridge/index.js:149)
    at <anonymous> (/script1.js:22318)
    at iosUiBiometricsBypass (/script1.js:22714)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23)
```

### Screenshot :
<img width="598" alt="Screenshot 2024-02-23 at 09 32 23" src="https://github.com/frida/frida/assets/25668079/6dd2c951-3593-4274-84f8-a49fce6b7d36">

### Expected Result :
Show the biometric bypass success instead of script error

### Environment :
```
Python 3.11.7
Frida 16.2.1
objection: 1.11.0
```

**Comment by N3Dx0o** [comment]
having same issue :/
