### ISSUE TITLE
Frida failed to spawn and something else?

### ISSUE THREAD

**Issue by ANELKAOS** [frida/frida#280]
First of all, Ole thank you for your awesome Frida.

CLIENT:
---
```
Metadata-Version: 2.0
Name: frida
Version: 10.0.11
Summary: Inject JavaScript to explore native apps on Windows, macOS, Linux, iOS, Android, and QNX
Home-page: http://www.frida.re
Author: Frida Developers
Author-email: oleavr@nowsecure.com
Installer: pip
License: wxWindows Library Licence, Version 3.1
Location: /home/username/.local/lib/python2.7/site-packages
Requires: pygments, prompt-toolkit, colorama
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Console
  Environment :: MacOS X
  Environment :: Win32 (MS Windows)
  Intended Audience :: Developers
  Intended Audience :: Science/Research
  License :: OSI Approved
  Natural Language :: English
  Operating System :: MacOS :: MacOS X
  Operating System :: Microsoft :: Windows
  Operating System :: POSIX :: Linux
  Programming Language :: Python :: 2
  Programming Language :: Python :: 3
  Programming Language :: Python :: Implementation :: CPython
  Programming Language :: JavaScript
  Topic :: Software Development :: Debuggers
  Topic :: Software Development :: Libraries :: Python Modules
Entry-points:
  [console_scripts]
  frida = frida.repl:main
  frida-discover = frida.discoverer:main
  frida-kill = frida.kill:main
  frida-ls-devices = frida.lsd:main
  frida-ps = frida.ps:main
  frida-trace = frida.tracer:main
```
SERVER (android 5.1):
---
```
frida-server-10.0.11-android-arm (and client client 10.0.11)
frida-server-10.0.10-android-arm (and client client 10.0.10)
frida-server-10.0.9-android-arm (and client client 10.0.9)
frida-server-10.0.8-android-arm (and client client 10.0.8)
shell@androide:/data/local/tmp $ ls -la frida-server-10.0.11-android-arm
-rwxr-xr-x root     root     19201320 2017-06-05 02:51 frida-server-10.0.11-android-arm
```
frida-server-10.0.8 worked for a few time.

Same issue from Debian/ubuntu/lubuntu (Linux 4.4.0-34-generic 53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux):

```
$ frida-trace -U -i open com.android.chrome
Waiting for USB device to appear...
Attaching...                                                            
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/username/.local/lib/python2.7/site-packages/frida/application.py", line 384, in _run
    work()
  File "/home/username/.local/lib/python2.7/site-packages/frida/application.py", line 241, in _try_start
    self._update_status("Failed to attach: %s" % e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)

```
I changed chmod 755 by 777, re-check, setenforce permissive, chown of the binary, etc... I can enforce UTF-8 encode,  but the issue still there and same exception is launched. 

```
 frida-ps -a -U
Waiting for USB device to appear...
Failed to enumerate applications: error binding to address: No such file or directory
```

**Comment by dzonerzy** [comment]
ok try this, modify /home/username/.local/lib/python2.7/site-packages/frida/application.py on line 241

change this:
self._update_status("Failed to attach: %s" % e)
to this
self._update_status("Failed to attach: %s" % e.encode('utf-8'))

Let me know

**Comment by jhscheer** [comment]
Hi,
I have the exact same error with `frida-server-10.5.12-android-arm` on a 5.1.1 Samsung device.
The fix suggested by @dzonerzy did not work :(
`File "/[...]/local/lib/python2.7/site-packages/frida/application.py", line 267, in _try_start                          
    self._update_status("Failed to attach: %s" % str(e).encode('utf-8'))                                
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)`

**Comment by Paulswith** [comment]
it's working , thanks guy
"ok try this, modify /home/username/.local/lib/python2.7/site-packages/frida/application.py on line 241

change this:
self._update_status("Failed to attach: %s" % e)
to this
self._update_status("Failed to attach: %s" % str(e).encode('utf-8'))

Let me know"
