### ISSUE TITLE
frida.NotSupportedError: command failed: 99

### ISSUE THREAD

**Issue by DontForgontPassword** [frida/frida#2847]
Traceback (most recent call last):
  File "C:\Users\Brain\Desktop\fridadow\python\launcher.py", line 6, in <module>
    device.spawn(["com.google.chrome"])
  File "C:\Users\Brain\AppData\Local\Programs\Python\Python311\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Brain\AppData\Local\Programs\Python\Python311\Lib\site-packages\frida\core.py", line 968, in spawn
    return self._impl.spawn(program, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.NotSupportedError: command failed: 99

**Comment by Moonlight-hello** [comment]
I recommend verifying that the package name is accurate. It appears that you are using Windows.
