### ISSUE TITLE
An error occurred when starting frida-server on Android

### ISSUE THREAD

**Issue by 4332weizi** [frida/frida#2851]
- frida: `16.2.1`
- frida-server: `frida-server-16.2.1-android-arm64`
- divice: `Pixel 7 Pro`
- OS version: `Android 15 VanillalceCream (AP31.240322.027)`

```
cheetah:/ # /data/local/tmp/frida-server &
[1] 14506
cheetah:/ # {"type":"error","description":"TypeError: t is not a function","stack":"TypeError: t is not a function
     at frida/node_modules/frida-java-bridge/lib/android.js:1591:1
     at frida/node_modules/frida-java-bridge/lib/class-model.js:113:1
     at CallbackContext.kt (frida/node_modules/frida-java-bridge/lib/android.js:586:1)
     at NativeFunction.<anonymous> (<anonymous>)
     at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)
     at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1
     at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)
     at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)
     at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)
     at frida/node_modules/frida-java-bridge/index.js:224:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1591,"columnNumber":1}
{"type":"error","description":"TypeError: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')
     at I.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1014:1)
     at I.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1030:1)
     at Object.get (frida/node_modules/frida-java-bridge/lib/class-factory.js:742:1)
     at frida/node_modules/frida-java-bridge/index.js:224:1
     at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)
     at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)
     at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)
     at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/class-factory.js","lineNumber":1014,"columnNumber":1}
```

**Comment by Amargy** [comment]
Same:
1) pixel8 and VanillalceCream
2) frida server for ARM64 Android

$ adb push frida-server /data/local/tmp/
$ adb shell "chmod 755 /data/local/tmp/frida-server"
$ adb shell "/data/local/tmp/frida-server &"

emu64a:/ # {"type":"error","description":"TypeError: t is not a function","stack":"TypeError: t is not a function\n    at frida/node_modules/frida-java-bridge/lib/android.js:1591:1\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:113:1\n    at CallbackContext.kt (frida/node_modules/frida-java-bridge/lib/android.js:586:1)\n    at NativeFunction.<anonymous> (<anonymous>)\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1591,"columnNumber":1}
{"type":"error","description":"TypeError: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')\n    at F.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1018:1)\n    at F.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1034:1)\n    at Object.get (frida/node_modules/frida-java-bridge/lib/class-factory.js:746:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/class-factory.js","lineNumber":1018,"columnNumber":1}

**Comment by Rat4er** [comment]
same:
Pixel 7 VanillalceCream
```
{"type":"error","description":"TypeError: t is not a function","stack":"TypeError: t is not a function\n    at frida/node_modules/frida-java-bridge/lib/android.js:1591:1\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:113:1\n    at CallbackContext.kt (frida/node_modules/frida-java-bridge/lib/android.js:586:1)\n    at NativeFunction.<anonymous> (<anonymous>)\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1591,"columnNumber":1}
{"type":"error","description":"TypeError: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')\n    at I.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1014:1)\n    at I.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1030:1)\n    at Object.get (frida/node_modules/frida-java-bridge/lib/class-factory.js:742:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/class-factory.js","lineNumber":1014,"columnNumber":1}

```

**Comment by NgoHuy** [comment]
I updated today and have same issue, it conflicted with some changes from new Android backport.

**Comment by NgoHuy** [comment]
seem to this line is changed https://github.com/frida/frida-java-bridge/blob/5b32afc28eaa83a45b895b29a5cdc7e39ca6a343/lib/class-factory.js#L746C15-L746C38

**Comment by Davenjoy** [comment]
Same issue

Pixel 8 VanillaIceCream
Android 13

{"type":"error","description":"TypeError: t is not a function","stack":"TypeError: t is not a function\n    at frida/node_modules/frida-java-bridge/lib/android.js:1591:1\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:113:1\n    at CallbackContext.kt (frida/node_modules/frida-java-bridge/lib/android.js:586:1)\n    at NativeFunction.<anonymous> (<anonymous>)\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1591,"columnNumber":1}
{"type":"error","description":"TypeError: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')\n    at I.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1014:1)\n    at I.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1030:1)\n    at Object.get (frida/node_modules/frida-java-bridge/lib/class-factory.js:742:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/class-factory.js","lineNumber":1014,"columnNumber":1}

**Comment by 0xbigshaq** [comment]
Same issue here, tested on frida-server 16.2.0 and 16.3.3 (Pixel 5 API 35)

**Comment by vapinto** [comment]
Same issue to, frida-server-16.3.3, Android pixel 8 Pro,

**Comment by lumaaaaaa** [comment]
Same issue, frida-server 16.3.3 on Pixel 4 API 35

**Comment by lumaaaaaa** [comment]
Downgrading my device to API 34 resolved this issue, I suspect the offsets are not yet updated to support the latest API or something of that sort.

**Comment by itormoza** [comment]
Same issue, frida-server 16.3.3 on A52s 5G API 34 - LineageOS

**Comment by shaoziintel** [comment]
same issue frida-server 16.4.3

**Comment by NgoHuy** [comment]
new error on latest release:
```
{"type":"error","description":"Error: libart.so: unable to find export '_ZNK3art2gc4Heap15MayUseCollectorENS0_13CollectorTypeE'","stack":"Error: libart.so: unable to find export '_ZNK3art2gc4Heap15MayUseCollectorENS0_13CollectorTypeE'\n    at Function.value [as getExportByName] (frida/runtime/core.js:250:1)\n    at Ft (frida/node_modules/frida-java-bridge/lib/android.js:837:1)\n    at Tt (frida/node_modules/frida-java-bridge/lib/android.js:762:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1331:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1189:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1103:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":250,"columnNumber":1}
```

**Comment by Aziffo** [comment]
Same error here.

**Comment by devnoname120** [comment]
The fix was merged, also I didn't test it: https://github.com/frida/frida-java-bridge/pull/330

**Comment by uin991** [comment]
> The fix was merged, although I didn't test it: [frida/frida-java-bridge#330](https://github.com/frida/frida-java-bridge/pull/330)
frida-server-16.5.1, Android 15


new error on latest release:
Error: libart.so: unable to find export '_ZN3art7Runtime18EnsurePluginLoadedEPKcPNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE'
    at value (frida/runtime/core.js:250)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/android.js:226)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at ze (frida/node_modules/frida-java-bridge/lib/android.js:234)
    at get (frida/node_modules/frida-java-bridge/lib/android.js:212)
    at _chooseObjectsJvm (frida/node_modules/frida-java-bridge/lib/class-factory.js:308)
    at choose (frida/node_modules/frida-java-bridge/lib/class-factory.js:300)
    at choose (frida/node_modules/frida-java-bridge/index.js:264)`
`

**Comment by zcfrank1st** [comment]
> > The fix was merged, although I didn't test it: [frida/frida-java-bridge#330](https://github.com/frida/frida-java-bridge/pull/330)
> > frida-server-16.5.1, Android 15
> 
> new error on latest release: Error: libart.so: unable to find export '_ZN3art7Runtime18EnsurePluginLoadedEPKcPNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE' at value (frida/runtime/core.js:250) at (frida/node_modules/frida-java-bridge/lib/android.js:226) at (frida/node_modules/frida-java-bridge/lib/vm.js:12) at ze (frida/node_modules/frida-java-bridge/lib/android.js:234) at get (frida/node_modules/frida-java-bridge/lib/android.js:212) at _chooseObjectsJvm (frida/node_modules/frida-java-bridge/lib/class-factory.js:308) at choose (frida/node_modules/frida-java-bridge/lib/class-factory.js:300) at choose (frida/node_modules/frida-java-bridge/index.js:264)` `

same error

**Comment by voraci0us** [comment]
> > > The fix was merged, although I didn't test it: [frida/frida-java-bridge#330](https://github.com/frida/frida-java-bridge/pull/330)
> > > frida-server-16.5.1, Android 15
> > 
> > 
> > new error on latest release: Error: libart.so: unable to find export '_ZN3art7Runtime18EnsurePluginLoadedEPKcPNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE' at value (frida/runtime/core.js:250) at (frida/node_modules/frida-java-bridge/lib/android.js:226) at (frida/node_modules/frida-java-bridge/lib/vm.js:12) at ze (frida/node_modules/frida-java-bridge/lib/android.js:234) at get (frida/node_modules/frida-java-bridge/lib/android.js:212) at _chooseObjectsJvm (frida/node_modules/frida-java-bridge/lib/class-factory.js:308) at choose (frida/node_modules/frida-java-bridge/lib/class-factory.js:300) at choose (frida/node_modules/frida-java-bridge/index.js:264)` `
> 
> same error
> 
> frida-server 16.5.2
> 
> lineageOS 21, pixel 5a

Same error on lineageOS 21, pixel 6, frida-server 16.5.9

`Error: libart.so: unable to find export '_ZN3art7Runtime18EnsurePluginLoadedEPKcPNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE'
    at value (frida/runtime/core.js:250)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/android.js:226)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at ze (frida/node_modules/frida-java-bridge/lib/android.js:234)
    at get (frida/node_modules/frida-java-bridge/lib/android.js:212)
    at _chooseObjectsJvm (frida/node_modules/frida-java-bridge/lib/class-factory.js:308)
    at choose (frida/node_modules/frida-java-bridge/lib/class-factory.js:300)
    at choose (frida/node_modules/frida-java-bridge/index.js:264)
    at <anonymous> (<input>:29)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250)
    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:225)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:244)
    at perform (frida/node_modules/frida-java-bridge/index.js:204)
    at <eval> (<input>:32)
    at eval (native)
    at <anonymous> (/frida/repl-1.js:34)
    at evaluate (/frida/repl-1.js:57)
    at fridaEvaluateExpression (/frida/repl-1.js:34)
    at call (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:11)
    at o (frida/runtime/message-dispatcher.js:23)
`

**Comment by 4332weizi** [comment]
Pixel 7 Pro, Android 16, Baklava, BP22.250124.010

```
cheetah:/ # /data/local/tmp/frida-server &
[1] 13776
cheetah:/ # Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
```

**Comment by 5peak2me** [comment]
> * frida: `16.6.6`
> * frida-server: `frida-server-16.6.6-android-arm64`
> * divice: `Pixel 7 Pro`
> * OS version: `Android 16 Baklava (BP22.250124.010)`
> 
> ```
> cheetah:/ # /data/local/tmp/frida-server &
> [1] 13776
> cheetah:/ # Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
> Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
> ```

Same as you.

**Comment by fknemi** [comment]
- frida: 17.5.1
- frida-server: frida-server-17.5.1-android-arm64
- device: Nothing 3a Pro
- OS version: Android 15 REL (AQ3A.241015.001)

```
{"type":"error","description":"Error: Unable to find copied methods in java/lang/Thread; please file a bug","stack":"Error: 
Unable to find copied methods in java/lang/Thread; please file a bug\n    at /internal-agent.js:1:47232\n    at Ie.perform (/
internal-agent.js:1:25891)\n    at Gn (/internal-agent.js:1:45951)\n    at Md (/internal-agent.js:1827:1640)\n    at Uo (/internal-
agent.js:1827:1258)\n    at Function.build (/internal-agent.js:1827:85)\n    at t._make (/internal-agent.js:1828:18234)\n    at 
t.use (/internal-agent.js:1828:17033)\n    at /internal-agent.js:1837:6963\n    at Ie.perform (/internal-
agent.js:1:25891)","fileName":"/internal-agent.js","lineNumber":1,"columnNumber":47232}
```

**Comment by BreezeSun** [comment]
This problem has been solved,executive command:pm uninstall com.google.android.art,Then restart the mobile phone.

**Comment by touseef7283-stack** [comment]
Same issue for frida=17.5.0
husky:/ # Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
{"type":"error","description":"Error: Unable to find copied methods in java/lang/Thread; please file a bug","stack":"Error: Unable to find copied methods in java/lang/Thread; please file a bug\n    at /internal-agent.js:1:47232\n    at Ie.perform (/internal-agent.js:1:25891)\n    at Gn (/internal-agent.js:1:45951)\n    at Md (/internal-agent.js:1827:1640)\n    at Uo (/internal-agent.js:1827:1258)\n    at Function.build (/internal-agent.js:1827:85)\n    at t._make (/internal-agent.js:1828:18234)\n    at t.use (/internal-agent.js:1828:17033)\n    at /internal-agent.js:1837:6963\n    at Ie.perform (/internal-agent.js:1:25891)","fileName":"/internal-agent.js","lineNumber":1,"columnNumber":47232}
