### ISSUE TITLE
error pip install frida-tools

### ISSUE THREAD

**Issue by firdaus-rx** [frida/frida#2864]
~ $ export FRIDA_CORE_DEVKIT=/sdcard/devkit/
~ $ pip install frida-tools
Collecting frida-tools
  Using cached frida_tools-12.4.2-py3-none-any.whl
Collecting colorama<1.0.0,>=0.2.7 (from frida-tools)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting frida<17.0.0,>=16.2.2 (from frida-tools)
  Using cached frida-16.2.5.tar.gz (917 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting prompt-toolkit<4.0.0,>=2.0.0 (from frida-tools)
  Using cached prompt_toolkit-3.0.43-py3-none-any.whl.metadata (6.5 kB)
Collecting pygments<3.0.0,>=2.0.2 (from frida-tools)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting wcwidth (from prompt-toolkit<4.0.0,>=2.0.0->frida-tools)
  Using cached wcwidth-0.2.13-py2.py3-none-any.whl.metadata (14 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached prompt_toolkit-3.0.43-py3-none-any.whl (386 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Building wheels for collected packages: frida
  Building wheel for frida (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for frida (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [115 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/frida
      copying frida/__init__.py -> build/lib.linux-aarch64-cpython-311/frida
      copying frida/core.py -> build/lib.linux-aarch64-cpython-311/frida
      copying frida/py.typed -> build/lib.linux-aarch64-cpython-311/frida
      creating build/lib.linux-aarch64-cpython-311/frida/_frida
      copying frida/_frida/__init__.pyi -> build/lib.linux-aarch64-cpython-311/frida/_frida
      copying frida/_frida/py.typed -> build/lib.linux-aarch64-cpython-311/frida/_frida
      running build_ext
      /data/data/com.termux/files/usr/bin/sh: 1: which: not found
      Downloading toolchain 20240514...
      Extracting toolchain...
      Downloading SDK 20240514 for linux-arm64...
      Extracting SDK...
      Cloning into 'frida-core'...
      The Meson build system
      Version: 1.4.99
      Source dir: /data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257
      Build dir: /data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257/build
      Build type: native build
      Program python3 found: YES (/data/data/com.termux/files/usr/bin/python3)
      Project name: frida-python
      Project version: 16.2.5
      C compiler for the host machine: /data/data/com.termux/files/usr/bin/cc -march=armv8-a (clang 18.1.6 "clang version 18.1.6")
      C linker for the host machine: /data/data/com.termux/files/usr/bin/cc -march=armv8-a ld.lld 18.1.6
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Program python3 found: YES (/data/data/com.termux/files/usr/bin/python)
      WARNING: We thought we found pkg-config '/data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257/deps/toolchain-linux-arm64/bin/pkg-config --static --define-variable=frida_sdk_prefix=/data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257/deps/sdk-linux-arm64' but now it's not there. How odd!
      Found pkg-config: NO
      Run-time dependency python found: YES 3.11
      Found CMake: /data/data/com.termux/files/usr/bin/cmake (3.29.3)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state
      Run-time dependency frida-core-1.0 found: NO (tried pkgconfig and cmake)
      Looking for a fallback subproject for the dependency frida-core-1.0

      Executing subproject frida-core for machine: host

      frida-core| Program python3 found: YES (/data/data/com.termux/files/usr/bin/python3)
      frida-core| Project name: frida-core
      frida-core| Project version: 16.2.5
      frida-core| C compiler for the host machine: /data/data/com.termux/files/usr/bin/cc -march=armv8-a (clang 18.1.6 "clang version 18.1.6")
      frida-core| C linker for the host machine: /data/data/com.termux/files/usr/bin/cc -march=armv8-a ld.lld 18.1.6
      frida-core| C++ compiler for the host machine: /data/data/com.termux/files/usr/bin/c++ -march=armv8-a (clang 18.1.6 "clang version 18.1.6")
      frida-core| C++ linker for the host machine: /data/data/com.termux/files/usr/bin/c++ -march=armv8-a ld.lld 18.1.6

      subprojects/frida-core/meson.build:1:0: ERROR: Could not execute Vala compiler: /data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257/deps/toolchain-linux-arm64/bin/valac-0.58 --vapidir=/data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257/deps/toolchain-linux-arm64/share/vala-0.58/vapi '--pkg-config=/data/data/com.termux/files/usr/bin/python /data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257/build/frida-pkg-config.py'

      A full log can be found at /data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257/build/meson-logs/meson-log.txt
      Command '['/data/data/com.termux/files/usr/bin/python', '/data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257/releng/meson/meson.py', 'setup', '-Dprefix=/usr/local', '-Ddefault_library=static', '-Doptimization=s', '-Db_ndebug=true', '-Dstrip=true', '--native-file=/data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257/build/frida-linux-arm64.txt', PosixPath('/data/data/com.termux/files/usr/tmp/pip-install-kjuc_0t0/frida_fd40a95a557545ab8dda25b46bdbe257/build')]' returned non-zero exit status 1.
      make: *** [Makefile:4: all] Error 1
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 130, in <module>
        File "<string>", line 18, in main
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/normal/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-yrltu8w_/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 120, in build_extension
        File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for frida
Failed to build frida
ERROR: Could not build wheels for frida, which is required to install pyproject.toml-based projects

**Comment by yazigegeda** [comment]
目前termux内的直接安装frida都会失败

1. apt / pkg install frida-python

会强制安装最新版 python ，而目前termux 的 frida包 
只支持 python3.11 版本，可从 

Setting up frida-python (16.1.1) ...
/data/data/com.termux/files/usr/var/lib/dpkg/info/frida-python.postinst: 2: pip3.11: not found
改文件查看使用pip3.11


2. pip install frida frida-tools  

构建frida的过程中，输出错误信息 需要 vala 0.58 版本，目前termux
安装的只有 vala 0.56版本，不知道是不是这个原因

旧的 
https://github.com/frida/frida/issues/2308 
楼主贴的输出错误信息显示需要 主动下载frida core dev
并 配置 FRIDA_CORE_DEVKIT 路径 才行，现在输出信息明显不一样，等待官方解决


开始教程

先更新下
pkg update -y && pkg upgrade -y && root-repo x11-repo tur-repo


方案一:  使用proot 安装个 Ubuntu ,在里面安装frida，简单快捷，支持最新版frida，缺点套了一层性能可能损耗。



pkg install proot-distro

proot-distro install ubuntu

proot-distro login ubuntu

apt update

apt install python (默认安装好了可以不用)

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

python get-pip.py

pip install frida frida-tools

frida --version


方案二: 直接在termux内安装frida，不过只能安装frida 16.1.1 版本且使用python3.11版本，安装方法有点复杂


假定你已经安装最新版python

pkg remove python3.11 #(需卸载3.11版本没有就不用)

pkg install python #(安装最新版py)

ln -s /data/data/com.termux/files/usr/bin/pip /data/data/com.termux/files/usr/bin/pip3.11

pkg install frida-python

pkg install python3.11

pip3.11 install colorama prompt_toolkit pygments

frida --version
