### ISSUE TITLE
[!] Error: 'StringDecoder' is not exported by

### ISSUE THREAD

**Issue by DeYouOS** [frida/frida#2872]
Linux ***** 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
node -v: v20.14.0
npm -v: 10.7.0

`Already configured. Wipe ./build to reconfigure.
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /home/external/frida/deps/toolchain-linux-x86_64/bin/ninja
[2/149] Generating subprojects/frida-core/src/compiler/frida-compiler-agent with a custom command
FAILED: subprojects/frida-core/src/compiler/agent.js subprojects/frida-core/src/compiler/snapshot.bin 
/usr/bin/python3 ../subprojects/frida-core/src/compiler/generate-agent.py /home/external/frida/build/subprojects/frida-core/src/compiler subprojects/frida-core/src/compiler/agent.js.p /home/external/frida/subprojects/frida-core/src/compiler /usr/bin/npm '' linux arm64 64
Command '[PosixPath('/usr/lib/node_modules/npm/bin/npm-cli.js'), 'run', 'build:agent-core', '--', '--environment', 'FRIDA_HOST_OS_FAMILY:linux,FRIDA_HOST_ARCH:arm64,FRIDA_HOST_CPU_MODE:64', '--silent']' returned non-zero exit status 1.
Output:
        | > frida-compiler-agent@1.0.0 build:agent-core
        | > rollup --config rollup.config.agent-core.ts --configPlugin typescript --environment FRIDA_HOST_OS_FAMILY:linux,FRIDA_HOST_ARCH:arm64,FRIDA_HOST_CPU_MODE:64 --silent
        | 
        | (!) `this` has been rewritten to `undefined`
        | https://rollupjs.org/guide/en/#error-this-is-undefined
        | node_modules/frida-fs/dist/index.js
        | 1: var __classPrivateFieldSet = (this && this.__classPrivateFieldSet) || function (receiver, state, value, kind, f) {
        |                                  ^
        | 2:     if (kind === "m") throw new TypeError("Private method is not writable");
        | 3:     if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a setter");
        | ...and 3 other occurrences
        | (!) Circular dependencies
        | node_modules/@frida/terser/lib/ast.js -> node_modules/@frida/terser/lib/parse.js -> node_modules/@frida/terser/lib/ast.js
        | node_modules/@frida/terser/main.js -> node_modules/@frida/terser/lib/cli.js -> node_modules/@frida/terser/main.js
        | [!] Error: 'StringDecoder' is not exported by ../../../../../../../../node_modules/string_decoder/lib/string_decoder.js, imported by node_modules/@frida/readable-stream/lib/readable.js
        | https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
        | node_modules/@frida/readable-stream/lib/readable.js (40:9)
        | 38: import EE from 'events';
        | 39: import process from 'process';
        | 40: import { StringDecoder } from 'string_decoder';
        |              ^
        | 41: 
        | 42: export default Readable;
        | Error: 'StringDecoder' is not exported by ../../../../../../../../node_modules/string_decoder/lib/string_decoder.js, imported by node_modules/@frida/readable-stream/lib/readable.js
        |     at error (/home/external/frida/build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/rollup/dist/shared/rollup.js:198:30)
        |     at Module.error (/home/external/frida/build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/rollup/dist/shared/rollup.js:12560:16)
        |     at Module.traceVariable (/home/external/frida/build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/rollup/dist/shared/rollup.js:12919:29)
        |     at ModuleScope.findVariable (/home/external/frida/build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/rollup/dist/shared/rollup.js:11571:39)
        |     at FunctionScope.findVariable (/home/external/frida/build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/rollup/dist/shared/rollup.js:6503:38)
        |     at ChildScope.findVariable (/home/external/frida/build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/rollup/dist/shared/rollup.js:6503:38)
        |     at TrackingScope.findVariable (/home/external/frida/build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/rollup/dist/shared/rollup.js:6503:38)
        |     at BlockScope.findVariable (/home/external/frida/build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/rollup/dist/shared/rollup.js:6503:38)
        |     at Identifier.bind (/home/external/frida/build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/rollup/dist/shared/rollup.js:7570:40)
        |     at NewExpression.bind (/home/external/frida/build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/rollup/dist/shared/rollup.js:5400:23)
[3/149] Generating subprojects/frida-gum/bindings/gumjs/gumjs-runtime with a custom command
ninja: build stopped: subcommand failed.
Command '['/usr/bin/python3', '/home/external/frida/releng/meson/meson.py', 'compile']' returned non-zero exit status 1.
make: *** [Makefile:4：all] 错误 1`

**Comment by 5andr0** [comment]
Bump! Can someone please post a solution?
the string_decoder package is installed in @frida. So it must be a pathing issue with the ../../../../../../../../
Just no idea how to solve it

**Comment by EsmaeelNabil** [comment]
Edit `build/subprojects/frida-core/src/compiler/agent.js.p/node_modules/@frida/readable-stream/lib/readable.js`

from this 
```javascript
import { StringDecoder } from 'string_decoder';
```


to:
```javascript
import * as stringDecoder from 'string_decoder';
const { StringDecoder } = stringDecoder;
```
