### ISSUE TITLE
Frida-server on Android 15 is not working

### ISSUE THREAD

**Issue by RomashkaTea** [frida/frida#2894]
Logs:
`Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
{"type":"error","description":"TypeError: t is not a function","stack":"TypeError: t is not a function\n    at frida/node_modules/frida-java-bridge/lib/android.js:1591:1\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:113:1\n    at CallbackContext.kt (frida/node_modules/frida-java-bridge/lib/android.js:586:1)\n    at NativeFunction.<anonymous> (<anonymous>)\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1591,"columnNumber":1}`
Android 15 beta 3, Pixel 7 Pro, frida-server 16.3.3

**Comment by Rycoh99** [comment]
Hi! Did you manage to fix this? Seems to be broken on A14 QPR2/AP2A as well, the error is very similar.

**Comment by githubZpp** [comment]
Android 15 V version，start /data/local/tmp/frida-server error:

 `{"type":"error","description":"TypeError: t is not a function","stack":"TypeError: t is not a function\n    at frida/node_modules/frida-java-bridge/lib/android.js:1591:1\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:113:1\n    at CallbackContext.kt (frida/node_modules/frida-java-bridge/lib/android.js:586:1)\n    at NativeFunction.<anonymous> (<anonymous>)\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1591,"columnNumber":1}
{"type":"error","description":"TypeError: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')\n    at F.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1018:1)\n    at F.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1034:1)\n    at Object.get (frida/node_modules/frida-java-bridge/lib/class-factory.js:746:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/class-factory.js","lineNumber":1018,"columnNumber":1}`

**Comment by NgoHuy** [comment]
it's same as #2851

**Comment by amao12580** [comment]
same issue with pixel 8 pro,the frida version is frida-server-17.2.11-android-arm64

**Comment by imb4dm4n** [comment]
I thought they fixed an old bug in higher version of frida. But it turns out that this bug still exists.
My pixel 6 pro on Android 15 was unable to run frida normally until I run this command "pm uninstall com.google.android.art"

**Comment by enovella** [comment]
Which Frida version are you on?

**Comment by BreezeSun** [comment]
This problem has been solved,executive command "pm uninstall com.google.android.art",Then restart the mobile phone.

**Comment by all3njk** [comment]
Just use Frida version 17. I don't understand why people are deleting ART.

**Comment by M0hmedGamal** [comment]
Just use the frida version 17.x.x I use frida 17.6.2
