### ISSUE TITLE
[bug] frida.InvalidOperationError: script has been destroyed

### ISSUE THREAD

**Issue by vladavoX** [frida/frida#2897]
- Please, fill in all of the sections in this template.
- Please read each section carefully. Each has a description of what information will help.
- Windows support is limited. There is a good chance that a pull request would help!
- The more information you give, the better.
- Remove this section when you are done.

**Describe the bug**
Tried on other apps, that are found by `frida-ps -Uai`, only this one fails

```
D:\Program Files\Nox\bin>frida-ps -Uai
 PID  Name               Identifier
----  -----------------  -----------------------------
2420  Facebook           com.facebook.katana
3306  Google Play Store  com.android.vending
   -  Amaze              com.amaze.filemanager
   -  App Center         com.android.Calendar
   -  Browser            com.android.browser
   -  Camera             com.android.camera2
   -  Files              com.android.documentsui
   -  Gallery            com.android.gallery3d
   -  Google Play Games  com.google.android.play.games
   -  GoogleSign         com.pekall.fmradio
   -  Rumble             com.blizzard.arc
   -  Settings           com.android.settings
   -  Tutorials          com.android.calculator2

D:\Program Files\Nox\bin>objection --gadget com.blizzard.arc explore
Using USB device `SM-G965N`
Agent injected and responds ok!
Traceback (most recent call last):
  File "\\?\C:\Users\voX\AppData\Local\Programs\Python\Python37-32\Scripts\objection-script.py", line 33, in <module>
    sys.exit(load_entry_point('objection==1.11.0', 'console_scripts', 'objection')())
  File "c:\users\vox\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\vox\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\users\vox\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\vox\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\vox\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\vox\appdata\local\programs\python\python37-32\lib\site-packages\objection\console\cli.py", line 156, in explore
    device_info = get_device_info()
  File "c:\users\vox\appdata\local\programs\python\python37-32\lib\site-packages\objection\commands\device.py", line 41, in get_device_info
    package_info = api.env_android()
  File "c:\users\vox\appdata\local\programs\python\python37-32\lib\site-packages\frida\core.py", line 180, in method
    return script._rpc_request(request, data, **kwargs)
  File "c:\users\vox\appdata\local\programs\python\python37-32\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "c:\users\vox\appdata\local\programs\python\python37-32\lib\site-packages\frida\core.py", line 497, in _rpc_request
    raise result.error
frida.InvalidOperationError: script has been destroyed
Asking jobs to stop...
Unloading objection agent...
Unable to run cleanups: script is destroyed
```
**To Reproduce**
1. Run command 'objection --gadget com.blizzard.arc explore'

**Expected behavior**
To enter explore

**Evidence / Logs / Screenshots**
Any output from objection, such as stack traces or errors that occurred. Be sure to run objection with the `--debug` flag so that errors from the agent are verbose enough to debug. For example:

```text
objection --debug explore
```

**Environment (please complete the following information):**
 - Device: Nox emular
 - OS: Android 9(64 bit)
 - Frida Version 16.3.3
- Objection Version 1.11.0

**Application**
If possible, please attach the target application where you can reproduce this bug to the issue.

**Additional context**

**Comment by antoinechauvn** [comment]
Same problem here

**Comment by zakodai** [comment]
same problem here

**Comment by vnBa0** [comment]
same problem here

**Comment by fudgebucket27** [comment]
getting this too

**Comment by Abhinandan-Khurana** [comment]
Try downgrading frida version to `16.5.2`, this works for me.

- tested with objection version `1.11.0`
- tested on mac arm64 and ubuntu amd64
- tested on iOS and Android both (arm64)

**Comment by saurabhcnigam** [comment]
Okay, so I also have been encountering this issue. There were few things I was doing wrong, and few things i dint knew.
* on jailbroken phone you do not need to patch the application either via objection or manually
* use altstore or sideloadly to install the IPA file
* if using bundle id, objection crashes, try using process id, for that you would need to manually invoke the app
* I have not figured out what if app does JB detection and closes before my objection can connect to it (No PID scenario)
* I use virtual python environment and following versions. 

```
(ios_lab) ios_lab ❯ python3 --version
Python 3.11.10
(ios_lab) ios_lab ❯ frida --version
16.7.4
(ios_lab) ios_lab ❯ objection version
objection: 1.11.0
```

**Comment by sudosuraj** [comment]
Instead of:
```
> objection -g com.myapp.mobile
```


Just do:
```
 > frida-ps -Uai
 PID  Name          Identifier
----  ------------  ---------------------------
1337  MyApp      com.myapp.mobile
```

```
> objection -g 1337 explore
```

**Comment by elcaza** [comment]
@sudosuraj thanks Bro, that was really helpful!

Some applications close  when you open them (usually because they detect the jailbreak), so we couldn't get a PID.

Do you happen to know of a solution to this problem?

==========================================================

## Update, auto reply: 

As @Abhinandan-Khurana  mentioned, you can install Frida version 16.5.2.

~~~bash
pip install frida==16.5.2 frida-tools objection
~~~

The following post explains it very well:

https://infosecwriteups.com/the-frida-objection-setup-guide-solving-version-hell-on-android-ios-timeless-guide-f55eb98459a0

Thanks guys.

==========================================================

## Final notes:

If you are running Frida 16.7.19 
~~~bash
objection -g PID explore
# It works

objection -g com.myapp.mobile explore
# It don't works
~~~

If you are running Frida 16.5.2
~~~bash
objection -g PID explore
# It don't works

objection -g com.myapp.mobile explore
# It  works
~~~
