### ISSUE TITLE
ModuleNotFoundError: No module named '_frida'

### ISSUE THREAD

**Issue by nachtigall18** [frida/frida#2924]
Hi all, recently I faced with the Frida. After installing a new version, I have received this error on my MAC OS:

Traceback (most recent call last):
  File "/Users/test/Library/Python/3.11/bin/frida", line 5, in <module>
    from frida_tools.repl import main
  File "/Users/test/Library/Python/3.11/lib/python/site-packages/frida_tools/repl.py", line 31, in <module>
    from frida_tools.application import ConsoleApplication
  File "/Users/test/Library/Python/3.11/lib/python/site-packages/frida_tools/application.py", line 17, in <module>
    import _frida
ModuleNotFoundError: No module named '_frida'

Do you know how I can solve this problem? Please help

My version of Python and pip:
pip 24.1.2 
Python 3.11.9

**Comment by kyle-lu** [comment]
frida-tools 12.3.0 + frida 16.2.1 seem to work.
`pip install frida==16.2.1 frida-tools==12.3.0`

**Comment by nclman** [comment]
Seeing the same issue with frida-tools 13.3.0.
But 13.2.1 doesn't have this problem.

**Comment by baptx** [comment]
Why are there still new Frida releases with this issue? It means some people creating releases don't have this issue and they have a solution for the latest version? @oleavr

**Comment by r1nzleer** [comment]
thank you so much, definitely that version works better "pip install frida==16.2.1 frida-tools==12.3.0"

**Comment by moinkrain** [comment]
Thank you so much,I encountered the same problem, and I was able to use it after trying your method. Also, may I ask if this version is compatible with Android 9?

**Comment by jirka-oone** [comment]
`pip install --upgrade frida-tools` works for me
`frida --version`
17.4.0
`pip show frida-tools`
Name: frida-tools
Version: 14.4.5

**Comment by moinkrain** [comment]
What is the version of frida-tools?
