### ISSUE TITLE
Issue when using frida-server-16.4.X-android-arm64

### ISSUE THREAD

**Issue by orelamihay86** [frida/frida#2941]
Hello guys!
so suddenly today Frida got crazy, when I start the Frida server on my OnePlus device (Oneplus 10 T 5G) it gave me an error message.
I used :
frida-server-16.4.7-android-arm64
And when I noticed the error I update to:
frida-server-16.4.8-android-arm64

This is the error please help!

`./frida-server-16.4.8-android-arm64
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}`

**Comment by SeelAlfrado** [comment]
I have the same Issue
tried to upgrade from frida-server 16.4.8 -> 16.4.9 arm64 on Pixel7
nothing worked

**Comment by pig837** [comment]
Try reboot, No problem on Pixel 6 Pro. (Frida 16.4.9, Pixel 6 Pro, Android 14, KernelSU 1.0.1)

Try reboot your device. That error is a classic bug that occurs after using Frida for a long time.

**Comment by xchopath** [comment]
Hi @pig837 

I have rebooted, but it still happens.

**Comment by pig837** [comment]
> Hi @pig837
> 
> I have rebooted the device, but it still happens.

I'm not sure, but if you're using a Magisk module or KernelSU module that affects hooking, try deleting it.

Of course, in some cases it may affect it permanently, so you may need to reset the device with Fastboot or ODIN and then root it again.

I just tested it again and it's still working fine.

**Comment by Rat4er** [comment]
Same issue on Pixel 7, removing all modules from magisk and upgrading the firmware did not fix it

**Comment by user154lt** [comment]
Having the same problem with version 16.14.10 on a Pixel 3 running Android 12. Rooted with Magisk but have never had any modules installed. Have tried rebooting the device to no avail. The only thing that has changed with the device is an update to Google Play Services. My device updated to version 25.31.37 on 17/08/24 which is in between when it was last working and now.

**Comment by MrFireFrog** [comment]
Are there any solutions to this problem?

**Comment by pig837** [comment]
> Having the same problem with version 16.14.10 on a Pixel 3 running Android 12. Rooted with Magisk but have never had any modules installed. Have tried rebooting the device to no avail. The only thing that has changed with the device is an update to Google Play Services. My device updated to version 25.31.37 on 17/08/24 which is in between when it was last working and now.
> 
> Update:
> 
> I got round to testing my theory today, I am not sure if it is Google Play Services specifically but in my case this error definitely seems to be related to the Aug 2024 Play System update. I reset the device by flashing a factory image and everything was working fine. I then installed the play system update, rebooted the device, and was presented with this error again upon trying to start the server on the device.

Yeah, yI think what you said is correct.

* Workaround: DO NOT UPDATE "Google Play System Update" until this issue is fixed

**Comment by user154lt** [comment]
> > Having the same problem with version 16.14.10 on a Pixel 3 running Android 12. Rooted with Magisk but have never had any modules installed. Have tried rebooting the device to no avail. The only thing that has changed with the device is an update to Google Play Services. My device updated to version 25.31.37 on 17/08/24 which is in between when it was last working and now.
> > Update:
> > I got round to testing my theory today, I am not sure if it is Google Play Services specifically but in my case this error definitely seems to be related to the Aug 2024 Play System update. I reset the device by flashing a factory image and everything was working fine. I then installed the play system update, rebooted the device, and was presented with this error again upon trying to start the server on the device.
> 
> Yeah, I think what you said is correct. I tried to update "Google Play System Update" on today, thus frida is broken.
> 
>     * Workaround: DO NOT UPDATE "Google Play System Update" until this issue is fixed
> 
> 
> `{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n at frida/node_modules/frida-java-bridge/index.js:224:1\n at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}`


Thanks for confirming, I'll be sure not to install the latest Play System update for the foreseeable.

**Comment by pig837** [comment]
> > > Having the same problem with version 16.14.10 on a Pixel 3 running Android 12. Rooted with Magisk but have never had any modules installed. Have tried rebooting the device to no avail. The only thing that has changed with the device is an update to Google Play Services. My device updated to version 25.31.37 on 17/08/24 which is in between when it was last working and now.
> > > Update:
> > > I got round to testing my theory today, I am not sure if it is Google Play Services specifically but in my case this error definitely seems to be related to the Aug 2024 Play System update. I reset the device by flashing a factory image and everything was working fine. I then installed the play system update, rebooted the device, and was presented with this error again upon trying to start the server on the device.
> > 
> > 
> > Yeah, I think what you said is correct. I tried to update "Google Play System Update" on today, thus frida is broken.
> > ```
> > * Workaround: DO NOT UPDATE "Google Play System Update" until this issue is fixed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n at frida/node_modules/frida-java-bridge/index.js:224:1\n at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}`
> 
> Thanks for confirming, I'll be sure not to install the latest Play System update for the foreseeable.

FYI:
https://github.com/frida/frida/issues/2958#issuecomment-2329917110

**Comment by user154lt** [comment]
> > > > Having the same problem with version 16.14.10 on a Pixel 3 running Android 12. Rooted with Magisk but have never had any modules installed. Have tried rebooting the device to no avail. The only thing that has changed with the device is an update to Google Play Services. My device updated to version 25.31.37 on 17/08/24 which is in between when it was last working and now.
> > > > Update:
> > > > I got round to testing my theory today, I am not sure if it is Google Play Services specifically but in my case this error definitely seems to be related to the Aug 2024 Play System update. I reset the device by flashing a factory image and everything was working fine. I then installed the play system update, rebooted the device, and was presented with this error again upon trying to start the server on the device.
> > > 
> > > 
> > > Yeah, I think what you said is correct. I tried to update "Google Play System Update" on today, thus frida is broken.
> > > ```
> > > * Workaround: DO NOT UPDATE "Google Play System Update" until this issue is fixed
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n at frida/node_modules/frida-java-bridge/index.js:224:1\n at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}`
> > 
> > 
> > Thanks for confirming, I'll be sure not to install the latest Play System update for the foreseeable.
> 
> I found another workaround.
> 
> FYI: [#2958 (comment)](https://github.com/frida/frida/issues/2958#issuecomment-2329917110)

Thank you, I hadn't noticed  that. I will give it a try later.
