### ISSUE TITLE
Android 14 Crash / Reboot while spawning applications

### ISSUE THREAD

**Issue by MrOplus** [frida/frida#2956]
Stack Trace : 
Frida Server Booting Error : 
```
{
  "type": "error",
  "description": "Error: libart.so: unable to find export '_ZNK3art2gc4Heap15MayUseCollectorENS0_13CollectorTypeE'",
  "stack": "Error: libart.so: unable to find export '_ZNK3art2gc4Heap15MayUseCollectorENS0_13CollectorTypeE'\n    at Function.value [as getExportByName] (frida/runtime/core.js:250:1)\n    at Ft (frida/node_modules/frida-java-bridge/lib/android.js:837:1)\n    at Tt (frida/node_modules/frida-java-bridge/lib/android.js:762:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1331:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1189:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1103:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)",
  "fileName": "frida/runtime/core.js",
  "lineNumber": 250,
  "columnNumber": 1
}
```
After Spawning Applications : 
```
{
  "type": "error",
  "description": "Error: invalid address",
  "stack": "Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:207:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1215:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1281:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1329:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1189:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1103:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)",
  "fileName": "frida/runtime/core.js",
  "lineNumber": 207,
  "columnNumber": 1
}
```
It seems [Frida Java Bridge](https://github.com/frida/frida-java-bridge/blob/a3b0de51451dd38e9dfcbaa1fbc744745bab9579/lib/android.js#L1898) cannot find _ZNK3art2gc4Heap15MayUseCollectorENS0_13CollectorTypeE in `libart.so` for some reasons.

Frida Server Version : frida-server-16.4.10-android-arm64. 
Frida PIP Version : 16.4.10
Android Build Number : sdk_gphone64_arm64-userdebug VanillaIceCream AP31.240426.022.B1 11834390 dev-keys

**Comment by cryptoexpertssss** [comment]
![image](https://github.com/user-attachments/assets/738d83f8-ab12-44d3-a45f-d0ec630f1e29)
![image](https://github.com/user-attachments/assets/42262b24-c693-4ecc-adbb-51ed05fdbc37)


Same Issur. . .  help me

**Comment by VendorAttestation** [comment]
Same Issue

**Comment by devnoname120** [comment]
Duplicate of: https://github.com/frida/frida/issues/2851
