### ISSUE TITLE
Failed to enumerate processes: cannot read properties of undefined (reading 'getRunningAppProcesses')

### ISSUE THREAD

**Issue by chihaamin** [frida/frida#2960]
whenever I try to run frida with 
$ frida-ps -U 
I get this error "Failed to enumerate processes: cannot read properties of undefined (reading 'getRunningAppProcesses')"
I can't spawn process or interact with the devices

**Comment by neryaz** [comment]
> whenever I try to run frida with $ frida-ps -U I get this error "Failed to enumerate processes: cannot read properties of undefined (reading 'getRunningAppProcesses')" I can't spawn process or interact with the devices

Take a look [here](https://github.com/frida/frida/issues/2958#issuecomment-2329917110)

**Comment by wAnFen1017** [comment]
```
pm uninstall com.google.android.art
reboot
```

**Comment by markcunninghamgit** [comment]
> ```
> pm uninstall com.google.android.art
> reboot
> ```

Can you give some more feedback on how this was discovered and why it works? I started getting the error seen above along with this
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}

without making any updates to frida recently. Uninstalling the com.google.android.art works though but I'd like to know why this suddenly started occurring and more about com.google.android.art's interaction

**Comment by mostwanted002** [comment]
Facing same issue on LineageOS, and the package `com.google.android.art` doesn't exist.

**Comment by wAnFen1017** [comment]
I’m not sure why either. I just happened to find that uninstalling com.google.android.art works. My Android version is 8.1. If anyone figures out the reason, please @ me. Thanks! 🙏

**Comment by typefe** [comment]
> I don't even have `com.google.android.art` on Android - Google Pixel 7a.

Same here, I don't have installed `com.google.android.art`.

Android 12 arm64, latest frida server. Any solution except removing the art?

**Comment by QRussia** [comment]
Hi. I have same problem, device with arm64 - Xiaomi Redmi 9T, Android 12.

**Comment by IlnazMan** [comment]
Hi. I have same problem, device with arm64 - Xiaomi Redmi 9T, Android 12.

**Comment by MostafaAshry513** [comment]
Same here
android 11, arm
infinix smart 5 x657b
and i don't have com.google.android.art
