### ISSUE TITLE
frida tells me to file a bug: Error: Unable to perform state transition; please file a bug

### ISSUE THREAD

**Issue by zzhichen** [frida/frida#2971]
when use frida to hook an app in OnePlus Nord CE3 5G, android version is 14, OxygenOS14.0 with command: 
frida -U -f com.gl.test  -l hook.js

frida shows:
   . . . .   Connected to CPH2569 (id=ea0bc24)
Failed to spawn: unexpectedly timed out while waiting for signal from process with PID 23273

the frida server shows below content(after format):
{
    "type": "error",
    "description": "Error: Unable to perform state transition; please file a bug",
    "stack": "Error: Unable to perform state transition; please file a bug\n    
	at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    
	at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    
	at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    
	at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    
	at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    
	at frida/node_modules/frida-java-bridge/index.js:224:1\n    
	at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    
	at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    
	at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    
	at /internal-agent.js:490:6",
    "fileName": "frida/node_modules/frida-java-bridge/lib/android.js",
    "lineNumber": 578,
    "columnNumber": 1
}

**Comment by pig837** [comment]
https://github.com/frida/frida/issues/2958

**Comment by Olegt0rr** [comment]
Workaround: https://github.com/frida/frida/issues/2037#issuecomment-2317730036
