### ISSUE TITLE
Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!

### ISSUE THREAD

**Issue by fuomag9** [frida/frida#2982]
Android 15 android studio emulator

```
(base) ➜  ~  adb root
restarting adbd as root
(base) ➜  ~  ~/Downloads
(base) ➜  Downloads  adb push frida-server /data/local/tmp/
frida-server: 1 file pushed, 0 skipped. 331.8 MB/s (56524280 bytes in 0.162s)
(base) ➜  Downloads  adb shell "chmod 755 /data/local/tmp/frida-server"
(base) ➜  Downloads  adb shell "/data/local/tmp/frida-server &"
Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}
```

**Comment by pig837** [comment]
https://github.com/frida/frida/issues/2958

**Comment by flamecopper** [comment]
luejay:/data/adb # Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!

Android 16, Pixel &a, tried to uninstall com.android.art but failed

**Comment by Hrushikraj** [comment]
> luejay:/data/adb # Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug! Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug! Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
> 
> Android 16, Pixel &a, tried to uninstall com.android.art but failed

Just disable the Play Store, force stop it, then reboot the device and try again. It worked for me.

Android 16, pixel 6a

**Comment by suryasarisa99** [comment]
> 
> Just disable the Play Store, force stop it, then reboot the device and try again. It worked for me.
> 

- this not works for me on android 16, still same error

**Comment by Zaykus** [comment]
## same here

adb shell su -c "/data/local/tmp/frida-server &"

Unexpectedly timed out while waiting for syscall on android.anim thread; please file a bug!

Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!

Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!

{"type":"error","description":"Error: Unable to find copied methods in java/lang/Thread; please file a bug","stack":"Error: Unable to find copied methods in java/lang/Thread; please file a bug\n    at /internal-agent.js:1:47232\n    at Ie.perform (/internal-agent.js:1:25891)\n    at Gn (/internal-agent.js:1:45951)\n    at Md (/internal-agent.js:1827:1640)\n    at Uo (/internal-agent.js:1827:1258)\n    at Function.build (/internal-agent.js:1827:85)\n    at t._make (/internal-agent.js:1828:18234)\n    at t.use (/internal-agent.js:1828:17033)\n    at /internal-agent.js:1837:6963\n    at Ie.perform (/internal-agent.js:1:25891)","fileName":"/internal-agent.js","lineNumber":1,"columnNumber":47232} 

A16, qr1, AOSP

**Comment by ckcr4lyf** [comment]
> > luejay:/data/adb # Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug! Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug! Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
> > Android 16, Pixel &a, tried to uninstall com.android.art but failed
> 
> Just disable the Play Store, force stop it, then reboot the device and try again. It worked for me.
> 
> Android 16, pixel 6a

Does not work for me, Also Pixel 6a + Android 16 (Nov 2025 security update).

Which frida are you using? I'm on 17.5.1

**Comment by Hrushikraj** [comment]
**Solution:**
I faced the same issue recently and found a working solution.
Run the following commands inside adb shell:

```
pm uninstall com.google.android.art
reboot
```
After uninstalling this package and rebooting the device, Frida started working correctly.

I am currently using Frida 17.2.17 on a Pixel 6a running Android 16.

**Comment by Hrushikraj** [comment]
> > > luejay:/data/adb # Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug! Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug! Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
> > > Android 16, Pixel &a, tried to uninstall com.android.art but failed
> > 
> > 
> > Just disable the Play Store, force stop it, then reboot the device and try again. It worked for me.
> > Android 16, pixel 6a
> 
> Does not work for me, Also Pixel 6a + Android 16 (Nov 2025 security update).
> 
> Which frida are you using? I'm on 17.5.1

https://github.com/frida/frida/issues/2982#issuecomment-3741913317
