### ISSUE TITLE
frida.TransportError: the connection is closed

### ISSUE THREAD

**Issue by henryhoang92** [frida/frida#303]
Traceback (most recent call last):
  File "D:/source/python/tracking_tools/Tracking.py", line 6, in <module>
    pid = device.spawn(["the.unamed.app"])
  File "C:\Users\Gigabyte\AppData\Roaming\Python\Python27\site-packages\frida\core.py", line 85, in spawn
    return self._impl.spawn(argv)
frida.TransportError: the connection is closed

**Comment by pickastar** [comment]
I ran into the same,,

**Comment by leiyugithub** [comment]
have you  solved this problem? i got  same with you

**Comment by RonaldinhoL** [comment]
got the same problem, android 10 pixel
