### ISSUE TITLE
unable to find process with name 'zygote'

### ISSUE THREAD

**Issue by henryhoang92** [frida/frida#304]
Traceback (most recent call last):
  File "D:/source/python/tracking_tools/Tracking.py", line 5, in <module>
    pid = device.spawn(["com.pppp"])
  File "C:\Users\Gigabyte\AppData\Roaming\Python\Python27\site-packages\frida\core.py", line 85, in spawn
    return self._impl.spawn(argv)
frida.ProcessNotFoundError: unable to find process with name 'zygote'

**Comment by henryhoang92** [comment]
I was test with last version 10.3.0. It's occur this error

**Comment by lee5783** [comment]
I got same error message with 10.7.7 and 10.7.6 version
Im using Android 4.4.2 x86 image (on Bluestacks)
