### ISSUE TITLE
Issue in initializing in android device Android 14 [Rooted]

### ISSUE THREAD

**Issue by shivvrat12** [frida/frida#3167]
Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
Unexpectedly timed out while waiting for syscall on NetworkPolicy thread; please file a bug!
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}

**Comment by pig837** [comment]
https://github.com/frida/frida/issues/2958
