### ISSUE TITLE
Genymotion Android 4.4.4 x86, Process terminated

### ISSUE THREAD

**Issue by dPhoeniixx** [frida/frida#318]
when run this code
```python
import frida,sys
 
def print_result(message):
            print("[*] Decrypting AES %s" %(message))
 
def on_message(message, data):
            # print_result(message['payload'])
            # print "%s" %(message)
            print("[*] {0}".format(message))

# Has errors, not sure why.

jscode = """
Java.perform(function () {

    var c = Java.use("kr.repo.h2spice.yekehtmai.c")
    c.a.implementation = function (str1, str2) {
        
        send("String1: " + str1)
        send("String2: " + str2)
        this.onResume();

    }
    
});

"""
 
process = frida.get_usb_device(1).attach("kr.repo.h2spice.yekehtmai")
 
script = process.create_script(jscode)
script.on('message', on_message)
 
print("[*] Decrypting AES Key")
 
script.load()
sys.stdin.read()
```
but when run this code kr.repo.h2spice.yekehtmai app crash !
logcat
```php
--------- beginning of /dev/log/main
D/dalvikvm( 3558): GC_CONCURRENT freed 139K, 6% free 3103K/3296K, paused 0ms+1ms, total 2ms
D/dalvikvm( 3558): GC_FOR_ALLOC freed 89K, 5% free 3274K/3436K, paused 1ms, total 1ms
I/dalvikvm-heap( 3558): Grow heap (frag case) to 4.323MB for 1127532-byte allocation
--------- beginning of /dev/log/system
W/genymotion_audio(  368): out_write() limiting sleep time 46802 to 39909
D/dalvikvm( 3558): GC_CONCURRENT freed 1K, 4% free 4373K/4540K, paused 0ms+0ms, total 2ms
D/dalvikvm( 3558): WAIT_FOR_CONCURRENT_GC blocked 2ms
E/dalvikvm( 3558): VM aborting
F/libc    ( 3558): Fatal signal 6 (SIGABRT) at 0x00000de6 (code=-6), thread 3601 (Thread-186)
W/EGL_genymotion( 3558): eglSurfaceAttrib not implemented
I/DEBUG   ( 3098): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 3098): Build fingerprint: 'generic/vbox86p/vbox86p:4.4.4/KTU84P/eng.genymotion.20170320.221842:userdebug/test-keys'
I/DEBUG   ( 3098): Revision: '0'
I/DEBUG   ( 3098): pid: 3558, tid: 3601, name: Thread-186  >>> kr.repo.h2spice.yekehtmai <<<
I/DEBUG   ( 3098): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
I/DEBUG   ( 3098):     eax 00000000  ebx 00000de6  ecx 00000e11  edx 00000006
I/DEBUG   ( 3098):     esi 00000e11  edi 00000002
I/DEBUG   ( 3098):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
I/DEBUG   ( 3098):     eip b76a4df6  ebp b7709ce0  esp 92481754  flags 00200203
I/DEBUG   ( 3098):
I/DEBUG   ( 3098): backtrace:
I/DEBUG   ( 3098):     #00  pc 0003bdf6  /system/lib/libc.so (tgkill+22)
I/DEBUG   ( 3098):     #01  pc 00000005  <unknown>
I/DEBUG   ( 3098):
I/DEBUG   ( 3098): stack:
I/DEBUG   ( 3098):          92481714  00000000
I/DEBUG   ( 3098):          92481718  b7705268  /system/lib/libc.so
I/DEBUG   ( 3098):          9248171c  00000000
I/DEBUG   ( 3098):          92481720  b7676f79  /system/lib/libc.so (pthread_mutex_unlock+25)
I/DEBUG   ( 3098):          92481724  b770518c  /system/lib/libc.so
I/DEBUG   ( 3098):          92481728  b8b55620  [heap]
I/DEBUG   ( 3098):          9248172c  00000015
I/DEBUG   ( 3098):          92481730  00000000
I/DEBUG   ( 3098):          92481734  00000000
I/DEBUG   ( 3098):          92481738  b76c3846  /system/lib/libc.so
I/DEBUG   ( 3098):          9248173c  b7704fcc  /system/lib/libc.so
I/DEBUG   ( 3098):          92481740  46505845
I/DEBUG   ( 3098):          92481744  00000000
I/DEBUG   ( 3098):          92481748  00000000
I/DEBUG   ( 3098):          9248174c  b7676da9  /system/lib/libc.so (pthread_mutex_lock+9)
I/DEBUG   ( 3098):          92481750  b7704fcc  /system/lib/libc.so
I/DEBUG   ( 3098):     #00  92481754  00000006
I/DEBUG   ( 3098):          92481758  00000e11
I/DEBUG   ( 3098):          9248175c  b7704fcc  /system/lib/libc.so
I/DEBUG   ( 3098):          92481760  b7681556  /system/lib/libc.so (pthread_kill+102)
I/DEBUG   ( 3098):          92481764  00000de6
I/DEBUG   ( 3098):          92481768  00000e11
I/DEBUG   ( 3098):          9248176c  00000006
I/DEBUG   ( 3098):          92481770  00000000
I/DEBUG   ( 3098):          92481774  b7705268  /system/lib/libc.so
I/DEBUG   ( 3098):          92481778  00000000
I/DEBUG   ( 3098):          9248177c  b76814f9  /system/lib/libc.so (pthread_kill+9)
I/DEBUG   ( 3098):          92481780  b7704fcc  /system/lib/libc.so
I/DEBUG   ( 3098):          92481784  924817d0  [stack:3601]
I/DEBUG   ( 3098):          92481788  92481a10  [stack:3601]
I/DEBUG   ( 3098):          9248178c  92481a38  [stack:3601]
I/DEBUG   ( 3098):          92481790  b768191c  /system/lib/libc.so (raise+44)
I/BootReceiver(  696): Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
W/ActivityManager(  696):   Force finishing activity kr.repo.h2spice.yekehtmai/.MainActivity
D/        (  696): HostConnection::get() New Host Connection established 0xb8d0be98, tid 3605
W/InputDispatcher(  696): channel '52991d68 kr.repo.h2spice.yekehtmai/kr.repo.h2spice.yekehtmai.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  696): channel '52991d68 kr.repo.h2spice.yekehtmai/kr.repo.h2spice.yekehtmai.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  696): channel '52aae848 kr.repo.h2spice.yekehtmai/kr.repo.h2spice.yekehtmai.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  696): channel '52aae848 kr.repo.h2spice.yekehtmai/kr.repo.h2spice.yekehtmai.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
D/Zygote  (  367): Process 3558 terminated by signal (6)
W/InputDispatcher(  696): Attempted to unregister already unregistered input channel '52991d68 kr.repo.h2spice.yekehtmai/kr.repo.h2spice.yekehtmai.MainActivity (server)'
W/InputDispatcher(  696): Attempted to unregister already unregistered input channel '52aae848 kr.repo.h2spice.yekehtmai/kr.repo.h2spice.yekehtmai.MainActivity (server)'
I/WindowState(  696): WIN DEATH: Window{52991d68 u0 kr.repo.h2spice.yekehtmai/kr.repo.h2spice.yekehtmai.MainActivity}
I/WindowState(  696): WIN DEATH: Window{52aae848 u0 kr.repo.h2spice.yekehtmai/kr.repo.h2spice.yekehtmai.MainActivity}
D/dalvikvm(  696): GC_FOR_ALLOC freed 2324K, 47% free 12969K/24116K, paused 7ms, total 7ms
W/ActivityManager(  696): Exception thrown during pause
W/ActivityManager(  696): android.os.DeadObjectException
W/ActivityManager(  696):       at android.os.BinderProxy.transact(Native Method)
W/ActivityManager(  696):       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
W/ActivityManager(  696):       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
W/ActivityManager(  696):       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2443)
W/ActivityManager(  696):       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2320)
W/ActivityManager(  696):       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2050)
W/ActivityManager(  696):       at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9548)
W/ActivityManager(  696):       at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9441)
W/ActivityManager(  696):       at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10086)
W/ActivityManager(  696):       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9637)
W/ActivityManager(  696):       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
I/ActivityManager(  696): Process kr.repo.h2spice.yekehtmai (pid 3558) has died.
W/EGL_genymotion(  898): eglSurfaceAttrib not implemented
```
sorry for my basic english :(

**Comment by erik-smit** [comment]
Frida also has trouble with Android/x86 on Android 5.1.
I don't know if this problem is related, but as an alternative, you could try installing Android Studio, and simulating an Android/ARM device there.
Frida works fine with that.

**Comment by dPhoeniixx** [comment]
@erik-smit 
work fine with android arm, but android arm so slow 😢

**Comment by oleavr** [comment]
Fixed in 10.6.12. Cheers!

**Comment by Sankalp-bst** [comment]
Hello @oleavr ,
I am facing same issue while hooking android function. I am using frida version 10.6.52 . Working fine in ARM devices. Can you help me to solve this issue please.

Thanks.

**Comment by oleavr** [comment]
@Sankalp-bst I'm afraid I won't have time to look into this anytime soon. Help appreciated!
