### ISSUE TITLE
frida.ServerNotRunningError: unable to connect to remote frida-server

### ISSUE THREAD

**Issue by ChengChengCC** [frida/frida#319]
use 'firda-ps' command is OK.
but when I use "python trace.py"
` python trace.py 
Traceback (most recent call last):
  File "trace.py", line 5, in <module>
    session = rdev.attach("com.example.cc.loadso")
  File "/Library/Python/2.7/site-packages/frida/core.py", line 97, in attach
    return Session(self._impl.attach(self._pid_of(target)))
  File "/Library/Python/2.7/site-packages/frida/core.py", line 115, in _pid_of
    return self.get_process(target).pid
  File "/Library/Python/2.7/site-packages/frida/core.py", line 67, in get_process
    matching = [process for process in self._impl.enumerate_processes() if fnmatch.fnmatchcase(process.name.lower(), process_name_lc)]
frida.ServerNotRunningError: unable to connect to remote frida-server`
the trace.py is 

import frida
rdev = frida.get_remote_device()
processes = rdev.enumerate_processes()
for process in processes:
    print process

**Comment by ChengChengCC** [comment]
oh ,I have resolved it. just use
 `adb forward tcp:27042 tcp:27042`
