### ISSUE TITLE
Failed to install the old version of Frida on Kali (12.1.1 or 12.8.20)

### ISSUE THREAD

**Issue by gnmmdk** [frida/frida#3252]
I can download the latest Frida using pip install Frida tools, but I want to download the available Frida version for Android 10, so I need to download an earlier Frida version.
The installation using Python 3.7.17 reported the following error. This is probably an issue with the installation version being too old, but as a novice on Linux systems, I don't know how to solve it.

┌──(root㉿kali)-[~/Desktop]
└─# pip install frida==12.1.1
Collecting frida==12.1.1
Using cached frida-12.1.1.tar.gz (6.5 kB)
Preparing metadata (setup.py) ...  done
Installing collected packages: frida
DEPRECATION: frida is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at  https://github.com/pypa/pip/issues/8559                                          
Running setup.py install for frida ... error                               
error: subprocess-exited-with-error
  
× Running setup.py install for frida did not run successfully.
│ exit code: 1
╰─> [63 lines of output]
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/frida
copying frida/__init__.py -> build/lib.linux-x86_64-3.7/frida
copying frida/core.py -> build/lib.linux-x86_64-3.7/frida
running build_ext
querying pypi for available prebuilds
network query failed
looking for prebuilt extension in home directory, i.e. /root/frida-12.1.1-py3.7-linux-x86_64.egg
no prebuilt extension found in home directory
Traceback (most recent call last):
File "<string>",  line 36, in <module>
File "<pip-setuptools-caller>",  line 34, in <module>
File "/tmp/pip-install-duelsn05/frida_566c06d3d50744568fc54127fc8c157b/setup.py",  line 179, in <module>
'build_ext': FridaPrebuiltExt
File "/root/.pyenv/versions/3.7.17/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
return distutils.core.setup(**attrs)
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/core.py", line 148, in setup
dist.run_commands()
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/dist.py",  line 966, in run_commands
self.run_command(cmd)
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/dist.py",  line 985, in run_command
cmd_obj.run()
File "/root/.pyenv/versions/3.7.17/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
return orig.install.run(self)
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/command/install.py", line 545, in run
self.run_command('build')
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/cmd.py",  line 313, in run_command
self.distribution.run_command(command)
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/dist.py",  line 985, in run_command
cmd_obj.run()
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/command/build.py", line 135, in run
self.run_command(cmd_name)
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/cmd.py",  line 313, in run_command
self.distribution.run_command(command)
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/dist.py",  line 985, in run_command
cmd_obj.run()
File "/root/.pyenv/versions/3.7.17/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
_build_ext.run(self)
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/command/build_ext.py", line 340, in run
self.build_extensions()
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/command/build_ext.py",  line 449, in build_extensions
self._build_extensions_serial()
File "/root/.pyenv/versions/3.7.17/lib/python3.7/distutils/command/build_ext.py",  line 474, in _build_extensions_serial
self.build_extension(ext)
File "/tmp/pip-install-duelsn05/frida_566c06d3d50744568fc54127fc8c157b/setup.py",  line 126, in build_extension
raise network_error
File "/tmp/pip-install-duelsn05/frida_566c06d3d50744568fc54127fc8c157b/setup.py",  line 85, in build_extension
urls = client.release_urls("frida", frida_version)
File "/root/.pyenv/versions/3.7.17/lib/python3.7/xmlrpc/client.py",  line 1112, in __call__
return self.__send(self.__ name, args)
File "/root/.pyenv/versions/3.7.17/lib/python3.7/xmlrpc/client.py",  line 1452, in __request
verbose=self.__verbose
File "/tmp/pip-install-duelsn05/frida_566c06d3d50744568fc54127fc8c157b/setup.py", line 56, in request
return self.parse_response(fp)
File "/root/.pyenv/versions/3.7.17/lib/python3.7/xmlrpc/client.py",  line 1342, in parse_response
return u.close()
File "/root/.pyenv/versions/3.7.17/lib/python3.7/xmlrpc/client.py", line 656, in close
raise Fault(**self._ stack[0])
xmlrpc.client.Fault: <Fault -32500: 'RuntimeError: PyPI no longer supports the XMLRPC package_releases method. Use JSON or Simple API instead. See  https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated -methods for more information.'>
[end of output]
  
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> frida
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update,  run: pip install --upgrade pip

**Comment by tomer8007** [comment]
I had this problem too, and managed to solve it by putting the frida `.egg` file from PyPi (e.g https://pypi.org/project/frida/12.8.0/#files) in my home directory.
As the error above says:
```
looking for prebuilt extension in home directory, i.e. /root/frida-12.1.1-py3.7-linux-x86_64.egg
```
