### ISSUE TITLE
Error: Unable to perform state transition; please file a bug"

### ISSUE THREAD

**Issue by iamsidharthbnair** [frida/frida#3256]
C:\Users\admin>adb shell
flame:/ $ su
flame:/ # cd /data/local/tmp
flame:/data/local/tmp # ls
frida-server-16.5.6-android-arm64  vysor.pwd
flame:/data/local/tmp # mv frida-server-16.5.6-android-arm64 ngrok
flame:/data/local/tmp # chmod 777 ngrok
flame:/data/local/tmp # ./ngrok
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}
![image](https://github.com/user-attachments/assets/eb04a23a-fe9b-4e34-9668-eeb66b000681)

after every 1st successful usage this issue always coming up now !

**Comment by pig837** [comment]
https://github.com/frida/frida/issues/2958
