### ISSUE TITLE
frida.NotSupportedError: unexpected error while mapping dylib (mach_vm_write(runtime) returned '(os/kern) invalid address')

### ISSUE THREAD

**Issue by zywu0221** [frida/frida#3270]
macOS Sequoia 15.0.1 
python3 3.11

TommydeMBP:~ root# python3 /Users/tommywu/Desktop/example.py
Traceback (most recent call last):
File "/Users/tommywu/Desktop/example.py", line 6, in
session = frida.attach("cat")
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/frida/init.py", line 95, in attach
return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
return f(*args, **kwargs)
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 1071, in attach
return Session(self._impl.attach(self._pid_of(target), **kwargs)) # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.NotSupportedError: unexpected error while mapping dylib (mach_vm_write(runtime) returned '(os/kern) invalid address')

**Comment by ZTOOTZ** [comment]
+1

**Comment by ITerydh** [comment]
+1
