### ISSUE TITLE
Starting frida-server on Android results in "Invalid Instruction" error, and attempting connection results in an inability to enumerate processes.

### ISSUE THREAD

**Issue by CoolSlimbo** [frida/frida#3311]
Running on latest version of Frida (16.5.7), results in the below errors.

Towards the device:
```shell
$ adb shell "/data/local/tmp/frida-server &"
{"type":"error","description":"Error: invalid instruction","stack":"Error: invalid instruction\n    at Function.value (frida/runtime/core.js:470:1)\n    at Tn (frida/node_modules/frida-java-bridge/lib/android.js:1741:1)\n    at frida/node_modules/frida-java-bridge/lib/android.js:1619:1\n    at Object.value [as patchCode] (frida/runtime/core.js:207:1)\n    at In (frida/node_modules/frida-java-bridge/lib/android.js:1618:1)\n    at vt (frida/node_modules/frida-java-bridge/lib/android.js:582:1)\n    at frida/node_modules/frida-java-bridge/lib/memoize.js:4:1\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)","fileName":"frida/runtime/core.js","lineNumber":470,"columnNumber":1} 
```

On my PC:
```shell
$ frida-ps -U
Failed to enumerate processes: cannot read properties of undefined (reading 'getRunningAppProcesses')
```

In the case of `frida-server`, the app doesn't automatically exit, it just floats, waiting.

**Device Information**
Samsung Galaxy S5 (G900I/kltedv), running Lineage OS 21, Android Version 14, rooted with Magisk (Using MagiskFrida does not work either).

**Comment by fateyan** [comment]
Same issue here,
It seems the crash is caused by Capstone failing to disassemble a particular instruction.
```bash
subprojects/frida-gum/bindings/gumjs/gumv8instruction.cpp:302:    _gum_v8_throw_ascii_literal (isolate, "invalid instruction");
subprojects/frida-gum/bindings/gumjs/gumquickinstruction.c:236:    return _gum_quick_throw_literal (ctx, "invalid instruction");
```
I'm not sure whether the failure happened in V8 instruction disassembly or in GumJS's QuickInstruction path, need more investigation.😅

**Comment by aaptel** [comment]
Same issue on android 11, rooted with magisk.
Samsung tab A SM-T510
