### ISSUE TITLE
Unable to perform state transition in `frida-java-bridge`

### ISSUE THREAD

**Issue by karjok** [frida/frida#3312]
Please help, i have encountering the following error while running `frida-server` on an Android device:

```json

{
  "type": "error",
  "description": "Error: Unable to perform state transition; please file a bug",
  "stack": "Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6",
  "fileName": "frida/node_modules/frida-java-bridge/lib/android.js",
  "lineNumber": 578,
  "columnNumber": 1
}

```
### Steps to Reproduce
- Run the `frida-server` binary on an Android device:
```bash

/data/local/tmp/frida-server-16.5.7-android-arm64
```
- Observe the error output.

### Expected Behavior
The `frida-server` should run without errors and allow interaction with the target device.

Actual Behavior
The server fails with an error stating:
`Error: Unable to perform state transition; please file a bug.`

### Environment
- **Frida Version:** 16.5.7
- **Platform:** Android
- **Device:** Infinix-X669C
- **Architecture:** arm64

### Additional Information
The error seems to originate from `frida-java-bridge` as indicated by the stack trace.

### Screenshoot

![image](https://github.com/user-attachments/assets/357e7edf-ad55-4648-b787-732dc5382e81)

**Comment by erik-smit** [comment]
Duplicate of https://github.com/frida/frida/issues/2954
