### ISSUE TITLE
Windows spawn x64 process from x86 python fails

### ISSUE THREAD

**Issue by stuxxn** [frida/frida#345]
Windows 7
python 2.7.14
Frida Version: 10.6.2

Hello,

I try to create a new process (x64) via "frida.spawn"  from a x86 python and it fails with the following error:

```
frida.NotSupportedError: unable to spawn executable at 'C:\Windows\sysnative\rundll32.exe': 0x00000032

Full:
Traceback (most recent call last):
  File ".\script.py", line 39, in <module>
    main()
  File ".\script.py", line 25, in main
    pid= frida.spawn( args)
  File "build\bdist.win32\egg\frida\__init__.py", line 48, in spawn
  File "build\bdist.win32\egg\frida\core.py", line 85, in spawn
frida.NotSupportedError: unable to spawn executable at 'C:\Windows\sysnative\rundll32.exe': 0x00000032
```

Is it not possible to create a new x64 process ? What would be a alternative ?

The script:

```python
from __future__ import print_function
import frida

cmd = "C:\\Windows\\sysnative\\rundll32.exe"	# using sysnative to force x64 process
args = [ cmd, "C:\\Users\\stuxxn\\Desktop\\CTF\\lvl6-payload\\payload.dll", "#1", "EntryPoint" ]

pid = frida.spawn( args)
print("PID: {}".format(pid))

```

**Comment by meiskam** [comment]
any updates on this? i'm having the same issue

**Comment by oleavr** [comment]
Either use a 64-bit Python or contribute to Frida, moving the `spawn()` implementation to the helper processes.
