### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by squidbobble** [frida/frida#355]
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    pid = device.spawn(["kik.android"])
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\frida\core.py", line 85, in spawn
    return self._impl.spawn(argv)
frida.TransportError: the connection is closed

cannot connect via frida.trace on any process id or name as it states that it is unable to find a process with that name or pid. 

frida-ps -U works fine and lists plenty of processes.

**Comment by squidbobble** [comment]
Using server 10.6.8 x86 vers on android

**Comment by juanriaza** [comment]
Seems to work fine with version 10.2.3

Source: #343, plus my own experience
