### ISSUE TITLE
frida.TransportError: timeout was reached

### ISSUE THREAD

**Issue by 3xp10it** [frida/frida#405]
I use below code`xxx.py` to attach an usb ios app on macOS,

```
import frida
import sys

session = frida.get_usb_device().attach(4420)
script_string = """

if (ObjC.available)
{
    try
    {
        var my_obj1=ObjC.chooseSync(ObjC.classes.PARSUserInfo)[0]
        console.log(my_obj1)
        var security_token=my_obj1["- encryptedPhoneStamp"]()
        console.log(security_token)
    }
    catch(err)
    {
        console.log("[!] Exception2: " + err.message);
    }
}
else
{
    console.log("Objective-C Runtime is not available!");
}
"""


script = session.create_script(script_string)


def on_message(message, data):
    if message['type'] == 'error':
        print("[!] " + message['stack'])
    elif message['type'] == 'send':
        print("[i] " + message['payload'])
    else:
        print(message)


script.on('message', on_message)
script.load()
sys.stdin.read()
```

It wors well and log the info I want,then I use `Ctrl+c` to stop `xxx.py` and try to run `python3 xxx.py` again,but it shows me below error this time:

```
Traceback (most recent call last):
  File "xxx.py", line 4, in <module>
    session = frida.get_usb_device().attach(4420)
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 97, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.TransportError: timeout was reached
```

I want to use `xxx.py` to attach the target ios app again without exit the ios app,Can you help me?

**Comment by henrymark92** [comment]
@oleavr  I have same this problem
I did  step by step of android example (https://www.frida.re/docs/examples/android/) and got a error.
```
Traceback (most recent call last):
  File "D:/source/App/test.py", line 58, in <module>
    session = frida.get_usb_device().attach("com.example.seccon2015.rock_paper_scissors")
  File "C:\python32\python-2.7.10\lib\site-packages\frida\core.py", line 97, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.TransportError: timeout was reached

Process finished with exit code 1

```
+ When I use debug then I saw a process of example app

![capture](https://user-images.githubusercontent.com/4132665/35195744-8f6aa456-fefa-11e7-8c18-685b8de0ffc4.PNG)

Device Info:
+frida-server-10.6.37-android-x86.xz
+Bluestack
 +Android version 4.4
+Win 10

**Comment by henrymark92** [comment]
@oleavr 
App was stop when click button R:
Here code:
```
import frida, sys

def on_message(message, data):
    if message['type'] == 'send':
        print("[*] {0}".format(message['payload']))
    else:
        print(message)

jscode = """
console.log('Done:');
Java.perform(function () {
    console.log('Done: 111');
    // Function to hook is defined here
    var MainActivity = Java.use('com.example.seccon2015.rock_paper_scissors.MainActivity');
    console.log(MainActivity);
    // Whenever button is clicked
    MainActivity.onClick.implementation = function (v) {
        // Show a message to know that the function got called
        console.log(v);
        send('onClick');

        // Call the original onClick handler
        this.onClick(v);

        // Set our values after running the original onClick handler
        this.m.value = 0;
        this.n.value = 1;
        this.cnt.value = 999;

        // Log to the console that it's done, and we should have the flag!
        console.log('Done:' + JSON.stringify(this.cnt));
    };
});
"""
#
device = frida.get_usb_device()
process = device.attach('com.example.seccon2015.rock_paper_scissors')
script = process.create_script(jscode)
script.on('message', on_message)
print('[*] Running CTF')
script.load()
sys.stdin.read()
```

output:
```
[*] Running CTF
Done:
Done: 111
<com.example.seccon2015.rock_paper_scissors.MainActivity>
```

Device Info:
+frida-server-10.6.39-android-x86
+Bluestack
+Android version 4.4
+Win 10

**Comment by oleavr** [comment]
@henrymark92 x86 emulators that only run ARM code (like Nox App Player, and presumably also Bluestack) are not supported.

@3xp10it Please reopen if still reproducible on 10.6.40 and you are willing to help me debug it on your device. (There's no way I can reproduce it otherwise.)

**Comment by RoyalFlushever** [comment]
Downgrade your frida-server version on your android devices.
For example, if you have frida-version 10.6.32 on your PC, you can install frida-server 10.0.X.
Note: only master version should match between frida-server and frida.

**Comment by Fr0stM0urne** [comment]
Had this on 16.0.10. Restarting frida server on the mobile device seems to fix the issue.

**Comment by bdbaigc** [comment]
> Had this on 16.0.10. Restarting frida server on the mobile device seems to fix the issue.

cool！this solve my problem too！
