### ISSUE TITLE
Gadget-32 crashes on Ubuntu server 16.04 32bit

### ISSUE THREAD

**Issue by ba0f3** [frida/frida#416]
I tried to use frida-gadget on docker container and virtualbox machine, both crashed w/ segment fault error.

frida-gadget version: 10.6.34
[backtrace.txt](https://github.com/frida/frida/files/1644789/backtrace.txt)

**Comment by oleavr** [comment]
Is this still reproducible in 10.6.40? If so, would you be interested in building it yourself with symbols? (By removing `--strip` from [here](https://github.com/frida/frida/blob/ee5bcf08bc04ec77d1ac258491d5702b0bcd2617/config.mk#L6)).

**Comment by ba0f3** [comment]
Lemme try it again. btw I can't make gadget-32 on both x86 and x86_64, due to this error:
```
/bin/sh: 1: /../frida/releng/ninja-linux-x86: not found
```

**Comment by ba0f3** [comment]
```
#0  0xb6590391 in ?? () from /tmp/frida-gadget-10.6.40-linux-x86.so
#1  0xb6599cfb in ?? () from /tmp/frida-gadget-10.6.40-linux-x86.so
#2  0xb657fdf4 in ?? () from /tmp/frida-gadget-10.6.40-linux-x86.so
#3  0xb773c465 in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0xbfcb8b04, env=0xbfcb8b10) at dl-init.c:72
#4  0xb773c58e in call_init (env=0xbfcb8b10, argv=0xbfcb8b04, argc=2, l=<optimized out>) at dl-init.c:30
#5  _dl_init (main_map=<optimized out>, argc=2, argv=0xbfcb8b04, env=0xbfcb8b10) at dl-init.c:120
#6  0xb772da5f in _dl_start_user () from /lib/ld-linux.so.2
```
Still crash on 10.6.40

**Comment by ba0f3** [comment]
finally I was able to make it, here is the backtrace w/ debug symbols:
```
#0  0xb65489d6 in frida_gadget_detect_location () at lib/gadget/frida-gadget@sha/gadget.c:5185
#1  0xb6552443 in frida_gadget_load () at lib/gadget/frida-gadget@sha/gadget.c:4270
#2  0xb653849c in on_load () at ../../../frida-core/lib/gadget/gadget-glue.c:133
#3  0xb7726465 in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0xbfe73294, env=0xbfe7329c) at dl-init.c:72
#4  0xb772658e in call_init (env=0xbfe7329c, argv=0xbfe73294, argc=1, l=<optimized out>) at dl-init.c:30
#5  _dl_init (main_map=<optimized out>, argc=1, argv=0xbfe73294, env=0xbfe7329c) at dl-init.c:120
#6  0xb7717a5f in _dl_start_user () from /lib/ld-linux.so.2
```

**Comment by ba0f3** [comment]
it seems fixed in recent releases
