### ISSUE TITLE
Which firda version is working best for android 86x?

### ISSUE THREAD

**Issue by henrymark92** [frida/frida#420]

**Comment by oleavr** [comment]
Frida 10.6.40 is compatible with 4.x, 5.x, 6.x, 7.x, and 8.x. Avoid emulators that are hardwired to execute ARM code though, like Nox App Player, those probably won't ever be supported. (If you need to be able to hook Java methods.)

**Comment by oleavr** [comment]
Either use Genymotion or one of the stock ones from Google, or use a real device.

**Comment by henrymark92** [comment]
@oleavr 
I tried with genymotion and got crash when click button R

Here logcat of other emulator (Bluestack). Please check log
Thanks.
```
--------- beginning of /dev/log/main
D/dalvikvm( 3123): GC_CONCURRENT freed 664K, 25% free 2682K/3536K, paused 0ms+0ms, total 10ms
D/BstCommandProcessor-httpd( 3132): command: ping
D/BstCommandProcessor-httpd( 3132): response: {"result":"ok"}
D/BstCommandProcessor-httpd( 3132): command: clipboard (with args)
D/BstCommandProcessor-httpd( 3132): response: {"result":"ok"}
D/su      ( 3974): su invoked.
D/su      ( 3974): starting daemon client 2000 0
D/su      ( 3977): remote pid: 3974
D/su      ( 3977): remote pts_slave: /dev/pts/5
D/su      ( 3977): waiting for child exit
D/su      ( 3979): daemon: stdin using PTY
D/su      ( 3979): daemon: stdout using PTY
D/su      ( 3979): daemon: stderr using PTY
D/su      ( 3980): su invoked.
D/su      ( 3980): Allowing shell.
D/su      ( 3980): 2000 /system/bin/sh executing 0 /data/local/tmp/frida-server & using binary /system/bin/sh : sh -c /data/local/tmp/frida-server &
D/su      ( 3977): sending code
D/su      ( 3977): child exited
--------- beginning of /dev/log/system
W/ActivityManager( 2955): Unable to start service Intent { act=com.google.android.gms.droidguard.service.START pkg=com.google.android.gms } U=0: not found
E/GmsClient( 3223): unable to connect to service: com.google.android.gms.droidguard.service.START
W/ActivityManager( 2955): Unbind failed: could not find connection for android.os.BinderProxy@330edddc
W/GLSUser ( 3223): [AppCertManager] IOException while requesting key:
W/GLSUser ( 3223): java.io.IOException: Invalid device key response.
W/GLSUser ( 3223):      at com.google.android.gms.auth.be.appcert.a.a(SourceFile:303)
W/GLSUser ( 3223):      at com.google.android.gms.auth.be.appcert.a.a(SourceFile:134)
W/GLSUser ( 3223):      at com.google.android.gms.auth.be.appcert.b.a(SourceFile:43)
W/GLSUser ( 3223):      at com.google.android.gms.auth.b.b.a(SourceFile:62)
W/GLSUser ( 3223):      at com.google.android.gms.auth.b.a.a(SourceFile:120)
W/GLSUser ( 3223):      at com.google.android.gms.auth.b.a.a(SourceFile:61)
W/GLSUser ( 3223):      at com.google.android.gms.auth.be.cron.AuthCronService.a(SourceFile:44)
W/GLSUser ( 3223):      at com.google.android.gms.gcm.ar.run(SourceFile:131)
D/dalvikvm( 3123): GC_CONCURRENT freed 664K, 25% free 2682K/3536K, paused 0ms+0ms, total 0ms
D/dalvikvm( 3123): GC_CONCURRENT freed 600K, 23% free 2746K/3536K, paused 10ms+0ms, total 20ms
D/dalvikvm( 3123): GC_FOR_ALLOC freed 664K, 25% free 2682K/3532K, paused 0ms, total 0ms
E/InputDispatcher( 2955): Motion event has invalid pointer count 0; value must be between 1 and 16.
E/InputDispatcher( 2955): Motion event has invalid pointer count 0; value must be between 1 and 16.
I/ActivityManager( 2955): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.example.seccon2015.rock_paper_scissors/.MainActivity} from pid 3171
D/ActivityManager( 2955): TopActivityInfo, pkgName: com.example.seccon2015.rock_paper_scissors activityName: com.example.seccon2015.rock_paper_scissors.MainActivitycallingPackage: com.cyanogenmod.trebuchet  bstSpecialAppKeyboardHandlingEnabled = false
D/ActivityManager( 2955): Showing guidance for pkgName: com.example.seccon2015.rock_paper_scissors
D/GuidanceScreen( 3146): event === app_launch
D/GuidanceScreen( 3146): hiding guidance
D/GuidanceScreen( 3146): hardKeyboard = 1
D/GuidanceScreen( 3146): controllerType === Keyboard
D/GuidanceScreen( 3146): appName: rock_paper_scissors, currentPkg: com.example.seccon2015.rock_paper_scissors, event: app_launch, controller: Keyboard
D/GuidanceScreen( 3146): appName: rock_paper_scissors
D/audio_hw_primary(  586): found out /dev/snd/pcmC0D0p
I/PGA     ( 2955): Attempting to create new SOCKET connectionn pid = 2955, tid = 3168
I/PGA     ( 2955): New SOCKET connection: system_server (pid 2955, tid 3168)
W/PGA     ( 2940): tid 2940: eglCreateSyncKHR: NOT IMPLEMENTED
D/dalvikvm( 2955): GC_FOR_ALLOC freed 895K, 22% free 5422K/6936K, paused 10ms, total 10ms
D/GuidanceScreen( 3146): no guidance for com.example.seccon2015.rock_paper_scissors.
W/audio_hw_primary(  586): out_write() limiting sleep time 112539 to 46439
I/ActivityManager( 2955): Start proc com.example.seccon2015.rock_paper_scissors for activity com.example.seccon2015.rock_paper_scissors/.MainActivity: pid=3990 uid=10053 gids={50053}
D/WindowManager( 2955): in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true   mHardKeyboardEnabled :true
D/dalvikvm( 3990): Trying to load lib /data/app-lib/com.example.seccon2015.rock_paper_scissors-1/libcalc.so 0x65f84b88
D/dalvikvm( 3990): Added shared lib /data/app-lib/com.example.seccon2015.rock_paper_scissors-1/libcalc.so 0x65f84b88
D/dalvikvm( 3990): No JNI_OnLoad found in /data/app-lib/com.example.seccon2015.rock_paper_scissors-1/libcalc.so 0x65f84b88, skipping init
D/WindowManager( 2955): Sending appClickStats request with data: [package=com.example.seccon2015.rock_paper_scissors, appname=rock_paper_scissors, appver=1.0, clickloc=system_server]
D/InputMethodManagerService( 2955): ime_enabled = false is same as last value, no change
W/audio_hw_primary(  586): out_write() limiting sleep time 65759 to 46439
I/PGA     ( 3990): Attempting to create new SOCKET connectionn pid = 3990, tid = 3990
I/PGA     ( 3990): New SOCKET connection: com.example.seccon2015.rock_paper_scissors (pid 3990, tid 3990)
I/ActivityManager( 2955): Displayed com.example.seccon2015.rock_paper_scissors/.MainActivity: +170ms
D/WindowManager( 2955): topDisplayedActivityInfo, appToken: Token{33147a30 ActivityRecord{33147980 u0 com.example.seccon2015.rock_paper_scissors/.MainActivity t5}}
D/WindowManager( 2955): topDisplayedActivityInfo, appToken: Token{33147a30 ActivityRecord{33147980 u0 com.example.seccon2015.rock_paper_scissors/.MainActivity t5}}
D/WindowManager( 2955): topDisplayedActivityInfo, appToken: Token{33147a30 ActivityRecord{33147980 u0 com.example.seccon2015.rock_paper_scissors/.MainActivity t5}}
E/InputDispatcher( 2955): Motion event has invalid pointer count 0; value must be between 1 and 16.
E/InputDispatcher( 2955): Motion event has invalid pointer count 0; value must be between 1 and 16.
E/dalvikvm( 3990): VM aborting
F/libc    ( 3990): Fatal signal 6 (SIGABRT) at 0x00000f96 (code=-6), thread 3990 (_paper_scissors)
D/audio_hw_primary(  586): found out /dev/snd/pcmC0D0p
W/audio_hw_primary(  586): out_write() limiting sleep time 112539 to 46439
W/audio_hw_primary(  586): out_write() limiting sleep time 65759 to 46439
I/DEBUG   (  574): pid: 3990, tid: 3990, pkg name: com.example.seccon2015.rock_paper_scissors
I/DEBUG   (  574): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  574): Build fingerprint: 'samsung/kltexx/klte:4.4.2/KOT49H/G900FXXU1ANCE:user/release-keys'
I/DEBUG   (  574): Revision: '0'
I/DEBUG   (  574): pid: 3990, tid: 3990, name: _paper_scissors  >>> com.example.seccon2015.rock_paper_scissors <<<
I/DEBUG   (  574): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
W/NativeCrashListener( 2955): Couldn't find ProcessRecord for pid 1885955130
I/DEBUG   (  574):     eax 00000000  ebx 00000f96  ecx 00000f96  edx 00000006
I/DEBUG   (  574): AM write failure (32 / Broken pipe)
I/DEBUG   (  574):     esi 00000f96  edi 0000000b
I/DEBUG   (  574):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
I/DEBUG   (  574):     eip 77673e96  ebp 776d8ce0  esp 7fc4ba94  flags 00210207
I/DEBUG   (  574):
I/DEBUG   (  574): backtrace:
I/DEBUG   (  574):     #00  pc 0003be96  /system/lib/libc.so (tgkill+22)
I/DEBUG   (  574):     #01  pc 00000005  <unknown>
I/DEBUG   (  574):
I/DEBUG   (  574): stack:
I/DEBUG   (  574):          7fc4ba54  00000000
I/DEBUG   (  574):          7fc4ba58  00000000
I/DEBUG   (  574):          7fc4ba5c  00000000
I/DEBUG   (  574):          7fc4ba60  00000000
I/DEBUG   (  574):          7fc4ba64  00000000
I/DEBUG   (  574):          7fc4ba68  00000000
I/DEBUG   (  574):          7fc4ba6c  00000000
I/DEBUG   (  574):          7fc4ba70  00000000
I/DEBUG   (  574):          7fc4ba74  00000000
I/DEBUG   (  574):          7fc4ba78  00000000
I/DEBUG   (  574):          7fc4ba7c  00000000
I/DEBUG   (  574):          7fc4ba80  7767df66  /system/lib/libc.so
I/DEBUG   (  574):          7fc4ba84  00000000
I/DEBUG   (  574):          7fc4ba88  00000000
I/DEBUG   (  574):          7fc4ba8c  77645dd9  /system/lib/libc.so (pthread_mutex_lock+9)
I/DEBUG   (  574):          7fc4ba90  776d3fcc  /system/lib/libc.so
I/DEBUG   (  574):     #00  7fc4ba94  00000006
I/DEBUG   (  574):          7fc4ba98  00000f96
I/DEBUG   (  574):          7fc4ba9c  776d3fcc  /system/lib/libc.so
I/DEBUG   (  574):          7fc4baa0  77650636  /system/lib/libc.so (pthread_kill+102)
I/DEBUG   (  574):          7fc4baa4  00000f96
I/DEBUG   (  574):          7fc4baa8  00000f96
I/DEBUG   (  574):          7fc4baac  00000006
I/DEBUG   (  574):          7fc4bab0  00000000
I/DEBUG   (  574):          7fc4bab4  776d4268  /system/lib/libc.so
I/DEBUG   (  574):          7fc4bab8  7fc4bc68  [stack]
I/DEBUG   (  574):          7fc4babc  776505d9  /system/lib/libc.so (pthread_kill+9)
I/DEBUG   (  574):          7fc4bac0  776d3fcc  /system/lib/libc.so
I/DEBUG   (  574):          7fc4bac4  7fc4bb10  [stack]
I/DEBUG   (  574):          7fc4bac8  7fc4bd50  [stack]
I/DEBUG   (  574):          7fc4bacc  7fc4bd78  [stack]
I/DEBUG   (  574):          7fc4bad0  776509fc  /system/lib/libc.so (raise+44)
D/BstCommandProcessor-Application( 3132): Application crash has been observed.
D/BstCommandProcessor-Application( 3132): in sendHttpRequest, request to send to (fqdn): http://10.0.2.2:2861/AppCrashedInfo
D/BstCommandProcessor-Application( 3132): data: {"packageName":"com.example.seccon2015.rock_paper_scissors","shortPackageName":"com.example.seccon2015.rock_paper_scissors","versionCode":1,"versionName":"1.0"}
W/ActivityThread( 3132): ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
I/BootReceiver( 2955): Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
I/ActivityManager( 2955): Process com.example.seccon2015.rock_paper_scissors (pid 3990) has died.
W/ActivityManager( 2955): Force removing ActivityRecord{33147980 u0 com.example.seccon2015.rock_paper_scissors/.MainActivity t5}: app died, no saved state
W/InputDispatcher( 2955): channel '3307d504 com.example.seccon2015.rock_paper_scissors/com.example.seccon2015.rock_paper_scissors.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 2955): channel '3307d504 com.example.seccon2015.rock_paper_scissors/com.example.seccon2015.rock_paper_scissors.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
D/Zygote  ( 2941): Process 3990 terminated by signal (6)
W/InputDispatcher( 2955): Attempted to unregister already unregistered input channel '3307d504 com.example.seccon2015.rock_paper_scissors/com.example.seccon2015.rock_paper_scissors.MainActivity (server)'
D/WindowManager( 2955): topDisplayedActivityInfo, appToken: Token{33147a30 ActivityRecord{33147980 u0 com.example.seccon2015.rock_paper_scissors/.MainActivity t5 f}}
D/ActivityManager( 2955): TopActivityInfo, pkgName: com.cyanogenmod.trebuchet activityName: com.cyanogenmod.trebuchet/com.android.launcher3.LaunchercallingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
I/WindowState( 2955): WIN DEATH: Window{3307d504 u0 com.example.seccon2015.rock_paper_scissors/com.example.seccon2015.rock_paper_scissors.MainActivity}
D/ActivityManager( 2955): Showing guidance for pkgName: com.cyanogenmod.trebuchet
D/GuidanceScreen( 3146): event === app_launch
D/GuidanceScreen( 3146): hiding guidance
D/GuidanceScreen( 3146): hardKeyboard = 1
D/GuidanceScreen( 3146): controllerType === Keyboard
D/GuidanceScreen( 3146): appName: Trebuchet, currentPkg: com.cyanogenmod.trebuchet, event: app_launch, controller: Keyboard
W/SurfaceFlinger( 2940): couldn't log to binary event log: overflow.
D/GuidanceScreen( 3146): appName: Trebuchet
D/WindowManager( 2955): in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true   mHardKeyboardEnabled :true
D/GuidanceScreen( 3146): no guidance for com.cyanogenmod.trebuchet.
D/InputMethodManagerService( 2955): ime_enabled = false is same as last value, no change
W/InputMethodManagerService( 2955): Got RemoteException sending setActive(false) notification to pid 3990 uid 10053
W/Binder  ( 3052): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 3052): java.lang.NullPointerException
W/Binder  ( 3052):      at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/Binder  ( 3052):      at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/Binder  ( 3052):      at android.os.Binder.execTransact(Binder.java:404)
W/Binder  ( 3052):      at dalvik.system.NativeStart.run(Native Method)
I/ActivityManager( 2955): Setting mBooting value to false, currently mBooted = true
D/WindowManager( 2955): topDisplayedActivityInfo, appToken: Token{330e3e64 ActivityRecord{330e3d28 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t1}}
D/WindowManager( 2955): topDisplayedActivityInfo, appToken: Token{330e3e64 ActivityRecord{330e3d28 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t1}}
D/dalvikvm( 3123): GC_CONCURRENT freed 663K, 25% free 2682K/3532K, paused 0ms+0ms, total 10ms
D/dalvikvm( 3123): GC_CONCURRENT freed 617K, 24% free 2699K/3516K, paused 10ms+0ms, total 20ms
W/ActivityManager( 2955): Unable to start service Intent { act=com.google.android.gms.droidguard.service.START pkg=com.google.android.gms } U=0: not found
E/GmsClient( 3223): unable to connect to service: com.google.android.gms.droidguard.service.START
W/ActivityManager( 2955): Unbind failed: could not find connection for android.os.BinderProxy@33126a50
D/dalvikvm( 3223): GC_CONCURRENT freed 1074K, 23% free 3821K/4928K, paused 10ms+0ms, total 30ms
W/GLSUser ( 3223): [AppCertManager] IOException while requesting key:
W/GLSUser ( 3223): java.io.IOException: Invalid device key response.
W/GLSUser ( 3223):      at com.google.android.gms.auth.be.appcert.a.a(SourceFile:303)
W/GLSUser ( 3223):      at com.google.android.gms.auth.be.appcert.a.a(SourceFile:134)
W/GLSUser ( 3223):      at com.google.android.gms.auth.be.appcert.b.a(SourceFile:43)
W/GLSUser ( 3223):      at com.google.android.gms.auth.b.b.a(SourceFile:62)
W/GLSUser ( 3223):      at com.google.android.gms.auth.b.a.a(SourceFile:120)
W/GLSUser ( 3223):      at com.google.android.gms.auth.b.a.a(SourceFile:61)
W/GLSUser ( 3223):      at com.google.android.gms.auth.be.cron.AuthCronService.a(SourceFile:44)
W/GLSUser ( 3223):      at com.google.android.gms.gcm.ar.run(SourceFile:131)
D/dalvikvm( 3123): GC_CONCURRENT freed 619K, 23% free 2709K/3516K, paused 10ms+0ms, total 20ms
D/BstCommandProcessor-httpd( 3132): command: ping
D/BstCommandProcessor-httpd( 3132): response: {"result":"ok"}
D/BstCommandProcessor-httpd( 3132): command: clipboard (with args)
D/BstCommandProcessor-httpd( 3132): response: {"result":"ok"}
D/dalvikvm( 3132): GC_CONCURRENT freed 1267K, 21% free 5153K/6456K, paused 10ms+0ms, total 30ms
D/dalvikvm( 3123): GC_FOR_ALLOC freed 586K, 24% free 2690K/3508K, paused 10ms, total 10ms
D/dalvikvm( 3788): GC_CONCURRENT freed 698K, 22% free 2845K/3608K, paused 0ms+0ms, total 10ms
D/dalvikvm( 3123): GC_FOR_ALLOC freed 598K, 24% free 2691K/3508K, paused 10ms, total 10ms
D/BstCommandProcessor-httpd( 3132): command: ping
D/BstCommandProcessor-httpd( 3132): response: {"result":"ok"}
W/BstCommandProcessor-httpd( 3132): Reached maxLineLength limit while reading the content of a file
D/dalvikvm( 3132): GC_FOR_ALLOC freed 1351K, 24% free 5151K/6740K, paused 0ms, total 0ms
D/dalvikvm( 3132): GC_FOR_ALLOC freed 1186K, 24% free 5151K/6740K, paused 0ms, total 0ms
D/dalvikvm( 3132): GC_FOR_ALLOC freed 1141K, 24% free 5156K/6740K, paused 0ms, total 0ms
D/dalvikvm( 3132): GC_FOR_ALLOC freed 1117K, 24% free 5152K/6740K, paused 0ms, total 0ms
D/dalvikvm( 3132): GC_FOR_ALLOC freed 1100K, 24% free 5161K/6740K, paused 0ms, total 0ms
D/dalvikvm( 3132): GC_FOR_ALLOC freed 1114K, 24% free 5163K/6752K, paused 10ms, total 10ms
D/BstCommandProcessor-httpd( 3132): command: clipboard (with args)
D/BstCommandProcessor-httpd( 3132): response: {"result":"ok"}
```
