### ISSUE TITLE
frida.TransportError: the connection is closed

### ISSUE THREAD

**Issue by henrymark92** [frida/frida#423]
Hello @oleavr. 
I found a bugs. Can you check it? 
Thanks
```
[*] Running CTF
Done:
Traceback (most recent call last):
  File "D:/source/SmartAuto/test.py", line 41, in <module>
    script.load()
  File "C:\python32\python-2.7.10\lib\site-packages\frida\core.py", line 300, in load
    self._impl.load()
frida.TransportError: the connection is closed
```

Logcat:
```
--------- beginning of /dev/log/main
D/su      ( 2738): su invoked.
D/su      ( 2738): starting daemon client 2000 0
D/su      ( 2741): remote pid: 2738
D/su      ( 2741): remote pts_slave: /dev/pts/5
D/su      ( 2741): waiting for child exit
D/su      ( 2743): daemon: stdin using PTY
D/su      ( 2743): daemon: stdout using PTY
D/su      ( 2743): daemon: stderr using PTY
D/su      ( 2744): su invoked.
D/su      ( 2744): Allowing shell.
D/su      ( 2744): 2000 /system/bin/sh executing 0 /data/local/tmp/frida-server & using binary /system/bin/sh : sh -c /data/local/tmp/frida-server &
D/su      ( 2741): sending code
D/su      ( 2741): child exited
F/GLib    ( 2460): g_path_get_basename: assertion 'file_name != NULL' failed
F/Frida   ( 2460): string_index_of: assertion 'self != NULL' failed
F/GLib    ( 2460): g_path_get_basename: assertion 'file_name != NULL' failed
F/GLib    ( 2460): g_path_get_basename: assertion 'file_name != NULL' failed
F/libc    ( 2460): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 2769 (gum-js-loop)
I/DEBUG   (  574): pid: 2460, tid: 2769, pkg name: com.example.seccon2015.rock_paper_scissors
I/DEBUG   (  574): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  574): Build fingerprint: 'samsung/kltexx/klte:4.4.2/KOT49H/G900FXXU1ANCE:user/release-keys'
I/DEBUG   (  574): Revision: '0'
I/DEBUG   (  574): pid: 2460, tid: 2769, name: gum-js-loop  >>> com.example.seccon2015.rock_paper_scissors <<<
I/DEBUG   (  574): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
--------- beginning of /dev/log/system
W/NativeCrashListener( 1721): Couldn't find ProcessRecord for pid 1885955130
D/BstCommandProcessor-Application( 1896): Application crash has been observed.
D/Zygote  ( 1106): Process 2460 terminated by signal (11)
W/InputDispatcher( 1721): channel '330ed490 com.example.seccon2015.rock_paper_scissors/com.example.seccon2015.rock_paper_scissors.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 1721): channel '330ed490 com.example.seccon2015.rock_paper_scissors/com.example.seccon2015.rock_paper_scissors.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
I/ActivityManager( 1721): Process com.example.seccon2015.rock_paper_scissors (pid 2460) has died.
W/ActivityManager( 1721): Force removing ActivityRecord{3308a11c u0 com.example.seccon2015.rock_paper_scissors/.MainActivity t2}: app died, no saved state
D/WindowManager( 1721): topDisplayedActivityInfo, appToken: Token{33045b20 ActivityRecord{3308a11c u0 com.example.seccon2015.rock_paper_scissors/.MainActivity t2 f}}
D/ActivityManager( 1721): TopActivityInfo, pkgName: com.cyanogenmod.trebuchet activityName: com.cyanogenmod.trebuchet/com.android.launcher3.LaunchercallingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
W/InputDispatcher( 1721): Attempted to unregister already unregistered input channel '330ed490 com.example.seccon2015.rock_paper_scissors/com.example.seccon2015.rock_paper_scissors.MainActivity (server)'
D/GuidanceScreen( 1912): event === app_launch
D/GuidanceScreen( 1912): hiding guidance
D/GuidanceScreen( 1912): hardKeyboard = 1
D/GuidanceScreen( 1912): controllerType === Keyboard
D/GuidanceScreen( 1912): appName: Trebuchet, currentPkg: com.cyanogenmod.trebuchet, event: app_launch, controller: Keyboard
D/GuidanceScreen( 1912): appName: Trebuchet
I/WindowState( 1721): WIN DEATH: Window{330ed490 u0 com.example.seccon2015.rock_paper_scissors/com.example.seccon2015.rock_paper_scissors.MainActivity}
D/ActivityManager( 1721): Showing guidance for pkgName: com.cyanogenmod.trebuchet
D/WindowManager( 1721): in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true   mHardKeyboardEnabled :true
W/SurfaceFlinger( 1105): couldn't log to binary event log: overflow.
D/GuidanceScreen( 1912): no guidance for com.cyanogenmod.trebuchet.
I/BootReceiver( 1721): Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
D/BstCommandProcessor-Application( 1896): in sendHttpRequest, request to send to (fqdn): http://10.0.2.2:2861/AppCrashedInfo
D/BstCommandProcessor-Application( 1896): data: {"packageName":"com.example.seccon2015.rock_paper_scissors","shortPackageName":"com.example.seccon2015.rock_paper_scissors","versionCode":1,"versionName":"1.0"}
W/ActivityThread( 1896): ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
D/InputMethodManagerService( 1721): ime_enabled = false is same as last value, no change
W/InputMethodManagerService( 1721): Got RemoteException sending setActive(false) notification to pid 2460 uid 10053
W/Binder  ( 1835): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 1835): java.lang.NullPointerException
W/Binder  ( 1835):      at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/Binder  ( 1835):      at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/Binder  ( 1835):      at android.os.Binder.execTransact(Binder.java:404)
W/Binder  ( 1835):      at dalvik.system.NativeStart.run(Native Method)
I/ActivityManager( 1721): Setting mBooting value to false, currently mBooted = true
D/WindowManager( 1721): topDisplayedActivityInfo, appToken: Token{330ca080 ActivityRecord{33095d14 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t1}}
D/WindowManager( 1721): topDisplayedActivityInfo, appToken: Token{330ca080 ActivityRecord{33095d14 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t1}}
I/GoogleURLConnFactory( 2074): Using platform SSLCertificateSocketFactory
I/GLSUser ( 2074): [ ChannelManager ] Attempting to channel bind connection HttpClient.
I/GLSUser ( 2074): [ ChannelManager ] Skip channel binding on pre-KLP devices.
W/GLSUser ( 2074): [DeviceKeyStore] Cannot load key: Device key file not found.
D/dalvikvm( 2074): GC_CONCURRENT freed 734K, 17% free 3787K/4556K, paused 0ms+10ms, total 10ms
W/ActivityManager( 1721): Unable to start service Intent { act=com.google.android.gms.droidguard.service.START pkg=com.google.android.gms } U=0: not found
E/GmsClient( 2074): unable to connect to service: com.google.android.gms.droidguard.service.START
W/ActivityManager( 1721): Unbind failed: could not find connection for android.os.BinderProxy@330d6670
W/GLSUser ( 2074): [AppCertManager] IOException while requesting key:
W/GLSUser ( 2074): java.io.IOException: Invalid device key response.
W/GLSUser ( 2074):      at com.google.android.gms.auth.be.appcert.a.a(SourceFile:303)
W/GLSUser ( 2074):      at com.google.android.gms.auth.be.appcert.a.a(SourceFile:134)
W/GLSUser ( 2074):      at com.google.android.gms.auth.be.appcert.b.a(SourceFile:43)
W/GLSUser ( 2074):      at com.google.android.gms.auth.b.b.a(SourceFile:62)
W/GLSUser ( 2074):      at com.google.android.gms.auth.b.a.a(SourceFile:120)
W/GLSUser ( 2074):      at com.google.android.gms.auth.b.a.a(SourceFile:61)
W/GLSUser ( 2074):      at com.google.android.gms.auth.be.cron.AuthCronService.a(SourceFile:44)
W/GLSUser ( 2074):      at com.google.android.gms.gcm.ar.run(SourceFile:131)
I/VacuumService( 2074): Vacuum at: now=1517407078669 tag=VacuumService
D/NetstatsCollectorService( 2339): User is not opt-in to Usage & Diagnostics.
D/dalvikvm( 2339): GC_CONCURRENT freed 754K, 19% free 3554K/4348K, paused 0ms+10ms, total 10ms
I/GoogleURLConnFactory( 2074): Using platform SSLCertificateSocketFactory
W/Uploader( 2074): No account for auth token provided
D/dalvikvm( 2074): GC_CONCURRENT freed 968K, 21% free 3803K/4808K, paused 10ms+10ms, total 20ms
W/Uploader( 2074):  no longer exists, so no auth token.
D/dalvikvm( 1880): GC_FOR_ALLOC freed 625K, 24% free 2691K/3524K, paused 10ms, total 10ms
D/dalvikvm( 1880): GC_CONCURRENT freed 0K, 24% free 2707K/3524K, paused 10ms+0ms, total 10ms
D/dalvikvm( 1880): GC_CONCURRENT freed 639K, 24% free 2682K/3516K, paused 0ms+0ms, total 0ms
D/BstCommandProcessor-httpd( 1896): command: ping
D/BstCommandProcessor-httpd( 1896): response: {"result":"ok"}
D/BstCommandProcessor-httpd( 1896): command: clipboard (with args)
D/BstCommandProcessor-httpd( 1896): response: {"result":"ok"}
D/BstCommandProcessor-httpd( 1896): command: ping
D/BstCommandProcessor-httpd( 1896): response: {"result":"ok"}
D/BstCommandProcessor-httpd( 1896): command: clipboard (with args)
D/BstCommandProcessor-httpd( 1896): response: {"result":"ok"}
D/dalvikvm( 1880): GC_FOR_ALLOC freed 623K, 24% free 2691K/3516K, paused 0ms, total 0ms
D/dalvikvm( 1880): GC_CONCURRENT freed 0K, 23% free 2707K/3516K, paused 0ms+0ms, total 0ms
W/ActivityManager( 1721): Unable to start service Intent { act=com.google.android.gms.droidguard.service.START pkg=com.google.android.gms } U=0: not found
E/GmsClient( 2074): unable to connect to service: com.google.android.gms.droidguard.service.START
W/ActivityManager( 1721): Unbind failed: could not find connection for android.os.BinderProxy@3319d868
W/GLSUser ( 2074): [AppCertManager] IOException while requesting key:
W/GLSUser ( 2074): java.io.IOException: Invalid device key response.
W/GLSUser ( 2074):      at com.google.android.gms.auth.be.appcert.a.a(SourceFile:303)
W/GLSUser ( 2074):      at com.google.android.gms.auth.be.appcert.a.a(SourceFile:134)
W/GLSUser ( 2074):      at com.google.android.gms.auth.be.appcert.b.a(SourceFile:43)
W/GLSUser ( 2074):      at com.google.android.gms.auth.b.b.a(SourceFile:62)
W/GLSUser ( 2074):      at com.google.android.gms.auth.b.a.a(SourceFile:120)
W/GLSUser ( 2074):      at com.google.android.gms.auth.b.a.a(SourceFile:61)
W/GLSUser ( 2074):      at com.google.android.gms.auth.be.cron.AuthCronService.a(SourceFile:44)
W/GLSUser ( 2074):      at com.google.android.gms.gcm.ar.run(SourceFile:131) 
```

**Comment by FrankSpierings** [comment]
Checkout https://github.com/frida/frida/issues/426. Might this be related?

**Comment by oleavr** [comment]
Fixed in latest versions.
