### ISSUE TITLE
 Failed to attach to a app process

### ISSUE THREAD

**Issue by henrymark92** [frida/frida#444]
I'm using on this emulator. I cannot attach to a app process.
Emulator:
http://www.mediafire.com/file/chzx2cymbvyj5l6/BlueStacks+App+Player+0.9.24.5311+Superuser+BSEasy+-+bo+2.msi

```
Traceback (most recent call last):
  File "D:/source/temp/test_frida/hog_test.py", line 33, in <module>
    process = frida.get_usb_device().attach('com.example.seccon2015.rock_paper_scissors')
  File "C:\python32\python-2.7.10\lib\site-packages\frida\core.py", line 97, in attach
    return Session(self._impl.attach(self._pid_of(target)))
  File "C:\python32\python-2.7.10\lib\site-packages\frida\core.py", line 115, in _pid_of
    return self.get_process(target).pid
  File "C:\python32\python-2.7.10\lib\site-packages\frida\core.py", line 73, in get_process
    raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)
frida.ProcessNotFoundError: unable to find process with name 'com.example.seccon2015.rock_paper_scissors'
```

**Comment by enovella** [comment]
Please provide more info about your issue. E.g. frida version, architecture, code snippets, OS host, OS target, etc etc

**Comment by srcdes** [comment]
Same here. The code snippet is in https://www.frida.re/docs/examples/android/ . The first example source code.

```bash
$ frida --version
12.7.5

$ adb root
adbd is already running as root

$ adb shell getprop ro.product.cpu.abi
x86
```

**Comment by selltool** [comment]
Me too
