### ISSUE TITLE
Object args inspect

### ISSUE THREAD

**Issue by H4oK3** [frida/frida#465]
Hi,

I would like to ask if there is a good way of doing sth like this:

~~~JAVA
// in Android code, isLit function takes an object as an argument
LitClazz lc = new LitClazz();
isLit(lc)

// LitClazz contains couple fields with different types such as String, int, etc. Or even it can contains another class objects
public class LitClazz {
    String str_lit = "7331";
    int int_lit = 7331;
    ...
}
~~~

And I would like to intercept `isLit` method and change the lc object and replace that `lc` arg with the modified object.

The problem is: when I tried to do that in frida; I got sth like this, that I cannot directly access the member variable within that class object:

~~~
[LGE Nexus 5X::com.ha0k3.overloads]-> lc = args[0]
{
    "": {},
    "$handle": "0x1004da",
    "$weakRef": 8
}
[LGE Nexus 5X::com.ha0k3.overloads]-> lc
{
    "": {},
    "$handle": "0x1004xx",
    "$weakRef": 8
}

[LGE Nexus 5X::com.ha0k3.overloads]-> lc.int_lit
Traceback (most recent call last):
  File "/usr/local/bin/frida", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/frida/repl.py", line 686, in main
    app.run()
  File "/usr/local/lib/python2.7/site-packages/frida/application.py", line 163, in run
    self._reactor.run()
  File "/usr/local/lib/python2.7/site-packages/frida/application.py", line 388, in run
    self._run_until_return(self)
  File "/usr/local/lib/python2.7/site-packages/frida/repl.py", line 254, in _process_input
    if not self._eval_and_print(expression):
  File "/usr/local/lib/python2.7/site-packages/frida/repl.py", line 260, in _eval_and_print
    (t, value) = self._evaluate(expression)
  File "/usr/local/lib/python2.7/site-packages/frida/repl.py", line 416, in _evaluate
    result = self._script.exports.evaluate(text)
  File "/usr/local/lib/python2.7/site-packages/frida/core.py", line 425, in method
    return script._rpc_request('call', js_name, args)
  File "/usr/local/lib/python2.7/site-packages/frida/core.py", line 355, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: VM::GetEnv failed: -2
    at e (frida/node_modules/frida-java/lib/result.js:7)
    at frida/node_modules/frida-java/lib/vm.js:72
    at input:1
    at frida/node_modules/frida-java/lib/class-factory.js:1192
    at stringify (native)
    at frida/runtime/core.js:50
    at c (frida/runtime/message-dispatcher.js:66)
    at e (frida/runtime/message-dispatcher.js:55)
    at t (frida/runtime/message-dispatcher.js:24)
~~~

I would like to ask for some advice on better ideas of doing this.

**Comment by SimonKoh** [comment]
I see your error is "frida.core.RPCException: Error: VM::GetEnv failed: -2",maybe you should use "lc.int_lit" in "Java.perform()".
Besides,if it doesn't work,you can use "Java.cast(Object,Java.use("your class"))",maybe you can get obj's field.

**Comment by SimonKoh** [comment]
Hey H4oK3, i have tried Java reflect,and it works, here is my Person.java:

```
public class Person {
    public String name;
    public int age;
    Person(String name,int age){
        this.name = name;
        this.age = age;
    }
    public String getName(){
        return this.name;
    }
    public int getAge() {
        return this.age;
    }
}
```

And i've wrote a test() method in MainActivity.java:

```
public class MainActivity extends AppCompatActivity {
    private static final String TAG = "MainActivity";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Button b = findViewById(R.id.button);
        b.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Person p = new Person("Simon",99);
                test(p);
            }
        });

    }
    public void test(Person test){
        Log.d(TAG, "test: " + test.name); 
    }
}
```
I just log person's name  in text(),and call test() in onClick() method,when i click button,then i can get person's name "Simon" in logcat.

> 04-05 02:59:59.513 8033-8033/com.simon.persontest D/MainActivity: test: Simon

What i want is to hook test() method and modify person's name and log it,here is my JS code:

```
Java.perform(function(){
    person = Java.use("com.simon.persontest.Person")
    main = Java.use("com.simon.persontest.MainActivity")
    field = Java.use("java.lang.reflect.Field")
    clazz = Java.use("java.lang.Class")
    main.test.implementation = function(p){
        var tmp = p
        console.log(tmp)
        var field_name = Java.cast(tmp.getClass(),clazz).getDeclaredField("name")
        field_name.setAccessible(true)
        field_name.set(tmp,"H4oK3")
        return this.test(p)
    }
});
```
Log is:

> 04-05 03:00:16.499 8033-8033/com.simon.persontest D/MainActivity: test: H4oK3


Here you see, i hook test method and modifiy Person's name to "H4oK3".Run JS code and click button you can see "H4oK3" in logcat instead.Then H40K3 Hacked.

**Comment by oleavr** [comment]
Must be accessed in `Java.perform()` or `Java.performNow()` since the Frida JS thread is not attached to the VM. (The REPL runs code on that thread.) Also make sure you do `lc = Java.retain(arg)`, so you create a global reference to the value so it doesn't get GCed after the method returns. This global reference then gets cleaned up when your variable gets GCed.
