### ISSUE TITLE
frida.TransportError: the connection is closed

### ISSUE THREAD

**Issue by leiyugithub** [frida/frida#525]
E:\Python36\python.exe E:/pychram/Frida-Server/test.py
Application(identifier="cn.kooki.app.chezhen", name="车镇车源", pid=1622)
Traceback (most recent call last):
  File "E:/pychram/Frida-Server/test.py", line 6, in <module>
    session = rdev.attach("cn.kooki.app.chezhen")
  File "E:\Python36\lib\site-packages\frida\core.py", line 108, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.TransportError: the connection is closed

when i use get_frontmost_application() it worked well but when  i use  attach() it make some  mistake 
so how to solve this proplem ?  plz!

**Comment by cvt126** [comment]
you should use 
adb forward tcp:27042 tcp:27042
adb forward tcp:27043 tcp:27043
