### ISSUE TITLE
npm install frida, GypError: binding.gyp not found (cwd: /Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/frida) while trying to load binding.gyp

### ISSUE THREAD

**Issue by huhuang03** [frida/frida#556]
It seems I run `npm i -g frida` failed. May be after I update brew? I can't remember.
I follow this step
```
pip install frida-tools # CLI tools
pip install frida       # Python bindings
npm install frida       # Node.js bindings
```
And It failed at last `npm install frida`, the full log is:
```
('Unexcepted error: ', <class 'gyp.common.GypError'>)
binding.gyp not found (cwd: /Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/frida) while trying to load binding.gyp
Traceback (most recent call last):
  File "/Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 539, in main
    return gyp_main(args)
  File "/Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 515, in gyp_main
    options.duplicate_basename_check)
  File "/Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 131, in Load
    params['parallel'], params['root_targets'])
  File "/Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2779, in Load
    variables, includes, depth, check, True)
  File "/Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 395, in LoadTargetBuildFile
    includes, True, check)
  File "/Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
    raise GypError("%s not found (cwd: %s)" % (build_file_path, os.getcwd()))
GypError: binding.gyp not found (cwd: /Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Users/th/.nvm/versions/node/v9.4.0/bin/node" "/Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/th/.nvm/versions/node/v9.4.0/lib/node_modules/frida
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.0.3 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frida@12.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/th/.npm/_logs/2018-07-16T05_57_42_359Z-debug.log
```
I cant' figure out what's failed at all, seems `prebuild-install` can't generate binding.gyp?  I'm not familiar to node. Any info can help?

**Comment by oleavr** [comment]
binding.gyp and the C++ source code is not part of the module in npm. This is by design, as it's not possible to compile this code without also having frida-core already built. So the issue here is that prebuild fails to download a prebuilt binding for your system. Firewall issue perhaps?

**Comment by huhuang03** [comment]
Thank you for your replay, 
It's my network issue, I'm in China and some site can't access.

**Comment by pharazone** [comment]
I have the same issue, how can I solve this? Thank you.
