### ISSUE TITLE
Installing 12.0.5 via pip3 - network query failed

### ISSUE THREAD

**Issue by TiffanyBlue** [frida/frida#569]
I've tried to update/install to 12.0.5 via pip3(python3.6.6) on Ubuntu16.04.4, but the installation fails.

This is error output.

Running setup.py install for frida ... error
    Complete output from command /usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-d58ajzw5/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5406jsva/install-record.txt --single-version-externally-managed --compile:
    /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/frida
    copying frida/core.py -> build/lib.linux-x86_64-3.6/frida
    copying frida/__init__.py -> build/lib.linux-x86_64-3.6/frida
    running build_ext
    querying pypi for available prebuilds
    downloading prebuilt extension from https://files.pythonhosted.org/packages/48/67/3d2799b8834a67ea7483a1747f50165028d88bda447fe628b01071df02c4/frida-12.0.5-py3.6-linux-x86_64.egg
    network query failed
    looking for prebuilt extension in home directory, i.e. /root/frida-12.0.5-py3.6-linux-x86_64.egg
    no prebuilt extension found in home directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d58ajzw5/frida/setup.py", line 178, in <module>
        'build_ext': FridaPrebuiltExt
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-d58ajzw5/frida/setup.py", line 126, in build_extension
        raise network_error
      File "/tmp/pip-install-d58ajzw5/frida/setup.py", line 109, in build_extension
        egg_data = urlopen(egg_url).read()
      File "/usr/local/lib/python3.6/http/client.py", line 462, in read
        s = self._safe_read(self.length)
      File "/usr/local/lib/python3.6/http/client.py", line 614, in _safe_read
        raise IncompleteRead(b''.join(s), amt)
    http.client.IncompleteRead: IncompleteRead(786432 bytes read, 19903684 more expected)
    
    ----------------------------------------
Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-d58ajzw5/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5406jsva/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-d58ajzw5/frida/

**Comment by minhtt159** [comment]
I don't know if this is safe, but, have you tried `sudo pip3`?
