### ISSUE TITLE
process attach problem

### ISSUE THREAD

**Issue by mahmutyazici** [frida/frida#574]
Hi all,

I have problem regarding to attaching process in frida.

I use santoku VM and genymotion business.  I have installed frida 12.0.7(latest version) on santoku and frida-server 12.0.7 for the android. I got response when I typed "frida-ps -U" successfully like below. 

> root@santoku1:.../Bonus# frida-ps -U | grep diva
> 1741  jakhar.aseem.diva

**But when I tried to write small python script like that:**

> import frida,sys
> 
> device=frida.get_usb_device()
> session = device.attach('jakhar.aseem.diva')
> print session

**I got following error:**

> root@santoku1:.../Bonus# python first_frida.py 
> Traceback (most recent call last):
>   File "first_frida.py", line 4, in <module>
>     session = device.attach('jakhar.aseem.diva')
>   File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 108, in attach
>     return Session(self._impl.attach(self._pid_of(target)))
>   File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 126, in _pid_of
>     return self.get_process(target).pid
>   File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 67, in get_process
>     matching = [process for process in self._impl.enumerate_processes() if fnmatch.fnmatchcase(process.name.lower(), process_name_lc)]
> frida.ProtocolError: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use

**By the way I also tried pid instead process name and the result was same.

When I tried something like following:**

> import frida,sys
> 
> session = frida.attach(1741)
> print session

**I got following error:**

> root@santoku1:.../Bonus# python first_frida.py 
> Traceback (most recent call last):
>   File "first_frida.py", line 6, in <module>
>     session = frida.attach(1741)
>   File "/usr/local/lib/python2.7/dist-packages/frida/__init__.py", line 57, in attach
>     return get_local_device().attach(target)
>   File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 108, in attach
>     return Session(self._impl.attach(self._pid_of(target)))
> frida.ProcessNotFoundError: unable to find process with pid 1741

Can you help me please?
Regards.

**Comment by HD421** [comment]
Hi, find your "USB" device like this
`device = frida.get_device_manager().enumerate_devices()[-1]`
then attach to your process: `session = device.attach('1741')`
