### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\xd6' 

### ISSUE THREAD

**Issue by qssq** [frida/frida#586]
cmd
```
frida-trace -U -i compare -i fstream -i isstream -i ofstream -i strstr -i strncat -i strcspn -i strcpy -i strcoll -i strchr -i *open -i *cmp -i exit -i system -i *kill -i gets -i printf -i tmpnam -i strcat cn.com.cycfc.cyxfjrapp>d:/record_all1.txt
```

exception:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\users\administrator\anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\administrator\anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\administrator\anaconda3\lib\site-packages\frida_tools\application.py", line 420, in
 _run
    work()
  File "c:\users\administrator\anaconda3\lib\site-packages\frida_tools\tracer.py", line 482, in <lam
bda>
    self._reactor.schedule(lambda: self._process_message(message, data, ui))
  File "c:\users\administrator\anaconda3\lib\site-packages\frida_tools\tracer.py", line 629, in _pro
cess_message
    ui.on_trace_events(events)
  File "c:\users\administrator\anaconda3\lib\site-packages\frida_tools\tracer.py", line 109, in on_t
race_events
    self._print("%6d ms  %s%s%s%s" % (timestamp, attributes, indent, message, no_attributes))
  File "c:\users\administrator\anaconda3\lib\site-packages\frida_tools\application.py", line 335, in
 _print
    print(*encoded_args, **kwargs)
  File "c:\users\administrator\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 40, in wri
te
    self.__convertor.write(text)
  File "c:\users\administrator\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 141, in wr
ite
    self.write_and_convert(text)
  File "c:\users\administrator\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 166, in wr
ite_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\users\administrator\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 174, in wr
ite_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'gbk' codec can't encode character '\xd6' in position 8: illegal multibyte seque
nce




```

**Comment by qssq** [comment]
strstr cause?
