### ISSUE TITLE
frida.attach not working if a process is not resumed

### ISSUE THREAD

**Issue by andreafioraldi** [frida/frida#616]
Hi guys,
I'm trying to understand how to spawn a process with frida.

Consider this code:
```python
import frida

def on_message(message, data):
    print("[on_message] message:", message, "data:", data)

pid = frida.spawn("/bin/cat")
#frida.resume(pid)

session = frida.attach(pid)

script = session.create_script("""'use strict';

rpc.exports.enumerateModules = function () {
  return Process.enumerateModulesSync();
};
""")
script.on("message", on_message)
script.load()

print([m["name"] for m in script.exports.enumerate_modules()])
```

It gives me this error:
```Traceback (most recent call last):
  File "frida_ex.py", line 9, in <module>
    session = frida.attach(pid)
  File "/home/andrea/.local/lib/python2.7/site-packages/frida/__init__.py", line 59, in attach
    return get_local_device().attach(target)
  File "/home/andrea/.local/lib/python2.7/site-packages/frida/core.py", line 110, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.NotSupportedError: remote_exec PTRACE_CONT wait failed: 0
```

But with the `frida.resume(pid)` call before attach it works.

Now i have a binary that is not like cat and doesn't hang so i don't want to resume it before the script injection. Is that possible?

Thanks.

**Comment by andreafioraldi** [comment]
Same issue with the cli, i think is a problem of frida with my os.

```
$ frida ./ais3_crackme ppp
     ____
    / _  |   Frida 12.1.0 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to attach: remote_exec PTRACE_CONT wait failed: 0
```

I'm using ubuntu 18.04, libc version: GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1) stable release version 2.27.
ptrace_scope is 0.
