### ISSUE TITLE
ImportError: DLL load failed:

### ISSUE THREAD

**Issue by cvt126** [frida/frida#618]
C:\Users\Administrator>frida

***
Failed to load the Frida native extension: DLL load failed: 找不到指定的模块。
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "D:\Program Files\Python36\Scripts\frida-script.py", line 11, in <module>

    load_entry_point('frida-tools==1.2.1', 'console_scripts', 'frida')()
  File "d:\program files\python36\lib\site-packages\frida_tools\repl.py", line 2
2, in main
    import frida
  File "d:\program files\python36\lib\site-packages\frida\__init__.py", line 24,
 in <module>
    raise ex
  File "d:\program files\python36\lib\site-packages\frida\__init__.py", line 7,
in <module>
    import _frida
ImportError: DLL load failed: 找不到指定的模块。

**Comment by cvt126** [comment]
I use python 3.6.6 and win 7 64

**Comment by oleavr** [comment]
The latest binaries were built for Python 3.7. Did you try upgrading to 3.7?

**Comment by cvt126** [comment]
I used 3.7 but no  solution，and I copy the 3.6.6 from my friend to solution.

**Comment by apoorvumang** [comment]
For me it was the opposite, 3.6.6 didn't work but 3.7 did

**Comment by raulsiles** [comment]
Potentially this issue is now fixed in Frida version 15.1.17. See #1878.
