### ISSUE TITLE
Frida-CLI REPL -- AttributeError on SyntaxError under Python 3.4

### ISSUE THREAD

**Issue by 0xABD** [frida/frida#65]
Frida-CLI REPL relies on Exception.message, which fails if run under Python 3.4:
```
File "C:\Python34\lib\site-packages\frida-4.4.0-py3.4-win-amd64.egg\frida\repl.py", line 167, in _eval_and_print
AttributeError: 'Exception' object has no attribute 'message'
```
Looks like `Exception.message` has been deprecated since Python 2.6. 

Full python backtrace:
```
C:\>frida -R 13662
    _____
   (_____)
    |   |    Frida 4.4.0 - A world-class dynamic instrumentation framework
    |   |
    |`-'|    Commands:
    |   |        help      -> Displays the help system
    |   |        object?   -> Display information about 'object'
    |   |        exit/quit -> Exit
    |   |
    |   |    More info at http://www.frida.re/docs/home/
    `._.'

[Remote::PID::13662]-> ?Array
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\frida-4.4.0-py3.4-win-amd64.egg\frida\repl.py", line 157, in _eval_and_print
  File "C:\Python34\lib\site-packages\frida-4.4.0-py3.4-win-amd64.egg\frida\repl.py", line 329, in _evaluate
Exception: {'message': 'Unexpected token ?', 'name': 'SyntaxError'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\frida-script.py", line 9, in <module>
    load_entry_point('frida==4.4.0', 'console_scripts', 'frida')()
  File "C:\Python34\lib\site-packages\frida-4.4.0-py3.4-win-amd64.egg\frida\repl.py", line 518, in main
  File "C:\Python34\lib\site-packages\frida-4.4.0-py3.4-win-amd64.egg\frida\application.py", line 125, in run
  File "C:\Python34\lib\site-packages\frida-4.4.0-py3.4-win-amd64.egg\frida\application.py", line 278, in run
  File "C:\Python34\lib\site-packages\frida-4.4.0-py3.4-win-amd64.egg\frida\repl.py", line 153, in _process_input
  File "C:\Python34\lib\site-packages\frida-4.4.0-py3.4-win-amd64.egg\frida\repl.py", line 167, in _eval_and_print
AttributeError: 'Exception' object has no attribute 'message'
```

**Comment by oleavr** [comment]
Thanks for reporting! This has recently been fixed and the fix will make it into the next release.
