### ISSUE TITLE
 DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by baptistapedro** [frida/frida#656]
C:\Users\G>frida -v

***
Failed to load the Frida native extension: DLL load failed: The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
File "C:\Users\G\AppData\Local\Programs\Python\Python35\Scripts\frida-script.py", line 9, in <module>
load_entry_point('frida-tools==1.2.2', 'console_scripts', 'frida')()
File "c:\users\g\appdata\local\programs\python\python35\lib\site-packages\frida_tools\repl.py", line 22, in main
import frida
File "c:\users\g\appdata\local\programs\python\python35\lib\site-packages\frida\__init__.py", line 24, in <module>
raise ex
File "c:\users\g\appdata\local\programs\python\python35\lib\site-packages\frida\__init__.py", line 7, in <module>
import _frida
ImportError: DLL load failed: The specified module could not be found.

-----------------

Not sure why I'm having this issue, I've reinstalled the package and python a couple times now...
Any ideas?

**Comment by oleavr** [comment]
Our current Windows binaries require Python 3.7. You'll have to build Frida yourself if you need to use a different version of Python.

**Comment by raulsiles** [comment]
Potentially this issue is now fixed in Frida version 15.1.17. See #1878.
