### ISSUE TITLE
Stalker either stalks itself or causes a segfault

### ISSUE THREAD

**Issue by kikones34** [frida/frida#672]
I've been trying to use the Stalker API to trace all 'call' instructions executed in my single-thread program.

If I use the following code:

```JavaScript
Stalker.follow({
    events: {
        call: true
    },
    onReceive: function (events) {
        console.log(Stalker.parse(events));
    }
});
```

Frida proceeds to stalk itself and endlessly shows calls way out of the memory region of the program I'm hooking.
This is because apparently, Frida stalks a Frida-created thread by default.
Specifying `Process.getCurrentThreadId()` as the first argument produces the exact same result.
Using the `transform` API also produces the same result. I've also verified that the iterator starts outside the memory region of my program and keeps incrementing infinitely.

After seeing this, I figured I'd have to manually specify the correct thread to stalk.
When I attach Frida to my program, 4 additional threads are created. There is only one thread which stays constant when attaching and detaching Frida. Thus, I figured this thread must be my program's thread.

Now, if I specify this thread as the first argument to the Stalker, my hooked program segfaults and Frida dies with the following error:

```Python
Traceback (most recent call last):
  File "test.py", line 66, in <module>
    S.stalk_calls()
  File "/usr/local/lib/python3.6/dist-packages/frida/core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "/usr/local/lib/python3.6/dist-packages/frida/core.py", line 250, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script is destroyed
```

I'm not sure if I'm doing something wrong or if this is an issue with Frida.
Any help is appreciated!

Some info:
OS: Kali Linux (Virtual Machine)
Architecture: x86_64
Frida version: 12.2.11

**Comment by kikones34** [comment]
Most likely doesn't apply anymore.
