### ISSUE TITLE
Error: Unable to determine ArtMethod field offsets (Android)

### ISSUE THREAD

**Issue by h3xstream** [frida/frida#679]
## Error

Tested with : 12.2.18 and 12.2.16

```
generic_x86:/data/local/tmp # ./frida-server
{"type":"error","description":"Error: Unable to determine ArtMethod field offsets" ,
"stack":"Error: Unable to determine ArtMethod field offsets\n
    at vm.perform (frida/node_modules/frida-java/lib/android.js:506:1)\n
    at VM.perform (frida/node_modules/frida-java/lib/vm.js:43:1)\n
    at _getArtMethodSpec (frida/node_modules/frida-java/lib/android.js:467:1)\n
    at frida/node_modules/frida-java/lib/android.js:1446:1\n
    at Function.replaceArtImplementation [as implementation] (frida/node_modules/frida-java/lib/class-factory.js:1662:1)\n
    at Function.set [as implementation] (frida/node_modules/frida-java/lib/class-factory.js:1443:1)\n
    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:177:24)\n
    at init (/internal-agent.js:26:3)\n
    at VM.perform (frida/node_modules/frida-java/lib/vm.js:43:1)\n
    at performPending (frida/node_modules/frida-java/index.js:347:1)",
"fileName":"frida/node_modules/frida-java/lib/android.js",
"lineNumber":506,
"columnNumber":1}
```

I later get this message trying to override methods:
```
 Error: access violation accessing 0x8
    at replaceArtImplementation (frida/node_modules/frida-java/lib/class-factory.js:1669)
    at frida/node_modules/frida-java/lib/class-factory.js:1443
    at /_java.js:2434
    at frida/node_modules/frida-java/lib/vm.js:39
    at /_java.js:2442
    at [anon] (/repl1.js:32)
    at frida/runtime/core.js:57
```

## OS version

Image: Nexus 5X API 28 x86

```
generic_x86:/data/local/tmp # uname -a
Linux localhost 4.4.124+ #1 SMP PREEMPT Sat Apr 28 14:33:54 UTC 2018 i686
```

**Comment by h3xstream** [comment]
I'm reading from unofficial source that Frida only works on really old images (Android 6 and below). I'm not sure if this is the case.

**Comment by oleavr** [comment]
My primary test device is a Nexus 5X running 8.1.0, so that's currently the best-supported version. Which ROM would you recommend for Android 9?

**Comment by h3xstream** [comment]
API 27 is working 👍

Thanks

**Comment by jkryanchou** [comment]
@h3xstream Could you modify script.js without restarting app.?

**Comment by h3xstream** [comment]
@jkryanchou The stack trace I had was a compatibility issue with Frida and API 28 images.

**Comment by jkryanchou** [comment]
@h3xstream Yeah, I upgrade my Android version from 5.5.1 to 6.1. It works well.
