### ISSUE TITLE
(Android): Is it Bug? Can not hook Android.os.Parcel

### ISSUE THREAD

**Issue by a1t3r570** [frida/frida#693]
I try to hook 'Android.os.Parcel',but frida did not get any errors and no feedback.
```
Java.perform(function(){
    var Parcel = Java.use("android.os.Parcel");
    Parcel.readInt.implementation = function(){
        send("readInt.");
        this.readInt();
    }
});
```
and I also hook the C++'s parcel,like this:
```
Interceptor.attach(Module.findExportByName("libbinder.so","_ZNK7android6Parcel9readInt32Ev"),{
    onEnter: function(args){
        send("int32");
    },
    onLeave: function(retval){
    }
});
```
The result is that c++ can be hooked, but java doesn't work. I am a bit confused, calendar apk should not call c++ parcel through java parcel? What is the reason for not getting it? If I misunderstand the parcel mechanism, please correct me.Thank you so much!

**Comment by wuliqilin** [comment]
Then I did some experiments, I used frida hook IAlarmManager$Stub$Proxy set(...) ,
```
//IAlarmManager.java
 public void set(int type, long triggerAtTime, long windowLength,
                long interval, int flags, android.app.PendingIntent operation,
                android.os.WorkSource workSource,
                android.app.AlarmManager.AlarmClockInfo alarmClock)
                throws android.os.RemoteException {
                android.os.Parcel _data = android.os.Parcel.obtain();
                android.os.Parcel _reply = android.os.Parcel.obtain();

                try {
                    _data.writeInterfaceToken(DESCRIPTOR);
                    _data.writeInt(type);
                    _data.writeLong(triggerAtTime);
                    _data.writeLong(windowLength);
                    _data.writeLong(interval);
                    _data.writeInt(flags);
```

 and at the same time hook **writeInt**(int), **nativewriteInt**(,), **writeLong**(long),**nativewriteLong**(,), 
```
// Parcel.java
public final void writeInt(int val) {
    nativeWriteInt(mNativePtr, val);
}
public final void writeLong(long val) {
    nativeWriteLong(mNativePtr, val);
}
```
the result can only print about native*. 
```
...
{u'type': u'send', u'payload': u'IAramManager--set--'}
{u'type': u'send', u'payload': u'nativeWriteInt.'}
{u'type': u'send', u'payload': u'nativeWriteLong.'}
{u'type': u'send', u'payload': u'nativeWriteLong.'}
{u'type': u'send', u'payload': u'nativeWriteLong.'}
{u'type': u'send', u'payload': u'nativeWriteInt.'}
{u'type': u'send', u'payload': u'nativeWriteInt.'}
{u'type': u'send', u'payload': u'nativeWriteInt.'}
{u'type': u'send', u'payload': u'nativeWriteInt.'}
{u'type': u'send', u'payload': u'--end--IAramManager--set--'}
...
```
At first I guess it maybe course by jvm inline function optimization, I don't know if this is right.
And Then I use Xposed hook writeInt(int) at the same time, the result can print writeInt and right stacktrace. 
```
D/fuzz-writeInt( 1110): writeInt
D/fuzz-writeInt( 1110): java.lang.Exception
D/fuzz-writeInt( 1110): 	at buptnsrc.com.xposed_example.Main$3.afterHookedMethod(Main.java:61)
D/fuzz-writeInt( 1110): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
D/fuzz-writeInt( 1110): 	at android.os.Parcel.writeInt(<Xposed>)
D/fuzz-writeInt( 1110): 	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:165)
D/fuzz-writeInt( 1110): 	at android.app.AlarmManager.setImpl(AlarmManager.java:409)
D/fuzz-writeInt( 1110): 	at android.app.AlarmManager.set(AlarmManager.java:208)
D/fuzz-writeInt( 1110): 	at com.example.android.apis.app.AlarmController$1.onClick(AlarmController.java:102)
D/fuzz-writeInt( 1110): 	at android.view.View.performClick(View.java:4780)
D/fuzz-writeInt( 1110): 	at android.view.View$PerformClick.run(View.java:19866)
D/fuzz-writeInt( 1110): 	at android.os.Handler.handleCallback(Handler.java:739)
D/fuzz-writeInt( 1110): 	at android.os.Handler.dispatchMessage(Handler.java:95)
D/fuzz-writeInt( 1110): 	at android.os.Looper.loop(Looper.java:135)
D/fuzz-writeInt( 1110): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
D/fuzz-writeInt( 1110): 	at java.lang.reflect.Method.invoke(Native Method)
D/fuzz-writeInt( 1110): 	at java.lang.reflect.Method.invoke(Method.java:372)
D/fuzz-writeInt( 1110): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
D/fuzz-writeInt( 1110): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
D/fuzz-writeInt( 1110): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```
Is this a bug? Is it wrong with my use of frida, how to fix it? help me！

**Comment by stevepoland85** [comment]
Try adding a return to your Java readInt, i.e., `return this.readInt()`.

**Comment by wuliqilin** [comment]
> Try adding a return to your Java readInt, i.e., `return this.readInt()`.
> 
> Worked fine for me on:
> 
> > `frida -U <some app>`
> > Paste in your code
> > I see a bunch of messages and it crashes (Probably due to no return)
> > message: {'type': 'send', 'payload': 'readInt.'} data: None
> > I try with the return, and see a bunch of messages and no crash.

emm..,it doesn't work for me. 
my test environment is:
frida 12.2.5
emulator 
android6.0
x86
test-app:API demos (system app)[com.example.android.apis/.AlarmController]
Can you elaborate on the details? Like,android version?frida verison?emulator or real machine?x86 or arm? I can't reproduce.Thank you so much,it's important for me.

**Comment by stevepoland85** [comment]
Nexus 5x Android 6.0 Rooted | Frida 12.2.22 | com.google.android.deskclock

**Comment by wuliqilin** [comment]
> Nexus 5x Android 6.0 Rooted | Frida 12.2.22 | com.google.android.deskclock

emmm.., I did it follow your context. Although it(readInt/writeInt) can be caught occasionally,it is not what I want. To make the problem more directional, please consider to hook the specified method like IAramManager.set(),like this:
```
Java.perform(function(){
    var ibinder = Java.use("android.app.IAlarmManager$Stub$Proxy");
    ibinder.set.overload('int', 'long','long','long','int', 'android.app.PendingIntent','android.os.WorkSource','android.app.AlarmManager$AlarmClockInfo').implementation = function(a,b,c,d,e,f,g,h){
        send("IAramManager--set--");
        var res = this.set(a,b,c,d,e,f,g,h);
        send("--end--IAramManager--set--");
        return res;
    }
});
Java.perform(function(){
    var Parcel = Java.use("android.os.Parcel");
    Parcel.writeInt.implementation = function(i){
        send("writeInt.");
        return this.writeInt(i);
    }
});
Java.perform(function(){
    var Parcel = Java.use("android.os.Parcel");
    Parcel.nativeWriteInt.implementation = function(a,b){
        send("nativeWriteInt.");
        return this.nativeWriteInt(a,b);
    }
});
```
And you can trigger set() by setting an alarm enable in com.google.android.deskclock.
The call relationship between the methods, please see my second comment. In my test,result is:
```
{u'type': u'send', u'payload': u'IAramManager--set--'}
{u'type': u'send', u'payload': u'nativeWriteInt.'}
{u'type': u'send', u'payload': u'nativeWriteInt.'}
{u'type': u'send', u'payload': u'nativeWriteInt.'}
{u'type': u'send', u'payload': u'nativeWriteInt.'}
{u'type': u'send', u'payload': u'nativeWriteInt.'}
{u'type': u'send', u'payload': u'--end--IAramManager--set--'}
```
But according to the source code, it should hook to writeInt, and I can hook to writeInt with Xposed.
If your results are different from me, please let me know. Thank you for your reply.
