### ISSUE TITLE
error in binding frida and python

### ISSUE THREAD

**Issue by J4ckt0rr4nc3** [frida/frida#697]
hello guys as i run python 1.py i got this error 
python 1.py 
Traceback (most recent call last):
  File "1.py", line 5, in <module>
    pid = device.spawn(["com.example.a11x256.frida_test"])
  File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 98, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.TransportError: the connection is closed

and i have mentioned the result of  adb devices in the following:

List of devices attached
emulator-5554	device
192.168.56.101:5555	device

and frida-ps -U is coming in the following

 PID  Name
----  ---------------------------------------
  55  adbd
6051  android.process.acore
5968  android.process.media
5877  com.android.browser
5472  com.android.deskclock
6025  com.android.dialer
4386  com.android.inputmethod.latin
4440  com.android.launcher
4423  com.android.phone
6134  com.android.sharedstoragebackup
4529  com.android.smspush
4236  com.android.systemui
5926  com.android.vending
5709  com.example.a11x256.frida_test
6076  com.google.android.gm
4681  com.google.android.gms
.
.
.
the frida works fine but i have some trouble when using automation with python
and my python is 2.7 and when i have used python3 with 1.py i got this following error
Traceback (most recent call last):
  File "1.py", line 2, in <module>
    import frida
ModuleNotFoundError: No module named 'frida'

and my 1.py file is in the following too
#python code
import frida
import time
device = frida.get_usb_device(1)
pid = device.spawn(["com.example.a11x256.frida_test"])
device.resume(pid)
time.sleep(1) #Without it Java.perform silently fails
session = device.attach(pid)
script = session.create_script(open("s1.js").read())
script.load()

#prevent the python script from terminating
raw_input()

is there any solution?

**Comment by J4ckt0rr4nc3** [comment]
@
