### ISSUE TITLE
Unable to determine ArtMethod field offsets (Android 9.0)

### ISSUE THREAD

**Issue by jasonross** [frida/frida#700]
`{"type":"error","description":"Error: Unable to determine ArtMethod field offsets","stack":"Error: Unable to determine ArtMethod field offsets\n    at vm.perform (frida/node_modules/frida-java/lib/android.js:506:1)\n    at VM.perform (frida/node_modules/frida-java/lib/vm.js:43:1)\n    at _getArtMethodSpec (frida/node_modules/frida-java/lib/android.js:467:1)\n    at frida/node_modules/frida-java/lib/android.js:1446:1\n    at Function.replaceArtImplementation [as implementation] (frida/node_modules/frida-java/lib/class-factory.js:1662:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java/lib/class-factory.js:1443:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:177:24)\n    at init (/internal-agent.js:26:3)\n    at VM.perform (frida/node_modules/frida-java/lib/vm.js:43:1)\n    at performPending (frida/node_modules/frida-java/index.js:347:1)","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":506,"columnNumber":1}`

try to run frida-server on an Android 9.0 device, and throws this error.

Any idea? Thanks a lot.

**Comment by stevepoland85** [comment]
Does Frida work on anybody's Android 9 device? I'm not sure Frida's been updated for Android 9.

**Comment by benji1801** [comment]
Hi,
I'm also on Android 9.0 device and Frida does not work... I've exactly same issue as you... :(

**Comment by jkryanchou** [comment]
Me too.. With same issue.

**Comment by eugenekolo** [comment]
I'm using a Samsung S4 on Android 9 and it works fine for me. So we need more device information about what's breaking.

Works:
Samsung S4 (jflte) arm7l
Android 9
LineageOS 16

**Comment by benji1801** [comment]
> I'm using a Samsung S4 on Android 9 and it works fine for me. So we need more device information about what's breaking.
> 
> Works:
> Samsung S4 (jflte) arm7l
> Android 9
> LineageOS 16
> 
> Edit: it actually does give me that error. But, hooks still seem to work, at least for native functions.
> `frida-trace -U -i 'read' com.android.messaging` and then playing around with the messaging app recorded a bunch of `read` calls.
> 
> Java hooks seem broken though.
> 
> ```
> [Samsung SGH-M919::com.android.messaging]-> Java.perform(function () {
>                                                 var bufferedReader = Java.use("java.io.BufferedReader");
>                                                 bufferedReader.close.implementation = function () {
>                                                     console.log("[*] close() got called!");
>                                                     this.close();
>                                                 };
>                                             });
> undefined
> Error: Unable to determine ArtMethod field offsets
>     at frida/node_modules/frida-java/lib/android.js:505
>     at frida/node_modules/frida-java/lib/vm.js:43
>     at x (frida/node_modules/frida-java/lib/android.js:527)
>     at frida/node_modules/frida-java/lib/android.js:1446
>     at replaceArtImplementation (frida/node_modules/frida-java/lib/class-factory.js:1662)
>     at frida/node_modules/frida-java/lib/class-factory.js:1443
>     at [anon] (input:6)
>     at frida/node_modules/frida-java/lib/vm.js:43
>     at frida/node_modules/frida-java/index.js:280
> ```
> This works however:
> 
> ```
> [Samsung SGH-M919::com.android.messaging]->Java.perform(function(){Java.enumerateLoadedClasses({"onMatch":function(className){ console.log(className) },"onComplete":function(){}})})
> bunch of things....
> ```

Yes I have same thing you, only java hook does not work... :(

**Comment by leezn** [comment]
OnePlus3:/data/local/tmp # ./frida-server &
./frida-server &
[1] 12640
OnePlus3:/data/local/tmp # {"type":"error","description":"Error: Unable to determine ArtMethod field offsets","stack":"Error: Unable to determine ArtMethod field offsets\n    at vm.perform (frida/node_modules/frida-java/lib/android.js:506:1)\n    at VM.perform (frida/node_modules/frida-java/lib/vm.js:43:1)\n    at _getArtMethodSpec (frida/node_modules/frida-java/lib/android.js:467:1)\n    at frida/node_modules/frida-java/lib/android.js:1446:1\n    at Function.replaceArtImplementation [as implementation] (frida/node_modules/frida-java/lib/class-factory.js:1662:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java/lib/class-factory.js:1443:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:177:24)\n    at init (/internal-agent.js:26:3)\n    at VM.perform (frida/node_modules/frida-java/lib/vm.js:43:1)\n    at performPending (frida/node_modules/frida-java/index.js:347:1)","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":506,"columnNumber":1}

oneplus3
nitrogen 9.0
android 9.0

**Comment by tfernandes** [comment]
Same issue. 

crosshatch:/data/local/tmp # ./frida-server                                                  
{"type":"error","description":"Error: Unable to determine ArtMethod field offsets","stack":"Error: Unable to determine ArtMethod field offsets\n    at vm.perform (frida/node_modules/frida-java/lib/android.js:506:1)\n    at VM.perform (frida/node_modules/frida-java/lib/vm.js:43:1)\n    at _getArtMethodSpec (frida/node_modules/frida-java/lib/android.js:467:1)\n    at frida/node_modules/frida-java/lib/android.js:1446:1\n    at Function.replaceArtImplementation [as implementation] (frida/node_modules/frida-java/lib/class-factory.js:1662:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java/lib/class-factory.js:1443:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:177:24)\n    at init (/internal-agent.js:26:3)\n    at VM.perform (frida/node_modules/frida-java/lib/vm.js:43:1)\n    at performPending (frida/node_modules/frida-java/index.js:347:1)","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":506,"columnNumber":1}

Android 9
Pixel 3XL 
Magisk Root

**Comment by rocco8620** [comment]
Same issue.

{"type":"error","description":"Error: Unable to determine ArtMethod field offsets","stack":"Error: Unable to determine ArtMethod field offsets\n    at vm.perform (frida/node_modules/frida-java/lib/android.js:505:1)\n    at VM.perform (frida/node_modules/frida-java/lib/vm.js:42:1)\n    at _getArtMethodSpec (frida/node_modules/frida-java/lib/android.js:466:1)\n    at frida/node_modules/frida-java/lib/android.js:1445:1\n    at Function.replaceArtImplementation [as implementation] (frida/node_modules/frida-java/lib/class-factory.js:1662:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java/lib/class-factory.js:1443:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:177:24)\n    at init (/internal-agent.js:26:3)\n    at VM.perform (frida/node_modules/frida-java/lib/vm.js:42:1)\n    at performPending (frida/node_modules/frida-java/index.js:347:1)","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":505,"columnNumber":1}

Xiaomi MI MIX 2S - stock rom, europe
Android 9
Magisk root

**Comment by oleavr** [comment]
"Me too" comments are not helpful, it's already clear what the problem is. Please open a PR fixing the issue instead.
