### ISSUE TITLE
frida.TransportError: the connection is closed

### ISSUE THREAD

**Issue by mr-m0nst3r** [frida/frida#722]
Sorry but I've checked all the other `connection is closed` issues, just can't find solution, only find `fixed in latest version`-like solution.

But... I'm using the latest, updated everything, and tried using python3 but failed.

Switch to python2, clear all caches and install and update, still same error.

```
Traceback (most recent call last):
  File "my-loader.py", line 51, in <module>
    load_script()
  File "my-loader.py", line 34, in load_script
    script.load()
  File "/usr/local/lib/python2.7/site-packages/frida/core.py", line 192, in load
    self._impl.load()
frida.TransportError: the connection is closed
```

Here's my helper.py
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import struct
import frida
import IPython

JS_FILE = "instance.js"
PACKAGE = "com.example.a11x256.frida_test"
frida_session = None
global script

script = None

reload(sys)
sys.setdefaultencoding('utf-8')


def on_message(message, data):
    print(message)
    print(data)


def load_script():
    global script
    if script is not None:
        script.unload()

    with open(JS_FILE, 'r') as rjs:
        hook_script = rjs.read()

    script = frida_session.create_script(hook_script)
    script.on('message', on_message)
    script.load()


if __name__ == "__main__":
    device = frida.get_device_manager().enumerate_devices()[-1]
    resume = False

    try:
        frida_session = device.attach(PACKAGE)
        print "[Info] Attach success!"
    except:
        pid = device.spawn(PACKAGE)
        frida_session = device.attach(pid)
        resume = True

        print "[Info] Spawn and attach success!"

    load_script()

    if resume:
        device.resume(pid)

    IPython.embed()
    script.unload()
    exit(0)
```

Here's the instance.js:
```
Java.perform(function(){ 
	Java.choose("com.example.a11x256.frida_test.my_activity", {
		onMatch: function(instance){
			console.log(instance);
		}, 
		onComplete: function(){}
	});  
});
```

I'm following this tutorial:
`https://11x256.github.io/Frida-hooking-android-part-2/`

Stuck and help please.

**Comment by mr-m0nst3r** [comment]
BTW, I'm using the latest Mac OSX.
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75
```

**Comment by iGio90** [comment]
a colleague of me is experiencing some issues with the Java.perform <- which is what hang (on our end). The solution (on our end) was to wrap Java.perform into a setTimeout(fn, 0);

hope it will be ur solution too!

**Comment by RaitoBezarius** [comment]
Same issue with latest version on Android 7.1 on Linux (Arch Linux, latest kernel version).

**Comment by comsians123** [comment]
I had the same issue i-e `frida.TransportError: the connection is closed` with the following script.
```
import frida, sys

def on_message(message, data):
    if message['type'] == 'send':
        print("[*] {0}".format(message['payload']))
    else:
        print(message)

jscode = """
Java.perform(function x() {
    //do stuff
});
"""

process = frida.get_usb_device().attach('com.package.name')
script = process.create_script(jscode)
script.on('message', on_message)
script.load()
sys.stdin.read()
```


and I solved it by changing the script to 

```
import frida, sys
import time

def on_message(message, data):
    if message['type'] == 'send':
        print("[*] {0}".format(message['payload']))
    else:
        print(message)

jscode = """
console.log("Script loaded successfully ");
Java.perform(function x() { 
    //do stuff
});
"""

device = frida.get_usb_device(1)
pid = device.spawn(["com.package.name"])
device.resume(pid)
time.sleep(1) #Without it Java.perform silently fails
process = device.attach(pid)
script = process.create_script(jscode)
script.on('message', on_message)
script.load()
sys.stdin.read()
```

Summary: 
Replace this line `process = frida.get_usb_device().attach('com.package.name')` with: 

```
device = frida.get_usb_device(1)
pid = device.spawn(["com.package.name"])
device.resume(pid)
time.sleep(1) #Without it Java.perform silently fails
process = device.attach(pid)
```

Don't forget to **_rerun_** frida-server on android device 
Hope it might help someone. Thanks
