### ISSUE TITLE
Failed to install frida-tools by pip ---network query failed

### ISSUE THREAD

**Issue by wangzery** [frida/frida#743]
Hi, I encountered this issue when I installing frida-tools-1.2.2.  
The environment is: 
Windows 7 x64 
python 2.7.15

```
λ pip install frida-tools
Requirement already satisfied: frida-tools in c:\python27\lib\site-packages\frida_tools-1.2.2-py2.7.egg (1.2.2)
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in c:\python27\lib\site-packages (from frida-tools) (0.4.0)
Collecting frida<13.0.0,>=12.1.0 (from frida-tools)
Using cached https://files.pythonhosted.org/packages/28/57/dfd4b2965cb5a9d13e998aba038eb0d8150f1570e0c12a78158278a7403f/frida-12.2.27.tar.gz
Requirement already satisfied: prompt-toolkit<2.0.0,>=0.57 in c:\python27\lib\site-packages\prompt_toolkit-1.0.15-py2.7.egg (from frida-tools) (1.0.15)
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in c:\python27\lib\site-packages (from frida-tools) (2.2.0)
Requirement already satisfied: six>=1.9.0 in c:\python27\lib\site-packages (from prompt-toolkit<2.0.0,>=0.57->frida-tools) (1.11.0)
Requirement already satisfied: wcwidth in c:\python27\lib\site-packages (from prompt-toolkit<2.0.0,>=0.57->frida-tools) (0.1.7)
Installing collected packages: frida
Running setup.py install for frida ... error
Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;file='c:\users\admini1\appdata\local\temp\pip-install-vswb32\frida\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record c:\users\admini1\appdata\local\temp\pip-record-xoqx17\install-record.txt --single-version-externally-managed --compile:
running install
running build
running build_py
creating build
creating build\lib.win-amd64-2.7
creating build\lib.win-amd64-2.7\frida
copying frida\core.py -> build\lib.win-amd64-2.7\frida
copying frida_init_.py -> build\lib.win-amd64-2.7\frida
running build_ext
querying pypi for available prebuilds
network query failed
looking for prebuilt extension in home directory, i.e. C:\Users\Administrator/frida-12.2.27-py2.7-win-amd64.egg
no prebuilt extension found in home directory
Traceback (most recent call last):
File "", line 1, in 
File "c:\users\admini1\appdata\local\temp\pip-install-vswb32\frida\setup.py", line 179, in 
'build_ext': FridaPrebuiltExt
File "c:\python27\lib\site-packages\setuptools_init_.py", line 143, in setup
return distutils.core.setup(**attrs)
File "c:\python27\lib\distutils\core.py", line 151, in setup
dist.run_commands()
File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
self.run_command(cmd)
File "c:\python27\lib\distutils\dist.py", line 972, in run_command
cmd_obj.run()
File "c:\python27\lib\site-packages\setuptools\command\install.py", line 61, in run
return orig.install.run(self)
File "c:\python27\lib\distutils\command\install.py", line 563, in run
self.run_command('build')
File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "c:\python27\lib\distutils\dist.py", line 972, in run_command
cmd_obj.run()
File "c:\python27\lib\distutils\command\build.py", line 127, in run
self.run_command(cmd_name)
File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "c:\python27\lib\distutils\dist.py", line 972, in run_command
cmd_obj.run()
File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
_build_ext.run(self)
File "c:\python27\lib\distutils\command\build_ext.py", line 340, in run
self.build_extensions()
File "c:\python27\lib\distutils\command\build_ext.py", line 449, in build_extensions
self.build_extension(ext)
File "c:\users\admini1\appdata\local\temp\pip-install-vswb32\frida\setup.py", line 126, in build_extension
raise network_error
Exception: Could not find prebuilt Frida extension. Prebuilds only provided for Python 2.7 and 3.4+.

----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;file='c:\users\admini1\appdata\local\temp\pip-install-vswb32\frida\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record c:\users\admini1\appdata\local\temp\pip-record-xoqx17\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\admini~1\appdata\local\temp\pip-install-vswb32\frida\
```

**Comment by thejunkjon** [comment]
@wangzery , please try using python 3.

**Comment by wangzery** [comment]
@thejunkjon 
Resolved , thanks for your solution !

**Comment by wangzery** [comment]
Using python2.7-32bit help it ,too.
