### ISSUE TITLE
help => Exception in thread Thread-1:

### ISSUE THREAD

**Issue by AnnibalAbreu** [frida/frida#755]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\python27\lib\site-packages\frida_tools\application.py", line 428, in _run
    work()
  File "c:\python27\lib\site-packages\frida_tools\application.py", line 275, in _try_start
    self._update_status("Failed to spawn: %s" % e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)

**Comment by gaoye02** [comment]
how to solve
