### ISSUE TITLE
Building error on Windows10

### ISSUE THREAD

**Issue by o0xmuhe** [frida/frida#763]
Hi there,
    I am building frida on windows10.According to the [document](https://www.frida.re/docs/building/),
I installed git, nodejs, py3.7,and they all in my PATH, everything is done. But I still got errors as follow:

```
Severity | Code | Description | Project | File | Line | Suppression State
Error (active) | E1696 | cannot open source file "frida-core.h" | frida-python27 | C:\Users\muhe\Desktop\frida\frida-python\src\_frida.c | 7 |  
Error (active) | E0020 | identifier "gint" is undefined | frida-python27 | C:\Users\muhe\Desktop\frida\frida-python\src\_frida.c | 92 |  
Error (active) | E0020 | identifier "GHashTable" is undefined | frida-python27 | C:\Users\muhe\Desktop\frida\frida-python\src\_frida.c | 97 |  
...
...

Error | MSB6006 | "cmd.exe" exited with code 1. | gumjs-64 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets | 209 |  
Error | LNK1104 | cannot open file 'C:\Users\muhe\Desktop\frida\build\tmp-windows\x64-Debug\gumjs-64\gumjs-64.lib' | frida-agent-64 | C:\Users\muhe\Desktop\frida\frida-core\lib\agent\LINK | 1 |  
Error | LNK1104 | cannot open file 'C:\Users\muhe\Desktop\frida\build\tmp-windows\Win32-Debug\gumjs-32\gumjs-32.lib' | frida-agent-32 | C:\Users\muhe\Desktop\frida\frida-core\lib\agent\LINK | 1 |  

```

I think it is because of the `frida-core.h` missing, I found the [issue] before(https://github.com/frida/frida/issues/58), oleavr said it needs py2.7 installed, but  I have installed py3.7, is there any conflict while I building it?

I have tried build `frida-core` alone, it still failed as before(can not find `frida-core.h`)   :(

How should I fix this error?

ps: I also try to build frida with `Incredbuild`, but I got other errors:

```
1>------ Build started: Project: gumjs-32, Configuration: Debug Win32 ------
2>------ Build started: Project: gumjs-64, Configuration: Debug x64 ------
1>Build started 1/20/2019 1:35:45 AM.
2>Build started 1/20/2019 1:35:45 AM.
1>Target ResolveProjectReferences:
1>Target CheckWindowsSDK71A:
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\Win32\PlatformToolsets\v141_xp\Toolset.targets(39,5): warning MSB8051: Support for targeting Windows XP is deprecated and will not be present in future releases of Visual Studio. Please see https://go.microsoft.com/fwlink/?linkid=2023588 for more information.
1>Done building target "CheckWindowsSDK71A" in project "gumjs-32.vcxproj".
1>Target InitializeBuildStatus:
1>  Touching "C:\Users\muhe\Desktop\frida\build\tmp-windows\Win32-Debug\gumjs-32\gumjs-32.tlog\unsuccessfulbuild".
2>Target ResolveProjectReferences:
2>Target CheckWindowsSDK71A:
2>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets\v141_xp\Toolset.targets(39,5): warning MSB8051: Support for targeting Windows XP is deprecated and will not be present in future releases of Visual Studio. Please see https://go.microsoft.com/fwlink/?linkid=2023588 for more information.
2>Done building target "CheckWindowsSDK71A" in project "gumjs-64.vcxproj".
1>Target CustomBuild:
1>  Generating bindings
2>Target InitializeBuildStatus:
2>  Touching "C:\Users\muhe\Desktop\frida\build\tmp-windows\x64-Debug\gumjs-64\gumjs-64.tlog\unsuccessfulbuild".
2>Target CustomBuild:
2>  Generating bindings
1>  Traceback (most recent call last):
1>    File "C:\Users\muhe\Desktop\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 2736, in <module>
1>      source_dir = sys.argv[1]
1>  IndexError: list index out of range
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building target "CustomBuild" in project "gumjs-32.vcxproj" -- FAILED.
1>
1>Done building project "gumjs-32.vcxproj" -- FAILED.
1>
1>Build FAILED.
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\Win32\PlatformToolsets\v141_xp\Toolset.targets(39,5): warning MSB8051: Support for targeting Windows XP is deprecated and will not be present in future releases of Visual Studio. Please see https://go.microsoft.com/fwlink/?linkid=2023588 for more information.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1.
1>    1 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:00.80
2>  Traceback (most recent call last):
2>    File "C:\Users\muhe\Desktop\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 2736, in <module>
2>      source_dir = sys.argv[1]
2>  IndexError: list index out of range
2>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1.
2>Done building target "CustomBuild" in project "gumjs-64.vcxproj" -- FAILED.
2>
2>Done building project "gumjs-64.vcxproj" -- FAILED.
2>
2>Build FAILED.
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets\v141_xp\Toolset.targets(39,5): warning MSB8051: Support for targeting Windows XP is deprecated and will not be present in future releases of Visual Studio. Please see https://go.microsoft.com/fwlink/?linkid=2023588 for more information.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1.
2>    1 Warning(s)
2>    1 Error(s)
```

**Comment by aliforever** [comment]
Same here, 
I saw this build log:
`Traceback (most recent call last):
12>  File "C:\Users\alier\Desktop\Projects\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 3070, in <module>
12>    source_dir = sys.argv[1]
12>IndexError: list index out of range`

**Comment by aliforever** [comment]
Same here,
I saw this in build log:
Traceback (most recent call last): 12> File "...\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 3070, in <module> 12> source_dir = sys.argv[1] 12>IndexError: list index out of range
