### ISSUE TITLE
frida.TransportError: the connection is closed

### ISSUE THREAD

**Issue by jkryanchou** [frida/frida#765]
My Android device was android 6.0, and frida was the latest version 12.2.29. While I try to print all classes.

Python snippets
```
# -*- coding: utf-8 -*-

import frida
import sys

package_name = "com.example.app"

def get_messages_from_js(message, data):
    print(message)


def instrument_debugger_checks():
    hook_code = """
    Java.perform(function(){
        Java.enumerateLoadedClasses({
            onMatch: function(className){
                send(className);
            },
            onComplete: function() {
                send("done");
            }
        });
    });
    """
    return hook_code


process = frida.get_device_manager().enumerate_devices()[-1].attach(package_name)
script = process.create_script(instrument_debugger_checks())
script.on('message', get_messages_from_js)
script.load()
sys.stdin.read()
```

It shows error like below.

```
Traceback (most recent call last):
  File "print_all_classes.py", line 33, in <module>
    script.load()
  File "/Users/Dev/android/venv/lib/python3.6/site-packages/frida/core.py", line 192, in load
    self._impl.load()
frida.TransportError: the connection is closed
```

While the script works fine on other android package. I have no idea what's wrong with this package.

**Comment by jkryanchou** [comment]
Finnaly found the solution. Upgrade my Android to 8.x it works.
