### ISSUE TITLE
Failed to load the Frida native extension

### ISSUE THREAD

**Issue by josebeo2016** [frida/frida#827]
Hi everyone,
I have a problem when I run frida:
```
***
Failed to load the Frida native extension: /usr/local/lib/python3.6/dist-packages/_frida.cpython-36m-arm-linux-gnueabihf.so: cannot open shared object file: No such file or directory
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "loader.py", line 2, in <module>
    import frida
  File "/usr/local/lib/python3.6/dist-packages/frida/__init__.py", line 24, in <module>
    raise ex
  File "/usr/local/lib/python3.6/dist-packages/frida/__init__.py", line 7, in <module>
    import _frida
ImportError: /usr/local/lib/python3.6/dist-packages/_frida.cpython-36m-arm-linux-gnueabihf.so: cannot open shared object file: No such file or directory
```
But I've checked that the file: ```/usr/local/lib/python3.6/dist-packages/_frida.cpython-36m-arm-linux-gnueabihf.so```
is there:
```
ll /usr/local/lib/python3.6/dist-packages/
total 57660
drwxrwsr-x 6 root staff     4096 Apr  4 02:35 ./
drwxrwsr-x 3 root staff     4096 Apr  4 02:23 ../
-rw-r--r-- 1 root staff 59015804 Apr  4 02:35 _frida.cpython-36m-arm-linux-gnueabihf.so
drwxr-sr-x 3 root staff     4096 Apr  4 02:35 frida/
drwxr-sr-x 2 root staff     4096 Apr  4 02:35 frida-12.4.7.dist-info/
drwxr-sr-x 5 root staff     4096 Apr  4 02:32 pip/
drwxr-sr-x 2 root staff     4096 Apr  4 02:32 pip-19.0.3.dist-info/
```
My system: Ubuntu 16.04 in Odroid.

**Comment by josebeo2016** [comment]
I've posted in wrong repo
