### ISSUE TITLE
TypeError: api.art::mirror::Object::Clone is not a function

### ISSUE THREAD

**Issue by jiangfeng0103** [frida/frida#869]
版本 Frida 12.4.8
每次启动 APP 都出现 错误

{"type":"error","description":"TypeError: api.art::mirror::Object::Clone is not a function","stack":"TypeError: api.art::mirror::Object::Clone is not a function\n    at cloneArtMethod (frida/node_modules/frida-java/lib/android.js:859:1)\n    at resolveArtTargetMethodId (frida/node_modules/frida-java/lib/class-factory.js:1655:1)\n    at klass.f (eval at makeMethod (frida/node_modules/frida-java/lib/class-factory.js:1568:1), <anonymous>:1:306)\n    at klass.f (frida/node_modules/frida-java/lib/class-factory.js:1395:1)\n    at klass.sendMessageDelayed.implementation (/internal-agent.js:196:31)\n    at f (eval at implement (frida/node_modules/frida-java/lib/class-factory.js:2105:1), <anonymous>:1:285)\n    at klass.f (eval at makeMethod (frida/node_modules/frida-java/lib/class-factory.js:1568:1), <anonymous>:1:365)\n    at klass.f (frida/node_modules/frida-java/lib/class-factory.js:1395:1)\n    at /internal-agent.js:115:23\n    at /internal-agent.js:233:22","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":859,"columnNumber":1}

**Comment by irever** [comment]
Hey , I had the same issue , after installed "Xposed Framework v90-beta3" with Magisk。
Try to remove Xposed from Magisk and reboot.
我在Magisk上安装了 Xposed Framework后也有同样的错误，试下把它移除之后还会不会。

**Comment by huhahu** [comment]
why ？？？？
