### ISSUE TITLE
frida obfuscated arguments

### ISSUE THREAD

**Issue by nomarlhack** [frida/frida#918]
I'm trying to hook up the forName method in java.lang.Class.

The forName function accepts one string as a factor.

The problem is that obfuscated factor names come from a broken string as follows: (You can see below that it is marked as ?.)

------------------ forName!--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
*******************************************************
arg[0]: ???

If you put this value in the factor of the forName method and run it, an error will cause the app to stop running.

Is there a way to solve this problem?

**Comment by nomarlhack** [comment]
If you look at the call stack, it's similarly marked as ?.

Backtrace:
java.lang.Exception
        at java.lang.Class.forName(Native Method)
        at ?.??.???(Unknown Source)
        at ?.??.?(Unknown Source)
        at ?.??.???(Unknown Source)
        at ?.??.run(Unknown Source)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
