### ISSUE TITLE
stalk problem

### ISSUE THREAD

**Issue by gaplan** [frida/frida#990]
**this is my simple code for stalk.**

 function stalk() {
	Stalker.follow(Process.getCurrentThreadId(), {
		events: {
			call: true
		},
	
		onReceive: function(events) {
			events = Stalker.parse(events);
			console.log("onReceive");

			},
			 onCallSummary: function (summary) {
  			console.log("onReceive");
  			},
		
	})
}
stalk()
**and this is the error** 

[iPhone::youtube]-> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/frida_tools/application.py", line 428, in _run
    work()                                                                                                                                                        
  File "/usr/local/lib/python2.7/site-packages/frida_tools/application.py", line 128, in <lambda>
    self._schedule_on_session_detached = lambda reason, crash: self._reactor.schedule(lambda: self._on_session_detached(reason, crash))
  File "/usr/local/lib/python2.7/site-packages/frida_tools/application.py", line 310, in _on_session_detached
    message = "Process crashed: " + crash.summary
AttributeError: 'unicode' object has no attribute 'summary'

**Comment by oleavr** [comment]
Your `frida` package is outdated. `pip install -U frida` should fix it.
